import type { Localized } from "@/i18n/config";
import type { CircuitGroup } from "./circuit-data";

export interface NodeCopy {
  label: string;
  sub: string;
  /** One honest sentence about what this part does in the system. */
  role: string;
}

export interface CircuitCopy {
  ui: {
    boardLabel: string;
    hint: string;
    keyboardHint: string;
    inspector: string;
    idle: string;
    idleBody: string;
    connected: string;
    designator: string;
    group: string;
    clear: string;
    selectLabel: string;
    selectPlaceholder: string;
    legend: string;
    caption: string;
    nodes: string;
    traces: string;
    scrollHint: string;
    live: string;
    staticSvg: string;
  };
  groups: Record<CircuitGroup, string>;
  nodes: Record<string, NodeCopy>;
}

const en: CircuitCopy = {
  ui: {
    boardLabel: "Interactive AI-native engineering circuit",
    hint: "Select a component to trace what it connects to.",
    keyboardHint: "Tab to a component, arrow keys to move, Enter to select, Esc to clear.",
    inspector: "Inspector",
    idle: "Nothing selected",
    idleBody: "Choose ChatGPT, Claude, Local AI or Python to see how each one is wired into the system.",
    connected: "Wired to",
    designator: "Ref",
    group: "Layer",
    clear: "Clear",
    selectLabel: "Component",
    selectPlaceholder: "Choose a component…",
    legend: "Layers",
    caption: "Generated by {generator} · {hash} · {nodes} nodes · {traces} traces",
    nodes: "nodes",
    traces: "traces",
    scrollHint: "Scroll sideways to explore the board",
    live: "{label} selected. {count} connected components highlighted.",
    staticSvg: "Open the static SVG",
  },
  groups: {
    human: "Human intent & review",
    orchestration: "Orchestration",
    model: "Models",
    agent: "Agents",
    tool: "Tools",
    data: "Data & context",
    quality: "Validation",
    delivery: "Delivery",
  },
  nodes: {
    intent: { label: "Human intent", sub: "goal · constraints", role: "Every run starts with a person: the goal, the constraints and what “done” means." },
    planner: { label: "Planner", sub: "task decomposition", role: "Breaks the goal into small, checkable tasks with a clear order." },
    orchestrator: { label: "Orchestrator", sub: "state · checkpoints", role: "Holds workflow state, hands tasks to models and agents, and stops at checkpoints." },
    research: { label: "Research", sub: "sources · analysis", role: "Collects documentation, prior art and options before anything is built." },
    chatgpt: { label: "ChatGPT", sub: "OpenAI ecosystem", role: "Research, analysis, reasoning, specifications and drafting — one model among several." },
    claude: { label: "Claude", sub: "Claude Code", role: "Repository analysis, planning, subagent delegation, implementation, refactoring and review." },
    "local-ai": { label: "Local AI", sub: "self-hosted models", role: "Private, offline-capable inference for data that should not leave the machine." },
    "private-data": { label: "Private data", sub: "documents · files", role: "Internal documents and files that stay on infrastructure you control." },
    router: { label: "Tool router", sub: "tool + model routing", role: "Chooses the tool or model for each step based on the task, privacy and cost." },
    embeddings: { label: "Embeddings · RAG", sub: "vector search", role: "Turns documents into searchable context so answers cite real sources." },
    "design-agent": { label: "Design agent", sub: "UI · tokens", role: "Drafts layouts and design tokens against an agreed visual system." },
    "frontend-agent": { label: "Frontend agent", sub: "React · Next.js", role: "Implements components and pages inside clear ownership boundaries." },
    "backend-agent": { label: "Backend agent", sub: "APIs · data", role: "Builds API routes, validation and data access." },
    "test-agent": { label: "Test agent", sub: "unit · e2e", role: "Writes and runs tests; failures go back to the orchestrator." },
    "review-agent": { label: "Review agent", sub: "diff · security", role: "Reviews diffs for bugs, security issues and inconsistencies." },
    python: { label: "Python", sub: "scripts · automation", role: "The glue: automation, data transformation, API clients, local AI tooling and generators like this circuit." },
    "web-api": { label: "Web · API", sub: "HTTP · webhooks", role: "Connects to external services, webhooks and the application's own endpoints." },
    data: { label: "Data", sub: "transform · parse", role: "Parses, cleans and reshapes data between systems." },
    github: { label: "GitHub", sub: "repository · CI", role: "Version control, history and the trigger for automated deployment." },
    automation: { label: "Automation", sub: "jobs · pipelines", role: "Repeatable jobs that replace manual, error-prone steps." },
    backend: { label: "Backend", sub: "server · validation", role: "Server logic, validation and the rules that keep data correct." },
    database: { label: "Database", sub: "PostgreSQL", role: "Durable storage with a schema that is designed, not improvised." },
    validation: { label: "Validation · tests", sub: "types · tests · review", role: "Type checks, linting, tests and a production build — nothing ships without passing." },
    "human-review": { label: "Human approval", sub: "verify · decide", role: "A person verifies the result and decides whether it goes live." },
    vercel: { label: "Deployment", sub: "Vercel", role: "Builds and deploys from the repository to Vercel." },
    production: { label: "Production", sub: "live application", role: "The running product, monitored through a health endpoint." },
  },
};

const de: CircuitCopy = {
  ui: {
    boardLabel: "Interaktiver Schaltplan für KI-natives Engineering",
    hint: "Wähle eine Komponente, um ihre Verbindungen zu verfolgen.",
    keyboardHint: "Tab zu einer Komponente, Pfeiltasten zum Wechseln, Enter zum Auswählen, Esc zum Zurücksetzen.",
    inspector: "Inspektor",
    idle: "Nichts ausgewählt",
    idleBody: "Wähle ChatGPT, Claude, Local AI oder Python, um zu sehen, wie sie ins System eingebunden sind.",
    connected: "Verbunden mit",
    designator: "Ref",
    group: "Ebene",
    clear: "Zurücksetzen",
    selectLabel: "Komponente",
    selectPlaceholder: "Komponente wählen…",
    legend: "Ebenen",
    caption: "Generiert von {generator} · {hash} · {nodes} Knoten · {traces} Leiterbahnen",
    nodes: "Knoten",
    traces: "Leiterbahnen",
    scrollHint: "Seitlich scrollen, um die Platine zu erkunden",
    live: "{label} ausgewählt. {count} verbundene Komponenten hervorgehoben.",
    staticSvg: "Statisches SVG öffnen",
  },
  groups: {
    human: "Mensch: Ziel & Prüfung",
    orchestration: "Orchestrierung",
    model: "Modelle",
    agent: "Agents",
    tool: "Tools",
    data: "Daten & Kontext",
    quality: "Validierung",
    delivery: "Auslieferung",
  },
  nodes: {
    intent: { label: "Menschliches Ziel", sub: "Ziel · Rahmen", role: "Jeder Durchlauf beginnt bei einem Menschen: Ziel, Rahmenbedingungen und was „fertig“ bedeutet." },
    planner: { label: "Planer", sub: "Aufgabenzerlegung", role: "Zerlegt das Ziel in kleine, prüfbare Aufgaben mit klarer Reihenfolge." },
    orchestrator: { label: "Orchestrator", sub: "Zustand · Checkpoints", role: "Hält den Workflow-Zustand, verteilt Aufgaben an Modelle und Agents und stoppt an Checkpoints." },
    research: { label: "Recherche", sub: "Quellen · Analyse", role: "Sammelt Dokumentation, Vorbilder und Optionen, bevor gebaut wird." },
    chatgpt: { label: "ChatGPT", sub: "OpenAI-Ökosystem", role: "Recherche, Analyse, Reasoning, Spezifikation und Entwürfe – ein Modell unter mehreren." },
    claude: { label: "Claude", sub: "Claude Code", role: "Repository-Analyse, Planung, Subagent-Delegation, Umsetzung, Refactoring und Review." },
    "local-ai": { label: "Local AI", sub: "selbst gehostete Modelle", role: "Private, offlinefähige Inferenz für Daten, die das Gerät nicht verlassen sollen." },
    "private-data": { label: "Private Daten", sub: "Dokumente · Dateien", role: "Interne Dokumente und Dateien, die auf eigener Infrastruktur bleiben." },
    router: { label: "Tool-Router", sub: "Tool- & Modell-Routing", role: "Wählt für jeden Schritt Tool oder Modell – nach Aufgabe, Datenschutz und Kosten." },
    embeddings: { label: "Embeddings · RAG", sub: "Vektorsuche", role: "Macht Dokumente durchsuchbar, damit Antworten echte Quellen nennen." },
    "design-agent": { label: "Design-Agent", sub: "UI · Tokens", role: "Entwirft Layouts und Design-Tokens innerhalb eines vereinbarten Systems." },
    "frontend-agent": { label: "Frontend-Agent", sub: "React · Next.js", role: "Setzt Komponenten und Seiten mit klaren Zuständigkeiten um." },
    "backend-agent": { label: "Backend-Agent", sub: "APIs · Daten", role: "Baut API-Routen, Validierung und Datenzugriff." },
    "test-agent": { label: "Test-Agent", sub: "Unit · E2E", role: "Schreibt und startet Tests; Fehler gehen zurück an den Orchestrator." },
    "review-agent": { label: "Review-Agent", sub: "Diff · Sicherheit", role: "Prüft Änderungen auf Fehler, Sicherheitsprobleme und Inkonsistenzen." },
    python: { label: "Python", sub: "Skripte · Automatisierung", role: "Das Bindeglied: Automatisierung, Datenumwandlung, API-Clients, Local-AI-Tooling und Generatoren wie dieser Schaltplan." },
    "web-api": { label: "Web · API", sub: "HTTP · Webhooks", role: "Verbindet externe Dienste, Webhooks und die eigenen Endpunkte der Anwendung." },
    data: { label: "Daten", sub: "umwandeln · parsen", role: "Parst, bereinigt und formt Daten zwischen Systemen um." },
    github: { label: "GitHub", sub: "Repository · CI", role: "Versionskontrolle, Historie und Auslöser für automatisches Deployment." },
    automation: { label: "Automatisierung", sub: "Jobs · Pipelines", role: "Wiederholbare Jobs statt manueller, fehleranfälliger Schritte." },
    backend: { label: "Backend", sub: "Server · Validierung", role: "Serverlogik, Validierung und die Regeln, die Daten korrekt halten." },
    database: { label: "Datenbank", sub: "PostgreSQL", role: "Dauerhafte Speicherung mit einem durchdachten Schema." },
    validation: { label: "Validierung · Tests", sub: "Typen · Tests · Review", role: "Typprüfung, Linting, Tests und ein Produktions-Build – ohne Bestehen geht nichts live." },
    "human-review": { label: "Menschliche Freigabe", sub: "prüfen · entscheiden", role: "Ein Mensch prüft das Ergebnis und entscheidet über den Livegang." },
    vercel: { label: "Deployment", sub: "Vercel", role: "Baut und deployt aus dem Repository auf Vercel." },
    production: { label: "Produktion", sub: "Live-Anwendung", role: "Das laufende Produkt, überwacht über einen Health-Endpunkt." },
  },
};

const th: CircuitCopy = {
  ui: {
    boardLabel: "วงจรวิศวกรรมแบบ AI-native แบบโต้ตอบได้",
    hint: "เลือกส่วนประกอบเพื่อดูว่าเชื่อมกับอะไรบ้าง",
    keyboardHint: "กด Tab เพื่อเลือกส่วนประกอบ ใช้ลูกศรเพื่อเลื่อน Enter เพื่อเลือก Esc เพื่อล้าง",
    inspector: "Inspector",
    idle: "ยังไม่ได้เลือก",
    idleBody: "ลองเลือก ChatGPT, Claude, Local AI หรือ Python เพื่อดูว่าแต่ละส่วนต่อเข้ากับระบบอย่างไร",
    connected: "เชื่อมต่อกับ",
    designator: "Ref",
    group: "ชั้น",
    clear: "ล้าง",
    selectLabel: "ส่วนประกอบ",
    selectPlaceholder: "เลือกส่วนประกอบ…",
    legend: "ชั้นของระบบ",
    caption: "สร้างโดย {generator} · {hash} · {nodes} โหนด · {traces} เส้นทาง",
    nodes: "โหนด",
    traces: "เส้นทาง",
    scrollHint: "เลื่อนด้านข้างเพื่อสำรวจวงจร",
    live: "เลือก {label} แล้ว ไฮไลต์ส่วนที่เชื่อมต่อ {count} ส่วน",
    staticSvg: "เปิดไฟล์ SVG แบบคงที่",
  },
  groups: {
    human: "เป้าหมายและการตรวจโดยคน",
    orchestration: "Orchestration",
    model: "โมเดล",
    agent: "Agent",
    tool: "เครื่องมือ",
    data: "ข้อมูลและบริบท",
    quality: "Validation",
    delivery: "การส่งมอบ",
  },
  nodes: {
    intent: { label: "เป้าหมายจากคน", sub: "เป้าหมาย · ข้อจำกัด", role: "ทุกรอบเริ่มจากคน: เป้าหมาย ข้อจำกัด และนิยามของคำว่า “เสร็จ”" },
    planner: { label: "Planner", sub: "แตกงานย่อย", role: "แตกเป้าหมายเป็นงานเล็ก ๆ ที่ตรวจสอบได้ และเรียงลำดับชัดเจน" },
    orchestrator: { label: "Orchestrator", sub: "state · checkpoint", role: "เก็บสถานะของ Workflow ส่งงานให้โมเดลและ Agent และหยุดตาม checkpoint" },
    research: { label: "Research", sub: "แหล่งข้อมูล · วิเคราะห์", role: "รวบรวมเอกสาร ตัวอย่าง และทางเลือกก่อนลงมือสร้าง" },
    chatgpt: { label: "ChatGPT", sub: "OpenAI ecosystem", role: "ค้นคว้า วิเคราะห์ ใช้เหตุผล เขียนสเปก และร่างเนื้อหา เป็นหนึ่งในหลายโมเดลที่ใช้" },
    claude: { label: "Claude", sub: "Claude Code", role: "วิเคราะห์ repository วางแผน แบ่งงานให้ subagent เขียนโค้ด refactor และรีวิว" },
    "local-ai": { label: "Local AI", sub: "โมเดลที่โฮสต์เอง", role: "ประมวลผลแบบส่วนตัวและออฟไลน์ได้ สำหรับข้อมูลที่ไม่ควรออกนอกเครื่อง" },
    "private-data": { label: "ข้อมูลส่วนตัว", sub: "เอกสาร · ไฟล์", role: "เอกสารภายในที่อยู่บนโครงสร้างพื้นฐานที่ควบคุมเอง" },
    router: { label: "Tool Router", sub: "เลือกเครื่องมือและโมเดล", role: "เลือกเครื่องมือหรือโมเดลให้แต่ละขั้นตอน ตามงาน ความเป็นส่วนตัว และต้นทุน" },
    embeddings: { label: "Embeddings · RAG", sub: "vector search", role: "แปลงเอกสารเป็นบริบทที่ค้นหาได้ เพื่อให้คำตอบอ้างอิงแหล่งจริง" },
    "design-agent": { label: "Design Agent", sub: "UI · tokens", role: "ร่างเลย์เอาต์และ design token ตามระบบดีไซน์ที่ตกลงกันไว้" },
    "frontend-agent": { label: "Frontend Agent", sub: "React · Next.js", role: "สร้างคอมโพเนนต์และหน้าเว็บภายในขอบเขตงานที่ชัดเจน" },
    "backend-agent": { label: "Backend Agent", sub: "API · ข้อมูล", role: "สร้าง API route, validation และการเข้าถึงข้อมูล" },
    "test-agent": { label: "Test Agent", sub: "unit · e2e", role: "เขียนและรันเทสต์ ถ้าไม่ผ่านจะส่งกลับไปที่ Orchestrator" },
    "review-agent": { label: "Review Agent", sub: "diff · security", role: "ตรวจ diff หาบั๊ก ปัญหาความปลอดภัย และความไม่สอดคล้อง" },
    python: { label: "Python", sub: "สคริปต์ · Automation", role: "ตัวเชื่อมทุกอย่าง: Automation แปลงข้อมูล API client เครื่องมือ Local AI และตัวสร้างวงจรนี้" },
    "web-api": { label: "Web · API", sub: "HTTP · webhook", role: "เชื่อมบริการภายนอก webhook และ endpoint ของแอปเอง" },
    data: { label: "Data", sub: "แปลง · parse", role: "อ่าน ทำความสะอาด และปรับรูปแบบข้อมูลระหว่างระบบ" },
    github: { label: "GitHub", sub: "repository · CI", role: "จัดการเวอร์ชัน ประวัติ และเป็นจุดเริ่ม Deploy อัตโนมัติ" },
    automation: { label: "Automation", sub: "job · pipeline", role: "งานที่รันซ้ำได้ แทนขั้นตอนที่ทำมือและพลาดง่าย" },
    backend: { label: "Backend", sub: "server · validation", role: "ลอจิกฝั่งเซิร์ฟเวอร์ validation และกฎที่ทำให้ข้อมูลถูกต้อง" },
    database: { label: "Database", sub: "PostgreSQL", role: "เก็บข้อมูลถาวร ด้วย schema ที่ออกแบบมาอย่างตั้งใจ" },
    validation: { label: "Validation · Tests", sub: "types · tests · review", role: "ตรวจ type, lint, เทสต์ และ production build ต้องผ่านทั้งหมดก่อนขึ้นจริง" },
    "human-review": { label: "อนุมัติโดยคน", sub: "ตรวจ · ตัดสินใจ", role: "คนตรวจผลลัพธ์และตัดสินใจว่าจะขึ้นระบบจริงหรือไม่" },
    vercel: { label: "Deploy", sub: "Vercel", role: "Build และ Deploy จาก repository ขึ้น Vercel" },
    production: { label: "Production", sub: "แอปที่ใช้งานจริง", role: "ระบบที่ทำงานจริง ตรวจสถานะผ่าน health endpoint" },
  },
};

export const circuitCopy: Localized<CircuitCopy> = { en, de, th };
