import type { Localized } from "@/i18n/config";
import type { CapabilityId, ChainId, DomainId, Family, FeaturedId } from "@/components/pages/capabilities/data";

const en = {
  meta: {
    title: "Capabilities",
    description:
      "A capability network across web engineering, Python, ChatGPT, Claude, autonomous agents and local AI: what can be connected to build a working system.",
  },
  hero: {
    eyebrow: "Capability network",
    title: "Not how good I am at React.",
    titleAccent: "What I can wire together.",
    lede: "Web engineering, Python, cloud and local AI are not separate skill lists. They are parts of one system. Select any node to see what it connects to and what it makes possible.",
    legendTitle: "On the board",
    nodes: "nodes",
    links: "links",
    noScores: "No percentages, levels or stars. Just connections.",
  },
  families: {
    web: { label: "Web engineering", body: "Interfaces, servers, data and delivery." },
    python: { label: "Python", body: "The connective layer between AI, data and automation." },
    ai: { label: "AI-native ecosystem", body: "ChatGPT, Claude, agents and AI-assisted engineering." },
    local: { label: "Local AI", body: "Private, self-hosted and hybrid model workflows." },
  } satisfies Record<Family, { label: string; body: string }>,
  domains: {
    interface: { label: "Interface", body: "Semantic, responsive and accessible UI built with React and Next.js." },
    server: { label: "Backend & data", body: "APIs, validation, databases and server logic that stay predictable under real use." },
    delivery: { label: "Delivery", body: "Version control, tests, performance work and deployment to production." },
    python: { label: "Python", body: "Scripts, automation, data work and the glue that connects models to tools." },
    local: { label: "Local AI", body: "Architecture concepts for private and self-hosted AI: local models, embeddings and RAG." },
    models: { label: "Models & bridges", body: "Cloud models used through their apps and APIs, connected to web and Python code." },
    autonomy: { label: "Autonomy", body: "Controlled agent loops: planning, orchestration, tool calls and routing." },
    "ai-engineering": { label: "AI-assisted engineering", body: "AI in the daily engineering loop, with a person verifying the result." },
  } satisfies Record<DomainId, { label: string; body: string }>,
  labels: {} as Partial<Record<CapabilityId, string>>,
  notes: {
    python:
      "The hub of the board. Python scripts call AI APIs, transform data, process files, drive local models and give agents tools they can actually use.",
    chatgpt:
      "Research, analysis, reasoning through options, drafting specifications and content, tool use and a second opinion during verification.",
    claude: "Long-context reasoning over specifications and codebases, structured output and API integration into products.",
    "claude-code":
      "Repository analysis, planning, delegating to subagents, implementation, refactoring, debugging, tests, review and Git workflows — all checked before anything ships.",
    nextjs: "Full websites and web apps: server rendering, routing, Server Actions and API routes in one codebase.",
    react: "Component systems that stay consistent as a product grows.",
    backend: "Server logic with validation, authentication concepts and clear error handling behind every form and feature.",
    postgresql: "Relational data models for submissions, users, content and anything that needs to be queried reliably.",
    "api-integration": "Connecting payment, email, CRM, AI and internal APIs into one predictable flow.",
    n8n: "Triggers, webhooks, schedules and API hand-offs as visible workflows — deterministic automation around the AI steps.",
    vercel: "Preview and production deployments straight from GitHub, with environment configuration kept out of the code.",
    "autonomous-ai": "Goal-driven loops that plan, act, check and stop at a checkpoint — never unbounded autonomy.",
    orchestration: "Splitting work across agents, passing context between them and aggregating results.",
    "multi-agent": "Specialised agents for design, frontend, backend, tests and review, coordinated by one orchestrator.",
    "tool-calling": "Letting a model call real functions — search, database, API — with validated inputs and outputs.",
    "local-models": "Running models on your own hardware when data should not leave the building.",
    rag: "Answering questions from your own documents by retrieving the right passages first.",
    "hybrid-routing": "Routing each request to a cloud or local model based on privacy, capability, cost, latency and availability.",
    "human-review": "Every AI-produced change is reviewed, tested and approved by a person before it reaches production.",
    "py-automation": "Repetitive work turned into scheduled, logged and testable pipelines.",
    "py-local-ai": "Python services that load documents, compute embeddings and talk to local model endpoints.",
  } satisfies Record<FeaturedId, string>,
  uses: {
    chatgpt: ["Research", "Analysis", "Reasoning", "Specification", "Content", "Tool use", "Engineering support", "Verification"],
    "claude-code": ["Repository analysis", "Planning", "Subagent delegation", "Implementation", "Refactoring", "Debugging", "Testing", "Review", "Git workflows", "Deployment support"],
  },
  ui: {
    boardLabel: "Capability network",
    selected: "Selected",
    connectsTo: "Connects to",
    usedFor: "Used for",
    builds: "What it makes possible",
    connections: "{n} connections",
    status: "{label} selected, {n} connections highlighted.",
    hint: "Select a node. Use Tab to move between nodes.",
    jump: "Jump to",
    concept: "Architecture concept",
    reset: "Back to Python",
    search: "Search capabilities",
    searchPlaceholder: "e.g. n8n, RAG, Next.js",
    clear: "Clear search",
    results: "Across all areas: {n}",
    noResults: "Nothing matches “{q}”.",
    areas: "Areas",
    tabs: { python: "Python", web: "Web", ai: "AI", local: "Local AI" } satisfies Record<Family, string>,
    browse: "All in {area}",
    paths: "Build paths",
    pathsHint: "Typical builds that pass through here",
    hub: "Hub",
  },
  chains: {
    eyebrow: "Paths through the network",
    title: "Four builds, traced.",
    body: "Real projects follow a path across domains. These are typical ones.",
    items: {
      redesign: { title: "Website redesign", outcome: "A faster, accessible site that is easier to maintain." },
      "ai-feature": { title: "AI feature in an existing product", outcome: "An AI capability behind validation and human review." },
      "private-search": { title: "Private document search", outcome: "Answers from internal documents without sending them to a cloud model." },
      automation: { title: "Workflow automation", outcome: "A repetitive task replaced by a tested pipeline." },
    } satisfies Record<ChainId, { title: string; outcome: string }>,
  },
  cta: {
    title: "Need these pieces connected for your project?",
    label: "Build with AI",
  },
};

export type CapabilitiesContent = typeof en;

const de: CapabilitiesContent = {
  meta: {
    title: "Fähigkeiten",
    description:
      "Ein Fähigkeitsnetzwerk aus Webentwicklung, Python, ChatGPT, Claude, autonomen Agents und lokaler KI: was sich verbinden lässt, um ein funktionierendes System zu bauen.",
  },
  hero: {
    eyebrow: "Fähigkeitsnetzwerk",
    title: "Nicht, wie gut ich React kann.",
    titleAccent: "Was ich miteinander verbinden kann.",
    lede: "Webentwicklung, Python, Cloud- und lokale KI sind keine getrennten Listen. Sie sind Teile eines Systems. Wähle einen Knoten, um zu sehen, womit er verbunden ist und was er möglich macht.",
    legendTitle: "Auf dem Board",
    nodes: "Knoten",
    links: "Verbindungen",
    noScores: "Keine Prozente, Level oder Sterne. Nur Verbindungen.",
  },
  families: {
    web: { label: "Webentwicklung", body: "Oberflächen, Server, Daten und Auslieferung." },
    python: { label: "Python", body: "Die verbindende Schicht zwischen KI, Daten und Automatisierung." },
    ai: { label: "KI-natives Ökosystem", body: "ChatGPT, Claude, Agents und KI-gestützte Entwicklung." },
    local: { label: "Lokale KI", body: "Private, selbst gehostete und hybride Modell-Workflows." },
  },
  domains: {
    interface: { label: "Oberfläche", body: "Semantische, responsive und barrierearme UI mit React und Next.js." },
    server: { label: "Backend & Daten", body: "APIs, Validierung, Datenbanken und Serverlogik, die auch unter echter Last berechenbar bleiben." },
    delivery: { label: "Auslieferung", body: "Versionskontrolle, Tests, Performance und Deployment in die Produktion." },
    python: { label: "Python", body: "Skripte, Automatisierung, Datenarbeit und die Verbindung zwischen Modellen und Tools." },
    local: { label: "Lokale KI", body: "Architekturkonzepte für private und selbst gehostete KI: lokale Modelle, Embeddings und RAG." },
    models: { label: "Modelle & Brücken", body: "Cloud-Modelle über Apps und APIs, verbunden mit Web- und Python-Code." },
    autonomy: { label: "Autonomie", body: "Kontrollierte Agent-Loops: Planung, Orchestrierung, Tool-Aufrufe und Routing." },
    "ai-engineering": { label: "KI-gestützte Entwicklung", body: "KI im täglichen Entwicklungsablauf, das Ergebnis prüft ein Mensch." },
  },
  labels: {
    "ui-architecture": "UI-Architektur",
    "api-integration": "API-Integration",
    n8n: "n8n-Workflow-Automatisierung",
    webhooks: "Webhooks",
    "database-design": "Datenbankdesign",
    validation: "Validierung",
    auth: "Authentifizierungskonzepte",
    "py-ai": "KI-Integration",
    "py-automation": "Automatisierung",
    "py-scripts": "Skripte",
    "py-data": "Datentransformation",
    "py-files": "Dateiverarbeitung",
    "py-api-clients": "API-Clients",
    "py-tools": "Tool-Orchestrierung",
    "py-local-ai": "Lokale KI-Workflows",
    "py-agent-utils": "Agent-Werkzeuge",
    "py-devtools": "Entwickler-Tools",
    "py-backend-utils": "Backend-Werkzeuge",
    "local-models": "Lokale Modelle",
    "self-hosted": "Selbst gehostete Inferenz",
    "local-endpoints": "Lokale Endpunkte",
    privacy: "Datenschutzbewusste KI",
    offline: "Offline-fähige Workflows",
    "hybrid-routing": "Cloud-/lokales Routing",
    "openai": "OpenAI-Ökosystem",
    "ai-api": "KI + API",
    "ai-web": "KI + Web",
    "ai-python": "KI + Python",
    "autonomous-ai": "Autonome KI",
    agentic: "Agentische Workflows",
    "multi-agent": "Multi-Agent-Systeme",
    orchestration: "Agent-Orchestrierung",
    "tool-calling": "Tool- & Function-Calling",
    routing: "Tool- & Modell-Routing",
    prompting: "Strukturiertes Prompting",
    "ai-assisted": "KI-gestützte Entwicklung",
    "ai-research": "KI-Recherche-Workflows",
    "code-analysis": "Codeanalyse",
    "ai-debugging": "KI-Debugging",
    "ai-testing": "KI-Testing",
    "ai-refactoring": "KI-Refactoring",
    "ai-docs": "KI-Dokumentation",
    "human-review": "Human-in-the-Loop-Prüfung",
    context: "Context Engineering",
    testing: "Tests",
  },
  notes: {
    python:
      "Der Knotenpunkt des Boards. Python-Skripte rufen KI-APIs auf, transformieren Daten, verarbeiten Dateien, steuern lokale Modelle und geben Agents Werkzeuge, die wirklich funktionieren.",
    chatgpt:
      "Recherche, Analyse, Abwägen von Optionen, Entwürfe für Spezifikationen und Inhalte, Tool-Nutzung und eine zweite Meinung bei der Prüfung.",
    claude: "Reasoning mit langem Kontext über Spezifikationen und Codebasen, strukturierte Ausgaben und API-Integration in Produkte.",
    "claude-code":
      "Repository-Analyse, Planung, Delegation an Subagents, Umsetzung, Refactoring, Debugging, Tests, Review und Git-Workflows – alles geprüft, bevor etwas live geht.",
    nextjs: "Komplette Websites und Web-Apps: Server-Rendering, Routing, Server Actions und API-Routen in einer Codebasis.",
    react: "Komponentensysteme, die konsistent bleiben, während ein Produkt wächst.",
    backend: "Serverlogik mit Validierung, Authentifizierungskonzepten und klarer Fehlerbehandlung hinter jedem Formular und Feature.",
    postgresql: "Relationale Datenmodelle für Anfragen, Nutzende, Inhalte und alles, was zuverlässig abgefragt werden muss.",
    "api-integration": "Zahlungs-, E-Mail-, CRM-, KI- und interne APIs zu einem berechenbaren Ablauf verbinden.",
    n8n: "Trigger, Webhooks, Zeitpläne und API-Übergaben als sichtbare Workflows – deterministische Automatisierung rund um die KI-Schritte.",
    vercel: "Preview- und Produktions-Deployments direkt aus GitHub; Umgebungsvariablen bleiben außerhalb des Codes.",
    "autonomous-ai": "Zielgerichtete Loops, die planen, handeln, prüfen und an einem Checkpoint anhalten – nie grenzenlose Autonomie.",
    orchestration: "Arbeit auf Agents verteilen, Kontext zwischen ihnen weitergeben und Ergebnisse zusammenführen.",
    "multi-agent": "Spezialisierte Agents für Design, Frontend, Backend, Tests und Review, koordiniert von einem Orchestrator.",
    "tool-calling": "Ein Modell echte Funktionen aufrufen lassen – Suche, Datenbank, API – mit validierten Ein- und Ausgaben.",
    "local-models": "Modelle auf eigener Hardware ausführen, wenn Daten das Haus nicht verlassen sollen.",
    rag: "Fragen aus eigenen Dokumenten beantworten, indem zuerst die passenden Abschnitte gesucht werden.",
    "hybrid-routing": "Jede Anfrage an ein Cloud- oder lokales Modell leiten – nach Datenschutz, Fähigkeit, Kosten, Latenz und Verfügbarkeit.",
    "human-review": "Jede KI-erzeugte Änderung wird von einem Menschen geprüft, getestet und freigegeben, bevor sie in Produktion geht.",
    "py-automation": "Wiederkehrende Arbeit wird zu geplanten, protokollierten und testbaren Pipelines.",
    "py-local-ai": "Python-Dienste, die Dokumente laden, Embeddings berechnen und mit lokalen Modell-Endpunkten sprechen.",
  },
  uses: {
    chatgpt: ["Recherche", "Analyse", "Reasoning", "Spezifikation", "Inhalte", "Tool-Nutzung", "Entwicklungsunterstützung", "Prüfung"],
    "claude-code": ["Repository-Analyse", "Planung", "Subagent-Delegation", "Umsetzung", "Refactoring", "Debugging", "Tests", "Review", "Git-Workflows", "Deployment-Unterstützung"],
  },
  ui: {
    boardLabel: "Fähigkeitsnetzwerk",
    selected: "Ausgewählt",
    connectsTo: "Verbunden mit",
    usedFor: "Eingesetzt für",
    builds: "Was das möglich macht",
    connections: "{n} Verbindungen",
    status: "{label} ausgewählt, {n} Verbindungen hervorgehoben.",
    hint: "Wähle einen Knoten. Mit Tab wechselst du zwischen Knoten.",
    jump: "Direkt zu",
    concept: "Architekturkonzept",
    reset: "Zurück zu Python",
    search: "Fähigkeiten durchsuchen",
    searchPlaceholder: "z. B. n8n, RAG, Next.js",
    clear: "Suche löschen",
    results: "In allen Bereichen: {n}",
    noResults: "Nichts passt zu „{q}“.",
    areas: "Bereiche",
    tabs: { python: "Python", web: "Web", ai: "KI", local: "Lokale KI" },
    browse: "Alles in {area}",
    paths: "Typische Wege",
    pathsHint: "Projekte, die hier vorbeiführen",
    hub: "Zentrum",
  },
  chains: {
    eyebrow: "Wege durch das Netzwerk",
    title: "Vier Projekte, nachgezeichnet.",
    body: "Echte Projekte folgen einem Weg über mehrere Bereiche. Hier sind typische Beispiele.",
    items: {
      redesign: { title: "Website-Redesign", outcome: "Eine schnellere, barrierearme Website, die leichter zu pflegen ist." },
      "ai-feature": { title: "KI-Feature in einem bestehenden Produkt", outcome: "Eine KI-Funktion hinter Validierung und menschlicher Prüfung." },
      "private-search": { title: "Private Dokumentensuche", outcome: "Antworten aus internen Dokumenten, ohne sie an ein Cloud-Modell zu senden." },
      automation: { title: "Workflow-Automatisierung", outcome: "Eine wiederkehrende Aufgabe, ersetzt durch eine getestete Pipeline." },
    },
  },
  cta: {
    title: "Sollen diese Bausteine in deinem Projekt verbunden werden?",
    label: "Mit KI bauen",
  },
};

const th: CapabilitiesContent = {
  meta: {
    title: "ความสามารถ",
    description:
      "เครือข่ายความสามารถที่เชื่อม Web Engineering, Python, ChatGPT, Claude, Autonomous Agent และ Local AI เข้าด้วยกันเพื่อสร้างระบบที่ใช้งานได้จริง",
  },
  hero: {
    eyebrow: "เครือข่ายความสามารถ",
    title: "ไม่ใช่คะแนนว่าเก่ง React แค่ไหน",
    titleAccent: "แต่คือสิ่งที่เชื่อมเข้าด้วยกันได้",
    lede: "Web Engineering, Python, Cloud AI และ Local AI ไม่ใช่รายการทักษะที่แยกขาดจากกัน ทั้งหมดคือส่วนหนึ่งของระบบเดียว เลือกโหนดใดก็ได้เพื่อดูว่าเชื่อมกับอะไร และทำให้อะไรเป็นไปได้",
    legendTitle: "บนบอร์ดนี้",
    nodes: "โหนด",
    links: "การเชื่อมต่อ",
    noScores: "ไม่มีเปอร์เซ็นต์ ไม่มีเลเวล ไม่มีดาว มีแต่การเชื่อมต่อ",
  },
  families: {
    web: { label: "Web Engineering", body: "อินเทอร์เฟซ เซิร์ฟเวอร์ ข้อมูล และการ Deploy" },
    python: { label: "Python", body: "ชั้นเชื่อมต่อระหว่าง AI ข้อมูล และระบบอัตโนมัติ" },
    ai: { label: "ระบบนิเวศ AI-native", body: "ChatGPT, Claude, Agent และการพัฒนาซอฟต์แวร์ด้วย AI" },
    local: { label: "Local AI", body: "Workflow ของโมเดลแบบส่วนตัว โฮสต์เอง และแบบไฮบริด" },
  },
  domains: {
    interface: { label: "อินเทอร์เฟซ", body: "UI ที่ใช้ HTML ถูกหลัก Semantic, Responsive และเข้าถึงได้ ด้วย React และ Next.js" },
    server: { label: "Backend และข้อมูล", body: "API, Validation, ฐานข้อมูล และตรรกะฝั่งเซิร์ฟเวอร์ที่ทำงานคงเส้นคงวาแม้ใช้งานจริง" },
    delivery: { label: "การส่งมอบ", body: "Version control, Testing, Performance และการ Deploy ขึ้น Production" },
    python: { label: "Python", body: "สคริปต์ ระบบอัตโนมัติ งานข้อมูล และตัวเชื่อมระหว่างโมเดลกับเครื่องมือ" },
    local: { label: "Local AI", body: "แนวคิดสถาปัตยกรรมสำหรับ AI แบบส่วนตัวและโฮสต์เอง: Local model, Embeddings และ RAG" },
    models: { label: "โมเดลและตัวเชื่อม", body: "Cloud model ผ่านแอปและ API ที่เชื่อมเข้ากับโค้ด Web และ Python" },
    autonomy: { label: "ระบบอัตโนมัติด้วย Agent", body: "Agent loop ที่ควบคุมได้: วางแผน Orchestration เรียกใช้ Tool และ Routing" },
    "ai-engineering": { label: "พัฒนาซอฟต์แวร์ด้วย AI", body: "AI อยู่ในงานพัฒนาประจำวัน โดยมีคนตรวจสอบผลลัพธ์" },
  },
  labels: {
    "ui-architecture": "UI Architecture",
    "database-design": "การออกแบบฐานข้อมูล",
    auth: "แนวคิด Authentication",
    "py-ai": "AI Integration",
    "py-data": "แปลงข้อมูล",
    "py-files": "ประมวลผลไฟล์",
    "py-scripts": "สคริปต์",
    "py-tools": "Tool Orchestration",
    "py-local-ai": "Local AI Workflow",
    "py-agent-utils": "เครื่องมือสำหรับ Agent",
    "py-devtools": "เครื่องมือนักพัฒนา",
    "py-backend-utils": "เครื่องมือฝั่ง Backend",
    "local-models": "Local model",
    "self-hosted": "Inference แบบโฮสต์เอง",
    "local-endpoints": "Local endpoint",
    privacy: "AI ที่ใส่ใจความเป็นส่วนตัว",
    offline: "Workflow ที่ทำงานออฟไลน์ได้",
    "hybrid-routing": "Routing ระหว่าง Cloud กับ Local",
    "human-review": "ตรวจสอบโดยมนุษย์ (Human-in-the-loop)",
    "ai-assisted": "พัฒนาซอฟต์แวร์ด้วย AI",
    "ai-research": "Workflow ค้นคว้าด้วย AI",
    openai: "OpenAI Ecosystem",
    "py-api-clients": "API Client",
    agentic: "Agentic Workflow",
    "multi-agent": "ระบบ Multi-agent",
    orchestration: "Agent Orchestration",
    "tool-calling": "Tool & Function Calling",
    routing: "Tool & Model Routing",
    context: "Context Engineering",
    prompting: "Structured Prompting",
    "code-analysis": "วิเคราะห์โค้ด",
    "ai-debugging": "Debug ด้วย AI",
    "ai-testing": "เทสต์ด้วย AI",
    "ai-refactoring": "Refactor ด้วย AI",
    "ai-docs": "เขียนเอกสารด้วย AI",
  },
  notes: {
    python:
      "ศูนย์กลางของบอร์ดนี้ สคริปต์ Python เรียก AI API แปลงข้อมูล ประมวลผลไฟล์ ควบคุม Local model และสร้างเครื่องมือที่ Agent ใช้งานได้จริง",
    chatgpt: "ค้นคว้า วิเคราะห์ คิดเปรียบเทียบทางเลือก ร่างสเปกและเนื้อหา ใช้ Tool และเป็นความเห็นที่สองระหว่างตรวจสอบงาน",
    claude: "Reasoning กับสเปกและโค้ดเบสขนาดใหญ่ด้วย context ยาว ให้ผลลัพธ์แบบมีโครงสร้าง และเชื่อมเข้ากับผลิตภัณฑ์ผ่าน API",
    "claude-code":
      "วิเคราะห์ Repository วางแผน แบ่งงานให้ Subagent ลงมือเขียนโค้ด Refactor Debug เขียนเทสต์ Review และจัดการ Git workflow โดยทุกอย่างผ่านการตรวจสอบก่อนขึ้นระบบจริง",
    nextjs: "เว็บไซต์และเว็บแอปครบวงจร: Server rendering, Routing, Server Actions และ API route ในโค้ดเบสเดียว",
    react: "ระบบคอมโพเนนต์ที่ยังคงสม่ำเสมอแม้ผลิตภัณฑ์จะเติบโตขึ้น",
    backend: "ตรรกะฝั่งเซิร์ฟเวอร์ที่มี Validation แนวคิด Authentication และการจัดการ error ที่ชัดเจนอยู่เบื้องหลังทุกฟอร์มและฟีเจอร์",
    postgresql: "โมเดลข้อมูลเชิงสัมพันธ์สำหรับข้อความติดต่อ ผู้ใช้ เนื้อหา และทุกอย่างที่ต้องค้นหาได้อย่างแม่นยำ",
    "api-integration": "เชื่อม API ด้านการชำระเงิน อีเมล CRM AI และระบบภายในให้ทำงานเป็นขั้นตอนเดียวที่คาดเดาได้",
    n8n: "Trigger, Webhook, ตารางเวลา และการส่งต่อข้อมูลผ่าน API เป็น Workflow ที่มองเห็นได้ ทำงานแบบกำหนดแน่นอนรอบขั้นตอนที่ใช้ AI",
    vercel: "Deploy ทั้ง Preview และ Production จาก GitHub โดยตรง พร้อมแยกค่าคอนฟิกออกจากโค้ด",
    "autonomous-ai": "Loop ที่ขับเคลื่อนด้วยเป้าหมาย วางแผน ลงมือ ตรวจสอบ และหยุดที่ checkpoint ไม่ใช่ปล่อยให้ทำงานไร้ขอบเขต",
    orchestration: "แบ่งงานให้หลาย Agent ส่งต่อ context ระหว่างกัน และรวบรวมผลลัพธ์",
    "multi-agent": "Agent เฉพาะทางด้าน Design, Frontend, Backend, Test และ Review ที่ทำงานประสานกันภายใต้ Orchestrator ตัวเดียว",
    "tool-calling": "ให้โมเดลเรียกฟังก์ชันจริง เช่น ค้นหา ฐานข้อมูล หรือ API โดยตรวจสอบทั้ง input และ output",
    "local-models": "รันโมเดลบนฮาร์ดแวร์ของตัวเอง เมื่อข้อมูลไม่ควรออกนอกองค์กร",
    rag: "ตอบคำถามจากเอกสารขององค์กรเอง โดยค้นหาส่วนที่เกี่ยวข้องก่อนแล้วค่อยให้โมเดลตอบ",
    "hybrid-routing": "ส่งแต่ละคำขอไปยัง Cloud หรือ Local model ตามความเป็นส่วนตัว ความสามารถ ต้นทุน ความหน่วง และความพร้อมใช้งาน",
    "human-review": "ทุกการเปลี่ยนแปลงที่ AI สร้างขึ้นต้องผ่านการรีวิว ทดสอบ และอนุมัติโดยคนก่อนขึ้น Production",
    "py-automation": "เปลี่ยนงานซ้ำซากให้เป็น Pipeline ที่ตั้งเวลาได้ มี log และทดสอบได้",
    "py-local-ai": "บริการ Python ที่โหลดเอกสาร สร้าง Embeddings และคุยกับ Local model endpoint",
  },
  uses: {
    chatgpt: ["ค้นคว้า", "วิเคราะห์", "Reasoning", "เขียนสเปก", "เนื้อหา", "ใช้ Tool", "ช่วยงานพัฒนา", "ตรวจสอบ"],
    "claude-code": ["วิเคราะห์ Repository", "วางแผน", "แบ่งงานให้ Subagent", "เขียนโค้ด", "Refactor", "Debug", "เทสต์", "Review", "Git workflow", "ช่วยเรื่อง Deploy"],
  },
  ui: {
    boardLabel: "เครือข่ายความสามารถ",
    selected: "ที่เลือก",
    connectsTo: "เชื่อมกับ",
    usedFor: "ใช้สำหรับ",
    builds: "สิ่งที่ทำได้",
    connections: "{n} การเชื่อมต่อ",
    status: "เลือก {label} แล้ว ไฮไลต์ {n} การเชื่อมต่อ",
    hint: "เลือกโหนด ใช้ปุ่ม Tab เพื่อเลื่อนไปยังโหนดอื่น",
    jump: "ไปที่",
    concept: "แนวคิดสถาปัตยกรรม",
    reset: "กลับไปที่ Python",
    search: "ค้นหาความสามารถ",
    searchPlaceholder: "เช่น n8n, RAG, Next.js",
    clear: "ล้างการค้นหา",
    results: "จากทุกหมวด: {n} รายการ",
    noResults: "ไม่พบรายการที่ตรงกับ “{q}”",
    areas: "หมวด",
    tabs: { python: "Python", web: "Web", ai: "AI", local: "Local AI" },
    browse: "ทั้งหมดในหมวด {area}",
    paths: "เส้นทางการสร้างงาน",
    pathsHint: "งานทั่วไปที่ผ่านจุดนี้",
    hub: "ศูนย์กลาง",
  },
  chains: {
    eyebrow: "เส้นทางผ่านเครือข่าย",
    title: "สี่งาน สี่เส้นทาง",
    body: "โปรเจกต์จริงมักเดินผ่านหลายส่วนของเครือข่าย นี่คือเส้นทางที่พบบ่อย",
    items: {
      redesign: { title: "Redesign เว็บไซต์", outcome: "เว็บที่เร็วขึ้น เข้าถึงได้ และดูแลต่อได้ง่ายขึ้น" },
      "ai-feature": { title: "เพิ่มฟีเจอร์ AI ให้ระบบเดิม", outcome: "ความสามารถด้าน AI ที่มี Validation และการตรวจสอบโดยคนคุมอยู่" },
      "private-search": { title: "ค้นหาเอกสารแบบส่วนตัว", outcome: "ได้คำตอบจากเอกสารภายใน โดยไม่ต้องส่งเอกสารขึ้น Cloud model" },
      automation: { title: "Workflow อัตโนมัติ", outcome: "เปลี่ยนงานซ้ำซากให้เป็น Pipeline ที่ผ่านการทดสอบ" },
    },
  },
  cta: {
    title: "อยากให้ชิ้นส่วนเหล่านี้ทำงานร่วมกันในโปรเจกต์ไหม",
    label: "สร้างด้วย AI",
  },
};

export const capabilitiesContent: Localized<CapabilitiesContent> = { en, de, th };
