import type { Localized } from "@/i18n/config";

export const caseStepIds = [
  "problem",
  "constraints",
  "decision",
  "architecture",
  "implementation",
  "tradeoffs",
  "testing",
  "deployment",
  "future",
] as const;
export type CaseStepId = (typeof caseStepIds)[number];

export interface CaseSection {
  /** One plain-language sentence for clients. */
  client: string;
  /** Technical detail for developers. */
  body: string;
  points: string[];
}

export interface TreeNode {
  label: string;
  children?: { edge: string; node: TreeNode }[];
}

export interface DiagramNode {
  label: string;
  detail: string;
}

export type DiagramContent =
  | { kind: "flow" | "layers"; title: string; caption: string; nodes: DiagramNode[] }
  | { kind: "tree"; title: string; caption: string; root: TreeNode }
  | { kind: "branch"; title: string; caption: string; before: DiagramNode[]; branches: DiagramNode[]; after: DiagramNode[] };

export interface CaseContent {
  id: string;
  kind: "demo" | "concept";
  /** Which service from the offer this case demonstrates. */
  service: string;
  title: string;
  tagline: string;
  facts: { label: string; value: string }[];
  stack: string[];
  sections: Record<CaseStepId, CaseSection>;
  /** Diagrams are attached to the chapter they illustrate. */
  diagrams: Partial<Record<CaseStepId, DiagramContent>>;
}

export interface CaseStudiesContent {
  meta: { title: string; description: string };
  hero: { eyebrow: string; title: string; titleEmph: string; lede: string };
  labels: {
    documents: string;
    kind: Record<CaseContent["kind"], string>;
    kindNote: Record<CaseContent["kind"], string>;
    service: string;
    stack: string;
    steps: Record<CaseStepId, string>;
    diagram: string;
    forClients: string;
    technical: string;
    reading: { label: string; full: string; overview: string };
    switcher: string;
    chapters: string;
  };
  cases: CaseContent[];
  cta: { label: string; title: string; body: string };
}

const en: CaseStudiesContent = {
  meta: {
    title: "Case studies",
    description:
      "How projects are reasoned, from problem to deployment: this portfolio's real architecture, plus a website-redesign concept and an AI-feature concept — clearly labelled.",
  },
  hero: {
    eyebrow: "Case studies",
    title: "Decisions,",
    titleEmph: "documented.",
    lede: "Each case runs from problem to deployment. Every chapter opens with one line in plain language; the technical detail follows.",
  },
  labels: {
    documents: "Documents",
    kind: { demo: "Technical demonstration", concept: "Concept project" },
    kindNote: {
      demo: "Real, running software — the site you are reading.",
      concept: "A design exercise. No real client; nothing was delivered.",
    },
    service: "Service",
    stack: "Stack",
    steps: {
      problem: "Problem",
      constraints: "Constraints",
      decision: "Design decision",
      architecture: "Architecture",
      implementation: "Implementation",
      tradeoffs: "Tradeoffs",
      testing: "Testing",
      deployment: "Deployment",
      future: "Future improvements",
    },
    diagram: "Diagram",
    forClients: "In short",
    technical: "Technical detail",
    reading: { label: "Reading mode", full: "Full detail", overview: "Quick overview" },
    switcher: "Choose a case",
    chapters: "Chapters",
  },
  cases: [
    {
      id: "portfolio",
      kind: "demo",
      service: "Full-stack build, idea to production",
      title: "This portfolio: a multilingual site with a real backend",
      tagline: "Ten pages in three languages, a contact pipeline that sends real email, and a circuit diagram generated by Python — deployed on Vercel.",
      facts: [
        { label: "Status", value: "Live — you are reading it" },
        { label: "Scope", value: "Design, frontend, backend, EN/DE/TH copy, deployment" },
      ],
      stack: ["Next.js", "TypeScript", "Tailwind CSS", "Zod", "Resend", "Python", "Vitest", "Playwright", "Vercel"],
      sections: {
        problem: {
          client: "A portfolio should prove the work, not just describe it — in the languages people actually read.",
          body: "Most developer portfolios are a list of logos and claims. This one had to let a visitor check the craft directly: real forms, real server code, a real deployment, readable in English, German and Thai.",
          points: ["Show running software, not screenshots", "Make the offer clear on the first screen", "Keep every claim checkable — the source is public"],
        },
        constraints: {
          client: "Three languages, no paid CMS, and it must stay fast and maintainable by one person.",
          body: "One developer maintains everything, so the architecture favours fewer moving parts over features. Copy lives in the repository; there is no runtime translation service and no database needed to render a page.",
          points: [
            "Equal quality in three locales, including Thai line height and wrapping",
            "No secrets in the browser; contact delivery stays server-side",
            "Pages must still render if GitHub's API or the database is unavailable",
          ],
        },
        decision: {
          client: "Every language has its own address, so a link always opens in the right language.",
          body: "The locale lives in the path (/en, /de, /th). A small proxy redirects unprefixed URLs using a remembered choice or the browser's language, and switching language keeps you on the same page.",
          points: [
            "Typed dictionaries: a missing German or Thai string fails the type check",
            "Server Components by default; client code only where something is interactive",
            "One set of design tokens; each page gets its own composition",
          ],
        },
        architecture: {
          client: "Pages are pre-built and served from the edge; only the contact form and status check run on a server.",
          body: "The Next.js App Router renders every page route statically at build time. The contact form posts to a Server Action, and /api/health is a Route Handler that reports safe, non-secret status.",
          points: [],
        },
        implementation: {
          client: "An enquiry is checked, protected against spam and delivered by email — or the form says honestly that it couldn't be.",
          body: "The Server Action validates input with a Zod schema whose errors are stable codes, translated in the browser. A honeypot field and a per-visitor rate limit run before delivery. A delivery service then sends to every configured channel: Resend email with Reply-To set to the sender, plus optional PostgreSQL and webhook.",
          points: [
            "Success only when at least one channel accepted the message",
            "Email content is HTML-escaped and subjects are stripped of line breaks",
            "The AI circuit is generated by a Python script and committed as JSON and SVG, so production never runs Python",
          ],
        },
        tradeoffs: {
          client: "A few choices trade convenience for reliability and lower running cost.",
          body: "Simplicity was preferred wherever the downside was acceptable for a portfolio, and each limit is documented rather than hidden.",
          points: [
            "The in-memory rate limit applies per server instance — a brake on bursts, not a global guarantee",
            "Copy in code means edits go through Git rather than a CMS",
            "Visitor confirmation emails need a verified sending domain; until then, only the owner is notified",
          ],
        },
        testing: {
          client: "Automated checks run before anything goes live.",
          body: "Unit tests cover locale routing, validation, rate limiting, email templates, delivery, the lab tools, the terminal and the generated circuit. Playwright scripts screenshot every page in every language at four screen sizes and flag console errors and horizontal overflow; a functional script exercises the real interactions.",
          points: ["Type check, lint, tests and production build gate every release", "Accessibility audited with axe across all locales"],
        },
        deployment: {
          client: "Pushing to the main branch publishes a new version, and any version can be rolled back.",
          body: "The GitHub repository is connected to Vercel. Server-side variables — Resend key, recipient and sender — are set in Vercel and never committed. /api/health reports the deployed commit and which delivery channels are active.",
          points: [],
        },
        future: {
          client: "Next: confirmations for visitors, and real project write-ups once there is work that can be shared.",
          body: "The remaining improvements are operational rather than architectural.",
          points: ["Verified sending domain for visitor confirmation emails", "A shared store for rate limiting across instances", "Real project write-ups once work can be shared"],
        },
      },
      diagrams: {
        decision: {
          kind: "tree",
          title: "Which language does a visitor see?",
          caption: "Decided once, in the proxy, before any page renders.",
          root: {
            label: "Does the URL start with /en, /de or /th?",
            children: [
              { edge: "Yes", node: { label: "Render that locale" } },
              {
                edge: "No",
                node: {
                  label: "Is a language remembered from an earlier visit?",
                  children: [
                    { edge: "Yes", node: { label: "Redirect to the remembered locale" } },
                    { edge: "No", node: { label: "Redirect to the best match from the browser's language, else English" } },
                  ],
                },
              },
            ],
          },
        },
        architecture: {
          kind: "layers",
          title: "Layers of the site",
          caption: "Each layer has one job and can be tested on its own.",
          nodes: [
            { label: "Browser", detail: "Server-rendered HTML; small client islands for menu, palette, terminal, form and lab tools." },
            { label: "Proxy", detail: "src/proxy.ts redirects unprefixed URLs to a locale." },
            { label: "App Router", detail: "Static pages under /[locale], typed dictionaries in src/content." },
            { label: "Server Action · Route Handler", detail: "Contact submission and /api/health." },
            { label: "Validation", detail: "Zod schema, honeypot and rate limit." },
            { label: "Delivery", detail: "Resend email, optional PostgreSQL and webhook." },
          ],
        },
        implementation: {
          kind: "branch",
          title: "Life of an enquiry",
          caption: "Every configured channel is attempted; the visitor sees success only if one accepted it.",
          before: [
            { label: "Form", detail: "Client-side check with the same schema" },
            { label: "Server Action", detail: "Runs only on the server" },
            { label: "Guard", detail: "Zod · honeypot · rate limit" },
          ],
          branches: [
            { label: "Resend email", detail: "To the owner, Reply-To the sender" },
            { label: "PostgreSQL", detail: "Optional, when configured" },
            { label: "Webhook", detail: "Optional, when configured" },
          ],
          after: [{ label: "Typed result", detail: "success · invalid · rate-limited · unavailable · error" }],
        },
        deployment: {
          kind: "flow",
          title: "From commit to production",
          caption: "Generated artifacts are committed, so the build needs no Python.",
          nodes: [
            { label: "Generate", detail: "python3 scripts/generate_ai_circuit.py" },
            { label: "Verify", detail: "Lint, types, tests, build" },
            { label: "Push", detail: "main on GitHub" },
            { label: "Build", detail: "Vercel builds and prerenders" },
            { label: "Release", detail: "Production deployment" },
            { label: "Check", detail: "/api/health and live QA" },
          ],
        },
      },
    },
    {
      id: "redesign",
      kind: "concept",
      service: "Website redesign",
      title: "Redesigning an outdated small-business website",
      tagline: "A concept for turning a slow, hard-to-edit site into a clear, fast one — without losing search visibility or existing links.",
      facts: [
        { label: "Status", value: "Concept — no client, not delivered" },
        { label: "Scope", value: "Audit, content structure, design system, migration plan" },
      ],
      stack: ["Next.js", "TypeScript", "Headless CMS or Markdown", "Image optimisation", "Server Actions", "Redirect map"],
      sections: {
        problem: {
          client: "Visitors can't find services or prices on a phone, and the owner can't update the site without help.",
          body: "The typical starting point: a theme-based site that grew page by page, with services buried in long text, a contact form that only sometimes works, and slow, oversized images.",
          points: ["No clear path from a service to an enquiry", "Content duplicated across pages and drifting apart", "Layouts that break on small screens"],
        },
        constraints: {
          client: "Existing links and search visibility must survive, and the owner must be able to edit content afterwards.",
          body: "A redesign that loses inbound links or rankings creates a new problem. The budget suits a small business, existing photography has to be reused, and editing has to work for someone who is not a developer.",
          points: ["Every old URL keeps working or redirects", "Content editing without touching code", "Accessibility as a baseline, not an extra"],
        },
        decision: {
          client: "Rebuild around what visitors want to do — understand a service, then ask about it — instead of copying the old menu.",
          body: "The content is restructured first: one page per service with a consistent shape (what, for whom, how it works, price guidance, enquiry), then a small design system that every page reuses.",
          points: ["Content model before visual design", "One enquiry path, reachable from every service", "Mobile layouts designed, not just stacked"],
        },
        architecture: {
          client: "The new site is pre-built for speed, with content edited in a simple editor.",
          body: "Pages are statically generated from a headless CMS (or Markdown in Git for very small sites). Images are resized at build time. The enquiry form posts to a server function that validates and emails the owner.",
          points: [],
        },
        implementation: {
          client: "The work happens in clear stages, each one reviewed before the next begins.",
          body: "An audit inventories every URL and its traffic, then a content model and design tokens are agreed. Templates are built against real content, and a redirect map links every old URL to its new home before launch.",
          points: ["Redirect map stored as data and checked automatically", "Templates built against real content, not placeholder text", "Form delivery tested end to end before launch"],
        },
        tradeoffs: {
          client: "Some choices keep the site simpler to run, even if they rule out a few extras.",
          body: "A headless CMS adds a service to maintain; Markdown in Git is cheaper but less friendly for non-developers. A custom design costs more than a theme but avoids fighting it later.",
          points: ["No heavy animation in the hero: speed and clarity first", "Fewer, better pages rather than migrating everything", "CMS choice made per client, not by default"],
        },
        testing: {
          client: "Before launch, every old link, form and page is checked automatically.",
          body: "An automated test requests every URL in the redirect map and expects a permanent redirect to the right page. Pages are checked at several screen sizes, with an accessibility audit and a performance budget.",
          points: ["Redirect map: every old URL resolves", "Form: validation, delivery and error states", "Accessibility and contrast checks on every template"],
        },
        deployment: {
          client: "The owner reviews a private preview, then the new site replaces the old one with no downtime.",
          body: "Every change gets a preview URL for review. Launch is a DNS switch to the new deployment, followed by watching 404 logs and search console for missed URLs.",
          points: ["Preview deployments for approval", "Rollback is one click", "404 monitoring in the first weeks"],
        },
        future: {
          client: "Once the foundation is solid, features can be added without another redesign.",
          body: "A clean content model makes later additions incremental.",
          points: ["Online booking or quotes", "A second language", "Analytics reviewed against the enquiry path"],
        },
      },
      diagrams: {
        decision: {
          kind: "tree",
          title: "Keep, merge or retire an old page?",
          caption: "Applied to every URL found in the audit.",
          root: {
            label: "Does the page get traffic or inbound links?",
            children: [
              {
                edge: "Yes",
                node: {
                  label: "Is its content still accurate?",
                  children: [
                    { edge: "Yes", node: { label: "Keep: rebuild on the new template, same or redirected URL" } },
                    { edge: "No", node: { label: "Merge into the matching service page and redirect" } },
                  ],
                },
              },
              { edge: "No", node: { label: "Retire: redirect to the closest parent page" } },
            ],
          },
        },
        implementation: {
          kind: "flow",
          title: "Redesign process",
          caption: "Each stage ends with something the owner can review.",
          nodes: [
            { label: "Audit", detail: "URLs, traffic, content, issues" },
            { label: "Content model", detail: "Page types and fields" },
            { label: "Design system", detail: "Type, colour, components" },
            { label: "Templates", detail: "Built with real content" },
            { label: "Migration", detail: "Content and redirect map" },
            { label: "Launch", detail: "DNS switch and monitoring" },
          ],
        },
      },
    },
    {
      id: "ai-feature",
      kind: "concept",
      service: "Feature development · AI integration",
      title: "Adding AI-drafted replies to an existing support tool",
      tagline: "A concept for bringing AI into a product people already use: drafts, not autopilot, with a person approving every message.",
      facts: [
        { label: "Status", value: "Concept — no client, not delivered" },
        { label: "Scope", value: "Feature design, AI architecture, rollout plan" },
      ],
      stack: ["React", "Node.js API", "PostgreSQL", "Python worker", "Embeddings · RAG", "Cloud + local models", "Feature flags"],
      sections: {
        problem: {
          client: "A support team answers the same questions all day; AI could draft replies, but the existing tool has to keep working.",
          body: "The product is an established helpdesk with a React frontend, a Node.js API and PostgreSQL. Agents retype similar answers from a knowledge base, and response quality depends on who is on shift.",
          points: ["Repetitive answers take most of the time", "The knowledge base exists but is hard to search", "A rewrite is not an option"],
        },
        constraints: {
          client: "Customer data must stay protected, costs must be predictable, and the feature must be easy to switch off.",
          body: "Some customers' contracts require that their data never leaves the company's own servers. Model calls cost money per request, and the team needs a kill switch if anything goes wrong.",
          points: ["Per-tenant privacy rules", "Budget caps on model usage", "Zero impact on the existing workflow when disabled"],
        },
        decision: {
          client: "The AI drafts, a person decides. Nothing is sent without approval.",
          body: "The feature suggests a reply with the knowledge-base sources it used, and the agent edits and sends it. The output is structured (draft, sources, confidence notes) so the UI can show where every claim came from.",
          points: ["Draft, never auto-send", "Sources shown with every suggestion", "Rollout behind a feature flag per team"],
        },
        architecture: {
          client: "A router sends each request to a cloud model or a private local model, depending on the customer's privacy rules.",
          body: "A context builder retrieves relevant articles with embeddings search. A model router picks a cloud model (such as ChatGPT or Claude via their APIs) for standard tenants and a self-hosted model for privacy-restricted ones. Every draft passes validation before it reaches the UI.",
          points: [],
        },
        implementation: {
          client: "The feature slots into the existing product as a suggestion panel; nothing else changes for the team.",
          body: "A Python worker ingests the knowledge base into an embeddings index. A new endpoint in the existing Node.js API builds context, calls the router and validates the structured response. The React app gains a suggestion panel beside the reply box; an audit log records every draft and edit.",
          points: ["Structured output validated against a schema", "Personal data check before any cloud call", "Audit log of drafts, edits and approvals"],
        },
        tradeoffs: {
          client: "Private local models protect data but may write slightly weaker drafts; that choice is made per customer.",
          body: "Local models trade some quality and speed for data control. Retrieval keeps answers grounded but needs the index kept fresh. Caps keep costs predictable at the price of occasionally skipping a draft.",
          points: ["Quality vs. privacy, chosen per tenant", "Freshness of the index vs. ingestion cost", "Skip a draft rather than exceed a budget"],
        },
        testing: {
          client: "Drafts are checked against real past questions before any team sees them.",
          body: "An evaluation set of anonymised past tickets compares drafts with the answers that were actually sent. Schema and safety checks run on every response, and failure paths fall back to the normal workflow.",
          points: ["Evaluation set from anonymised history", "Schema, personal-data and length checks", "Graceful fallback: no draft, no disruption"],
        },
        deployment: {
          client: "It starts invisible, then opt-in, then default — and can be switched off instantly.",
          body: "Shadow mode first: drafts are generated and logged but not shown. Then opt-in for one team, then default on. A feature flag doubles as the kill switch.",
          points: ["Shadow mode → opt-in → default", "Per-team feature flags", "Kill switch without a redeploy"],
        },
        future: {
          client: "The same pipeline can later tag, summarise and route tickets.",
          body: "With retrieval, routing and validation in place, related features reuse the pipeline.",
          points: ["Automatic tagging and routing", "Thread summaries for handovers", "Learning from agents' edits"],
        },
      },
      diagrams: {
        architecture: {
          kind: "branch",
          title: "Draft pipeline",
          caption: "The router chooses the model per tenant; validation and a person stand between the model and the customer.",
          before: [
            { label: "Ticket", detail: "Incoming question" },
            { label: "Context", detail: "Embeddings search over the knowledge base" },
            { label: "Router", detail: "Privacy rules · budget · availability" },
          ],
          branches: [
            { label: "Cloud model", detail: "ChatGPT or Claude via API" },
            { label: "Local model", detail: "Self-hosted, data stays in-house" },
          ],
          after: [
            { label: "Validation", detail: "Schema · personal data · length" },
            { label: "Human approval", detail: "Agent edits and sends" },
          ],
        },
        deployment: {
          kind: "flow",
          title: "Rollout",
          caption: "Each step can be reversed with a flag.",
          nodes: [
            { label: "Shadow", detail: "Drafts logged, not shown" },
            { label: "Evaluate", detail: "Compare with sent answers" },
            { label: "Opt-in", detail: "One team, feedback loop" },
            { label: "Default", detail: "On for all teams" },
          ],
        },
      },
    },
  ],
  cta: {
    label: "Contact me",
    title: "Like how this is reasoned?",
    body: "I'm open to junior IT roles and Quereinsteiger positions in web development, automation and AI-assisted digital work. Describe the role and I'll reply with how my experience fits.",
  },
};

const de: CaseStudiesContent = {
  meta: {
    title: "Fallstudien",
    description:
      "Wie Projekte durchdacht werden, vom Problem bis zum Deployment: die echte Architektur dieses Portfolios, dazu ein Redesign-Konzept und ein KI-Feature-Konzept – klar gekennzeichnet.",
  },
  hero: {
    eyebrow: "Fallstudien",
    title: "Entscheidungen,",
    titleEmph: "dokumentiert.",
    lede: "Jeder Fall führt vom Problem bis zum Deployment. Jedes Kapitel beginnt mit einem Satz in einfacher Sprache; danach folgen die technischen Details.",
  },
  labels: {
    documents: "Dokumente",
    kind: { demo: "Technische Demonstration", concept: "Konzeptprojekt" },
    kindNote: {
      demo: "Echte, laufende Software – die Website, die du gerade liest.",
      concept: "Eine Entwurfsübung. Kein echter Auftrag, nichts wurde ausgeliefert.",
    },
    service: "Leistung",
    stack: "Stack",
    steps: {
      problem: "Problem",
      constraints: "Rahmenbedingungen",
      decision: "Gestaltungsentscheidung",
      architecture: "Architektur",
      implementation: "Umsetzung",
      tradeoffs: "Abwägungen",
      testing: "Tests",
      deployment: "Deployment",
      future: "Nächste Schritte",
    },
    diagram: "Diagramm",
    forClients: "Kurz gesagt",
    technical: "Technische Details",
    reading: { label: "Lesemodus", full: "Alle Details", overview: "Kurzüberblick" },
    switcher: "Fall auswählen",
    chapters: "Kapitel",
  },
  cases: [
    {
      id: "portfolio",
      kind: "demo",
      service: "Full-Stack-Entwicklung, von der Idee bis zum Livegang",
      title: "Dieses Portfolio: eine mehrsprachige Website mit echtem Backend",
      tagline: "Zehn Seiten in drei Sprachen, eine Kontaktstrecke, die echte E-Mails verschickt, und ein Schaltplan, den Python erzeugt – deployt auf Vercel.",
      facts: [
        { label: "Status", value: "Live – du liest sie gerade" },
        { label: "Umfang", value: "Design, Frontend, Backend, Texte in EN/DE/TH, Deployment" },
      ],
      stack: ["Next.js", "TypeScript", "Tailwind CSS", "Zod", "Resend", "Python", "Vitest", "Playwright", "Vercel"],
      sections: {
        problem: {
          client: "Ein Portfolio sollte die Arbeit belegen, nicht nur beschreiben – in den Sprachen, die Menschen wirklich lesen.",
          body: "Die meisten Entwickler-Portfolios sind eine Liste aus Logos und Behauptungen. Hier sollte man das Handwerk direkt prüfen können: echte Formulare, echter Servercode, ein echtes Deployment, lesbar auf Englisch, Deutsch und Thai.",
          points: ["Laufende Software statt Screenshots", "Das Angebot auf dem ersten Bildschirm klar machen", "Jede Aussage überprüfbar – der Quellcode ist öffentlich"],
        },
        constraints: {
          client: "Drei Sprachen, kein kostenpflichtiges CMS, und alles muss schnell und von einer Person wartbar bleiben.",
          body: "Eine Person pflegt alles, deshalb zählen wenige bewegliche Teile mehr als viele Features. Texte liegen im Repository; es gibt keinen Übersetzungsdienst zur Laufzeit und keine Datenbank, die zum Rendern nötig wäre.",
          points: [
            "Gleiche Qualität in drei Sprachen, inklusive Zeilenhöhe und Umbruch für Thai",
            "Keine Secrets im Browser; die Zustellung bleibt serverseitig",
            "Seiten rendern auch, wenn die GitHub-API oder die Datenbank ausfällt",
          ],
        },
        decision: {
          client: "Jede Sprache hat ihre eigene Adresse, damit ein Link immer in der richtigen Sprache öffnet.",
          body: "Die Sprache steht im Pfad (/en, /de, /th). Ein kleiner Proxy leitet URLs ohne Präfix anhand der gespeicherten Wahl oder der Browsersprache weiter, und ein Sprachwechsel behält die aktuelle Seite bei.",
          points: [
            "Typisierte Wörterbücher: Fehlt ein deutscher oder thailändischer Text, schlägt der Typecheck fehl",
            "Standardmäßig Server Components; Client-Code nur, wo etwas interaktiv ist",
            "Ein Satz Design-Tokens; jede Seite hat ihre eigene Komposition",
          ],
        },
        architecture: {
          client: "Die Seiten sind vorgerendert und kommen vom Edge; nur Kontaktformular und Statusprüfung laufen auf einem Server.",
          body: "Der Next.js App Router rendert alle Seitenrouten beim Build statisch. Das Kontaktformular sendet an eine Server Action, und /api/health ist ein Route Handler, der unkritische Statusdaten liefert.",
          points: [],
        },
        implementation: {
          client: "Eine Anfrage wird geprüft, gegen Spam geschützt und per E-Mail zugestellt – oder das Formular sagt ehrlich, dass es nicht geklappt hat.",
          body: "Die Server Action prüft die Eingaben mit einem Zod-Schema, dessen Fehler stabile Codes sind und im Browser übersetzt werden. Vor der Zustellung laufen ein Honeypot-Feld und ein Rate Limit pro Besuch. Ein Zustelldienst sendet dann an jeden konfigurierten Kanal: E-Mail über Resend mit Reply-To auf die absendende Person, dazu optional PostgreSQL und ein Webhook.",
          points: [
            "Erfolg nur, wenn mindestens ein Kanal die Nachricht angenommen hat",
            "E-Mail-Inhalte werden HTML-escaped, Betreffzeilen von Zeilenumbrüchen bereinigt",
            "Der KI-Schaltplan wird von einem Python-Skript erzeugt und als JSON und SVG eingecheckt – in Produktion läuft kein Python",
          ],
        },
        tradeoffs: {
          client: "Einige Entscheidungen tauschen Bequemlichkeit gegen Zuverlässigkeit und niedrige Betriebskosten.",
          body: "Wo der Nachteil für ein Portfolio vertretbar war, hatte Einfachheit Vorrang – und jede Grenze ist dokumentiert statt versteckt.",
          points: [
            "Das Rate Limit im Speicher gilt pro Serverinstanz – eine Bremse für Spitzen, keine globale Garantie",
            "Texte im Code bedeuten: Änderungen laufen über Git statt über ein CMS",
            "Bestätigungsmails an Besuchende brauchen eine verifizierte Absenderdomain; bis dahin geht die Benachrichtigung nur an mich",
          ],
        },
        testing: {
          client: "Automatische Prüfungen laufen, bevor etwas live geht.",
          body: "Unit-Tests decken Sprachrouting, Validierung, Rate Limit, E-Mail-Vorlagen, Zustellung, die Labor-Tools, das Terminal und den generierten Schaltplan ab. Playwright-Skripte fotografieren jede Seite in jeder Sprache in vier Bildschirmgrößen und melden Konsolenfehler und horizontales Überlaufen; ein Funktionsskript testet die echten Interaktionen.",
          points: ["Typecheck, Lint, Tests und Produktions-Build vor jedem Release", "Barrierefreiheit mit axe in allen Sprachen geprüft"],
        },
        deployment: {
          client: "Ein Push auf den main-Branch veröffentlicht eine neue Version, und jede Version lässt sich zurückrollen.",
          body: "Das GitHub-Repository ist mit Vercel verbunden. Serverseitige Variablen – Resend-Key, Empfänger und Absender – liegen in Vercel und werden nie eingecheckt. /api/health zeigt den deployten Commit und die aktiven Zustellkanäle.",
          points: [],
        },
        future: {
          client: "Als Nächstes: Bestätigungen für Besuchende und echte Projektberichte, sobald es Arbeiten gibt, die gezeigt werden dürfen.",
          body: "Die offenen Verbesserungen betreffen den Betrieb, nicht die Architektur.",
          points: ["Verifizierte Absenderdomain für Bestätigungsmails", "Gemeinsamer Speicher für das Rate Limit über Instanzen hinweg", "Echte Projektberichte, sobald Arbeiten gezeigt werden dürfen"],
        },
      },
      diagrams: {
        decision: {
          kind: "tree",
          title: "Welche Sprache sehen Besuchende?",
          caption: "Einmal im Proxy entschieden, bevor eine Seite rendert.",
          root: {
            label: "Beginnt die URL mit /en, /de oder /th?",
            children: [
              { edge: "Ja", node: { label: "Diese Sprache rendern" } },
              {
                edge: "Nein",
                node: {
                  label: "Ist eine Sprache aus einem früheren Besuch gespeichert?",
                  children: [
                    { edge: "Ja", node: { label: "Zur gespeicherten Sprache weiterleiten" } },
                    { edge: "Nein", node: { label: "Zur besten Übereinstimmung mit der Browsersprache weiterleiten, sonst Englisch" } },
                  ],
                },
              },
            ],
          },
        },
        architecture: {
          kind: "layers",
          title: "Schichten der Website",
          caption: "Jede Schicht hat eine Aufgabe und lässt sich einzeln testen.",
          nodes: [
            { label: "Browser", detail: "Serverseitig gerendertes HTML; kleine Client-Inseln für Menü, Palette, Terminal, Formular und Labor-Tools." },
            { label: "Proxy", detail: "src/proxy.ts leitet URLs ohne Präfix zu einer Sprache weiter." },
            { label: "App Router", detail: "Statische Seiten unter /[locale], typisierte Wörterbücher in src/content." },
            { label: "Server Action · Route Handler", detail: "Kontaktanfrage und /api/health." },
            { label: "Validierung", detail: "Zod-Schema, Honeypot und Rate Limit." },
            { label: "Zustellung", detail: "E-Mail über Resend, optional PostgreSQL und Webhook." },
          ],
        },
        implementation: {
          kind: "branch",
          title: "Der Weg einer Anfrage",
          caption: "Jeder konfigurierte Kanal wird versucht; Erfolg gibt es nur, wenn einer angenommen hat.",
          before: [
            { label: "Formular", detail: "Prüfung im Browser mit demselben Schema" },
            { label: "Server Action", detail: "Läuft nur auf dem Server" },
            { label: "Schutz", detail: "Zod · Honeypot · Rate Limit" },
          ],
          branches: [
            { label: "E-Mail (Resend)", detail: "An mich, Reply-To an die absendende Person" },
            { label: "PostgreSQL", detail: "Optional, falls konfiguriert" },
            { label: "Webhook", detail: "Optional, falls konfiguriert" },
          ],
          after: [{ label: "Typisiertes Ergebnis", detail: "success · invalid · rate-limited · unavailable · error" }],
        },
        deployment: {
          kind: "flow",
          title: "Vom Commit in die Produktion",
          caption: "Generierte Artefakte sind eingecheckt, der Build braucht also kein Python.",
          nodes: [
            { label: "Erzeugen", detail: "python3 scripts/generate_ai_circuit.py" },
            { label: "Prüfen", detail: "Lint, Typen, Tests, Build" },
            { label: "Pushen", detail: "main auf GitHub" },
            { label: "Bauen", detail: "Vercel baut und rendert vor" },
            { label: "Veröffentlichen", detail: "Produktions-Deployment" },
            { label: "Kontrollieren", detail: "/api/health und Live-QA" },
          ],
        },
      },
    },
    {
      id: "redesign",
      kind: "concept",
      service: "Website-Redesign",
      title: "Redesign einer veralteten Website für ein kleines Unternehmen",
      tagline: "Ein Konzept, wie aus einer langsamen, schwer pflegbaren Website eine klare, schnelle wird – ohne Sichtbarkeit in Suchmaschinen oder bestehende Links zu verlieren.",
      facts: [
        { label: "Status", value: "Konzept – kein Auftrag, nicht ausgeliefert" },
        { label: "Umfang", value: "Audit, Inhaltsstruktur, Designsystem, Migrationsplan" },
      ],
      stack: ["Next.js", "TypeScript", "Headless CMS oder Markdown", "Bildoptimierung", "Server Actions", "Redirect-Map"],
      sections: {
        problem: {
          client: "Auf dem Handy findet man weder Leistungen noch Preise, und Änderungen gehen nur mit fremder Hilfe.",
          body: "Der typische Ausgangspunkt: eine Theme-Website, die Seite für Seite gewachsen ist, Leistungen in langen Texten versteckt, ein Kontaktformular, das nur manchmal funktioniert, und langsame, übergroße Bilder.",
          points: ["Kein klarer Weg von einer Leistung zur Anfrage", "Doppelte Inhalte, die auseinanderlaufen", "Layouts, die auf kleinen Bildschirmen brechen"],
        },
        constraints: {
          client: "Bestehende Links und die Sichtbarkeit in Suchmaschinen müssen erhalten bleiben, und Inhalte sollen danach selbst pflegbar sein.",
          body: "Ein Redesign, das eingehende Links oder Rankings verliert, schafft ein neues Problem. Das Budget passt zu einem kleinen Betrieb, vorhandene Fotos werden weiterverwendet, und die Pflege muss ohne Entwicklungskenntnisse gehen.",
          points: ["Jede alte URL funktioniert weiter oder leitet um", "Inhalte pflegen, ohne Code anzufassen", "Barrierefreiheit als Grundlage, nicht als Extra"],
        },
        decision: {
          client: "Neu aufgebaut wird um das, was Besuchende tun wollen – eine Leistung verstehen und anfragen –, statt das alte Menü zu kopieren.",
          body: "Zuerst wird der Inhalt neu strukturiert: eine Seite pro Leistung mit gleicher Gliederung (was, für wen, Ablauf, Preisrahmen, Anfrage), danach ein kleines Designsystem, das jede Seite nutzt.",
          points: ["Inhaltsmodell vor visuellem Design", "Ein Anfrageweg, von jeder Leistung aus erreichbar", "Mobile Layouts gestaltet, nicht nur gestapelt"],
        },
        architecture: {
          client: "Die neue Website ist für Geschwindigkeit vorgerendert, Inhalte werden in einem einfachen Editor gepflegt.",
          body: "Seiten werden statisch aus einem Headless CMS erzeugt (bei sehr kleinen Websites aus Markdown in Git). Bilder werden beim Build skaliert. Das Anfrageformular sendet an eine Serverfunktion, die prüft und den Betrieb per E-Mail informiert.",
          points: [],
        },
        implementation: {
          client: "Die Arbeit läuft in klaren Etappen, jede wird abgenommen, bevor die nächste beginnt.",
          body: "Ein Audit erfasst jede URL samt Zugriffen, danach werden Inhaltsmodell und Design-Tokens festgelegt. Templates entstehen mit echten Inhalten, und vor dem Livegang verbindet eine Redirect-Map jede alte URL mit ihrem neuen Ziel.",
          points: ["Redirect-Map als Daten gespeichert und automatisch geprüft", "Templates mit echten Inhalten statt Platzhaltertext", "Formularzustellung vor dem Livegang komplett getestet"],
        },
        tradeoffs: {
          client: "Manche Entscheidungen halten den Betrieb einfacher, auch wenn dafür ein paar Extras wegfallen.",
          body: "Ein Headless CMS ist ein zusätzlicher Dienst; Markdown in Git ist günstiger, aber weniger freundlich für Laien. Ein eigenes Design kostet mehr als ein Theme, erspart aber, später gegen dessen Grenzen anzuarbeiten.",
          points: ["Keine schwere Animation im Hero: Tempo und Klarheit zuerst", "Weniger, bessere Seiten statt alles zu migrieren", "CMS-Wahl pro Auftrag, nicht aus Gewohnheit"],
        },
        testing: {
          client: "Vor dem Livegang werden alle alten Links, Formulare und Seiten automatisch geprüft.",
          body: "Ein automatischer Test ruft jede URL der Redirect-Map auf und erwartet eine dauerhafte Weiterleitung auf die richtige Seite. Seiten werden in mehreren Bildschirmgrößen geprüft, mit Barrierefreiheits-Audit und Performance-Budget.",
          points: ["Redirect-Map: jede alte URL führt ans Ziel", "Formular: Validierung, Zustellung und Fehlerzustände", "Barrierefreiheit und Kontrast auf jedem Template"],
        },
        deployment: {
          client: "Der Betrieb prüft eine private Vorschau, dann ersetzt die neue Website die alte ohne Ausfallzeit.",
          body: "Jede Änderung bekommt eine Vorschau-URL zur Abnahme. Der Livegang ist ein DNS-Wechsel auf das neue Deployment, danach werden 404-Logs und die Search Console auf vergessene URLs beobachtet.",
          points: ["Vorschau-Deployments zur Abnahme", "Rollback mit einem Klick", "404-Monitoring in den ersten Wochen"],
        },
        future: {
          client: "Steht das Fundament, lassen sich Funktionen ohne neues Redesign ergänzen.",
          body: "Ein sauberes Inhaltsmodell macht spätere Erweiterungen schrittweise möglich.",
          points: ["Onlinebuchung oder Angebotsanfrage", "Eine zweite Sprache", "Analytics entlang des Anfragewegs auswerten"],
        },
      },
      diagrams: {
        decision: {
          kind: "tree",
          title: "Alte Seite behalten, zusammenführen oder aufgeben?",
          caption: "Angewendet auf jede URL aus dem Audit.",
          root: {
            label: "Hat die Seite Zugriffe oder eingehende Links?",
            children: [
              {
                edge: "Ja",
                node: {
                  label: "Ist der Inhalt noch korrekt?",
                  children: [
                    { edge: "Ja", node: { label: "Behalten: auf neuem Template, gleiche oder umgeleitete URL" } },
                    { edge: "Nein", node: { label: "In die passende Leistungsseite übernehmen und umleiten" } },
                  ],
                },
              },
              { edge: "Nein", node: { label: "Aufgeben: auf die nächste übergeordnete Seite umleiten" } },
            ],
          },
        },
        implementation: {
          kind: "flow",
          title: "Ablauf des Redesigns",
          caption: "Jede Etappe endet mit etwas, das der Betrieb prüfen kann.",
          nodes: [
            { label: "Audit", detail: "URLs, Zugriffe, Inhalte, Probleme" },
            { label: "Inhaltsmodell", detail: "Seitentypen und Felder" },
            { label: "Designsystem", detail: "Schrift, Farbe, Komponenten" },
            { label: "Templates", detail: "Mit echten Inhalten gebaut" },
            { label: "Migration", detail: "Inhalte und Redirect-Map" },
            { label: "Livegang", detail: "DNS-Wechsel und Monitoring" },
          ],
        },
      },
    },
    {
      id: "ai-feature",
      kind: "concept",
      service: "Feature-Entwicklung · KI-Integration",
      title: "KI-Antwortentwürfe für ein bestehendes Support-Tool",
      tagline: "Ein Konzept, wie KI in ein Produkt kommt, das schon im Einsatz ist: Entwürfe statt Autopilot, und jede Nachricht gibt ein Mensch frei.",
      facts: [
        { label: "Status", value: "Konzept – kein Auftrag, nicht ausgeliefert" },
        { label: "Umfang", value: "Feature-Design, KI-Architektur, Rollout-Plan" },
      ],
      stack: ["React", "Node.js-API", "PostgreSQL", "Python-Worker", "Embeddings · RAG", "Cloud- und lokale Modelle", "Feature Flags"],
      sections: {
        problem: {
          client: "Ein Support-Team beantwortet ständig dieselben Fragen; KI könnte Antworten vorschreiben, aber das bestehende Tool muss weiterlaufen.",
          body: "Das Produkt ist ein etablierter Helpdesk mit React-Frontend, Node.js-API und PostgreSQL. Das Team tippt ähnliche Antworten aus einer Wissensdatenbank neu, und die Qualität hängt davon ab, wer gerade Dienst hat.",
          points: ["Wiederkehrende Antworten kosten die meiste Zeit", "Die Wissensdatenbank existiert, ist aber schwer durchsuchbar", "Ein Neubau kommt nicht infrage"],
        },
        constraints: {
          client: "Kundendaten müssen geschützt, Kosten planbar und das Feature leicht abschaltbar sein.",
          body: "Manche Kundenverträge verlangen, dass ihre Daten die eigenen Server nie verlassen. Modellaufrufe kosten pro Anfrage Geld, und das Team braucht einen Notschalter, falls etwas schiefgeht.",
          points: ["Datenschutzregeln pro Mandant", "Budgetgrenzen für Modellnutzung", "Kein Einfluss auf den bestehenden Ablauf, wenn deaktiviert"],
        },
        decision: {
          client: "Die KI entwirft, ein Mensch entscheidet. Nichts wird ohne Freigabe verschickt.",
          body: "Das Feature schlägt eine Antwort samt verwendeter Quellen aus der Wissensdatenbank vor; das Team bearbeitet und versendet sie. Die Ausgabe ist strukturiert (Entwurf, Quellen, Hinweise zur Verlässlichkeit), damit die Oberfläche zeigen kann, woher jede Aussage stammt.",
          points: ["Entwerfen, nie automatisch senden", "Quellen bei jedem Vorschlag sichtbar", "Rollout per Feature Flag pro Team"],
        },
        architecture: {
          client: "Ein Router schickt jede Anfrage an ein Cloud-Modell oder ein privates lokales Modell – je nach Datenschutzregeln der Kundschaft.",
          body: "Ein Context Builder holt passende Artikel per Embeddings-Suche. Ein Model Router wählt für Standard-Mandanten ein Cloud-Modell (etwa ChatGPT oder Claude über deren APIs) und für datenschutzsensible ein selbst gehostetes Modell. Jeder Entwurf wird validiert, bevor er die Oberfläche erreicht.",
          points: [],
        },
        implementation: {
          client: "Das Feature fügt sich als Vorschlagsbereich ins bestehende Produkt ein; sonst ändert sich für das Team nichts.",
          body: "Ein Python-Worker überführt die Wissensdatenbank in einen Embeddings-Index. Ein neuer Endpunkt in der bestehenden Node.js-API baut den Kontext, ruft den Router auf und validiert die strukturierte Antwort. Die React-App bekommt einen Vorschlagsbereich neben dem Antwortfeld; ein Audit-Log hält jeden Entwurf und jede Änderung fest.",
          points: ["Strukturierte Ausgabe gegen ein Schema validiert", "Prüfung auf personenbezogene Daten vor jedem Cloud-Aufruf", "Audit-Log für Entwürfe, Änderungen und Freigaben"],
        },
        tradeoffs: {
          client: "Private lokale Modelle schützen Daten, schreiben aber eventuell etwas schwächere Entwürfe; das wird pro Mandant entschieden.",
          body: "Lokale Modelle tauschen etwas Qualität und Tempo gegen Datenhoheit. Retrieval hält Antworten faktennah, braucht aber einen aktuellen Index. Budgetgrenzen halten Kosten planbar, dafür fällt gelegentlich ein Entwurf aus.",
          points: ["Qualität gegen Datenschutz, pro Mandant gewählt", "Aktualität des Index gegen Aufwand der Aufnahme", "Lieber kein Entwurf als ein überschrittenes Budget"],
        },
        testing: {
          client: "Entwürfe werden an echten früheren Fragen geprüft, bevor ein Team sie sieht.",
          body: "Ein Evaluierungsset aus anonymisierten alten Tickets vergleicht Entwürfe mit den tatsächlich gesendeten Antworten. Schema- und Sicherheitsprüfungen laufen bei jeder Antwort, und Fehlerpfade fallen auf den normalen Ablauf zurück.",
          points: ["Evaluierungsset aus anonymisierter Historie", "Prüfung von Schema, personenbezogenen Daten und Länge", "Sanfter Rückfall: kein Entwurf, keine Störung"],
        },
        deployment: {
          client: "Erst unsichtbar, dann freiwillig, dann Standard – und jederzeit sofort abschaltbar.",
          body: "Zuerst Schattenbetrieb: Entwürfe entstehen und werden protokolliert, aber nicht angezeigt. Dann freiwillig für ein Team, dann standardmäßig an. Das Feature Flag ist zugleich der Notschalter.",
          points: ["Schattenbetrieb → freiwillig → Standard", "Feature Flags pro Team", "Notschalter ohne neues Deployment"],
        },
        future: {
          client: "Dieselbe Pipeline kann später Tickets taggen, zusammenfassen und zuweisen.",
          body: "Sind Retrieval, Routing und Validierung vorhanden, nutzen verwandte Features die Pipeline mit.",
          points: ["Automatisches Taggen und Zuweisen", "Zusammenfassungen für Übergaben", "Lernen aus den Änderungen des Teams"],
        },
      },
      diagrams: {
        architecture: {
          kind: "branch",
          title: "Entwurfs-Pipeline",
          caption: "Der Router wählt das Modell pro Mandant; zwischen Modell und Kundschaft stehen Validierung und ein Mensch.",
          before: [
            { label: "Ticket", detail: "Eingehende Frage" },
            { label: "Kontext", detail: "Embeddings-Suche in der Wissensdatenbank" },
            { label: "Router", detail: "Datenschutz · Budget · Verfügbarkeit" },
          ],
          branches: [
            { label: "Cloud-Modell", detail: "ChatGPT oder Claude per API" },
            { label: "Lokales Modell", detail: "Selbst gehostet, Daten bleiben im Haus" },
          ],
          after: [
            { label: "Validierung", detail: "Schema · personenbezogene Daten · Länge" },
            { label: "Freigabe", detail: "Das Team bearbeitet und sendet" },
          ],
        },
        deployment: {
          kind: "flow",
          title: "Rollout",
          caption: "Jeder Schritt lässt sich per Flag zurücknehmen.",
          nodes: [
            { label: "Schatten", detail: "Entwürfe protokolliert, nicht angezeigt" },
            { label: "Auswerten", detail: "Mit gesendeten Antworten vergleichen" },
            { label: "Freiwillig", detail: "Ein Team, Feedback-Schleife" },
            { label: "Standard", detail: "Für alle Teams an" },
          ],
        },
      },
    },
  ],
  cta: {
    label: "Kontakt aufnehmen",
    title: "Gefällt Ihnen, wie hier gedacht wird?",
    body: "Ich bin offen für Junior-IT-Stellen und Quereinsteiger-Positionen in Webentwicklung, Automatisierung und KI-gestützter digitaler Arbeit. Beschreiben Sie die Stelle, und ich antworte, wie meine Erfahrung dazu passt.",
  },
};

const th: CaseStudiesContent = {
  meta: {
    title: "กรณีศึกษา",
    description:
      "เบื้องหลังการคิดโปรเจกต์ตั้งแต่ปัญหาจนถึง Deploy: สถาปัตยกรรมจริงของพอร์ตโฟลิโอนี้ พร้อมโปรเจกต์แนวคิดด้าน Website Redesign และการเพิ่มฟีเจอร์ AI ซึ่งระบุไว้ชัดเจน",
  },
  hero: {
    eyebrow: "กรณีศึกษา",
    title: "ทุกการตัดสินใจ",
    titleEmph: "มีที่มาที่ไป",
    lede: "แต่ละกรณีเล่าตั้งแต่ปัญหาจนถึง Deploy ทุกบทเริ่มด้วยสรุปหนึ่งประโยคแบบภาษาง่าย ๆ ตามด้วยรายละเอียดเชิงเทคนิค",
  },
  labels: {
    documents: "เอกสาร",
    kind: { demo: "งานสาธิตทางเทคนิค", concept: "โปรเจกต์แนวคิด" },
    kindNote: {
      demo: "ซอฟต์แวร์ที่ใช้งานจริง คือเว็บไซต์นี้เอง",
      concept: "แบบฝึกการออกแบบ ไม่มีลูกค้าจริงและไม่ได้ส่งมอบงาน",
    },
    service: "บริการ",
    stack: "Stack",
    steps: {
      problem: "ปัญหา",
      constraints: "ข้อจำกัด",
      decision: "การตัดสินใจด้านการออกแบบ",
      architecture: "สถาปัตยกรรม",
      implementation: "การพัฒนา",
      tradeoffs: "สิ่งที่ต้องแลก",
      testing: "การทดสอบ",
      deployment: "Deployment",
      future: "สิ่งที่จะพัฒนาต่อ",
    },
    diagram: "แผนภาพ",
    forClients: "สรุปสั้น ๆ",
    technical: "รายละเอียดทางเทคนิค",
    reading: { label: "โหมดการอ่าน", full: "รายละเอียดทั้งหมด", overview: "สรุปสั้น" },
    switcher: "เลือกกรณีศึกษา",
    chapters: "บท",
  },
  cases: [
    {
      id: "portfolio",
      kind: "demo",
      service: "Full-stack ตั้งแต่ไอเดียจนขึ้นระบบจริง",
      title: "พอร์ตโฟลิโอนี้: เว็บไซต์หลายภาษาที่มี Backend จริง",
      tagline: "สิบหน้าในสามภาษา ระบบติดต่อที่ส่งอีเมลจริง และแผนผังวงจรที่สร้างด้วย Python ทั้งหมด Deploy บน Vercel",
      facts: [
        { label: "สถานะ", value: "ใช้งานจริง คือเว็บไซต์นี้เอง" },
        { label: "ขอบเขต", value: "ออกแบบ Frontend Backend เนื้อหา EN/DE/TH และ Deploy" },
      ],
      stack: ["Next.js", "TypeScript", "Tailwind CSS", "Zod", "Resend", "Python", "Vitest", "Playwright", "Vercel"],
      sections: {
        problem: {
          client: "พอร์ตโฟลิโอควรพิสูจน์ฝีมือได้จริง ไม่ใช่แค่บรรยาย และต้องอ่านได้ในภาษาที่ผู้คนอ่านจริง",
          body: "พอร์ตโฟลิโอนักพัฒนาส่วนใหญ่เป็นแค่รายการโลโก้และคำอ้าง เว็บนี้ต้องให้ผู้เข้าชมตรวจฝีมือได้เอง ทั้งฟอร์มจริง โค้ดฝั่งเซิร์ฟเวอร์จริง และการ Deploy จริง อ่านได้ทั้งภาษาอังกฤษ เยอรมัน และไทย",
          points: ["แสดงซอฟต์แวร์ที่ทำงานจริง ไม่ใช่ภาพหน้าจอ", "บอกบริการให้ชัดตั้งแต่หน้าจอแรก", "ทุกข้อความตรวจสอบได้ เพราะซอร์สโค้ดเปิดสาธารณะ"],
        },
        constraints: {
          client: "สามภาษา ไม่ใช้ CMS แบบเสียเงิน และต้องเร็วและดูแลได้ด้วยคนเดียว",
          body: "ดูแลทั้งหมดโดยนักพัฒนาคนเดียว สถาปัตยกรรมจึงเน้นชิ้นส่วนน้อยมากกว่าฟีเจอร์เยอะ เนื้อหาอยู่ใน Repository ไม่มีบริการแปลขณะรันไทม์ และไม่ต้องใช้ฐานข้อมูลเพื่อแสดงหน้าเว็บ",
          points: [
            "คุณภาพเท่ากันทั้งสามภาษา รวมถึงระยะบรรทัดและการตัดคำภาษาไทย",
            "ไม่มี Secret ในเบราว์เซอร์ การส่งข้อความทำฝั่งเซิร์ฟเวอร์เท่านั้น",
            "หน้าเว็บยังแสดงได้แม้ GitHub API หรือฐานข้อมูลล่ม",
          ],
        },
        decision: {
          client: "ทุกภาษามีที่อยู่ของตัวเอง ลิงก์จึงเปิดในภาษาที่ถูกต้องเสมอ",
          body: "ภาษาอยู่ใน Path (/en, /de, /th) มี Proxy ขนาดเล็กคอยพา URL ที่ไม่มี Prefix ไปยังภาษาที่เคยเลือกไว้หรือภาษาของเบราว์เซอร์ และเมื่อเปลี่ยนภาษาจะยังอยู่หน้าเดิม",
          points: [
            "Dictionary แบบ Typed ถ้าขาดข้อความภาษาเยอรมันหรือไทย Type check จะไม่ผ่าน",
            "ใช้ Server Components เป็นค่าเริ่มต้น โค้ดฝั่ง Client เฉพาะส่วนที่โต้ตอบได้",
            "ใช้ Design Token ชุดเดียว แต่ละหน้ามีการจัดวางของตัวเอง",
          ],
        },
        architecture: {
          client: "หน้าเว็บถูกสร้างไว้ล่วงหน้าและส่งจาก Edge มีเพียงฟอร์มติดต่อกับการเช็กสถานะที่ทำงานบนเซิร์ฟเวอร์",
          body: "Next.js App Router เรนเดอร์ทุกหน้าแบบ Static ตอน Build ฟอร์มติดต่อส่งไปที่ Server Action ส่วน /api/health เป็น Route Handler ที่รายงานสถานะซึ่งไม่ใช่ข้อมูลลับ",
          points: [],
        },
        implementation: {
          client: "ข้อความที่ส่งมาจะถูกตรวจสอบ กันสแปม และส่งเป็นอีเมล หากส่งไม่ได้ ฟอร์มจะบอกตรง ๆ",
          body: "Server Action ตรวจข้อมูลด้วย Zod Schema ที่คืนค่า Error เป็นรหัสคงที่และแปลในเบราว์เซอร์ ก่อนส่งจะผ่าน Honeypot และ Rate Limit ต่อผู้ใช้ จากนั้นบริการส่งข้อความจะส่งไปทุกช่องทางที่ตั้งค่าไว้ ได้แก่ อีเมลผ่าน Resend ที่ตั้ง Reply-To เป็นผู้ส่ง และ PostgreSQL หรือ Webhook หากเปิดใช้",
          points: [
            "นับว่าสำเร็จเมื่อมีอย่างน้อยหนึ่งช่องทางรับข้อความได้",
            "เนื้อหาอีเมลถูก Escape HTML และตัดการขึ้นบรรทัดใหม่ออกจากหัวเรื่อง",
            "วงจร AI สร้างด้วยสคริปต์ Python แล้ว Commit เป็น JSON และ SVG ระบบจริงจึงไม่ต้องรัน Python",
          ],
        },
        tradeoffs: {
          client: "บางการตัดสินใจแลกความสะดวกกับความเสถียรและค่าใช้จ่ายที่ต่ำ",
          body: "เลือกความเรียบง่ายเมื่อข้อเสียยอมรับได้สำหรับพอร์ตโฟลิโอ และบันทึกข้อจำกัดทุกข้อไว้อย่างเปิดเผย",
          points: [
            "Rate Limit ในหน่วยความจำมีผลต่อเซิร์ฟเวอร์แต่ละตัว ใช้ชะลอการยิงถี่ ๆ แต่ไม่ใช่การรับประกันทั้งระบบ",
            "เนื้อหาอยู่ในโค้ด การแก้ไขจึงผ่าน Git แทน CMS",
            "อีเมลยืนยันถึงผู้เข้าชมต้องใช้โดเมนผู้ส่งที่ยืนยันแล้ว ระหว่างนี้แจ้งเตือนเฉพาะเจ้าของเว็บ",
          ],
        },
        testing: {
          client: "ทุกอย่างผ่านการตรวจอัตโนมัติก่อนขึ้นระบบจริง",
          body: "Unit test ครอบคลุมการจัดการภาษา การตรวจข้อมูล Rate Limit เทมเพลตอีเมล การส่งข้อความ เครื่องมือใน Lab Terminal และวงจรที่สร้างขึ้น สคริปต์ Playwright ถ่ายภาพทุกหน้าในทุกภาษาที่สี่ขนาดหน้าจอ แจ้ง Console Error และการล้นแนวนอน และมีสคริปต์ทดสอบการใช้งานจริง",
          points: ["Type check, Lint, Test และ Production Build ก่อนทุก Release", "ตรวจ Accessibility ด้วย axe ครบทุกภาษา"],
        },
        deployment: {
          client: "Push ขึ้น main ก็เผยแพร่เวอร์ชันใหม่ได้ทันที และย้อนกลับได้ทุกเวอร์ชัน",
          body: "Repository บน GitHub เชื่อมกับ Vercel ตัวแปรฝั่งเซิร์ฟเวอร์อย่าง Resend Key ผู้รับ และผู้ส่ง ตั้งไว้ใน Vercel และไม่เคยถูก Commit ส่วน /api/health แสดง Commit ที่ Deploy อยู่และช่องทางส่งข้อความที่เปิดใช้",
          points: [],
        },
        future: {
          client: "ขั้นต่อไป: อีเมลยืนยันถึงผู้เข้าชม และกรณีศึกษาจากโปรเจกต์จริงเมื่อมีงานที่เปิดเผยได้",
          body: "สิ่งที่เหลือเป็นเรื่องการดูแลระบบ ไม่ใช่สถาปัตยกรรม",
          points: ["โดเมนผู้ส่งที่ยืนยันแล้วสำหรับอีเมลยืนยัน", "ที่เก็บข้อมูลกลางสำหรับ Rate Limit ข้ามเซิร์ฟเวอร์", "เพิ่มกรณีศึกษาจากโปรเจกต์จริงเมื่อมีงานที่เปิดเผยได้"],
        },
      },
      diagrams: {
        decision: {
          kind: "tree",
          title: "ผู้เข้าชมจะเห็นภาษาไหน",
          caption: "ตัดสินครั้งเดียวที่ Proxy ก่อนหน้าเว็บจะเรนเดอร์",
          root: {
            label: "URL ขึ้นต้นด้วย /en, /de หรือ /th หรือไม่",
            children: [
              { edge: "ใช่", node: { label: "แสดงภาษานั้น" } },
              {
                edge: "ไม่",
                node: {
                  label: "เคยเลือกภาษาไว้จากการเข้าชมครั้งก่อนหรือไม่",
                  children: [
                    { edge: "ใช่", node: { label: "พาไปยังภาษาที่เคยเลือก" } },
                    { edge: "ไม่", node: { label: "พาไปยังภาษาที่ตรงกับเบราว์เซอร์ที่สุด ถ้าไม่มีใช้ภาษาอังกฤษ" } },
                  ],
                },
              },
            ],
          },
        },
        architecture: {
          kind: "layers",
          title: "ชั้นของเว็บไซต์",
          caption: "แต่ละชั้นมีหน้าที่เดียวและทดสอบแยกได้",
          nodes: [
            { label: "Browser", detail: "HTML ที่เรนเดอร์จากเซิร์ฟเวอร์ มี Client Component เล็ก ๆ สำหรับเมนู Palette Terminal ฟอร์ม และ Lab" },
            { label: "Proxy", detail: "src/proxy.ts พา URL ที่ไม่มี Prefix ไปยังภาษาที่เหมาะสม" },
            { label: "App Router", detail: "หน้า Static ใต้ /[locale] และ Dictionary แบบ Typed ใน src/content" },
            { label: "Server Action · Route Handler", detail: "รับข้อความติดต่อและ /api/health" },
            { label: "Validation", detail: "Zod Schema, Honeypot และ Rate Limit" },
            { label: "การส่งข้อความ", detail: "อีเมลผ่าน Resend และ PostgreSQL หรือ Webhook หากเปิดใช้" },
          ],
        },
        implementation: {
          kind: "branch",
          title: "เส้นทางของข้อความติดต่อ",
          caption: "ลองส่งทุกช่องทางที่ตั้งค่าไว้ ผู้เข้าชมจะเห็นว่าสำเร็จก็ต่อเมื่อมีช่องทางรับได้",
          before: [
            { label: "ฟอร์ม", detail: "ตรวจในเบราว์เซอร์ด้วย Schema เดียวกัน" },
            { label: "Server Action", detail: "ทำงานบนเซิร์ฟเวอร์เท่านั้น" },
            { label: "ด่านป้องกัน", detail: "Zod · Honeypot · Rate Limit" },
          ],
          branches: [
            { label: "อีเมล (Resend)", detail: "ถึงเจ้าของเว็บ Reply-To เป็นผู้ส่ง" },
            { label: "PostgreSQL", detail: "เมื่อเปิดใช้" },
            { label: "Webhook", detail: "เมื่อเปิดใช้" },
          ],
          after: [{ label: "ผลลัพธ์แบบ Typed", detail: "success · invalid · rate-limited · unavailable · error" }],
        },
        deployment: {
          kind: "flow",
          title: "จาก Commit สู่ระบบจริง",
          caption: "ไฟล์ที่สร้างขึ้นถูก Commit ไว้แล้ว การ Build จึงไม่ต้องใช้ Python",
          nodes: [
            { label: "Generate", detail: "python3 scripts/generate_ai_circuit.py" },
            { label: "ตรวจสอบ", detail: "Lint, Types, Tests, Build" },
            { label: "Push", detail: "main บน GitHub" },
            { label: "Build", detail: "Vercel Build และ Prerender" },
            { label: "Release", detail: "Production Deployment" },
            { label: "เช็ก", detail: "/api/health และ QA บนระบบจริง" },
          ],
        },
      },
    },
    {
      id: "redesign",
      kind: "concept",
      service: "Website Redesign",
      title: "Redesign เว็บไซต์เก่าของธุรกิจขนาดเล็ก",
      tagline: "แนวคิดการเปลี่ยนเว็บที่ช้าและแก้ยาก ให้เป็นเว็บที่ชัดเจนและเร็ว โดยไม่เสียอันดับการค้นหาหรือลิงก์เดิม",
      facts: [
        { label: "สถานะ", value: "แนวคิด ไม่มีลูกค้าจริง ไม่ได้ส่งมอบ" },
        { label: "ขอบเขต", value: "Audit โครงสร้างเนื้อหา Design System และแผนย้ายระบบ" },
      ],
      stack: ["Next.js", "TypeScript", "Headless CMS หรือ Markdown", "Image optimisation", "Server Actions", "Redirect map"],
      sections: {
        problem: {
          client: "เปิดบนมือถือแล้วหาบริการหรือราคาไม่เจอ และเจ้าของแก้เว็บเองไม่ได้",
          body: "จุดเริ่มต้นที่พบบ่อย: เว็บจาก Theme ที่เพิ่มหน้าไปเรื่อย ๆ บริการซ่อนอยู่ในข้อความยาว ฟอร์มติดต่อใช้ได้บ้างไม่ได้บ้าง และรูปภาพใหญ่จนโหลดช้า",
          points: ["ไม่มีเส้นทางชัดเจนจากบริการไปสู่การติดต่อ", "เนื้อหาซ้ำกันหลายหน้าและเริ่มไม่ตรงกัน", "เลย์เอาต์พังบนจอเล็ก"],
        },
        constraints: {
          client: "ลิงก์เดิมและอันดับการค้นหาต้องอยู่ครบ และเจ้าของต้องแก้เนื้อหาเองได้หลังส่งมอบ",
          body: "Redesign ที่ทำให้ลิงก์หรืออันดับหายเท่ากับสร้างปัญหาใหม่ งบประมาณเหมาะกับธุรกิจขนาดเล็ก ต้องใช้รูปถ่ายเดิม และการแก้เนื้อหาต้องทำได้โดยไม่ต้องเป็นนักพัฒนา",
          points: ["URL เดิมทุกอันยังใช้ได้หรือ Redirect ไปหน้าใหม่", "แก้เนื้อหาได้โดยไม่แตะโค้ด", "Accessibility เป็นพื้นฐาน ไม่ใช่ของเสริม"],
        },
        decision: {
          client: "สร้างใหม่โดยยึดสิ่งที่ผู้เข้าชมต้องการทำ คือเข้าใจบริการแล้วติดต่อ แทนที่จะลอกเมนูเดิม",
          body: "เริ่มจากจัดโครงสร้างเนื้อหาใหม่ บริการละหนึ่งหน้าในรูปแบบเดียวกัน (คืออะไร เหมาะกับใคร ขั้นตอน ช่วงราคา และการติดต่อ) แล้วจึงสร้าง Design System ขนาดเล็กที่ทุกหน้าใช้ร่วมกัน",
          points: ["วาง Content Model ก่อนออกแบบหน้าตา", "เส้นทางติดต่อเดียว เข้าถึงได้จากทุกบริการ", "ออกแบบเลย์เอาต์มือถือโดยเฉพาะ ไม่ใช่แค่เรียงต่อกัน"],
        },
        architecture: {
          client: "เว็บใหม่สร้างไว้ล่วงหน้าเพื่อความเร็ว และแก้เนื้อหาผ่านหน้าจอแก้ไขที่ใช้ง่าย",
          body: "หน้าเว็บสร้างแบบ Static จาก Headless CMS (หรือ Markdown ใน Git สำหรับเว็บเล็กมาก) รูปภาพถูกปรับขนาดตอน Build ฟอร์มติดต่อส่งไปยังฟังก์ชันฝั่งเซิร์ฟเวอร์ที่ตรวจข้อมูลและส่งอีเมลถึงเจ้าของ",
          points: [],
        },
        implementation: {
          client: "งานแบ่งเป็นขั้นชัดเจน ตรวจรับทีละขั้นก่อนเริ่มขั้นต่อไป",
          body: "เริ่มจาก Audit ทุก URL พร้อมจำนวนผู้เข้าชม แล้วตกลง Content Model และ Design Token สร้าง Template ด้วยเนื้อหาจริง และก่อนขึ้นระบบมี Redirect Map เชื่อม URL เดิมทุกอันไปยังหน้าใหม่",
          points: ["Redirect Map เก็บเป็นข้อมูลและตรวจอัตโนมัติ", "สร้าง Template ด้วยเนื้อหาจริง ไม่ใช่ข้อความตัวอย่าง", "ทดสอบการส่งฟอร์มครบทั้งเส้นทางก่อนขึ้นระบบ"],
        },
        tradeoffs: {
          client: "บางการตัดสินใจทำให้ดูแลง่ายขึ้น แม้จะตัดของเสริมบางอย่างออก",
          body: "Headless CMS เพิ่มบริการที่ต้องดูแล ส่วน Markdown ใน Git ถูกกว่าแต่ใช้ยากสำหรับคนทั่วไป การออกแบบเฉพาะมีค่าใช้จ่ายมากกว่า Theme แต่ไม่ต้องฝืนข้อจำกัดของ Theme ภายหลัง",
          points: ["ไม่มีแอนิเมชันหนัก ๆ ใน Hero ความเร็วและความชัดเจนมาก่อน", "หน้าน้อยลงแต่ดีขึ้น แทนการย้ายทุกอย่าง", "เลือก CMS ตามลูกค้าแต่ละราย ไม่ใช่ตามความเคยชิน"],
        },
        testing: {
          client: "ก่อนขึ้นระบบ ลิงก์เดิม ฟอร์ม และทุกหน้าจะถูกตรวจอัตโนมัติ",
          body: "การทดสอบอัตโนมัติเรียกทุก URL ใน Redirect Map และต้องได้ Redirect ถาวรไปหน้าที่ถูกต้อง ตรวจหน้าเว็บหลายขนาดหน้าจอ พร้อม Audit ด้าน Accessibility และ Performance Budget",
          points: ["Redirect Map: URL เดิมทุกอันไปถึงปลายทาง", "ฟอร์ม: การตรวจข้อมูล การส่ง และสถานะผิดพลาด", "ตรวจ Accessibility และ Contrast ทุก Template"],
        },
        deployment: {
          client: "เจ้าของตรวจผ่านลิงก์พรีวิวส่วนตัว จากนั้นเว็บใหม่แทนที่เว็บเดิมโดยไม่มีช่วงล่ม",
          body: "ทุกการแก้ไขมี Preview URL ให้ตรวจรับ การขึ้นระบบคือการสลับ DNS ไปยัง Deployment ใหม่ แล้วเฝ้าดู Log 404 และ Search Console เพื่อหา URL ที่ตกหล่น",
          points: ["Preview Deployment สำหรับตรวจรับ", "ย้อนกลับได้ในคลิกเดียว", "เฝ้าดู 404 ในช่วงสัปดาห์แรก"],
        },
        future: {
          client: "เมื่อฐานแน่นแล้ว เพิ่มฟีเจอร์ได้โดยไม่ต้อง Redesign ใหม่",
          body: "Content Model ที่สะอาดทำให้ต่อยอดทีละส่วนได้",
          points: ["จองหรือขอใบเสนอราคาออนไลน์", "เพิ่มภาษาที่สอง", "วิเคราะห์ Analytics ตามเส้นทางการติดต่อ"],
        },
      },
      diagrams: {
        decision: {
          kind: "tree",
          title: "หน้าเดิม เก็บไว้ รวม หรือเลิกใช้",
          caption: "ใช้กับทุก URL ที่พบใน Audit",
          root: {
            label: "หน้านี้มีผู้เข้าชมหรือลิงก์จากที่อื่นหรือไม่",
            children: [
              {
                edge: "มี",
                node: {
                  label: "เนื้อหายังถูกต้องอยู่หรือไม่",
                  children: [
                    { edge: "ใช่", node: { label: "เก็บไว้: สร้างใหม่บน Template ใช้ URL เดิมหรือ Redirect" } },
                    { edge: "ไม่", node: { label: "รวมเข้ากับหน้าบริการที่ตรงกันแล้ว Redirect" } },
                  ],
                },
              },
              { edge: "ไม่มี", node: { label: "เลิกใช้: Redirect ไปหน้าหลักที่ใกล้ที่สุด" } },
            ],
          },
        },
        implementation: {
          kind: "flow",
          title: "ขั้นตอน Redesign",
          caption: "ทุกขั้นจบด้วยสิ่งที่เจ้าของตรวจรับได้",
          nodes: [
            { label: "Audit", detail: "URL ผู้เข้าชม เนื้อหา และปัญหา" },
            { label: "Content Model", detail: "ประเภทหน้าและฟิลด์" },
            { label: "Design System", detail: "ตัวอักษร สี และคอมโพเนนต์" },
            { label: "Template", detail: "สร้างด้วยเนื้อหาจริง" },
            { label: "ย้ายระบบ", detail: "เนื้อหาและ Redirect Map" },
            { label: "ขึ้นระบบ", detail: "สลับ DNS และเฝ้าดู" },
          ],
        },
      },
    },
    {
      id: "ai-feature",
      kind: "concept",
      service: "พัฒนาฟีเจอร์ · AI Integration",
      title: "เพิ่มร่างคำตอบด้วย AI ให้ระบบ Support ที่ใช้อยู่แล้ว",
      tagline: "แนวคิดการนำ AI เข้าสู่ผลิตภัณฑ์ที่มีคนใช้งานอยู่ AI ช่วยร่าง ไม่ได้ทำงานแทนอัตโนมัติ และทุกข้อความต้องมีคนอนุมัติ",
      facts: [
        { label: "สถานะ", value: "แนวคิด ไม่มีลูกค้าจริง ไม่ได้ส่งมอบ" },
        { label: "ขอบเขต", value: "ออกแบบฟีเจอร์ สถาปัตยกรรม AI และแผน Rollout" },
      ],
      stack: ["React", "Node.js API", "PostgreSQL", "Python worker", "Embeddings · RAG", "Cloud + Local models", "Feature flags"],
      sections: {
        problem: {
          client: "ทีม Support ตอบคำถามเดิม ๆ ทั้งวัน AI ช่วยร่างคำตอบได้ แต่ระบบเดิมต้องทำงานต่อไปได้",
          body: "ผลิตภัณฑ์เป็นระบบ Helpdesk ที่ใช้งานมานาน มี Frontend เป็น React, API เป็น Node.js และ PostgreSQL ทีมต้องพิมพ์คำตอบคล้าย ๆ เดิมจาก Knowledge Base และคุณภาพขึ้นอยู่กับว่าใครเข้ากะ",
          points: ["คำตอบซ้ำ ๆ กินเวลามากที่สุด", "มี Knowledge Base แต่ค้นหายาก", "สร้างระบบใหม่ทั้งหมดไม่ใช่ทางเลือก"],
        },
        constraints: {
          client: "ข้อมูลลูกค้าต้องปลอดภัย ค่าใช้จ่ายต้องคาดการณ์ได้ และปิดฟีเจอร์ได้ง่าย",
          body: "สัญญาของลูกค้าบางรายกำหนดว่าข้อมูลต้องไม่ออกนอกเซิร์ฟเวอร์ของบริษัท การเรียกโมเดลมีค่าใช้จ่ายต่อครั้ง และทีมต้องมีสวิตช์ปิดฉุกเฉินหากเกิดปัญหา",
          points: ["กฎความเป็นส่วนตัวแยกตามลูกค้าแต่ละราย", "เพดานงบสำหรับการใช้โมเดล", "เมื่อปิดใช้ ระบบเดิมต้องไม่ได้รับผลกระทบ"],
        },
        decision: {
          client: "AI ร่าง คนตัดสินใจ ไม่มีข้อความไหนส่งออกไปโดยไม่ผ่านการอนุมัติ",
          body: "ฟีเจอร์เสนอร่างคำตอบพร้อมแหล่งอ้างอิงจาก Knowledge Base ที่ใช้ ทีมแก้ไขแล้วจึงส่ง Output เป็นแบบมีโครงสร้าง (ร่างคำตอบ แหล่งอ้างอิง และระดับความมั่นใจ) เพื่อให้หน้าจอแสดงที่มาของทุกข้อความได้",
          points: ["ร่างเท่านั้น ไม่ส่งอัตโนมัติ", "แสดงแหล่งอ้างอิงกับทุกคำแนะนำ", "Rollout ผ่าน Feature Flag แยกตามทีม"],
        },
        architecture: {
          client: "Router จะส่งแต่ละคำขอไปยังโมเดลบน Cloud หรือโมเดล Local ส่วนตัว ตามกฎความเป็นส่วนตัวของลูกค้า",
          body: "Context Builder ดึงบทความที่เกี่ยวข้องด้วย Embeddings Search ส่วน Model Router เลือกโมเดลบน Cloud (เช่น ChatGPT หรือ Claude ผ่าน API) สำหรับลูกค้าทั่วไป และโมเดลที่โฮสต์เองสำหรับลูกค้าที่จำกัดเรื่องข้อมูล ทุกร่างต้องผ่าน Validation ก่อนแสดงบนหน้าจอ",
          points: [],
        },
        implementation: {
          client: "ฟีเจอร์เข้ามาเป็นแผงคำแนะนำในระบบเดิม การทำงานส่วนอื่นของทีมไม่เปลี่ยน",
          body: "Python Worker นำ Knowledge Base เข้า Embeddings Index เพิ่ม Endpoint ใหม่ใน Node.js API เดิมเพื่อสร้าง Context เรียก Router และตรวจ Response แบบมีโครงสร้าง แอป React มีแผงคำแนะนำข้างช่องตอบ และมี Audit Log บันทึกทุกร่างและการแก้ไข",
          points: ["ตรวจ Output แบบมีโครงสร้างกับ Schema", "ตรวจข้อมูลส่วนบุคคลก่อนเรียก Cloud ทุกครั้ง", "Audit Log ของร่าง การแก้ไข และการอนุมัติ"],
        },
        tradeoffs: {
          client: "โมเดล Local ปกป้องข้อมูลได้ดีกว่า แต่ร่างอาจด้อยกว่าเล็กน้อย จึงเลือกตามลูกค้าแต่ละราย",
          body: "โมเดล Local แลกคุณภาพและความเร็วบางส่วนกับการควบคุมข้อมูล Retrieval ทำให้คำตอบอิงข้อเท็จจริงแต่ต้องอัปเดต Index สม่ำเสมอ เพดานงบทำให้ค่าใช้จ่ายคาดการณ์ได้ แม้บางครั้งต้องข้ามการร่าง",
          points: ["คุณภาพกับความเป็นส่วนตัว เลือกตามลูกค้า", "ความสดใหม่ของ Index กับต้นทุนการนำเข้า", "ข้ามการร่างดีกว่าใช้งบเกิน"],
        },
        testing: {
          client: "ทดสอบร่างกับคำถามจริงในอดีตก่อนให้ทีมใดเห็น",
          body: "ชุดประเมินจาก Ticket เก่าที่ลบข้อมูลระบุตัวตนแล้ว ใช้เทียบร่างกับคำตอบที่ส่งจริง ทุก Response ผ่านการตรวจ Schema และความปลอดภัย หากผิดพลาดจะกลับไปใช้ขั้นตอนปกติ",
          points: ["ชุดประเมินจากประวัติที่ลบข้อมูลระบุตัวตนแล้ว", "ตรวจ Schema ข้อมูลส่วนบุคคล และความยาว", "Fallback อย่างนุ่มนวล ไม่มีร่างก็ไม่กระทบงาน"],
        },
        deployment: {
          client: "เริ่มแบบมองไม่เห็น แล้วเปิดให้เลือกใช้ จากนั้นเป็นค่าเริ่มต้น และปิดได้ทันทีทุกเมื่อ",
          body: "เริ่มด้วย Shadow Mode สร้างร่างและบันทึกไว้แต่ไม่แสดง จากนั้นเปิดให้ทีมเดียวเลือกใช้ แล้วจึงเปิดเป็นค่าเริ่มต้น Feature Flag ทำหน้าที่เป็นสวิตช์ปิดฉุกเฉินด้วย",
          points: ["Shadow → Opt-in → Default", "Feature Flag แยกตามทีม", "ปิดฉุกเฉินได้โดยไม่ต้อง Deploy ใหม่"],
        },
        future: {
          client: "Pipeline เดียวกันนำไปติดแท็ก สรุป และกระจาย Ticket ได้ในอนาคต",
          body: "เมื่อมี Retrieval, Routing และ Validation แล้ว ฟีเจอร์ใกล้เคียงก็ใช้ Pipeline เดิมต่อได้",
          points: ["ติดแท็กและกระจายงานอัตโนมัติ", "สรุปบทสนทนาสำหรับส่งต่องาน", "เรียนรู้จากการแก้ไขของทีม"],
        },
      },
      diagrams: {
        architecture: {
          kind: "branch",
          title: "Pipeline การร่างคำตอบ",
          caption: "Router เลือกโมเดลตามลูกค้าแต่ละราย ระหว่างโมเดลกับลูกค้ามี Validation และคนคั่นอยู่เสมอ",
          before: [
            { label: "Ticket", detail: "คำถามที่เข้ามา" },
            { label: "Context", detail: "Embeddings Search ใน Knowledge Base" },
            { label: "Router", detail: "ความเป็นส่วนตัว · งบ · ความพร้อมใช้งาน" },
          ],
          branches: [
            { label: "Cloud Model", detail: "ChatGPT หรือ Claude ผ่าน API" },
            { label: "Local Model", detail: "โฮสต์เอง ข้อมูลอยู่ในองค์กร" },
          ],
          after: [
            { label: "Validation", detail: "Schema · ข้อมูลส่วนบุคคล · ความยาว" },
            { label: "คนอนุมัติ", detail: "ทีมแก้ไขแล้วส่ง" },
          ],
        },
        deployment: {
          kind: "flow",
          title: "Rollout",
          caption: "ทุกขั้นย้อนกลับได้ด้วย Flag",
          nodes: [
            { label: "Shadow", detail: "บันทึกร่าง ไม่แสดง" },
            { label: "ประเมิน", detail: "เทียบกับคำตอบที่ส่งจริง" },
            { label: "Opt-in", detail: "ทีมเดียว พร้อมรับ Feedback" },
            { label: "Default", detail: "เปิดให้ทุกทีม" },
          ],
        },
      },
    },
  ],
  cta: {
    label: "ติดต่อ",
    title: "ชอบวิธีคิดแบบนี้ไหม",
    body: "เปิดรับตำแหน่ง IT ระดับ Junior และงาน Quereinsteiger สายพัฒนาเว็บ ระบบอัตโนมัติ หรืองานดิจิทัลที่ใช้ AI เล่าเรื่องตำแหน่งงานมาได้เลย แล้วจะตอบกลับว่าประสบการณ์เข้ากันได้อย่างไร",
  },
};

export const caseStudiesContent: Localized<CaseStudiesContent> = { en, de, th };
