import type { Localized } from "@/i18n/config";
import type { AgentRole, CapabilityGroupId, LoopStep, StackRowId } from "@/lib/terminal/data";
import type { CommandName, StatusLabel } from "@/lib/terminal/engine";

const en = {
  meta: {
    title: "Engineering command center",
    description: "A live console for this portfolio: system status, web and AI stack, autonomous workflows, local AI, Python tooling, email delivery, repository and deployment — plus a safe terminal.",
  },
  header: {
    eyebrow: "Command center",
    title: "The system behind the portfolio, live.",
    lede: "Status, stack and delivery read from the running deployment and the repository. Anything that is a concept is labelled as one.",
    paletteButton: "Command palette",
    paletteKeys: "Shortcut",
    legendLive: "Live from /api/health",
    legendBuild: "Measured at build time",
    legendConcept: "Concept / capability",
  },
  tabs: {
    label: "Console sections",
    groups: { stack: "Stack", platform: "Platform", map: "Routes" },
  },
  status: {
    title: "System status",
    endpoint: "GET /api/health",
    loading: "Checking…",
    error: "The health endpoint could not be reached.",
    retry: "Check again",
    raw: "Raw JSON",
    measured: "Round trip (measured now)",
    status: { ok: "Operational", degraded: "Degraded" },
    fields: { environment: "Environment", region: "Region", runtime: "Runtime", commit: "Commit", database: "Database", email: "Email", channels: "Contact channels" },
  },
  values: {
    ok: "Operational",
    degraded: "Degraded",
    connected: "Connected",
    unreachable: "Unreachable",
    "not-configured": "Not configured",
    configured: "Configured",
    "configured-test-sender": "Configured (test sender)",
    production: "production",
    preview: "preview",
    development: "development",
    local: "local",
  } as Record<string, string>,
  panels: {
    web: { title: "Web stack", note: "What this site is built with, and what client projects are built with." },
    ai: {
      title: "AI stack",
      note: "Tools in the engineering environment. Listed as capabilities, not as usage statistics.",
      roles: [
        { name: "ChatGPT", role: "Research, analysis, specification, drafting" },
        { name: "OpenAI API", role: "Model calls, tool and function calling in applications" },
        { name: "Claude", role: "Reasoning over long context, review, writing" },
        { name: "Claude Code", role: "Repository analysis, planning, subagents, implementation, tests" },
        { name: "Local models", role: "Private or offline workloads (concept)" },
      ],
    },
    autonomous: {
      title: "Autonomous workflows",
      note: "A bounded loop: every run has a goal, checkpoints and a person who approves the result.",
      steps: {
        goal: "Goal and constraints from a person",
        plan: "Planner splits the work into tasks",
        route: "Router picks the model and tools per task",
        act: "Specialised agents execute with tools",
        validate: "Types, tests and schema checks",
        review: "Human approval before anything ships",
        result: "Merged, deployed, documented",
      } satisfies Record<LoopStep, string>,
      guardrails: ["Retry limits", "Workflow state", "Context passing", "Result aggregation"],
    },
    localAi: {
      title: "Local AI",
      badge: "Architecture concept",
      note: "Patterns for keeping data on your own hardware. Presented as architecture, not as a production claim.",
      items: ["Local LLM endpoints (Ollama / LM Studio style)", "llama.cpp-compatible models", "Embeddings and RAG over private documents", "Cloud / local routing by privacy, cost and latency"],
    },
    python: {
      title: "Python",
      note: "The connective layer: automation, API clients, data and file processing, agent utilities.",
      uses: ["Automation scripts", "API clients", "Data transformation", "File processing", "Agent tooling", "Code generation"],
      generator: "Generated artifact",
      fields: { file: "Generator", nodes: "Nodes", traces: "Traces", groups: "Groups", copper: "Trace length", hash: "Topology hash" },
      view: "See the circuit",
      thumbAlt: "Static rendering of the Python-generated AI circuit",
    },
    backend: {
      title: "Backend",
      note: "How a contact submission is handled on the server.",
      rows: [
        { label: "Entry point", value: "Server Action" },
        { label: "Validation", value: "Zod, stable error codes" },
        { label: "Spam", value: "Honeypot + rate limit" },
        { label: "Health", value: "Route Handler /api/health" },
      ],
      channels: "Delivery channels",
      none: "None configured",
    },
    email: {
      title: "Email delivery",
      provider: "Provider",
      state: "State",
      destination: "Notifications to",
      replyTo: "Reply-To",
      replyToValue: "The visitor's address",
      explain: {
        configured: "Enquiries are emailed through Resend from a verified sender.",
        "configured-test-sender": "Resend is active with its test sender, which delivers to the owner's inbox only.",
        "not-configured": "Email delivery is not configured in this environment.",
      } as Record<string, string>,
    },
    repository: { title: "Repository", repo: "Source", branch: "Branch", commit: "Deployed commit", pending: "Reading…" },
    deployment: { title: "Deployment", platform: "Platform", environment: "Environment", region: "Region", runtime: "Runtime", headers: "Security headers", headersValue: "HSTS · nosniff · frame deny · referrer · permissions" },
    routes: { title: "Routes", total: "Localized routes", pages: "Pages", api: "API" },
    locales: { title: "Locales", caption: "Supported locales", cols: { language: "Language", prefix: "Prefix", html: "lang" } },
  },
  terminal: {
    eyebrow: "Safe terminal",
    title: "Ask the portfolio",
    body: "A read-only console that only knows the commands in help. Nothing runs on a server or in a shell.",
    label: "Portfolio terminal",
    logLabel: "Terminal output",
    badge: "read-only",
    prompt: "visitor@portfolio:~$",
    placeholder: "Type a command, e.g. help",
    submit: "Run",
    quick: "Try",
    intro: "Safe, read-only terminal. Type help to list commands.",
    messages: {
      helpTitle: "Available commands",
      helpHint: "Tab completes. ArrowUp and ArrowDown browse your history.",
      unknown: "Command not found: {command}. Type help for the list of commands.",
      openArg: "page",
      openUsage: "Usage: open <page>. Pages: {pages}.",
      openUnknown: "No page named “{name}”. Pages: {pages}.",
      opening: "Opening {page}…",
      langUsage: "Current language: {current}. Usage: lang <{codes}>.",
      langUnknown: "Unsupported language “{name}”. Available: {codes}.",
      langCurrent: "Already using {language}.",
      langSwitching: "Switching to {language}…",
      historyEmpty: "No commands yet.",
      statusTitle: "System status (from /api/health)",
      statusPending: "Health data is still loading. Check the System status panel, then run status again.",
      descriptions: {
        help: "List all commands",
        about: "Who builds this",
        services: "What you can hire me for",
        capabilities: "Capabilities by area (alias: skills)",
        projects: "What the project pages contain",
        stack: "The real stack of this site",
        ai: "ChatGPT, Claude and Claude Code in the workflow",
        agents: "The multi-agent development setup",
        "local-ai": "Local and private AI concepts",
        python: "Where Python fits",
        architecture: "How this site is built",
        status: "Live status from /api/health",
        contact: "Email, phone and contact form",
        email: "Email address only",
        open: "Go to a page",
        lang: "Switch language",
        history: "Commands entered so far",
        clear: "Clear the screen",
      } satisfies Record<CommandName, string>,
    },
    labels: { name: "Name", location: "Location", availability: "Availability", github: "GitHub", email: "Email", phone: "Phone", form: "Contact form", source: "Source" },
    about: {
      heading: "About",
      text: "Web developer × AI-native builder. Websites, redesigns, new features, full-stack apps and AI-enabled systems — taken to production.",
    },
    services: {
      heading: "Services",
      items: ["New websites", "Website redesigns", "Features for existing products", "Full-stack web applications", "AI integration", "AI workflows and automation", "Local / private AI concepts", "Python automation", "Performance and responsive fixes", "Deployment (GitHub, Vercel)"],
      hint: "Start one with: open contact",
    },
    capabilities: {
      heading: "Capabilities",
      groups: { web: "Web", backend: "Backend", python: "Python", ai: "AI", local: "Local AI", delivery: "Delivery" } satisfies Record<CapabilityGroupId, string>,
      hint: "The full network: open capabilities",
    },
    projects: {
      heading: "Projects",
      text: "Concept projects and technical demonstrations, labelled as such. None of them is presented as client work.",
      hint: "Explore them with: open projects",
    },
    stack: {
      heading: "Stack",
      rows: { framework: "Framework", styling: "Styling", validation: "Validation", email: "Email", data: "Data", python: "Python", tooling: "Tooling", hosting: "Hosting" } satisfies Record<StackRowId, string>,
    },
    ai: {
      heading: "AI in the workflow",
      text: "AI accelerates research, implementation, review and testing. Architecture, security and the decision to ship stay with an engineer.",
      hint: "Details: open ai-native",
    },
    agents: {
      heading: "Multi-agent development",
      text: "An orchestrator delegates to specialised agents, then merges, validates and ships through Git, CI and Vercel.",
      roles: {
        orchestrator: "Plans, delegates, merges",
        design: "Layout, tokens, visual review",
        frontend: "Components, routing, accessibility",
        backend: "APIs, validation, data",
        research: "Docs, options, constraints",
        test: "Unit and end-to-end tests",
        review: "Diff review, security, consistency",
      } satisfies Record<AgentRole, string>,
    },
    localAi: {
      heading: "Local AI (concept)",
      text: "Local models, private documents and embeddings behind a router that decides what may leave the machine.",
      hint: "Architecture: open ai-native",
    },
    python: {
      heading: "Python",
      text: "Automation, API clients, data and file processing, agent utilities. The circuit on the AI systems page is generated by a Python script in this repository.",
    },
    architecture: { heading: "Architecture", hint: "Full diagram below on this page." },
    contact: { heading: "Contact", text: "Fastest route: the project form. Email and phone work too.", hint: "Or press Ctrl + K and choose Start a project." },
  },
  architecture: {
    eyebrow: "How this portfolio is built",
    title: "From browser to inbox",
    lede: "Every step maps to real files in the repository.",
    pathLabel: "Where",
    branchLabel: "Delivery channels",
    nodes: [
      { id: "browser", label: "Browser", path: "/[locale]/…", desc: "Server-rendered HTML first. Client islands only where interaction needs them: menu, palette, terminal, tools and forms." },
      { id: "server", label: "Next.js App Router", path: "src/app · src/proxy.ts", desc: "A [locale] segment for en, de and th. The proxy redirects unprefixed URLs. Copy lives in typed dictionaries in src/content." },
      { id: "handler", label: "Server Action & Route Handler", path: "src/app/actions · src/app/api/health", desc: "The project form posts to a Server Action. /api/health reports safe, non-secret status." },
      { id: "validation", label: "Validation & protection", path: "src/lib/contact", desc: "Zod schema with stable error codes, a honeypot field and a rate limit — all on the server." },
      {
        id: "delivery",
        label: "Delivery",
        path: "src/lib/contact/deliver.ts",
        desc: "Every configured channel is tried. Success means at least one accepted the message; otherwise the form says so honestly.",
        branches: ["Resend email", "PostgreSQL (Neon)", "Webhook"],
      },
      { id: "python", label: "Python build artifact", path: "scripts/generate_ai_circuit.py", desc: "Generates the AI circuit JSON and SVG ahead of time. Production never needs a Python runtime." },
      { id: "vercel", label: "GitHub → Vercel", path: "next.config.ts", desc: "Pushes to main deploy to Vercel. Security headers are set in next.config.ts." },
    ],
  },
  facts: {
    title: "Measured from the repository",
    lede: "Counted when the site is built, from the same files that drive navigation and tests.",
    items: { pages: "Pages", languages: "Languages", routes: "Localized routes", content: "Content modules", api: "API endpoints", tests: "Test files", python: "Python scripts" },
  },
  statusLabels: { status: "Status", environment: "Environment", region: "Region", commit: "Commit", database: "Database", email: "Email", channels: "Channels" } satisfies Record<StatusLabel, string>,
};

export type CommandCenterContent = typeof en;

const de: CommandCenterContent = {
  meta: {
    title: "Kommandozentrale",
    description: "Eine Live-Konsole für dieses Portfolio: Systemstatus, Web- und KI-Stack, autonome Workflows, lokale KI, Python, E-Mail-Zustellung, Repository und Deployment – plus ein sicheres Terminal.",
  },
  header: {
    eyebrow: "Kommandozentrale",
    title: "Das System hinter dem Portfolio, live.",
    lede: "Status, Stack und Zustellung kommen aus dem laufenden Deployment und dem Repository. Was ein Konzept ist, ist als Konzept markiert.",
    paletteButton: "Befehlspalette",
    paletteKeys: "Tastenkürzel",
    legendLive: "Live aus /api/health",
    legendBuild: "Beim Build gemessen",
    legendConcept: "Konzept / Fähigkeit",
  },
  tabs: {
    label: "Bereiche der Konsole",
    groups: { stack: "Stack", platform: "Plattform", map: "Routen" },
  },
  status: {
    title: "Systemstatus",
    endpoint: "GET /api/health",
    loading: "Wird geprüft …",
    error: "Der Health-Endpunkt ist nicht erreichbar.",
    retry: "Erneut prüfen",
    raw: "Roh-JSON",
    measured: "Antwortzeit (jetzt gemessen)",
    status: { ok: "In Betrieb", degraded: "Eingeschränkt" },
    fields: { environment: "Umgebung", region: "Region", runtime: "Runtime", commit: "Commit", database: "Datenbank", email: "E-Mail", channels: "Kontaktkanäle" },
  },
  values: {
    ok: "In Betrieb",
    degraded: "Eingeschränkt",
    connected: "Verbunden",
    unreachable: "Nicht erreichbar",
    "not-configured": "Nicht eingerichtet",
    configured: "Eingerichtet",
    "configured-test-sender": "Eingerichtet (Test-Absender)",
    production: "Produktion",
    preview: "Preview",
    development: "Entwicklung",
    local: "lokal",
  },
  panels: {
    web: { title: "Web-Stack", note: "Womit diese Website gebaut ist – und womit Kundenprojekte gebaut werden." },
    ai: {
      title: "KI-Stack",
      note: "Werkzeuge in der Entwicklungsumgebung. Als Fähigkeiten aufgeführt, nicht als Nutzungsstatistik.",
      roles: [
        { name: "ChatGPT", role: "Recherche, Analyse, Spezifikation, Entwürfe" },
        { name: "OpenAI API", role: "Modellaufrufe, Tool- und Function-Calling in Anwendungen" },
        { name: "Claude", role: "Arbeit mit langem Kontext, Reviews, Texte" },
        { name: "Claude Code", role: "Repository-Analyse, Planung, Subagents, Umsetzung, Tests" },
        { name: "Lokale Modelle", role: "Private oder Offline-Workloads (Konzept)" },
      ],
    },
    autonomous: {
      title: "Autonome Workflows",
      note: "Eine begrenzte Schleife: Jeder Lauf hat ein Ziel, Checkpoints und eine Person, die das Ergebnis freigibt.",
      steps: {
        goal: "Ziel und Rahmen kommen von einem Menschen",
        plan: "Der Planner zerlegt die Arbeit in Aufgaben",
        route: "Der Router wählt Modell und Tools pro Aufgabe",
        act: "Spezialisierte Agents arbeiten mit Tools",
        validate: "Typen, Tests und Schema-Prüfungen",
        review: "Freigabe durch einen Menschen vor dem Release",
        result: "Gemergt, deployed, dokumentiert",
      },
      guardrails: ["Retry-Limits", "Workflow-Zustand", "Kontextübergabe", "Ergebnis-Aggregation"],
    },
    localAi: {
      title: "Lokale KI",
      badge: "Architekturkonzept",
      note: "Muster, mit denen Daten auf eigener Hardware bleiben. Als Architektur dargestellt, nicht als Produktionsnachweis.",
      items: ["Lokale LLM-Endpunkte (à la Ollama / LM Studio)", "llama.cpp-kompatible Modelle", "Embeddings und RAG über private Dokumente", "Routing zwischen Cloud und lokal nach Datenschutz, Kosten und Latenz"],
    },
    python: {
      title: "Python",
      note: "Die verbindende Schicht: Automatisierung, API-Clients, Daten- und Dateiverarbeitung, Agent-Utilities.",
      uses: ["Automatisierungsskripte", "API-Clients", "Datentransformation", "Dateiverarbeitung", "Agent-Tooling", "Codegenerierung"],
      generator: "Generiertes Artefakt",
      fields: { file: "Generator", nodes: "Knoten", traces: "Leiterbahnen", groups: "Gruppen", copper: "Bahnlänge", hash: "Topologie-Hash" },
      view: "Zum Schaltplan",
      thumbAlt: "Statische Darstellung des mit Python generierten KI-Schaltplans",
    },
    backend: {
      title: "Backend",
      note: "So wird eine Anfrage auf dem Server verarbeitet.",
      rows: [
        { label: "Einstieg", value: "Server Action" },
        { label: "Validierung", value: "Zod, stabile Fehlercodes" },
        { label: "Spam", value: "Honeypot + Rate-Limit" },
        { label: "Health", value: "Route Handler /api/health" },
      ],
      channels: "Zustellkanäle",
      none: "Keine eingerichtet",
    },
    email: {
      title: "E-Mail-Zustellung",
      provider: "Anbieter",
      state: "Zustand",
      destination: "Benachrichtigung an",
      replyTo: "Reply-To",
      replyToValue: "Adresse der anfragenden Person",
      explain: {
        configured: "Anfragen werden über Resend von einem verifizierten Absender verschickt.",
        "configured-test-sender": "Resend ist mit dem Test-Absender aktiv; der stellt nur an das Postfach des Inhabers zu.",
        "not-configured": "In dieser Umgebung ist keine E-Mail-Zustellung eingerichtet.",
      },
    },
    repository: { title: "Repository", repo: "Quelle", branch: "Branch", commit: "Deployter Commit", pending: "Wird gelesen …" },
    deployment: { title: "Deployment", platform: "Plattform", environment: "Umgebung", region: "Region", runtime: "Runtime", headers: "Security-Header", headersValue: "HSTS · nosniff · frame deny · referrer · permissions" },
    routes: { title: "Routen", total: "Lokalisierte Routen", pages: "Seiten", api: "API" },
    locales: { title: "Sprachen", caption: "Unterstützte Sprachen", cols: { language: "Sprache", prefix: "Präfix", html: "lang" } },
  },
  terminal: {
    eyebrow: "Sicheres Terminal",
    title: "Frag das Portfolio",
    body: "Eine schreibgeschützte Konsole, die nur die Befehle aus help kennt. Nichts läuft auf einem Server oder in einer Shell.",
    label: "Portfolio-Terminal",
    logLabel: "Terminal-Ausgabe",
    badge: "schreibgeschützt",
    prompt: "besucher@portfolio:~$",
    placeholder: "Befehl eingeben, z. B. help",
    submit: "Ausführen",
    quick: "Probier",
    intro: "Sicheres, schreibgeschütztes Terminal. Mit help siehst du alle Befehle.",
    messages: {
      helpTitle: "Verfügbare Befehle",
      helpHint: "Tab vervollständigt. Pfeil hoch und runter blättern durch den Verlauf.",
      unknown: "Befehl nicht gefunden: {command}. Mit help siehst du alle Befehle.",
      openArg: "seite",
      openUsage: "Aufruf: open <seite>. Seiten: {pages}.",
      openUnknown: "Keine Seite namens „{name}“. Seiten: {pages}.",
      opening: "{page} wird geöffnet …",
      langUsage: "Aktuelle Sprache: {current}. Aufruf: lang <{codes}>.",
      langUnknown: "Sprache „{name}“ wird nicht unterstützt. Verfügbar: {codes}.",
      langCurrent: "{language} ist bereits aktiv.",
      langSwitching: "Wechsel zu {language} …",
      historyEmpty: "Noch keine Befehle.",
      statusTitle: "Systemstatus (aus /api/health)",
      statusPending: "Die Health-Daten laden noch. Sieh in den Bereich Systemstatus und führe status dann erneut aus.",
      descriptions: {
        help: "Alle Befehle anzeigen",
        about: "Wer das baut",
        services: "Wofür du mich buchen kannst",
        capabilities: "Fähigkeiten nach Bereich (Alias: skills)",
        projects: "Was die Projektseiten enthalten",
        stack: "Der echte Stack dieser Website",
        ai: "ChatGPT, Claude und Claude Code im Workflow",
        agents: "Das Multi-Agent-Setup für Entwicklung",
        "local-ai": "Konzepte für lokale und private KI",
        python: "Wo Python seinen Platz hat",
        architecture: "Wie diese Website gebaut ist",
        status: "Live-Status aus /api/health",
        contact: "E-Mail, Telefon und Formular",
        email: "Nur die E-Mail-Adresse",
        open: "Zu einer Seite wechseln",
        lang: "Sprache wechseln",
        history: "Bisher eingegebene Befehle",
        clear: "Bildschirm leeren",
      },
    },
    labels: { name: "Name", location: "Standort", availability: "Verfügbarkeit", github: "GitHub", email: "E-Mail", phone: "Telefon", form: "Kontaktformular", source: "Quellcode" },
    about: {
      heading: "Über",
      text: "Webentwicklung × KI-natives Bauen. Websites, Redesigns, neue Features, Full-Stack-Apps und KI-gestützte Systeme – bis in die Produktion.",
    },
    services: {
      heading: "Leistungen",
      items: ["Neue Websites", "Website-Redesigns", "Features für bestehende Produkte", "Full-Stack-Webanwendungen", "KI-Integration", "KI-Workflows und Automatisierung", "Konzepte für lokale / private KI", "Python-Automatisierung", "Performance- und Responsive-Fixes", "Deployment (GitHub, Vercel)"],
      hint: "Projekt starten: open contact",
    },
    capabilities: {
      heading: "Fähigkeiten",
      groups: { web: "Web", backend: "Backend", python: "Python", ai: "KI", local: "Lokale KI", delivery: "Auslieferung" },
      hint: "Das ganze Netzwerk: open capabilities",
    },
    projects: {
      heading: "Projekte",
      text: "Konzeptprojekte und technische Demonstrationen, klar als solche gekennzeichnet. Keines davon wird als Kundenprojekt ausgegeben.",
      hint: "Ansehen mit: open projects",
    },
    stack: {
      heading: "Stack",
      rows: { framework: "Framework", styling: "Styling", validation: "Validierung", email: "E-Mail", data: "Daten", python: "Python", tooling: "Tooling", hosting: "Hosting" },
    },
    ai: {
      heading: "KI im Workflow",
      text: "KI beschleunigt Recherche, Umsetzung, Review und Tests. Architektur, Sicherheit und die Entscheidung zum Release bleiben bei einem Menschen.",
      hint: "Details: open ai-native",
    },
    agents: {
      heading: "Multi-Agent-Entwicklung",
      text: "Ein Orchestrator verteilt Aufgaben an spezialisierte Agents, führt die Ergebnisse zusammen, prüft sie und liefert über Git, CI und Vercel aus.",
      roles: {
        orchestrator: "Plant, delegiert, führt zusammen",
        design: "Layout, Tokens, visuelles Review",
        frontend: "Komponenten, Routing, Barrierefreiheit",
        backend: "APIs, Validierung, Daten",
        research: "Doku, Optionen, Rahmenbedingungen",
        test: "Unit- und End-to-End-Tests",
        review: "Diff-Review, Sicherheit, Konsistenz",
      },
    },
    localAi: {
      heading: "Lokale KI (Konzept)",
      text: "Lokale Modelle, private Dokumente und Embeddings hinter einem Router, der entscheidet, was das Gerät verlassen darf.",
      hint: "Architektur: open ai-native",
    },
    python: {
      heading: "Python",
      text: "Automatisierung, API-Clients, Daten- und Dateiverarbeitung, Agent-Utilities. Der Schaltplan auf der Seite KI-Systeme wird von einem Python-Skript in diesem Repository erzeugt.",
    },
    architecture: { heading: "Architektur", hint: "Das vollständige Diagramm steht weiter unten." },
    contact: { heading: "Kontakt", text: "Am schnellsten über das Projektformular. E-Mail und Telefon gehen auch.", hint: "Oder Strg + K drücken und Projekt starten wählen." },
  },
  architecture: {
    eyebrow: "So ist dieses Portfolio gebaut",
    title: "Vom Browser bis ins Postfach",
    lede: "Jeder Schritt entspricht echten Dateien im Repository.",
    pathLabel: "Wo",
    branchLabel: "Zustellkanäle",
    nodes: [
      { id: "browser", label: "Browser", path: "/[locale]/…", desc: "Zuerst serverseitig gerendertes HTML. Client-Inseln nur dort, wo Interaktion sie braucht: Menü, Palette, Terminal, Tools und Formulare." },
      { id: "server", label: "Next.js App Router", path: "src/app · src/proxy.ts", desc: "Ein [locale]-Segment für en, de und th. Der Proxy leitet URLs ohne Präfix weiter. Texte liegen in typisierten Wörterbüchern in src/content." },
      { id: "handler", label: "Server Action & Route Handler", path: "src/app/actions · src/app/api/health", desc: "Das Projektformular sendet an eine Server Action. /api/health liefert einen sicheren Status ohne Geheimnisse." },
      { id: "validation", label: "Validierung & Schutz", path: "src/lib/contact", desc: "Zod-Schema mit stabilen Fehlercodes, ein Honeypot-Feld und ein Rate-Limit – alles auf dem Server." },
      {
        id: "delivery",
        label: "Zustellung",
        path: "src/lib/contact/deliver.ts",
        desc: "Alle eingerichteten Kanäle werden versucht. Erfolg heißt: Mindestens einer hat die Nachricht angenommen – sonst sagt das Formular das ehrlich.",
        branches: ["Resend-E-Mail", "PostgreSQL (Neon)", "Webhook"],
      },
      { id: "python", label: "Python-Build-Artefakt", path: "scripts/generate_ai_circuit.py", desc: "Erzeugt JSON und SVG des KI-Schaltplans im Voraus. Die Produktion braucht nie eine Python-Runtime." },
      { id: "vercel", label: "GitHub → Vercel", path: "next.config.ts", desc: "Pushes auf main werden auf Vercel deployed. Security-Header sind in next.config.ts gesetzt." },
    ],
  },
  facts: {
    title: "Aus dem Repository gemessen",
    lede: "Beim Build gezählt, aus denselben Dateien, die Navigation und Tests steuern.",
    items: { pages: "Seiten", languages: "Sprachen", routes: "Lokalisierte Routen", content: "Content-Module", api: "API-Endpunkte", tests: "Testdateien", python: "Python-Skripte" },
  },
  statusLabels: { status: "Status", environment: "Umgebung", region: "Region", commit: "Commit", database: "Datenbank", email: "E-Mail", channels: "Kanäle" },
};

const th: CommandCenterContent = {
  meta: {
    title: "Command Center",
    description: "คอนโซลสดของพอร์ตโฟลิโอนี้: สถานะระบบ สแตก Web และ AI, Autonomous Workflow, Local AI, Python, การส่งอีเมล, Repository และการ Deploy พร้อม Terminal ที่ปลอดภัย",
  },
  header: {
    eyebrow: "Command Center",
    title: "ระบบเบื้องหลังพอร์ตโฟลิโอ แบบสด ๆ",
    lede: "สถานะ สแตก และการส่งข้อความอ่านจาก Deployment ที่กำลังทำงานและจาก Repository จริง ส่วนไหนเป็นแนวคิดจะติดป้ายบอกไว้ชัดเจน",
    paletteButton: "Command Palette",
    paletteKeys: "คีย์ลัด",
    legendLive: "ข้อมูลสดจาก /api/health",
    legendBuild: "วัดตอน Build",
    legendConcept: "แนวคิด / ความสามารถ",
  },
  tabs: {
    label: "ส่วนต่าง ๆ ของคอนโซล",
    groups: { stack: "สแตก", platform: "แพลตฟอร์ม", map: "Routes" },
  },
  status: {
    title: "สถานะระบบ",
    endpoint: "GET /api/health",
    loading: "กำลังตรวจสอบ…",
    error: "เชื่อมต่อ Health Endpoint ไม่ได้",
    retry: "ตรวจอีกครั้ง",
    raw: "ดู JSON",
    measured: "เวลาตอบกลับ (วัดตอนนี้)",
    status: { ok: "ทำงานปกติ", degraded: "ทำงานได้บางส่วน" },
    fields: { environment: "Environment", region: "Region", runtime: "Runtime", commit: "Commit", database: "ฐานข้อมูล", email: "อีเมล", channels: "ช่องทางติดต่อ" },
  },
  values: {
    ok: "ทำงานปกติ",
    degraded: "ทำงานได้บางส่วน",
    connected: "เชื่อมต่อแล้ว",
    unreachable: "เชื่อมต่อไม่ได้",
    "not-configured": "ยังไม่ได้ตั้งค่า",
    configured: "ตั้งค่าแล้ว",
    "configured-test-sender": "ตั้งค่าแล้ว (ผู้ส่งทดสอบ)",
    production: "production",
    preview: "preview",
    development: "development",
    local: "local",
  },
  panels: {
    web: { title: "Web Stack", note: "เครื่องมือที่ใช้สร้างเว็บไซต์นี้ และใช้กับงานของลูกค้า" },
    ai: {
      title: "AI Stack",
      note: "เครื่องมือในสภาพแวดล้อมการพัฒนา แสดงเป็นความสามารถ ไม่ใช่สถิติการใช้งาน",
      roles: [
        { name: "ChatGPT", role: "ค้นคว้า วิเคราะห์ เขียน Spec และร่างเนื้อหา" },
        { name: "OpenAI API", role: "เรียกใช้โมเดล Tool Calling และ Function Calling ในแอป" },
        { name: "Claude", role: "ทำงานกับ Context ยาว รีวิว และงานเขียน" },
        { name: "Claude Code", role: "วิเคราะห์ Repository วางแผน Subagent ลงมือพัฒนา และเทสต์" },
        { name: "Local Models", role: "งานที่ต้องเป็นส่วนตัวหรือออฟไลน์ (แนวคิด)" },
      ],
    },
    autonomous: {
      title: "Autonomous Workflow",
      note: "เป็นลูปที่มีขอบเขต ทุกครั้งที่รันต้องมีเป้าหมาย Checkpoint และคนที่อนุมัติผลลัพธ์",
      steps: {
        goal: "เป้าหมายและข้อจำกัดมาจากคน",
        plan: "Planner แตกงานเป็น Task ย่อย",
        route: "Router เลือกโมเดลและเครื่องมือให้แต่ละ Task",
        act: "Agent เฉพาะทางลงมือทำงานด้วยเครื่องมือ",
        validate: "ตรวจ Type เทสต์ และ Schema",
        review: "คนอนุมัติก่อนขึ้นระบบจริง",
        result: "Merge, Deploy และมีเอกสาร",
      },
      guardrails: ["จำกัดจำนวน Retry", "Workflow State", "ส่งต่อ Context", "รวมผลลัพธ์"],
    },
    localAi: {
      title: "Local AI",
      badge: "แนวคิดเชิงสถาปัตยกรรม",
      note: "รูปแบบที่ทำให้ข้อมูลอยู่บนเครื่องของคุณเอง นำเสนอในเชิงสถาปัตยกรรม ไม่ได้อ้างว่าใช้งานจริงใน Production แล้ว",
      items: ["Local LLM Endpoint (แบบ Ollama / LM Studio)", "โมเดลที่รองรับ llama.cpp", "Embeddings และ RAG บนเอกสารส่วนตัว", "Routing ระหว่าง Cloud กับ Local ตามความเป็นส่วนตัว ต้นทุน และ Latency"],
    },
    python: {
      title: "Python",
      note: "ตัวเชื่อมของระบบ: Automation, API Client, การแปลงข้อมูลและไฟล์ และเครื่องมือสำหรับ Agent",
      uses: ["สคริปต์ Automation", "API Client", "แปลงข้อมูล", "ประมวลผลไฟล์", "เครื่องมือสำหรับ Agent", "สร้างโค้ดอัตโนมัติ"],
      generator: "ไฟล์ที่ Generate ขึ้น",
      fields: { file: "Generator", nodes: "Node", traces: "เส้นวงจร", groups: "กลุ่ม", copper: "ความยาวเส้น", hash: "Topology Hash" },
      view: "ดูวงจร",
      thumbAlt: "ภาพนิ่งของวงจร AI ที่สร้างด้วย Python",
    },
    backend: {
      title: "Backend",
      note: "ขั้นตอนที่เซิร์ฟเวอร์จัดการข้อความจากฟอร์มติดต่อ",
      rows: [
        { label: "จุดเข้า", value: "Server Action" },
        { label: "Validation", value: "Zod พร้อม Error Code คงที่" },
        { label: "กันสแปม", value: "Honeypot + Rate Limit" },
        { label: "Health", value: "Route Handler /api/health" },
      ],
      channels: "ช่องทางส่งข้อความ",
      none: "ยังไม่ได้ตั้งค่า",
    },
    email: {
      title: "การส่งอีเมล",
      provider: "ผู้ให้บริการ",
      state: "สถานะ",
      destination: "แจ้งเตือนไปที่",
      replyTo: "Reply-To",
      replyToValue: "อีเมลของผู้ติดต่อ",
      explain: {
        configured: "คำขอโปรเจกต์ถูกส่งเป็นอีเมลผ่าน Resend จากผู้ส่งที่ยืนยันโดเมนแล้ว",
        "configured-test-sender": "เปิดใช้ Resend ด้วยผู้ส่งทดสอบ ซึ่งส่งได้เฉพาะกล่องอีเมลของเจ้าของบัญชี",
        "not-configured": "ยังไม่ได้ตั้งค่าการส่งอีเมลใน Environment นี้",
      },
    },
    repository: { title: "Repository", repo: "ซอร์สโค้ด", branch: "Branch", commit: "Commit ที่ Deploy", pending: "กำลังอ่าน…" },
    deployment: { title: "Deployment", platform: "แพลตฟอร์ม", environment: "Environment", region: "Region", runtime: "Runtime", headers: "Security Header", headersValue: "HSTS · nosniff · frame deny · referrer · permissions" },
    routes: { title: "Routes", total: "Route ทุกภาษา", pages: "หน้า", api: "API" },
    locales: { title: "ภาษา", caption: "ภาษาที่รองรับ", cols: { language: "ภาษา", prefix: "Prefix", html: "lang" } },
  },
  terminal: {
    eyebrow: "Terminal ที่ปลอดภัย",
    title: "ถามพอร์ตโฟลิโอได้เลย",
    body: "คอนโซลแบบอ่านอย่างเดียว รู้จักเฉพาะคำสั่งใน help ไม่มีอะไรรันบนเซิร์ฟเวอร์หรือ Shell",
    label: "Terminal ของพอร์ตโฟลิโอ",
    logLabel: "ผลลัพธ์ของ Terminal",
    badge: "อ่านอย่างเดียว",
    prompt: "visitor@portfolio:~$",
    placeholder: "พิมพ์คำสั่ง เช่น help",
    submit: "รัน",
    quick: "ลองเลย",
    intro: "Terminal แบบอ่านอย่างเดียวที่ปลอดภัย พิมพ์ help เพื่อดูคำสั่งทั้งหมด",
    messages: {
      helpTitle: "คำสั่งที่ใช้ได้",
      helpHint: "กด Tab เพื่อเติมคำสั่ง ใช้ลูกศรขึ้นลงเพื่อดูคำสั่งก่อนหน้า",
      unknown: "ไม่พบคำสั่ง: {command} พิมพ์ help เพื่อดูคำสั่งทั้งหมด",
      openArg: "หน้า",
      openUsage: "วิธีใช้: open <หน้า> หน้าที่มี: {pages}",
      openUnknown: "ไม่มีหน้าชื่อ “{name}” หน้าที่มี: {pages}",
      opening: "กำลังเปิด {page}…",
      langUsage: "ภาษาปัจจุบัน: {current} วิธีใช้: lang <{codes}>",
      langUnknown: "ไม่รองรับภาษา “{name}” ภาษาที่มี: {codes}",
      langCurrent: "กำลังใช้ {language} อยู่แล้ว",
      langSwitching: "กำลังเปลี่ยนเป็น {language}…",
      historyEmpty: "ยังไม่มีคำสั่ง",
      statusTitle: "สถานะระบบ (จาก /api/health)",
      statusPending: "ข้อมูล Health ยังโหลดไม่เสร็จ ดูที่แผงสถานะระบบ แล้วรัน status อีกครั้ง",
      descriptions: {
        help: "แสดงคำสั่งทั้งหมด",
        about: "คนที่สร้างงานนี้",
        services: "บริการที่รับทำ",
        capabilities: "ความสามารถแยกตามด้าน (ใช้ skills ได้)",
        projects: "หน้าโปรเจกต์มีอะไรบ้าง",
        stack: "สแตกจริงของเว็บไซต์นี้",
        ai: "ChatGPT, Claude และ Claude Code ใน Workflow",
        agents: "การพัฒนาแบบ Multi-Agent",
        "local-ai": "แนวคิด Local AI และ Private AI",
        python: "บทบาทของ Python",
        architecture: "โครงสร้างของเว็บไซต์นี้",
        status: "สถานะสดจาก /api/health",
        contact: "อีเมล โทรศัพท์ และฟอร์มติดต่อ",
        email: "แสดงเฉพาะอีเมล",
        open: "ไปยังหน้าที่ต้องการ",
        lang: "เปลี่ยนภาษา",
        history: "คำสั่งที่พิมพ์ไปแล้ว",
        clear: "ล้างหน้าจอ",
      },
    },
    labels: { name: "ชื่อ", location: "ที่อยู่", availability: "การรับงาน", github: "GitHub", email: "อีเมล", phone: "โทรศัพท์", form: "ฟอร์มติดต่อ", source: "ซอร์สโค้ด" },
    about: {
      heading: "เกี่ยวกับ",
      text: "นักพัฒนาเว็บ × AI-native builder ทำเว็บไซต์ Redesign ฟีเจอร์ใหม่ Full-stack App และระบบที่ใช้ AI จนขึ้นใช้งานจริง",
    },
    services: {
      heading: "บริการ",
      items: ["เว็บไซต์ใหม่", "Redesign เว็บไซต์เดิม", "เพิ่มฟีเจอร์ให้ระบบเดิม", "Full-stack Web Application", "AI Integration", "AI Workflow และ Automation", "แนวคิด Local AI / Private AI", "Python Automation", "ปรับ Performance และ Responsive", "Deploy (GitHub, Vercel)"],
      hint: "เริ่มโปรเจกต์: open contact",
    },
    capabilities: {
      heading: "ความสามารถ",
      groups: { web: "Web", backend: "Backend", python: "Python", ai: "AI", local: "Local AI", delivery: "Delivery" },
      hint: "ดูเครือข่ายทั้งหมด: open capabilities",
    },
    projects: {
      heading: "โปรเจกต์",
      text: "โปรเจกต์แนวคิดและงานสาธิตทางเทคนิค ติดป้ายไว้ชัดเจน ไม่มีชิ้นไหนอ้างว่าเป็นงานลูกค้า",
      hint: "ดูได้ด้วย: open projects",
    },
    stack: {
      heading: "สแตก",
      rows: { framework: "Framework", styling: "Styling", validation: "Validation", email: "อีเมล", data: "ข้อมูล", python: "Python", tooling: "Tooling", hosting: "Hosting" },
    },
    ai: {
      heading: "AI ใน Workflow",
      text: "AI ช่วยเร่งงานค้นคว้า การพัฒนา การรีวิว และการเทสต์ ส่วนสถาปัตยกรรม ความปลอดภัย และการตัดสินใจขึ้นระบบยังเป็นหน้าที่ของวิศวกร",
      hint: "รายละเอียด: open ai-native",
    },
    agents: {
      heading: "การพัฒนาแบบ Multi-Agent",
      text: "Orchestrator แจกงานให้ Agent เฉพาะทาง แล้วรวมผล ตรวจสอบ และส่งขึ้นระบบผ่าน Git, CI และ Vercel",
      roles: {
        orchestrator: "วางแผน แจกงาน รวมผล",
        design: "Layout, Token และรีวิวงานภาพ",
        frontend: "Component, Routing และ Accessibility",
        backend: "API, Validation และข้อมูล",
        research: "เอกสาร ทางเลือก และข้อจำกัด",
        test: "Unit Test และ End-to-End Test",
        review: "รีวิว Diff ความปลอดภัย และความสม่ำเสมอ",
      },
    },
    localAi: {
      heading: "Local AI (แนวคิด)",
      text: "Local Model เอกสารส่วนตัว และ Embeddings อยู่หลัง Router ที่ตัดสินว่าข้อมูลไหนออกจากเครื่องได้",
      hint: "สถาปัตยกรรม: open ai-native",
    },
    python: {
      heading: "Python",
      text: "Automation, API Client, การแปลงข้อมูลและไฟล์ และเครื่องมือสำหรับ Agent วงจรในหน้าระบบ AI สร้างจากสคริปต์ Python ใน Repository นี้",
    },
    architecture: { heading: "สถาปัตยกรรม", hint: "ดูแผนภาพเต็มได้ด้านล่าง" },
    contact: { heading: "ติดต่อ", text: "เร็วที่สุดคือฟอร์มโปรเจกต์ อีเมลและโทรศัพท์ก็ได้เช่นกัน", hint: "หรือกด Ctrl + K แล้วเลือกเริ่มโปรเจกต์" },
  },
  architecture: {
    eyebrow: "พอร์ตโฟลิโอนี้สร้างอย่างไร",
    title: "จากเบราว์เซอร์ถึงกล่องอีเมล",
    lede: "ทุกขั้นตอนตรงกับไฟล์จริงใน Repository",
    pathLabel: "ไฟล์",
    branchLabel: "ช่องทางส่งข้อความ",
    nodes: [
      { id: "browser", label: "เบราว์เซอร์", path: "/[locale]/…", desc: "เรนเดอร์ HTML ฝั่งเซิร์ฟเวอร์ก่อน ใช้ Client Component เฉพาะส่วนที่ต้องโต้ตอบ เช่น เมนู Palette, Terminal เครื่องมือ และฟอร์ม" },
      { id: "server", label: "Next.js App Router", path: "src/app · src/proxy.ts", desc: "มี Segment [locale] สำหรับ en, de และ th โดย Proxy จะ Redirect URL ที่ไม่มี Prefix ข้อความทั้งหมดอยู่ใน Dictionary แบบมี Type ใน src/content" },
      { id: "handler", label: "Server Action และ Route Handler", path: "src/app/actions · src/app/api/health", desc: "ฟอร์มโปรเจกต์ส่งไปที่ Server Action ส่วน /api/health รายงานสถานะที่ไม่มีข้อมูลลับ" },
      { id: "validation", label: "Validation และการป้องกัน", path: "src/lib/contact", desc: "Zod Schema ที่มี Error Code คงที่ ช่อง Honeypot และ Rate Limit ทั้งหมดทำงานบนเซิร์ฟเวอร์" },
      {
        id: "delivery",
        label: "การส่งข้อความ",
        path: "src/lib/contact/deliver.ts",
        desc: "ลองส่งทุกช่องทางที่ตั้งค่าไว้ สำเร็จเมื่ออย่างน้อยหนึ่งช่องทางรับข้อความได้ ถ้าไม่ได้ ฟอร์มจะบอกตามจริง",
        branches: ["อีเมลผ่าน Resend", "PostgreSQL (Neon)", "Webhook"],
      },
      { id: "python", label: "ไฟล์ Build จาก Python", path: "scripts/generate_ai_circuit.py", desc: "สร้าง JSON และ SVG ของวงจร AI ไว้ล่วงหน้า ตอนใช้งานจริงจึงไม่ต้องมี Python Runtime" },
      { id: "vercel", label: "GitHub → Vercel", path: "next.config.ts", desc: "Push ขึ้น main แล้ว Deploy บน Vercel อัตโนมัติ Security Header ตั้งไว้ใน next.config.ts" },
    ],
  },
  facts: {
    title: "วัดจาก Repository จริง",
    lede: "นับตอน Build จากไฟล์ชุดเดียวกับที่ใช้สร้างเมนูและเทสต์",
    items: { pages: "หน้า", languages: "ภาษา", routes: "Route ทุกภาษา", content: "Content Module", api: "API Endpoint", tests: "ไฟล์เทสต์", python: "สคริปต์ Python" },
  },
  statusLabels: { status: "สถานะ", environment: "Environment", region: "Region", commit: "Commit", database: "ฐานข้อมูล", email: "อีเมล", channels: "ช่องทาง" },
};

export const commandCenterContent: Localized<CommandCenterContent> = { en, de, th };
