import type { Localized } from "@/i18n/config";
import type { PageId } from "@/config/pages";

const en = {
  brandLabel: "Home",
  brandTag: "Digital builder",
  skipToContent: "Skip to content",
  nav: {
    home: "Home",
    projects: "Projects",
    capabilities: "Skills",
    "ai-native": "AI systems",
    "case-studies": "Case studies",
    lab: "Lab",
    systems: "Systems",
    "command-center": "Console",
    operator: "Operator",
    about: "About",
    contact: "Contact",
  } satisfies Record<PageId, string>,
  /** One-line description of each page, used in the menu and command palette. */
  navHint: {
    home: "Positioning, strengths and selected work",
    projects: "Real projects, prototypes and experiments",
    capabilities: "Practical skills and what I am exploring",
    "ai-native": "How AI is used in practice",
    "case-studies": "How decisions get made",
    lab: "Working tools in the browser",
    systems: "The real architecture behind this site",
    "command-center": "Live status, stack and console",
    operator: "After hours, inside the system",
    about: "Who I am and my background",
    contact: "Contact me",
  } satisfies Record<PageId, string>,
  menu: { open: "Menu", close: "Close", title: "Navigation", contact: "Direct contact" },
  primaryNav: "Main",
  startProject: "Contact",
  language: "Language",
  availability: {
    open: "Open to employment opportunities in IT, Web & AI-assisted digital work",
    limited: "Open to selected employment opportunities in IT & Web",
    closed: "Not looking for new opportunities right now",
    services: "Based in Germany · IT Quereinsteiger",
  },
  contact: {
    email: "Email",
    phone: "Phone",
    call: "Call",
    write: "Write an email",
    copy: "Copy",
    copied: "Copied",
  },
  commandPalette: {
    hint: "Search pages and actions",
    shortcut: "Ctrl K",
    placeholder: "Go to a page or run an action…",
    pages: "Pages",
    actions: "Actions",
    empty: "No matching command",
    contact: "Contact me",
    email: "Write an email",
    phone: "Call",
    github: "GitHub profile",
    source: "Source code of this site",
    switchTo: "Switch language to {language}",
    close: "Close",
  },
  footer: {
    tagline: "I turn ideas into working web, app and automation prototypes — with modern AI tools.",
    explore: "Explore",
    elsewhere: "Elsewhere",
    source: "Source code",
    builtWith: "Next.js · TypeScript · Python-generated circuit · Deployed on Vercel",
    rights: "All rights reserved.",
  },
  cta: {
    viewWork: "View projects",
    startProject: "Contact me",
    exploreAi: "See how I use AI",
    tellMe: "Tell me about the role",
    discussRedesign: "Contact me",
    addFeature: "Contact me",
    buildWithAi: "Contact me",
    contact: "Contact me",
    github: "GitHub",
  },
  band: {
    eyebrow: "Next step",
    title: "Let's talk about your team.",
    body: "I'm looking for a junior IT role or Quereinsteiger position in web development, automation or AI-assisted digital work. Write to me and I'll get back to you quickly.",
  },
  notFound: { title: "This page doesn't exist", body: "The link may be outdated. Head back to the start.", cta: "Back to home" },
  externalLink: "opens in a new tab",
};

export type CommonContent = typeof en;

const de: CommonContent = {
  brandLabel: "Start",
  brandTag: "Digital Builder",
  skipToContent: "Zum Inhalt springen",
  nav: {
    home: "Start",
    projects: "Projekte",
    capabilities: "Fähigkeiten",
    "ai-native": "KI-Systeme",
    "case-studies": "Fallstudien",
    lab: "Labor",
    systems: "Systeme",
    "command-center": "Konsole",
    operator: "Operator",
    about: "Über mich",
    contact: "Kontakt",
  },
  navHint: {
    home: "Positionierung, Stärken und ausgewählte Arbeiten",
    projects: "Echte Projekte, Prototypen und Experimente",
    capabilities: "Praktische Fähigkeiten und was ich gerade erkunde",
    "ai-native": "Wie KI in der Praxis eingesetzt wird",
    "case-studies": "Wie Entscheidungen entstehen",
    lab: "Funktionierende Tools im Browser",
    systems: "Die echte Architektur dieser Website",
    "command-center": "Live-Status, Stack und Konsole",
    operator: "Nach Feierabend, im System",
    about: "Wer ich bin und mein Hintergrund",
    contact: "Kontakt aufnehmen",
  },
  menu: { open: "Menü", close: "Schließen", title: "Navigation", contact: "Direkter Kontakt" },
  primaryNav: "Hauptnavigation",
  startProject: "Kontakt",
  language: "Sprache",
  availability: {
    open: "Offen für Anstellungen in IT, Web & KI-gestützter digitaler Arbeit",
    limited: "Offen für ausgewählte Anstellungen in IT & Web",
    closed: "Derzeit nicht auf der Suche nach neuen Möglichkeiten",
    services: "Ansässig in Deutschland · IT-Quereinsteiger",
  },
  contact: {
    email: "E-Mail",
    phone: "Telefon",
    call: "Anrufen",
    write: "E-Mail schreiben",
    copy: "Kopieren",
    copied: "Kopiert",
  },
  commandPalette: {
    hint: "Seiten und Aktionen durchsuchen",
    shortcut: "Strg K",
    placeholder: "Seite öffnen oder Aktion ausführen …",
    pages: "Seiten",
    actions: "Aktionen",
    empty: "Kein passender Befehl",
    contact: "Kontakt aufnehmen",
    email: "E-Mail schreiben",
    phone: "Anrufen",
    github: "GitHub-Profil",
    source: "Quellcode dieser Website",
    switchTo: "Sprache wechseln zu {language}",
    close: "Schließen",
  },
  footer: {
    tagline: "Aus Ideen mache ich funktionierende Web-, App- und Automatisierungs-Prototypen – mit modernen KI-Werkzeugen.",
    explore: "Entdecken",
    elsewhere: "Weitere Kanäle",
    source: "Quellcode",
    builtWith: "Next.js · TypeScript · Python-generierter Schaltplan · Gehostet auf Vercel",
    rights: "Alle Rechte vorbehalten.",
  },
  cta: {
    viewWork: "Projekte ansehen",
    startProject: "Kontakt aufnehmen",
    exploreAi: "So nutze ich KI",
    tellMe: "Erzählen Sie mir von der Stelle",
    discussRedesign: "Kontakt aufnehmen",
    addFeature: "Kontakt aufnehmen",
    buildWithAi: "Kontakt aufnehmen",
    contact: "Kontakt aufnehmen",
    github: "GitHub",
  },
  band: {
    eyebrow: "Nächster Schritt",
    title: "Sprechen wir über Ihr Team.",
    body: "Ich suche eine Junior-IT-Stelle oder eine Quereinsteiger-Position in Webentwicklung, Automatisierung oder KI-gestützter digitaler Arbeit. Schreiben Sie mir, und ich melde mich schnell zurück.",
  },
  notFound: { title: "Diese Seite gibt es nicht", body: "Der Link ist vielleicht veraltet. Zurück zum Anfang.", cta: "Zur Startseite" },
  externalLink: "öffnet in neuem Tab",
};

const th: CommonContent = {
  brandLabel: "หน้าแรก",
  brandTag: "นักสร้างดิจิทัล",
  skipToContent: "ข้ามไปยังเนื้อหา",
  nav: {
    home: "หน้าแรก",
    projects: "โปรเจกต์",
    capabilities: "ทักษะ",
    "ai-native": "ระบบ AI",
    "case-studies": "กรณีศึกษา",
    lab: "Lab",
    systems: "ระบบ",
    "command-center": "คอนโซล",
    operator: "Operator",
    about: "เกี่ยวกับ",
    contact: "ติดต่อ",
  },
  navHint: {
    home: "จุดยืน จุดแข็ง และผลงานที่คัดมา",
    projects: "โปรเจกต์จริง ต้นแบบ และโปรเจกต์ทดลอง",
    capabilities: "ทักษะที่ใช้ได้จริง และสิ่งที่กำลังเรียนรู้",
    "ai-native": "วิธีใช้ AI ในงานจริง",
    "case-studies": "เบื้องหลังการตัดสินใจ",
    lab: "เครื่องมือที่ใช้งานได้จริงบนเบราว์เซอร์",
    systems: "สถาปัตยกรรมจริงเบื้องหลังเว็บไซต์นี้",
    "command-center": "สถานะสด สแตก และคอนโซล",
    operator: "ยามดึก ภายในระบบ",
    about: "ตัวตนและภูมิหลัง",
    contact: "ช่องทางการติดต่อ",
  },
  menu: { open: "เมนู", close: "ปิด", title: "เมนูนำทาง", contact: "ติดต่อโดยตรง" },
  primaryNav: "เมนูหลัก",
  startProject: "ติดต่อ",
  language: "ภาษา",
  availability: {
    open: "เปิดรับโอกาสทำงานในสาย IT, Web และงานดิจิทัลที่ใช้ AI",
    limited: "เปิดรับโอกาสทำงานบางตำแหน่งในสาย IT และ Web",
    closed: "ยังไม่เปิดรับโอกาสใหม่ในขณะนี้",
    services: "อยู่ที่เยอรมนี · IT Quereinsteiger",
  },
  contact: {
    email: "อีเมล",
    phone: "โทรศัพท์",
    call: "โทร",
    write: "ส่งอีเมล",
    copy: "คัดลอก",
    copied: "คัดลอกแล้ว",
  },
  commandPalette: {
    hint: "ค้นหาหน้าและคำสั่ง",
    shortcut: "Ctrl K",
    placeholder: "ไปยังหน้าหรือสั่งงาน…",
    pages: "หน้า",
    actions: "คำสั่ง",
    empty: "ไม่พบคำสั่งที่ตรงกัน",
    contact: "ติดต่อ",
    email: "ส่งอีเมล",
    phone: "โทร",
    github: "โปรไฟล์ GitHub",
    source: "ซอร์สโค้ดของเว็บไซต์นี้",
    switchTo: "เปลี่ยนภาษาเป็น {language}",
    close: "ปิด",
  },
  footer: {
    tagline: "เปลี่ยนไอเดียให้เป็นต้นแบบเว็บ แอป และระบบอัตโนมัติที่ใช้งานได้จริง ด้วยเครื่องมือ AI สมัยใหม่",
    explore: "สำรวจ",
    elsewhere: "ช่องทางอื่น",
    source: "ซอร์สโค้ด",
    builtWith: "Next.js · TypeScript · วงจรที่สร้างด้วย Python · Deploy บน Vercel",
    rights: "สงวนลิขสิทธิ์",
  },
  cta: {
    viewWork: "ดูโปรเจกต์",
    startProject: "ติดต่อ",
    exploreAi: "ดูวิธีใช้ AI",
    tellMe: "เล่าเรื่องตำแหน่งงานให้ฟัง",
    discussRedesign: "ติดต่อ",
    addFeature: "ติดต่อ",
    buildWithAi: "ติดต่อ",
    contact: "ติดต่อ",
    github: "GitHub",
  },
  band: {
    eyebrow: "ขั้นตอนถัดไป",
    title: "มาคุยเรื่องทีมของคุณกัน",
    body: "กำลังมองหาตำแหน่งงาน IT ระดับ Junior หรืองาน Quereinsteiger สายพัฒนาเว็บ ระบบอัตโนมัติ หรืองานดิจิทัลที่ใช้ AI เขียนมาได้เลย จะรีบตอบกลับ",
  },
  notFound: { title: "ไม่พบหน้านี้", body: "ลิงก์อาจล้าสมัยแล้ว กลับไปเริ่มต้นใหม่ได้เลย", cta: "กลับหน้าแรก" },
  externalLink: "เปิดในแท็บใหม่",
};

export const common: Localized<CommonContent> = { en, de, th };
