import type { Localized } from "@/i18n/config";
import type { PageId } from "@/config/pages";

const en = {
  brandLabel: "Home",
  skipToContent: "Skip to content",
  nav: {
    home: "Home",
    projects: "Work",
    capabilities: "Capabilities",
    "ai-native": "AI systems",
    "case-studies": "Case studies",
    lab: "Lab",
    systems: "Systems",
    "command-center": "Command center",
    operator: "Operator",
    about: "About",
    contact: "Contact",
  } satisfies Record<PageId, string>,
  /** One-line description of each page, used in the menu and command palette. */
  navHint: {
    home: "Services and overview",
    projects: "Concept projects and demonstrations",
    capabilities: "Web, Python and AI as one network",
    "ai-native": "Orchestration, agents, cloud and local AI",
    "case-studies": "How decisions get made",
    lab: "Working tools in the browser",
    systems: "The real architecture behind this site",
    "command-center": "Live status, stack and console",
    operator: "After hours, inside the system",
    about: "Who builds this",
    contact: "Start a project",
  } satisfies Record<PageId, string>,
  menu: { open: "Menu", close: "Close", title: "Navigation", contact: "Direct contact" },
  primaryNav: "Main",
  startProject: "Start a project",
  language: "Language",
  availability: {
    open: "Available for freelance projects",
    limited: "Limited freelance availability",
    closed: "Not taking new projects right now",
    services: "Websites · Redesigns · New features · AI integration",
  },
  contact: {
    email: "Email",
    phone: "Phone",
    call: "Call",
    write: "Write an email",
    copy: "Copy",
    copied: "Copied",
  },
  commandPalette: {
    hint: "Search pages and actions",
    shortcut: "Ctrl K",
    placeholder: "Go to a page or run an action…",
    pages: "Pages",
    actions: "Actions",
    empty: "No matching command",
    contact: "Start a project",
    email: "Write an email",
    phone: "Call",
    github: "GitHub profile",
    source: "Source code of this site",
    switchTo: "Switch language to {language}",
    close: "Close",
  },
  footer: {
    tagline: "Websites, web applications and AI-enabled systems — designed, built and shipped.",
    explore: "Explore",
    elsewhere: "Elsewhere",
    source: "Source code",
    builtWith: "Next.js · TypeScript · Python-generated circuit · Deployed on Vercel",
    rights: "All rights reserved.",
  },
  cta: {
    viewWork: "View work",
    startProject: "Start a project",
    exploreAi: "Explore AI systems",
    tellMe: "Tell me what you're building",
    discussRedesign: "Discuss a redesign",
    addFeature: "Add a feature",
    buildWithAi: "Build with AI",
    contact: "Contact me",
  },
  band: {
    eyebrow: "Next step",
    title: "Have a project in mind? Let's build it.",
    body: "New site, redesign, a feature for an existing product or an AI workflow — describe it and you'll get a clear reply about scope, approach and timing.",
  },
  notFound: { title: "This page doesn't exist", body: "The link may be outdated. Head back to the start.", cta: "Back to home" },
  externalLink: "opens in a new tab",
};

export type CommonContent = typeof en;

const de: CommonContent = {
  brandLabel: "Startseite",
  skipToContent: "Zum Inhalt springen",
  nav: {
    home: "Start",
    projects: "Arbeiten",
    capabilities: "Fähigkeiten",
    "ai-native": "KI-Systeme",
    "case-studies": "Fallstudien",
    lab: "Labor",
    systems: "Systeme",
    "command-center": "Kommandozentrale",
    operator: "Operator",
    about: "Über mich",
    contact: "Kontakt",
  },
  navHint: {
    home: "Leistungen und Überblick",
    projects: "Konzeptprojekte und Demonstrationen",
    capabilities: "Web, Python und KI als ein Netzwerk",
    "ai-native": "Orchestrierung, Agents, Cloud- und lokale KI",
    "case-studies": "Wie Entscheidungen entstehen",
    lab: "Funktionierende Tools im Browser",
    systems: "Die echte Architektur dieser Website",
    "command-center": "Live-Status, Stack und Konsole",
    operator: "Nach Feierabend, im System",
    about: "Wer das baut",
    contact: "Projekt starten",
  },
  menu: { open: "Menü", close: "Schließen", title: "Navigation", contact: "Direkter Kontakt" },
  primaryNav: "Hauptnavigation",
  startProject: "Projekt starten",
  language: "Sprache",
  availability: {
    open: "Verfügbar für Freelance-Projekte",
    limited: "Begrenzt verfügbar für Freelance-Projekte",
    closed: "Derzeit keine neuen Projekte",
    services: "Websites · Redesigns · Neue Features · KI-Integration",
  },
  contact: {
    email: "E-Mail",
    phone: "Telefon",
    call: "Anrufen",
    write: "E-Mail schreiben",
    copy: "Kopieren",
    copied: "Kopiert",
  },
  commandPalette: {
    hint: "Seiten und Aktionen durchsuchen",
    shortcut: "Strg K",
    placeholder: "Seite öffnen oder Aktion ausführen…",
    pages: "Seiten",
    actions: "Aktionen",
    empty: "Kein passender Befehl",
    contact: "Projekt starten",
    email: "E-Mail schreiben",
    phone: "Anrufen",
    github: "GitHub-Profil",
    source: "Quellcode dieser Website",
    switchTo: "Sprache wechseln zu {language}",
    close: "Schließen",
  },
  footer: {
    tagline: "Websites, Webanwendungen und KI-gestützte Systeme – konzipiert, gebaut und ausgeliefert.",
    explore: "Entdecken",
    elsewhere: "Online",
    source: "Quellcode",
    builtWith: "Next.js · TypeScript · Python-generierter Schaltplan · Gehostet auf Vercel",
    rights: "Alle Rechte vorbehalten.",
  },
  cta: {
    viewWork: "Arbeiten ansehen",
    startProject: "Projekt starten",
    exploreAi: "KI-Systeme entdecken",
    tellMe: "Erzähl mir, was du baust",
    discussRedesign: "Redesign besprechen",
    addFeature: "Feature ergänzen",
    buildWithAi: "Mit KI bauen",
    contact: "Kontakt aufnehmen",
  },
  band: {
    eyebrow: "Nächster Schritt",
    title: "Ein Projekt im Kopf? Lass es uns bauen.",
    body: "Neue Website, Redesign, ein Feature für ein bestehendes Produkt oder ein KI-Workflow – beschreib es kurz und du bekommst eine klare Antwort zu Umfang, Vorgehen und Zeitplan.",
  },
  notFound: { title: "Diese Seite gibt es nicht", body: "Der Link ist vielleicht veraltet. Zurück zum Anfang.", cta: "Zur Startseite" },
  externalLink: "öffnet in neuem Tab",
};

const th: CommonContent = {
  brandLabel: "หน้าแรก",
  skipToContent: "ข้ามไปยังเนื้อหา",
  nav: {
    home: "หน้าแรก",
    projects: "ผลงาน",
    capabilities: "ความสามารถ",
    "ai-native": "ระบบ AI",
    "case-studies": "กรณีศึกษา",
    lab: "Lab",
    systems: "ระบบ",
    "command-center": "Command Center",
    operator: "Operator",
    about: "เกี่ยวกับ",
    contact: "ติดต่อ",
  },
  navHint: {
    home: "บริการและภาพรวม",
    projects: "โปรเจกต์แนวคิดและงานสาธิต",
    capabilities: "Web, Python และ AI ในเครือข่ายเดียว",
    "ai-native": "Orchestration, Agent, Cloud AI และ Local AI",
    "case-studies": "เบื้องหลังการตัดสินใจ",
    lab: "เครื่องมือที่ใช้งานได้จริงบนเบราว์เซอร์",
    systems: "สถาปัตยกรรมจริงของเว็บไซต์นี้",
    "command-center": "สถานะสด สแตก และคอนโซล",
    operator: "ยามดึก ภายในระบบ",
    about: "คนที่สร้างงานนี้",
    contact: "เริ่มโปรเจกต์",
  },
  menu: { open: "เมนู", close: "ปิด", title: "เมนูนำทาง", contact: "ติดต่อโดยตรง" },
  primaryNav: "เมนูหลัก",
  startProject: "เริ่มโปรเจกต์",
  language: "ภาษา",
  availability: {
    open: "รับงานฟรีแลนซ์",
    limited: "รับงานฟรีแลนซ์ได้จำกัด",
    closed: "ยังไม่รับโปรเจกต์ใหม่ในขณะนี้",
    services: "เว็บไซต์ · Redesign · ฟีเจอร์ใหม่ · AI Integration",
  },
  contact: {
    email: "อีเมล",
    phone: "โทรศัพท์",
    call: "โทร",
    write: "ส่งอีเมล",
    copy: "คัดลอก",
    copied: "คัดลอกแล้ว",
  },
  commandPalette: {
    hint: "ค้นหาหน้าและคำสั่ง",
    shortcut: "Ctrl K",
    placeholder: "ไปยังหน้าหรือสั่งงาน…",
    pages: "หน้า",
    actions: "คำสั่ง",
    empty: "ไม่พบคำสั่งที่ตรงกัน",
    contact: "เริ่มโปรเจกต์",
    email: "ส่งอีเมล",
    phone: "โทร",
    github: "โปรไฟล์ GitHub",
    source: "ซอร์สโค้ดของเว็บไซต์นี้",
    switchTo: "เปลี่ยนภาษาเป็น {language}",
    close: "ปิด",
  },
  footer: {
    tagline: "เว็บไซต์ เว็บแอป และระบบที่ใช้ AI ตั้งแต่ออกแบบ พัฒนา จนขึ้นใช้งานจริง",
    explore: "สำรวจ",
    elsewhere: "ช่องทางอื่น",
    source: "ซอร์สโค้ด",
    builtWith: "Next.js · TypeScript · วงจรที่สร้างด้วย Python · Deploy บน Vercel",
    rights: "สงวนลิขสิทธิ์",
  },
  cta: {
    viewWork: "ดูผลงาน",
    startProject: "เริ่มโปรเจกต์",
    exploreAi: "สำรวจระบบ AI",
    tellMe: "เล่าให้ฟังว่ากำลังสร้างอะไร",
    discussRedesign: "คุยเรื่อง Redesign",
    addFeature: "เพิ่มฟีเจอร์",
    buildWithAi: "สร้างด้วย AI",
    contact: "ติดต่อ",
  },
  band: {
    eyebrow: "ขั้นตอนถัดไป",
    title: "มีโปรเจกต์ในใจไหม มาสร้างด้วยกัน",
    body: "เว็บไซต์ใหม่ Redesign ฟีเจอร์สำหรับระบบเดิม หรือ AI Workflow เล่ามาสั้น ๆ แล้วจะได้คำตอบที่ชัดเจนเรื่องขอบเขต แนวทาง และระยะเวลา",
  },
  notFound: { title: "ไม่พบหน้านี้", body: "ลิงก์อาจล้าสมัยแล้ว กลับไปเริ่มต้นใหม่ได้เลย", cta: "กลับหน้าแรก" },
  externalLink: "เปิดในแท็บใหม่",
};

export const common: Localized<CommonContent> = { en, de, th };
