import type { Localized } from "@/i18n/config";
import type { PageId } from "@/config/pages";

const en = {
  brandLabel: "Home",
  skipToContent: "Skip to content",
  nav: {
    home: "Home",
    about: "Journey",
    skills: "Toolbox",
    projects: "Projects",
    "case-studies": "Case studies",
    "ai-native": "AI-native",
    lab: "Lab",
    systems: "Systems",
    "command-center": "Command center",
  } satisfies Record<PageId, string>,
  menu: { open: "Menu", close: "Close", title: "All pages", hint: "Nine pages, each a little more technical than the last." },
  pageProgress: "Page {n} of {total}",
  progressLabel: "Portfolio progress",
  hireMe: "Hire me",
  language: "Language",
  commandPalette: {
    hint: "Search pages and actions",
    shortcut: "Ctrl K",
    placeholder: "Go to a page or run an action…",
    pages: "Pages",
    actions: "Actions",
    empty: "No matching command",
    contact: "Contact form",
    github: "GitHub profile",
    source: "Source code of this site",
    switchTo: "Switch language to {language}",
    close: "Close",
  },
  footer: {
    tagline: "Web developer × AI-native builder. Modern interfaces, real backends, production-ready.",
    availability: { open: "Available for new projects", limited: "Limited availability", closed: "Not taking new projects" },
    explore: "Explore",
    elsewhere: "Elsewhere",
    source: "Source code",
    builtWith: "Built with Next.js, TypeScript and Tailwind CSS.",
    rights: "All rights reserved.",
  },
  cta: {
    viewWork: "View my work",
    startConversation: "Start a conversation",
    discussProject: "Discuss a project",
    seeHowIBuild: "See how I build",
    tellMe: "Tell me about your project",
    next: "Next page",
    previous: "Previous page",
  },
  band: {
    eyebrow: "Next step",
    title: "Have a project in mind? Let's build it.",
    body: "Tell me what you need. You'll get a clear reply about scope, approach and timing.",
  },
  notFound: { title: "This page doesn't exist", body: "The link may be outdated. Head back to the start.", cta: "Back to home" },
  externalLink: "opens in a new tab",
};

export type CommonContent = typeof en;

const de: CommonContent = {
  brandLabel: "Startseite",
  skipToContent: "Zum Inhalt springen",
  nav: {
    home: "Start",
    about: "Werdegang",
    skills: "Werkzeugkasten",
    projects: "Projekte",
    "case-studies": "Fallstudien",
    "ai-native": "KI-nativ",
    lab: "Labor",
    systems: "Systeme",
    "command-center": "Kommandozentrale",
  },
  menu: { open: "Menü", close: "Schließen", title: "Alle Seiten", hint: "Neun Seiten, jede ein Stück technischer als die vorige." },
  pageProgress: "Seite {n} von {total}",
  progressLabel: "Fortschritt im Portfolio",
  hireMe: "Jetzt anfragen",
  language: "Sprache",
  commandPalette: {
    hint: "Seiten und Aktionen durchsuchen",
    shortcut: "Strg K",
    placeholder: "Seite öffnen oder Aktion ausführen…",
    pages: "Seiten",
    actions: "Aktionen",
    empty: "Kein passender Befehl",
    contact: "Kontaktformular",
    github: "GitHub-Profil",
    source: "Quellcode dieser Website",
    switchTo: "Sprache wechseln zu {language}",
    close: "Schließen",
  },
  footer: {
    tagline: "Webentwicklung × KI-natives Arbeiten. Moderne Oberflächen, echte Backends, bereit für die Produktion.",
    availability: { open: "Für neue Projekte verfügbar", limited: "Begrenzte Verfügbarkeit", closed: "Derzeit keine neuen Projekte" },
    explore: "Entdecken",
    elsewhere: "Online",
    source: "Quellcode",
    builtWith: "Gebaut mit Next.js, TypeScript und Tailwind CSS.",
    rights: "Alle Rechte vorbehalten.",
  },
  cta: {
    viewWork: "Arbeiten ansehen",
    startConversation: "Gespräch beginnen",
    discussProject: "Projekt besprechen",
    seeHowIBuild: "So arbeite ich",
    tellMe: "Projekt schildern",
    next: "Nächste Seite",
    previous: "Vorherige Seite",
  },
  band: {
    eyebrow: "Nächster Schritt",
    title: "Ein Projekt im Kopf? Lass es uns bauen.",
    body: "Schildere kurz, was du brauchst. Du bekommst eine klare Antwort zu Umfang, Vorgehen und Zeitplan.",
  },
  notFound: { title: "Diese Seite gibt es nicht", body: "Der Link ist vielleicht veraltet. Zurück zum Anfang.", cta: "Zur Startseite" },
  externalLink: "öffnet in neuem Tab",
};

const th: CommonContent = {
  brandLabel: "หน้าแรก",
  skipToContent: "ข้ามไปยังเนื้อหา",
  nav: {
    home: "หน้าแรก",
    about: "เส้นทาง",
    skills: "เครื่องมือ",
    projects: "โปรเจกต์",
    "case-studies": "กรณีศึกษา",
    "ai-native": "AI-native",
    lab: "ห้องทดลอง",
    systems: "ระบบหลังบ้าน",
    "command-center": "ศูนย์ควบคุม",
  },
  menu: { open: "เมนู", close: "ปิด", title: "ทุกหน้า", hint: "เก้าหน้า แต่ละหน้าลึกทางเทคนิคขึ้นเรื่อย ๆ" },
  pageProgress: "หน้า {n} จาก {total}",
  progressLabel: "ความคืบหน้าของพอร์ตโฟลิโอ",
  hireMe: "ร่วมงานกัน",
  language: "ภาษา",
  commandPalette: {
    hint: "ค้นหาหน้าและคำสั่ง",
    shortcut: "Ctrl K",
    placeholder: "ไปยังหน้าหรือสั่งงาน…",
    pages: "หน้า",
    actions: "คำสั่ง",
    empty: "ไม่พบคำสั่งที่ตรงกัน",
    contact: "แบบฟอร์มติดต่อ",
    github: "โปรไฟล์ GitHub",
    source: "ซอร์สโค้ดของเว็บไซต์นี้",
    switchTo: "เปลี่ยนภาษาเป็น {language}",
    close: "ปิด",
  },
  footer: {
    tagline: "นักพัฒนาเว็บ × การทำงานแบบ AI-native อินเทอร์เฟซทันสมัย แบ็กเอนด์ใช้งานจริง พร้อมขึ้นระบบจริง",
    availability: { open: "พร้อมรับโปรเจกต์ใหม่", limited: "รับงานได้จำกัด", closed: "ไม่รับโปรเจกต์ใหม่ในขณะนี้" },
    explore: "สำรวจ",
    elsewhere: "ช่องทางอื่น",
    source: "ซอร์สโค้ด",
    builtWith: "สร้างด้วย Next.js, TypeScript และ Tailwind CSS",
    rights: "สงวนลิขสิทธิ์",
  },
  cta: {
    viewWork: "ดูผลงาน",
    startConversation: "เริ่มคุยกัน",
    discussProject: "ปรึกษาโปรเจกต์",
    seeHowIBuild: "ดูวิธีการทำงาน",
    tellMe: "เล่าโปรเจกต์ของคุณ",
    next: "หน้าถัดไป",
    previous: "หน้าก่อนหน้า",
  },
  band: {
    eyebrow: "ขั้นตอนถัดไป",
    title: "มีโปรเจกต์ในใจไหม มาสร้างด้วยกัน",
    body: "เล่าสิ่งที่ต้องการมาได้เลย จะได้คำตอบที่ชัดเจนเรื่องขอบเขต แนวทาง และระยะเวลา",
  },
  notFound: { title: "ไม่พบหน้านี้", body: "ลิงก์อาจล้าสมัยแล้ว กลับไปเริ่มต้นใหม่ได้เลย", cta: "กลับหน้าแรก" },
  externalLink: "เปิดในแท็บใหม่",
};

export const common: Localized<CommonContent> = { en, de, th };
