import type { Localized } from "@/i18n/config";

const en = {
  meta: {
    title: "Engineering command center",
    description: "An instrument panel for this portfolio: a safe terminal, the real architecture, live backend health and a Ctrl/Cmd + K palette.",
  },
  hero: {
    eyebrow: "Command center",
    complexity: "Complexity",
    title: { lead: "The whole system,", accent: "in one view." },
    lede: "Everything the earlier pages describe, made inspectable: a read-only terminal, the real architecture of this site and its live backend health.",
  },
  palette: {
    eyebrow: "Command palette",
    title: "Navigate with the keyboard",
    body: "Press Ctrl + K (⌘ + K on Mac) on any page to jump between pages, open the contact form or switch language.",
    button: "Open command palette",
    keys: "Shortcut",
  },
  terminal: {
    eyebrow: "Safe terminal",
    title: "Ask the portfolio",
    body: "A controlled, read-only console. It only understands the commands listed in help. Nothing is executed on a server or in a shell.",
    label: "Portfolio terminal",
    logLabel: "Terminal output",
    badge: "read-only",
    prompt: "visitor@portfolio:~$",
    placeholder: "Type a command, e.g. help",
    submit: "Run",
    quick: "Try a command",
    intro: "Welcome. This is a safe, read-only terminal. Type help to see what it can do.",
    messages: {
      helpTitle: "Available commands",
      helpHint: "Tab completes a command. ArrowUp and ArrowDown browse your history.",
      unknown: "Command not found: {command}. Type help for the list of commands.",
      openArg: "page",
      openUsage: "Usage: open <page>. Pages: {pages}. A page number such as 4 works too.",
      openUnknown: "No page named “{name}”. Pages: {pages}.",
      opening: "Opening {page}…",
      langUsage: "Current language: {current}. Usage: lang <{codes}>.",
      langUnknown: "Unsupported language “{name}”. Available: {codes}.",
      langCurrent: "Already using {language}.",
      langSwitching: "Switching to {language}…",
      descriptions: {
        help: "List all commands",
        about: "Who is behind this portfolio",
        skills: "Capabilities by area",
        projects: "What the project pages contain",
        stack: "Technologies used to build this site",
        ai: "The AI-native workflow",
        architecture: "How this site is built",
        contact: "How to get in touch",
        open: "Go to a page",
        lang: "Switch language",
        clear: "Clear the screen",
      },
    },
    labels: { name: "Name", location: "Location", availability: "Availability", github: "GitHub", email: "Email", form: "Contact form", source: "Source" },
    about: {
      heading: "About",
      text: "Web developer × AI-native builder. Modern interfaces, real backends and AI-assisted workflows, taken from idea to production.",
    },
    skills: { heading: "Skills", groups: { frontend: "Frontend", backend: "Backend", ai: "AI-native", engineering: "Engineering" } },
    projects: {
      heading: "Projects",
      text: "The project pages hold concept projects and technical demonstrations. They are labeled as such and are not client work.",
      categories: "Categories",
      categoryList: "SaaS · business website · dashboard · e-commerce concept · AI workflow · internal tool · landing page · developer tool",
      hint: "Explore them with: open projects",
    },
    stack: { heading: "Stack", rows: { framework: "Framework", styling: "Styling", validation: "Validation", data: "Data", tooling: "Tooling", hosting: "Hosting" } },
    ai: {
      heading: "AI-native workflow",
      text: "AI accelerates the workflow. Human engineering judgment controls the outcome.",
      steps: ["Understand", "Research", "Plan", "Prototype", "Build", "Review", "Test", "Refactor", "Deploy"],
      hint: "Details: open ai-native",
    },
    architecture: { heading: "Architecture", hint: "Full diagram below on this page." },
    contact: { heading: "Contact", text: "The contact form validates on the server and is the primary channel.", hint: "Or press Ctrl + K and choose Contact form." },
  },
  architecture: {
    eyebrow: "How this portfolio is built",
    title: "From browser to database, in seven steps",
    lede: "Every box below maps to real files in the repository. Nothing here is a mock-up.",
    pathLabel: "Where",
    branchLabel: "Two delivery channels",
    nodes: [
      { id: "browser", label: "Browser", path: "/[locale]/…", desc: "Server-rendered HTML first. Small client islands only where interaction needs them: menu, palette, terminal and forms." },
      { id: "components", label: "Components", path: "src/components", desc: "Shared primitives, the site shell and one folder per page. Server Components by default." },
      { id: "server", label: "Next.js server", path: "src/app · src/proxy.ts", desc: "App Router with a [locale] segment. The proxy redirects unprefixed URLs to /en, /de or /th. Copy lives in typed dictionaries in src/content." },
      { id: "handler", label: "Server Action & Route Handler", path: "src/app/actions · src/app/api/health", desc: "The contact form posts to a Server Action. /api/health reports safe, non-secret status." },
      { id: "validation", label: "Validation & protection", path: "src/lib/contact", desc: "A Zod schema with stable error codes, a honeypot field and a best-effort rate limit run on the server before anything is stored." },
      {
        id: "delivery",
        label: "Delivery",
        path: "contact_submissions · CONTACT_WEBHOOK_URL",
        desc: "A submission is written to PostgreSQL when DATABASE_URL is set and sent to a webhook when CONTACT_WEBHOOK_URL is set. If neither is configured, the form says so instead of pretending to succeed.",
        branches: ["PostgreSQL (Neon)", "Webhook"],
      },
      { id: "vercel", label: "Vercel", path: "next.config.ts", desc: "Deployed on Vercel. Security headers such as nosniff, frame denial, HSTS and referrer and permissions policies are set in next.config.ts." },
    ],
  },
  facts: {
    title: "Measured from the repository",
    lede: "Computed when the site is built, from the same configuration files that drive the navigation.",
    items: { pages: "Pages", languages: "Languages", routes: "Localized routes", content: "Content modules", api: "API endpoints" },
  },
  health: {
    eyebrow: "Live backend",
    title: "Health endpoint",
    endpoint: "GET /api/health",
    loading: "Checking…",
    error: "The health endpoint could not be reached.",
    retry: "Check again",
    raw: "View raw JSON",
    status: { ok: "Operational", degraded: "Degraded" },
    fields: { status: "Status", environment: "Environment", region: "Region", commit: "Commit", database: "Database", webhook: "Webhook", latency: "Round trip", node: "Runtime" },
    values: { connected: "Connected", unreachable: "Unreachable", "not-configured": "Not configured", configured: "Configured", local: "local" },
  },
  overview: {
    eyebrow: "System overview",
    title: "Three languages, one codebase",
    lede: "Every public page exists in English, German and Thai. Copy is stored locally, with no runtime translation service.",
    caption: "Supported locales and their URL structure",
    cols: { language: "Language", prefix: "URL prefix", html: "HTML lang", pages: "Pages", sample: "Example route" },
  },
  cta: { label: "Start a conversation" },
};

export type CommandCenterContent = typeof en;

const de: CommandCenterContent = {
  meta: {
    title: "Kommandozentrale",
    description: "Ein Instrumentenbrett für dieses Portfolio: sicheres Terminal, reale Architektur, Live-Status des Backends und eine Strg/Cmd + K-Palette.",
  },
  hero: {
    eyebrow: "Kommandozentrale",
    complexity: "Komplexität",
    title: { lead: "Das ganze System,", accent: "auf einen Blick." },
    lede: "Alles, was die früheren Seiten beschreiben, zum Nachprüfen: ein schreibgeschütztes Terminal, die echte Architektur dieser Website und der Live-Status ihres Backends.",
  },
  palette: {
    eyebrow: "Befehlspalette",
    title: "Navigieren per Tastatur",
    body: "Drücke auf jeder Seite Strg + K (⌘ + K auf dem Mac), um zwischen Seiten zu springen, das Kontaktformular zu öffnen oder die Sprache zu wechseln.",
    button: "Befehlspalette öffnen",
    keys: "Tastenkürzel",
  },
  terminal: {
    eyebrow: "Sicheres Terminal",
    title: "Frag das Portfolio",
    body: "Eine kontrollierte, schreibgeschützte Konsole. Sie versteht nur die Befehle aus help. Nichts wird auf einem Server oder in einer Shell ausgeführt.",
    label: "Portfolio-Terminal",
    logLabel: "Terminal-Ausgabe",
    badge: "schreibgeschützt",
    prompt: "besucher@portfolio:~$",
    placeholder: "Befehl eingeben, z. B. help",
    submit: "Ausführen",
    quick: "Befehl ausprobieren",
    intro: "Willkommen. Dies ist ein sicheres, schreibgeschütztes Terminal. Mit help siehst du, was möglich ist.",
    messages: {
      helpTitle: "Verfügbare Befehle",
      helpHint: "Mit Tab wird ein Befehl vervollständigt. Pfeil hoch und runter blättern durch den Verlauf.",
      unknown: "Befehl nicht gefunden: {command}. Mit help siehst du alle Befehle.",
      openArg: "seite",
      openUsage: "Aufruf: open <seite>. Seiten: {pages}. Auch eine Seitennummer wie 4 funktioniert.",
      openUnknown: "Keine Seite namens „{name}“. Seiten: {pages}.",
      opening: "{page} wird geöffnet …",
      langUsage: "Aktuelle Sprache: {current}. Aufruf: lang <{codes}>.",
      langUnknown: "Sprache „{name}“ wird nicht unterstützt. Verfügbar: {codes}.",
      langCurrent: "{language} ist bereits aktiv.",
      langSwitching: "Wechsel zu {language} …",
      descriptions: {
        help: "Alle Befehle auflisten",
        about: "Wer hinter diesem Portfolio steckt",
        skills: "Fähigkeiten nach Bereich",
        projects: "Was die Projektseiten enthalten",
        stack: "Technologien dieser Website",
        ai: "Der KI-native Arbeitsablauf",
        architecture: "Wie diese Website gebaut ist",
        contact: "So kommst du mit mir in Kontakt",
        open: "Zu einer Seite wechseln",
        lang: "Sprache wechseln",
        clear: "Bildschirm leeren",
      },
    },
    labels: { name: "Name", location: "Standort", availability: "Verfügbarkeit", github: "GitHub", email: "E-Mail", form: "Kontaktformular", source: "Quellcode" },
    about: {
      heading: "Über",
      text: "Webentwicklung × KI-natives Arbeiten. Moderne Oberflächen, echte Backends und KI-gestützte Abläufe, von der Idee bis zur Produktion.",
    },
    skills: { heading: "Fähigkeiten", groups: { frontend: "Frontend", backend: "Backend", ai: "KI-nativ", engineering: "Engineering" } },
    projects: {
      heading: "Projekte",
      text: "Die Projektseiten zeigen Konzeptprojekte und technische Demonstrationen. Sie sind entsprechend gekennzeichnet und keine Kundenarbeiten.",
      categories: "Kategorien",
      categoryList: "SaaS · Unternehmenswebsite · Dashboard · E-Commerce-Konzept · KI-Workflow · internes Tool · Landingpage · Entwickler-Tool",
      hint: "Ansehen mit: open projects",
    },
    stack: { heading: "Stack", rows: { framework: "Framework", styling: "Styling", validation: "Validierung", data: "Daten", tooling: "Werkzeuge", hosting: "Hosting" } },
    ai: {
      heading: "KI-nativer Ablauf",
      text: "KI beschleunigt den Ablauf. Das Urteil der Entwicklung bestimmt das Ergebnis.",
      steps: ["Verstehen", "Recherchieren", "Planen", "Prototypen", "Bauen", "Prüfen", "Testen", "Refaktorieren", "Ausliefern"],
      hint: "Details: open ai-native",
    },
    architecture: { heading: "Architektur", hint: "Das vollständige Diagramm steht weiter unten auf dieser Seite." },
    contact: { heading: "Kontakt", text: "Das Kontaktformular validiert serverseitig und ist der wichtigste Weg.", hint: "Oder drücke Strg + K und wähle Kontaktformular." },
  },
  architecture: {
    eyebrow: "So ist dieses Portfolio gebaut",
    title: "Vom Browser bis zur Datenbank in sieben Schritten",
    lede: "Jeder Block unten entspricht echten Dateien im Repository. Nichts davon ist eine Attrappe.",
    pathLabel: "Wo",
    branchLabel: "Zwei Zustellwege",
    nodes: [
      { id: "browser", label: "Browser", path: "/[locale]/…", desc: "Zuerst serverseitig gerendertes HTML. Kleine Client-Inseln nur dort, wo Interaktion sie braucht: Menü, Palette, Terminal und Formulare." },
      { id: "components", label: "Komponenten", path: "src/components", desc: "Gemeinsame Bausteine, die Seitenhülle und ein Ordner pro Seite. Standardmäßig Server Components." },
      { id: "server", label: "Next.js-Server", path: "src/app · src/proxy.ts", desc: "App Router mit einem [locale]-Segment. Der Proxy leitet URLs ohne Präfix auf /en, /de oder /th um. Die Texte liegen in typisierten Wörterbüchern in src/content." },
      { id: "handler", label: "Server Action & Route Handler", path: "src/app/actions · src/app/api/health", desc: "Das Kontaktformular sendet an eine Server Action. /api/health liefert einen sicheren Status ohne Geheimnisse." },
      { id: "validation", label: "Validierung & Schutz", path: "src/lib/contact", desc: "Ein Zod-Schema mit stabilen Fehlercodes, ein Honeypot-Feld und ein Rate Limit nach bestem Bemühen laufen auf dem Server, bevor etwas gespeichert wird." },
      {
        id: "delivery",
        label: "Zustellung",
        path: "contact_submissions · CONTACT_WEBHOOK_URL",
        desc: "Eine Anfrage wird in PostgreSQL gespeichert, wenn DATABASE_URL gesetzt ist, und an einen Webhook gesendet, wenn CONTACT_WEBHOOK_URL gesetzt ist. Ist keines von beiden konfiguriert, meldet das Formular das, statt Erfolg vorzutäuschen.",
        branches: ["PostgreSQL (Neon)", "Webhook"],
      },
      { id: "vercel", label: "Vercel", path: "next.config.ts", desc: "Ausgeliefert über Vercel. Sicherheits-Header wie nosniff, Frame-Sperre, HSTS sowie Referrer- und Permissions-Policy sind in next.config.ts gesetzt." },
    ],
  },
  facts: {
    title: "Aus dem Repository gemessen",
    lede: "Beim Build berechnet, aus denselben Konfigurationsdateien, die auch die Navigation steuern.",
    items: { pages: "Seiten", languages: "Sprachen", routes: "Lokalisierte Routen", content: "Inhaltsmodule", api: "API-Endpunkte" },
  },
  health: {
    eyebrow: "Live-Backend",
    title: "Health-Endpunkt",
    endpoint: "GET /api/health",
    loading: "Wird geprüft …",
    error: "Der Health-Endpunkt war nicht erreichbar.",
    retry: "Erneut prüfen",
    raw: "Rohes JSON ansehen",
    status: { ok: "In Betrieb", degraded: "Eingeschränkt" },
    fields: { status: "Status", environment: "Umgebung", region: "Region", commit: "Commit", database: "Datenbank", webhook: "Webhook", latency: "Antwortzeit", node: "Laufzeit" },
    values: { connected: "Verbunden", unreachable: "Nicht erreichbar", "not-configured": "Nicht konfiguriert", configured: "Konfiguriert", local: "lokal" },
  },
  overview: {
    eyebrow: "Systemübersicht",
    title: "Drei Sprachen, eine Codebasis",
    lede: "Jede öffentliche Seite gibt es auf Englisch, Deutsch und Thai. Die Texte liegen lokal, ohne Übersetzungsdienst zur Laufzeit.",
    caption: "Unterstützte Sprachen und ihre URL-Struktur",
    cols: { language: "Sprache", prefix: "URL-Präfix", html: "HTML-lang", pages: "Seiten", sample: "Beispielroute" },
  },
  cta: { label: "Gespräch beginnen" },
};

const th: CommandCenterContent = {
  meta: {
    title: "ศูนย์ควบคุมวิศวกรรม",
    description: "แผงควบคุมของพอร์ตโฟลิโอนี้ ทั้งเทอร์มินัลที่ปลอดภัย สถาปัตยกรรมจริง สถานะแบ็กเอนด์แบบสด และ Command Palette ด้วย Ctrl/Cmd + K",
  },
  hero: {
    eyebrow: "ศูนย์ควบคุม",
    complexity: "ระดับความซับซ้อน",
    title: { lead: "ทั้งระบบ", accent: "ในมุมมองเดียว" },
    lede: "ทุกสิ่งที่หน้าก่อนหน้าเล่าไว้ เปิดให้ตรวจสอบได้จริง ทั้งเทอร์มินัลแบบอ่านอย่างเดียว สถาปัตยกรรมของเว็บไซต์นี้ และสถานะแบ็กเอนด์แบบสด",
  },
  palette: {
    eyebrow: "Command Palette",
    title: "ใช้งานด้วยคีย์บอร์ด",
    body: "กด Ctrl + K (⌘ + K บน Mac) ได้ทุกหน้า เพื่อข้ามไปยังหน้าต่าง ๆ เปิดแบบฟอร์มติดต่อ หรือเปลี่ยนภาษา",
    button: "เปิด Command Palette",
    keys: "ปุ่มลัด",
  },
  terminal: {
    eyebrow: "เทอร์มินัลที่ปลอดภัย",
    title: "ถามพอร์ตโฟลิโอได้เลย",
    body: "คอนโซลแบบควบคุมและอ่านอย่างเดียว รู้จักเฉพาะคำสั่งที่แสดงใน help ไม่มีสิ่งใดถูกรันบนเซิร์ฟเวอร์หรือในเชลล์",
    label: "เทอร์มินัลพอร์ตโฟลิโอ",
    logLabel: "ผลลัพธ์ของเทอร์มินัล",
    badge: "อ่านอย่างเดียว",
    prompt: "visitor@portfolio:~$",
    placeholder: "พิมพ์คำสั่ง เช่น help",
    submit: "รัน",
    quick: "ลองคำสั่ง",
    intro: "ยินดีต้อนรับ นี่คือเทอร์มินัลที่ปลอดภัยและอ่านอย่างเดียว พิมพ์ help เพื่อดูว่าทำอะไรได้บ้าง",
    messages: {
      helpTitle: "คำสั่งที่ใช้ได้",
      helpHint: "กด Tab เพื่อเติมคำสั่งอัตโนมัติ และใช้ลูกศรขึ้นหรือลงเพื่อดูประวัติ",
      unknown: "ไม่พบคำสั่ง: {command} พิมพ์ help เพื่อดูรายการคำสั่ง",
      openArg: "หน้า",
      openUsage: "วิธีใช้: open <หน้า> หน้าที่มี: {pages} ใช้เลขหน้า เช่น 4 ได้เช่นกัน",
      openUnknown: "ไม่พบหน้า “{name}” หน้าที่มี: {pages}",
      opening: "กำลังเปิด {page}…",
      langUsage: "ภาษาปัจจุบัน: {current} วิธีใช้: lang <{codes}>",
      langUnknown: "ไม่รองรับภาษา “{name}” ภาษาที่มี: {codes}",
      langCurrent: "ใช้ภาษา{language}อยู่แล้ว",
      langSwitching: "กำลังเปลี่ยนเป็นภาษา{language}…",
      descriptions: {
        help: "แสดงคำสั่งทั้งหมด",
        about: "เจ้าของพอร์ตโฟลิโอนี้",
        skills: "ความสามารถแยกตามด้าน",
        projects: "สิ่งที่อยู่ในหน้าโปรเจกต์",
        stack: "เทคโนโลยีที่ใช้สร้างเว็บไซต์นี้",
        ai: "ขั้นตอนการทำงานแบบ AI-native",
        architecture: "เว็บไซต์นี้ถูกสร้างอย่างไร",
        contact: "ช่องทางติดต่อ",
        open: "ไปยังหน้าที่ต้องการ",
        lang: "เปลี่ยนภาษา",
        clear: "ล้างหน้าจอ",
      },
    },
    labels: { name: "ชื่อ", location: "ที่ตั้ง", availability: "สถานะการรับงาน", github: "GitHub", email: "อีเมล", form: "แบบฟอร์มติดต่อ", source: "ซอร์สโค้ด" },
    about: {
      heading: "เกี่ยวกับ",
      text: "นักพัฒนาเว็บ × การทำงานแบบ AI-native อินเทอร์เฟซทันสมัย แบ็กเอนด์ใช้งานจริง และขั้นตอนที่มี AI ช่วย ตั้งแต่ไอเดียไปจนถึงระบบจริง",
    },
    skills: { heading: "ทักษะ", groups: { frontend: "ฟรอนต์เอนด์", backend: "แบ็กเอนด์", ai: "AI-native", engineering: "วิศวกรรม" } },
    projects: {
      heading: "โปรเจกต์",
      text: "หน้าโปรเจกต์รวบรวมโปรเจกต์ต้นแบบและงานสาธิตทางเทคนิค ระบุไว้ชัดเจนว่าเป็นเช่นนั้น และไม่ใช่งานของลูกค้า",
      categories: "หมวดหมู่",
      categoryList: "SaaS · เว็บไซต์ธุรกิจ · แดชบอร์ด · ต้นแบบอีคอมเมิร์ซ · เวิร์กโฟลว์ AI · เครื่องมือภายในองค์กร · แลนดิ้งเพจ · เครื่องมือสำหรับนักพัฒนา",
      hint: "ไปดูได้ด้วย: open projects",
    },
    stack: { heading: "สแตก", rows: { framework: "เฟรมเวิร์ก", styling: "สไตล์", validation: "การตรวจสอบข้อมูล", data: "ข้อมูล", tooling: "เครื่องมือ", hosting: "โฮสติ้ง" } },
    ai: {
      heading: "ขั้นตอนแบบ AI-native",
      text: "AI ช่วยเร่งขั้นตอนการทำงาน ส่วนวิจารณญาณทางวิศวกรรมของมนุษย์เป็นผู้กำหนดผลลัพธ์",
      steps: ["ทำความเข้าใจ", "ค้นคว้า", "วางแผน", "ทำต้นแบบ", "สร้าง", "ตรวจทาน", "ทดสอบ", "ปรับโครงสร้าง", "ขึ้นระบบ"],
      hint: "รายละเอียด: open ai-native",
    },
    architecture: { heading: "สถาปัตยกรรม", hint: "แผนภาพเต็มอยู่ด้านล่างของหน้านี้" },
    contact: { heading: "ติดต่อ", text: "แบบฟอร์มติดต่อตรวจสอบข้อมูลฝั่งเซิร์ฟเวอร์ และเป็นช่องทางหลัก", hint: "หรือกด Ctrl + K แล้วเลือกแบบฟอร์มติดต่อ" },
  },
  architecture: {
    eyebrow: "พอร์ตโฟลิโอนี้ถูกสร้างอย่างไร",
    title: "จากเบราว์เซอร์ถึงฐานข้อมูล ใน 7 ขั้นตอน",
    lede: "ทุกกล่องด้านล่างตรงกับไฟล์จริงใน repository ไม่มีส่วนไหนเป็นภาพจำลอง",
    pathLabel: "ตำแหน่ง",
    branchLabel: "สองช่องทางส่งข้อมูล",
    nodes: [
      { id: "browser", label: "เบราว์เซอร์", path: "/[locale]/…", desc: "เริ่มจาก HTML ที่เรนเดอร์ฝั่งเซิร์ฟเวอร์ และใช้ส่วนฝั่งไคลเอนต์เล็ก ๆ เฉพาะจุดที่ต้องโต้ตอบ เช่น เมนู พาเลต เทอร์มินัล และแบบฟอร์ม" },
      { id: "components", label: "คอมโพเนนต์", path: "src/components", desc: "ส่วนประกอบพื้นฐานที่ใช้ร่วมกัน โครงหน้าเว็บ และหนึ่งโฟลเดอร์ต่อหนึ่งหน้า ใช้ Server Components เป็นค่าเริ่มต้น" },
      { id: "server", label: "เซิร์ฟเวอร์ Next.js", path: "src/app · src/proxy.ts", desc: "App Router พร้อมเซกเมนต์ [locale] โดย proxy จะเปลี่ยนเส้นทาง URL ที่ไม่มีคำนำหน้าไปยัง /en, /de หรือ /th ส่วนข้อความเก็บในพจนานุกรมแบบมีชนิดข้อมูลที่ src/content" },
      { id: "handler", label: "Server Action และ Route Handler", path: "src/app/actions · src/app/api/health", desc: "แบบฟอร์มติดต่อส่งข้อมูลไปยัง Server Action ส่วน /api/health รายงานสถานะที่ปลอดภัยและไม่เปิดเผยความลับ" },
      { id: "validation", label: "การตรวจสอบและป้องกัน", path: "src/lib/contact", desc: "สกีมา Zod ที่มีรหัสข้อผิดพลาดคงที่ ช่อง honeypot และการจำกัดอัตราแบบพยายามเต็มที่ ทำงานบนเซิร์ฟเวอร์ก่อนมีการบันทึกข้อมูลใด ๆ" },
      {
        id: "delivery",
        label: "การส่งข้อมูล",
        path: "contact_submissions · CONTACT_WEBHOOK_URL",
        desc: "ข้อความจะถูกบันทึกลง PostgreSQL เมื่อตั้งค่า DATABASE_URL และส่งไปยัง webhook เมื่อตั้งค่า CONTACT_WEBHOOK_URL หากไม่ได้ตั้งค่าทั้งสองอย่าง แบบฟอร์มจะแจ้งตามจริงแทนที่จะแสดงว่าสำเร็จ",
        branches: ["PostgreSQL (Neon)", "Webhook"],
      },
      { id: "vercel", label: "Vercel", path: "next.config.ts", desc: "ขึ้นระบบบน Vercel ส่วน security headers เช่น nosniff การปิดกั้นเฟรม HSTS รวมถึง referrer และ permissions policy กำหนดไว้ใน next.config.ts" },
    ],
  },
  facts: {
    title: "ตัวเลขจาก repository จริง",
    lede: "คำนวณตอนบิลด์เว็บไซต์ จากไฟล์ตั้งค่าชุดเดียวกับที่ใช้สร้างระบบนำทาง",
    items: { pages: "หน้า", languages: "ภาษา", routes: "เส้นทางตามภาษา", content: "โมดูลเนื้อหา", api: "API endpoint" },
  },
  health: {
    eyebrow: "แบ็กเอนด์แบบสด",
    title: "Health endpoint",
    endpoint: "GET /api/health",
    loading: "กำลังตรวจสอบ…",
    error: "เข้าถึง health endpoint ไม่ได้",
    retry: "ตรวจสอบอีกครั้ง",
    raw: "ดู JSON ดิบ",
    status: { ok: "ทำงานปกติ", degraded: "ทำงานบางส่วน" },
    fields: { status: "สถานะ", environment: "สภาพแวดล้อม", region: "ภูมิภาค", commit: "คอมมิต", database: "ฐานข้อมูล", webhook: "Webhook", latency: "เวลาตอบสนอง", node: "รันไทม์" },
    values: { connected: "เชื่อมต่อแล้ว", unreachable: "เข้าถึงไม่ได้", "not-configured": "ยังไม่ได้ตั้งค่า", configured: "ตั้งค่าแล้ว", local: "เครื่องท้องถิ่น" },
  },
  overview: {
    eyebrow: "ภาพรวมระบบ",
    title: "สามภาษา โค้ดเบสเดียว",
    lede: "ทุกหน้าสาธารณะมีทั้งภาษาอังกฤษ เยอรมัน และไทย ข้อความเก็บไว้ในโปรเจกต์ ไม่ใช้บริการแปลภาษาขณะรันไทม์",
    caption: "ภาษาที่รองรับและโครงสร้าง URL",
    cols: { language: "ภาษา", prefix: "คำนำหน้า URL", html: "HTML lang", pages: "หน้า", sample: "เส้นทางตัวอย่าง" },
  },
  cta: { label: "เริ่มคุยกัน" },
};

export const commandCenterContent: Localized<CommandCenterContent> = { en, de, th };
