import type { Localized } from "@/i18n/config";

const en = {
  meta: {
    title: "Web developer × AI-native builder",
    description:
      "Freelance web developer for new websites, redesigns, new features, full-stack web applications, AI integration and automation — designed, built and shipped to production.",
  },
  hero: {
    role: "Web developer × AI-native builder",
    titleA: "Build it new.",
    titleB: "Make it better.",
    titleAccent: "Ship it.",
    lede:
      "I design and develop websites and web applications, redesign the ones that have fallen behind and add features to products already in use — connected to APIs, backends and AI where it earns its place, and taken all the way to production.",
    secondary: "Explore AI systems",
    outcomesLabel: "What I take on",
    outcomes: [
      "New websites",
      "Website redesigns",
      "New features",
      "Web applications",
      "AI integration",
      "Automation",
      "APIs & backend",
      "Production deployment",
    ],
  },
  services: {
    eyebrow: "Work with me",
    title: "Four ways most projects start.",
    lede: "Whether you are starting from zero or improving something that already runs, the work covers design, code and delivery — not just one slice of it.",
    youGet: "What you get",
    lead: [
      {
        id: "new-website",
        title: "Build a new website",
        outcome: "A fast, responsive site that explains your offer clearly and is easy to keep up to date.",
        points: ["Structure and copy hierarchy", "Custom design, not a theme", "Responsive and accessible", "SEO basics and analytics-ready"],
        cta: "Start a project",
      },
      {
        id: "redesign",
        title: "Redesign an existing website",
        outcome: "Your current site, rebuilt to look current, load quickly and work properly on phones.",
        points: ["Audit of what works and what doesn't", "Visual and technical modernisation", "Content carried over", "Redirects so nothing breaks"],
        cta: "Discuss a redesign",
      },
      {
        id: "features",
        title: "Add features to an existing application",
        outcome: "New pages, workflows, dashboards or integrations — added cleanly to the system you already have.",
        points: ["Reading the existing codebase first", "Changes that follow its conventions", "Tests around new behaviour", "Reviewed, documented hand-over"],
        cta: "Add a feature",
      },
      {
        id: "webapp",
        title: "Build a web application",
        outcome: "Frontend, backend, database and APIs as one working product, deployed and ready for real users.",
        points: ["Product scope and data model", "Typed frontend and backend", "Auth, validation and error states", "CI and production deployment"],
        cta: "Start a project",
      },
    ],
    more: {
      title: "Also available",
      engineering: {
        title: "Engineering",
        items: [
          { title: "Frontend development", note: "React, Next.js, TypeScript and accessible, responsive UI." },
          { title: "Backend development", note: "Route handlers, server actions, validation and data." },
          { title: "API integration", note: "Payments, CRMs, email, webhooks and third-party APIs." },
          { title: "Performance & responsive fixes", note: "Slow pages, broken mobile layouts, layout shifts." },
          { title: "Deployment", note: "GitHub, Vercel and a release process you can repeat." },
        ],
      },
      ai: {
        title: "AI & automation",
        items: [
          { title: "AI integration", note: "ChatGPT, Claude or other models inside your site or tool." },
          { title: "AI workflow automation", note: "Repetitive steps handled by AI, checked by people." },
          { title: "Autonomous agent workflows", note: "Planned, tool-using agents with checkpoints and approval." },
          { title: "Local AI concepts", note: "Private, self-hosted model setups for sensitive data." },
          { title: "Python automation", note: "Scripts, data processing and glue between systems." },
        ],
        cta: "Build with AI",
      },
    },
  },
  ai: {
    eyebrow: "AI systems",
    title: "Not a chatbot bolted on. A system with checks.",
    body:
      "ChatGPT, Claude and local models each have a place. The work is orchestrating them with Python, APIs and real data — and keeping tests and human approval between the model and production.",
    generated: "This board is generated by a Python script in the repository: {nodes} components, {edges} traces.",
    imageAlt:
      "Circuit diagram: human intent flows into an orchestrator, out to ChatGPT, Claude and local AI, through a tool router to Python, web APIs, data and GitHub, then through validation and human approval to deployment and production.",
  },
  process: {
    eyebrow: "How a project runs",
    title: "Clear steps, visible progress.",
    steps: [
      { title: "Scope", body: "We agree on goals, pages or features, and what done means — in writing." },
      { title: "Build", body: "Work happens in small, reviewable steps you can see and comment on." },
      { title: "Ship", body: "Tested, deployed to production and handed over with documentation." },
      { title: "Iterate", body: "Real usage shows what to improve next. Further changes are easy to add." },
    ],
  },
  work: {
    eyebrow: "Proof of work",
    title: "See how the work is done.",
    body: "Concept projects, case studies and working tools — clearly labelled for what they are.",
  },
  closing: {
    title: "Tell me what you're building.",
    body: "A new site, a redesign, a feature for an existing product or an AI workflow. Describe it in a few lines and you'll get a clear reply about scope, approach and timing.",
  },
};

export type HomeContent = typeof en;

const de: HomeContent = {
  meta: {
    title: "Webentwicklung × KI-natives Bauen",
    description:
      "Freelance-Webentwicklung für neue Websites, Redesigns, neue Features, Full-Stack-Webanwendungen, KI-Integration und Automatisierung – konzipiert, gebaut und live gebracht.",
  },
  hero: {
    role: "Webentwicklung × KI-natives Bauen",
    titleA: "Neu bauen.",
    titleB: "Besser machen.",
    titleAccent: "Live bringen.",
    lede:
      "Ich entwerfe und entwickle Websites und Webanwendungen, bringe veraltete Auftritte auf den aktuellen Stand und ergänze Produkte, die bereits laufen, um neue Features – angebunden an APIs, Backends und KI, wo es sinnvoll ist, und bis in die Produktion begleitet.",
    secondary: "KI-Systeme entdecken",
    outcomesLabel: "Was ich übernehme",
    outcomes: [
      "Neue Websites",
      "Website-Redesigns",
      "Neue Features",
      "Webanwendungen",
      "KI-Integration",
      "Automatisierung",
      "APIs & Backend",
      "Deployment",
    ],
  },
  services: {
    eyebrow: "Zusammenarbeit",
    title: "Vier typische Einstiege.",
    lede: "Ob du bei null anfängst oder etwas verbessern willst, das schon läuft: Die Arbeit umfasst Design, Code und Auslieferung – nicht nur einen Ausschnitt davon.",
    youGet: "Was du bekommst",
    lead: [
      {
        id: "new-website",
        title: "Neue Website bauen",
        outcome: "Eine schnelle, responsive Website, die dein Angebot klar erklärt und sich leicht pflegen lässt.",
        points: ["Struktur und Text-Hierarchie", "Eigenes Design statt Theme", "Responsive und barrierearm", "SEO-Grundlagen, bereit für Analytics"],
        cta: "Projekt starten",
      },
      {
        id: "redesign",
        title: "Bestehende Website neu gestalten",
        outcome: "Deine aktuelle Website, neu aufgebaut: zeitgemäß, schnell und auf dem Smartphone wirklich gut nutzbar.",
        points: ["Analyse, was funktioniert und was nicht", "Visuelle und technische Modernisierung", "Inhalte werden übernommen", "Weiterleitungen, damit kein Link ins Leere führt"],
        cta: "Redesign besprechen",
      },
      {
        id: "features",
        title: "Features für bestehende Anwendungen",
        outcome: "Neue Seiten, Workflows, Dashboards oder Integrationen – sauber in dein bestehendes System eingefügt.",
        points: ["Erst den bestehenden Code verstehen", "Änderungen im vorhandenen Stil", "Tests für neues Verhalten", "Review und dokumentierte Übergabe"],
        cta: "Feature ergänzen",
      },
      {
        id: "webapp",
        title: "Webanwendung entwickeln",
        outcome: "Frontend, Backend, Datenbank und APIs als ein funktionierendes Produkt – deployed und bereit für echte Nutzung.",
        points: ["Produktumfang und Datenmodell", "Typisiertes Frontend und Backend", "Auth, Validierung und Fehlerzustände", "CI und Produktions-Deployment"],
        cta: "Projekt starten",
      },
    ],
    more: {
      title: "Außerdem",
      engineering: {
        title: "Engineering",
        items: [
          { title: "Frontend-Entwicklung", note: "React, Next.js, TypeScript und barrierearme, responsive UI." },
          { title: "Backend-Entwicklung", note: "Route Handlers, Server Actions, Validierung und Daten." },
          { title: "API-Integration", note: "Zahlungen, CRM, E-Mail, Webhooks und externe APIs." },
          { title: "Performance & Responsive", note: "Langsame Seiten, kaputte Mobil-Layouts, springende Inhalte." },
          { title: "Deployment", note: "GitHub, Vercel und ein Release-Prozess, der sich wiederholen lässt." },
        ],
      },
      ai: {
        title: "KI & Automatisierung",
        items: [
          { title: "KI-Integration", note: "ChatGPT, Claude oder andere Modelle in deiner Website oder deinem Tool." },
          { title: "KI-Workflow-Automatisierung", note: "Wiederkehrende Schritte übernimmt die KI, Menschen prüfen." },
          { title: "Autonome Agent-Workflows", note: "Geplante Agents mit Tools, Checkpoints und Freigabe." },
          { title: "Lokale KI-Konzepte", note: "Private, selbst gehostete Modelle für sensible Daten." },
          { title: "Python-Automatisierung", note: "Skripte, Datenverarbeitung und Verbindungen zwischen Systemen." },
        ],
        cta: "Mit KI bauen",
      },
    },
  },
  ai: {
    eyebrow: "KI-Systeme",
    title: "Kein angeschraubter Chatbot. Ein System mit Kontrollen.",
    body:
      "ChatGPT, Claude und lokale Modelle haben jeweils ihren Platz. Die eigentliche Arbeit ist, sie mit Python, APIs und echten Daten zu orchestrieren – mit Tests und menschlicher Freigabe zwischen Modell und Produktion.",
    generated: "Diese Platine wird von einem Python-Skript im Repository erzeugt: {nodes} Bauteile, {edges} Leiterbahnen.",
    imageAlt:
      "Schaltplan: Menschliche Absicht fließt in einen Orchestrator, weiter zu ChatGPT, Claude und lokaler KI, über einen Tool-Router zu Python, Web-APIs, Daten und GitHub, dann über Validierung und menschliche Freigabe zu Deployment und Produktion.",
  },
  process: {
    eyebrow: "So läuft ein Projekt",
    title: "Klare Schritte, sichtbarer Fortschritt.",
    steps: [
      { title: "Umfang", body: "Wir klären Ziele, Seiten oder Features und was „fertig“ heißt – schriftlich." },
      { title: "Bauen", body: "Gearbeitet wird in kleinen, prüfbaren Schritten, die du sehen und kommentieren kannst." },
      { title: "Ausliefern", body: "Getestet, in Produktion gebracht und mit Dokumentation übergeben." },
      { title: "Weiterentwickeln", body: "Echte Nutzung zeigt, was als Nächstes kommt. Weitere Änderungen lassen sich leicht ergänzen." },
    ],
  },
  work: {
    eyebrow: "Arbeitsproben",
    title: "Sieh dir an, wie ich arbeite.",
    body: "Konzeptprojekte, Fallstudien und funktionierende Tools – klar gekennzeichnet als das, was sie sind.",
  },
  closing: {
    title: "Erzähl mir, was du baust.",
    body: "Eine neue Website, ein Redesign, ein Feature für ein bestehendes Produkt oder ein KI-Workflow. Beschreib es in ein paar Zeilen und du bekommst eine klare Antwort zu Umfang, Vorgehen und Zeitplan.",
  },
};

const th: HomeContent = {
  meta: {
    title: "นักพัฒนาเว็บ × AI-native builder",
    description:
      "รับงานฟรีแลนซ์ทำเว็บไซต์ใหม่ Redesign เพิ่มฟีเจอร์ เว็บแอปแบบ Full-stack, AI Integration และระบบอัตโนมัติ ตั้งแต่ออกแบบ พัฒนา จนขึ้นใช้งานจริง",
  },
  hero: {
    role: "นักพัฒนาเว็บ × AI-native builder",
    titleA: "สร้างใหม่",
    titleB: "ทำให้ดีขึ้น",
    titleAccent: "ส่งขึ้นใช้งานจริง",
    lede:
      "ออกแบบและพัฒนาเว็บไซต์และเว็บแอป ปรับโฉมเว็บที่ล้าสมัย และเพิ่มฟีเจอร์ให้ระบบที่ใช้งานอยู่แล้ว เชื่อมต่อ API, Backend และ AI เมื่อช่วยได้จริง แล้วพางานไปจนถึง Production",
    secondary: "สำรวจระบบ AI",
    outcomesLabel: "งานที่รับ",
    outcomes: [
      "เว็บไซต์ใหม่",
      "Redesign เว็บไซต์",
      "เพิ่มฟีเจอร์",
      "เว็บแอปพลิเคชัน",
      "AI Integration",
      "ระบบอัตโนมัติ",
      "API และ Backend",
      "Deploy ขึ้น Production",
    ],
  },
  services: {
    eyebrow: "ทำงานร่วมกัน",
    title: "สี่จุดเริ่มต้นที่พบบ่อย",
    lede: "จะเริ่มจากศูนย์หรือปรับปรุงสิ่งที่ใช้งานอยู่แล้วก็ได้ งานครอบคลุมทั้งดีไซน์ โค้ด และการส่งมอบ ไม่ใช่แค่ส่วนใดส่วนหนึ่ง",
    youGet: "สิ่งที่ได้รับ",
    lead: [
      {
        id: "new-website",
        title: "สร้างเว็บไซต์ใหม่",
        outcome: "เว็บไซต์ที่เร็ว รองรับทุกหน้าจอ อธิบายสินค้าและบริการได้ชัด และอัปเดตเองได้ง่าย",
        points: ["วางโครงสร้างและลำดับเนื้อหา", "ดีไซน์เฉพาะ ไม่ใช่ธีมสำเร็จรูป", "Responsive และเข้าถึงได้", "พื้นฐาน SEO พร้อมต่อ Analytics"],
        cta: "เริ่มโปรเจกต์",
      },
      {
        id: "redesign",
        title: "Redesign เว็บไซต์เดิม",
        outcome: "สร้างเว็บเดิมขึ้นใหม่ให้ดูทันสมัย โหลดเร็ว และใช้งานบนมือถือได้ดีจริง",
        points: ["ตรวจว่าอะไรใช้ได้ อะไรต้องแก้", "ปรับทั้งภาพลักษณ์และเทคนิค", "ย้ายเนื้อหาเดิมมาให้ครบ", "ตั้ง Redirect ไม่ให้ลิงก์เสีย"],
        cta: "คุยเรื่อง Redesign",
      },
      {
        id: "features",
        title: "เพิ่มฟีเจอร์ให้ระบบที่มีอยู่",
        outcome: "หน้าใหม่ Workflow Dashboard หรือการเชื่อมต่อระบบ ใส่เข้าไปในระบบเดิมอย่างเรียบร้อย",
        points: ["อ่านโค้ดเดิมให้เข้าใจก่อน", "เขียนตามแนวทางของโปรเจกต์เดิม", "มีเทสต์ครอบฟีเจอร์ใหม่", "รีวิวและส่งมอบพร้อมเอกสาร"],
        cta: "เพิ่มฟีเจอร์",
      },
      {
        id: "webapp",
        title: "สร้างเว็บแอปพลิเคชัน",
        outcome: "Frontend, Backend, ฐานข้อมูล และ API รวมเป็นผลิตภัณฑ์เดียวที่ใช้งานได้จริง Deploy พร้อมให้ผู้ใช้จริง",
        points: ["ขอบเขตผลิตภัณฑ์และ Data model", "Frontend และ Backend แบบ Typed", "Auth, Validation และสถานะ Error", "CI และ Deploy ขึ้น Production"],
        cta: "เริ่มโปรเจกต์",
      },
    ],
    more: {
      title: "บริการอื่น ๆ",
      engineering: {
        title: "Engineering",
        items: [
          { title: "Frontend Development", note: "React, Next.js, TypeScript และ UI ที่ Responsive และเข้าถึงได้" },
          { title: "Backend Development", note: "Route Handler, Server Action, Validation และข้อมูล" },
          { title: "API Integration", note: "ระบบชำระเงิน CRM อีเมล Webhook และ API ภายนอก" },
          { title: "Performance และ Responsive", note: "หน้าเว็บช้า Layout บนมือถือพัง และหน้าเว็บขยับไปมาระหว่างโหลด" },
          { title: "Deployment", note: "GitHub, Vercel และขั้นตอน Release ที่ทำซ้ำได้" },
        ],
      },
      ai: {
        title: "AI และระบบอัตโนมัติ",
        items: [
          { title: "AI Integration", note: "ใส่ ChatGPT, Claude หรือโมเดลอื่นเข้าไปในเว็บหรือเครื่องมือที่ใช้อยู่" },
          { title: "AI Workflow Automation", note: "ให้ AI ทำงานซ้ำ ๆ แทน โดยมีคนตรวจสอบ" },
          { title: "Autonomous Agent Workflow", note: "Agent ที่วางแผนและใช้เครื่องมือ มี Checkpoint และการอนุมัติ" },
          { title: "แนวคิด Local AI", note: "ระบบโมเดลแบบ Self-hosted สำหรับข้อมูลที่ต้องเก็บเป็นความลับ" },
          { title: "Python Automation", note: "สคริปต์ ประมวลผลข้อมูล และเชื่อมระบบเข้าด้วยกัน" },
        ],
        cta: "สร้างด้วย AI",
      },
    },
  },
  ai: {
    eyebrow: "ระบบ AI",
    title: "ไม่ใช่แค่ติด Chatbot แต่เป็นระบบที่มีการตรวจสอบ",
    body:
      "ChatGPT, Claude และ Local AI ต่างมีจุดที่เหมาะของตัวเอง งานจริงคือการ Orchestrate ทั้งหมดเข้ากับ Python, API และข้อมูลจริง โดยมีเทสต์และการอนุมัติจากคนคั่นระหว่างโมเดลกับ Production",
    generated: "แผงวงจรนี้สร้างจากสคริปต์ Python ใน Repository: {nodes} ชิ้นส่วน {edges} เส้นทาง",
    imageAlt:
      "แผนผังวงจร: ความต้องการของคนเข้าสู่ Orchestrator ส่งต่อไปยัง ChatGPT, Claude และ Local AI ผ่าน Tool router ไปยัง Python, Web API, ข้อมูล และ GitHub จากนั้นผ่าน Validation และการอนุมัติของคน ไปสู่ Deployment และ Production",
  },
  process: {
    eyebrow: "ขั้นตอนการทำงาน",
    title: "ขั้นตอนชัด เห็นความคืบหน้า",
    steps: [
      { title: "กำหนดขอบเขต", body: "ตกลงเป้าหมาย หน้า หรือฟีเจอร์ และแบบไหนถึงเรียกว่าเสร็จ เป็นลายลักษณ์อักษร" },
      { title: "พัฒนา", body: "ทำงานเป็นช่วงสั้น ๆ ที่ตรวจดูและให้ความเห็นได้ตลอด" },
      { title: "ส่งมอบ", body: "ผ่านการทดสอบ Deploy ขึ้น Production แล้วส่งมอบพร้อมเอกสาร" },
      { title: "ต่อยอด", body: "การใช้งานจริงบอกว่าควรปรับอะไรต่อ และต่อยอดภายหลังได้ง่าย" },
    ],
  },
  work: {
    eyebrow: "ตัวอย่างงาน",
    title: "ดูวิธีทำงานจริง",
    body: "โปรเจกต์แนวคิด กรณีศึกษา และเครื่องมือที่ใช้งานได้จริง ระบุประเภทไว้ชัดเจนทุกชิ้น",
  },
  closing: {
    title: "เล่าให้ฟังว่ากำลังสร้างอะไร",
    body: "เว็บไซต์ใหม่ Redesign ฟีเจอร์สำหรับระบบเดิม หรือ AI Workflow เล่ามาสั้น ๆ แล้วจะได้คำตอบที่ชัดเจนเรื่องขอบเขต แนวทาง และระยะเวลา",
  },
};

export const homeContent: Localized<HomeContent> = { en, de, th };
