import type { Localized } from "@/i18n/config";

const en = {
  meta: {
    title: "AI-assisted Digital Builder & IT Quereinsteiger",
    description:
      "Portfolio of Chaiyaphol — an IT Quereinsteiger in Germany building web, app and automation prototypes with AI assistance. Real projects with honest labels, practical skills and clear positioning.",
  },
  hero: {
    role: "AI-assisted Digital Builder · IT Quereinsteiger",
    titleA: "Ideas in.",
    titleB: "Prototypes out.",
    titleAccent: "Built with AI.",
    lede:
      "I turn ideas into working web, app and automation prototypes with the help of modern AI tools. My strengths are requirement definition, iterative problem solving, practical Git workflows and learning new technologies quickly.",
    secondary: "See how I use AI",
    outcomesLabel: "What I bring",
    outcomes: [
      "Requirement definition",
      "Web & app prototyping",
      "AI-assisted development",
      "API integration",
      "Automation",
      "Testing & debugging",
      "Practical Git workflows",
      "Deployment",
    ],
  },
  services: {
    eyebrow: "What I contribute",
    title: "Strengths that matter in a team.",
    lede: "I don't claim to be a senior engineer. What I bring is proven: ideas become working prototypes, clearly scoped, built with AI assistance, tested and iterated until they hold up.",
    youGet: "What that means in practice",
    lead: [
      {
        id: "prototypes",
        title: "Web & app prototypes",
        outcome: "From a first sketch to a working, deployed prototype — with clean structure, real validation and an honest scope.",
        points: ["Next.js, React and TypeScript", "Responsive, accessible interfaces", "APIs and server logic", "Deployed and documented"],
        cta: "See projects",
        href: "projects",
      },
      {
        id: "ai-assisted",
        title: "AI-assisted development",
        outcome: "I use Claude, ChatGPT and Claude Code every day — to draft, review, debug and test — while I define the requirements and make the decisions.",
        points: ["Requirement breakdown and prompting", "Reviewing and understanding AI-generated code", "Iterative debugging with AI", "Human review before anything ships"],
        cta: "How I use AI",
        href: "ai-native",
      },
      {
        id: "automation",
        title: "Automation & integration",
        outcome: "Small, reliable automations that connect APIs, forms and data — with clear checkpoints where a person stays in control.",
        points: ["Python scripts and pipelines", "API and webhook integration", "n8n workflow concepts", "Validation and error handling"],
        cta: "See experiments",
        href: "projects",
      },
      {
        id: "quality",
        title: "Testing & iteration",
        outcome: "Every prototype is tested, checked on real devices and improved in short loops — because working means verified, not just deployed.",
        points: ["Unit and integration tests", "Type checking and linting", "Responsive QA across devices", "Fast, documented iterations"],
        cta: "See case studies",
        href: "case-studies",
      },
    ],
    more: {
      title: "Toolbox",
      engineering: {
        title: "Practical",
        items: [
          { title: "Frontend development", note: "React, Next.js, TypeScript and accessible, responsive UI." },
          { title: "Backend development", note: "Route handlers, server actions, validation and data." },
          { title: "API integration", note: "REST APIs, webhooks and third-party services." },
          { title: "Deployment", note: "GitHub, Vercel and a repeatable release process." },
          { title: "Testing", note: "Vitest, Playwright and real-device QA checks." },
        ],
      },
      ai: {
        title: "Exploring",
        items: [
          { title: "AI-assisted workflows", note: "Claude Code, ChatGPT and structured prompting." },
          { title: "Agentic workflows", note: "Multi-agent concepts with human approval gates." },
          { title: "RAG experiments", note: "Retrieval before generation, with cited answers." },
          { title: "Automation platforms", note: "n8n concepts for visible, deterministic workflows." },
          { title: "Local AI concepts", note: "Private, self-hosted model setups." },
        ],
        cta: "Contact me",
      },
    },
  },
  ai: {
    eyebrow: "How I use AI",
    title: "AI makes me faster. I stay in control.",
    body:
      "ChatGPT, Claude and Claude Code are part of my everyday workflow: they draft, explain and test. I define the requirements, review the code, run the checks and decide what ships — every step is verified by me, not by the model.",
    generated: "This board is generated by a Python script in the repository: {nodes} components, {edges} traces.",
    imageAlt:
      "Circuit diagram: human intent flows into an orchestrator, out to ChatGPT, Claude and local AI, through a tool router to Python, web APIs, data and GitHub, then through validation and human approval to deployment and production.",
  },
  process: {
    eyebrow: "How I work",
    title: "Four steps from idea to working prototype.",
    steps: [
      { title: "Requirements", body: "Goals, constraints and a definition of done — written down before any code exists." },
      { title: "Build", body: "Small, reviewable steps with AI assistance. Every change is read and understood." },
      { title: "Verify", body: "Tests, type checks, linting and QA on real screen sizes before anything ships." },
      { title: "Iterate", body: "Real usage and feedback show what to improve next. Loops stay short." },
    ],
  },
  work: {
    eyebrow: "Proof of work",
    title: "Real projects, clearly labelled.",
    body: "Live projects, prototypes and experiments — each one honestly labelled, so you can tell what shipped and what was built to learn.",
  },
  featured: {
    eyebrow: "Selected work",
    title: "Strongest projects, first.",
  },
  closing: {
    title: "Let's talk about your team.",
    body: "I'm looking for a junior IT role or Quereinsteiger position in web development, automation or AI-assisted digital work. Describe the role and I'll reply with how my experience fits.",
  },
};

export type HomeContent = typeof en;

const de: HomeContent = {
  meta: {
    title: "AI-gestützter Digital Builder & IT-Quereinsteiger",
    description:
      "Portfolio von Chaiyaphol – ein IT-Quereinsteiger in Deutschland, der mit KI-Unterstützung Web-, App- und Automatisierungs-Prototypen baut. Echte Projekte mit ehrlichen Labels, praktische Fähigkeiten und klarer Positionierung.",
  },
  hero: {
    role: "AI-gestützter Digital Builder · IT-Quereinsteiger",
    titleA: "Ideen rein.",
    titleB: "Prototypen raus.",
    titleAccent: "Mit KI gebaut.",
    lede:
      "Ich verwandle Ideen in funktionierende Web-, App- und Automatisierungs-Prototypen – mit Unterstützung moderner KI-Werkzeuge. Meine Stärken: Anforderungen definieren, Probleme iterativ lösen, praktische Git-Workflows und neue Technologien schnell lernen.",
    secondary: "So nutze ich KI",
    outcomesLabel: "Das bringe ich mit",
    outcomes: [
      "Anforderungen definieren",
      "Web- & App-Prototyping",
      "KI-gestützte Entwicklung",
      "API-Integration",
      "Automatisierung",
      "Testen & Debugging",
      "Praktische Git-Workflows",
      "Deployment",
    ],
  },
  services: {
    eyebrow: "Was ich einbringe",
    title: "Stärken, die in einem Team zählen.",
    lede: "Ich behaupte nicht, Senior Engineer zu sein. Was ich mitbringe, ist belegt: Aus Ideen werden funktionierende Prototypen – klar umrissen, mit KI-Unterstützung gebaut, getestet und iteriert, bis sie standhalten.",
    youGet: "Was das in der Praxis bedeutet",
    lead: [
      {
        id: "prototypes",
        title: "Web- & App-Prototypen",
        outcome: "Von der ersten Skizze bis zum funktionierenden, deployten Prototyp – mit sauberer Struktur, echter Prüfung und ehrlichem Umfang.",
        points: ["Next.js, React und TypeScript", "Responsive, barrierefreie Oberflächen", "APIs und Serverlogik", "Deployt und dokumentiert"],
        cta: "Projekte ansehen",
        href: "projects",
      },
      {
        id: "ai-assisted",
        title: "KI-gestützte Entwicklung",
        outcome: "Ich arbeite täglich mit Claude, ChatGPT und Claude Code – zum Entwerfen, Prüfen, Debuggen und Testen – während ich die Anforderungen definiere und die Entscheidungen treffe.",
        points: ["Anforderungen zerlegen und prompten", "KI-generierten Code lesen und verstehen", "Iteratives Debugging mit KI", "Menschlicher Review, bevor etwas live geht"],
        cta: "So nutze ich KI",
        href: "ai-native",
      },
      {
        id: "automation",
        title: "Automatisierung & Integration",
        outcome: "Kleine, zuverlässige Automatisierungen, die APIs, Formulare und Daten verbinden – mit klaren Kontrollpunkten, an denen ein Mensch das Steuer behält.",
        points: ["Python-Skripte und Pipelines", "API- und Webhook-Integration", "n8n-Workflow-Konzepte", "Validierung und Fehlerbehandlung"],
        cta: "Experimente ansehen",
        href: "projects",
      },
      {
        id: "quality",
        title: "Testen & Iterieren",
        outcome: "Jeder Prototyp wird getestet, auf echten Geräten geprüft und in kurzen Schleifen verbessert – denn funktionierend heißt verifiziert, nicht nur deployt.",
        points: ["Unit- und Integrationstests", "Typprüfung und Linting", "Responsive QA auf verschiedenen Geräten", "Schnelle, dokumentierte Iterationen"],
        cta: "Fallstudien ansehen",
        href: "case-studies",
      },
    ],
    more: {
      title: "Werkzeugkasten",
      engineering: {
        title: "Praktisch",
        items: [
          { title: "Frontend-Entwicklung", note: "React, Next.js, TypeScript und barrierefreie, responsive UI." },
          { title: "Backend-Entwicklung", note: "Route Handlers, Server Actions, Validierung und Daten." },
          { title: "API-Integration", note: "REST-APIs, Webhooks und Drittanbieter-Dienste." },
          { title: "Deployment", note: "GitHub, Vercel und ein wiederholbarer Release-Prozess." },
          { title: "Testen", note: "Vitest, Playwright und QA-Prüfungen auf echten Geräten." },
        ],
      },
      ai: {
        title: "Am Erkunden",
        items: [
          { title: "KI-gestützte Workflows", note: "Claude Code, ChatGPT und strukturiertes Prompting." },
          { title: "Agentische Workflows", note: "Multi-Agent-Konzepte mit Freigabestufen für Menschen." },
          { title: "RAG-Experimente", note: "Erst abrufen, dann generieren – mit Quellenangaben." },
          { title: "Automatisierungsplattformen", note: "n8n-Konzepte für sichtbare, deterministische Workflows." },
          { title: "Lokale KI-Konzepte", note: "Private, selbst gehostete Modell-Setups." },
        ],
        cta: "Kontakt aufnehmen",
      },
    },
  },
  ai: {
    eyebrow: "So nutze ich KI",
    title: "KI macht mich schneller. Ich behalte die Kontrolle.",
    body:
      "ChatGPT, Claude und Claude Code gehören zu meinem Arbeitsalltag: Sie entwerfen, erklären und testen. Ich definiere die Anforderungen, lese den Code, führe die Prüfungen aus und entscheide, was live geht – jeder Schritt wird von mir verifiziert, nicht vom Modell.",
    generated: "Dieses Board wird von einem Python-Skript im Repository erzeugt: {nodes} Komponenten, {edges} Verbindungen.",
    imageAlt:
      "Schaltplan: Menschliche Absicht fließt in einen Orchestrator, weiter zu ChatGPT, Claude und lokaler KI, über einen Tool-Router zu Python, Web-APIs, Daten und GitHub, dann über Validierung und menschliche Freigabe zu Deployment und Produktion.",
  },
  process: {
    eyebrow: "So arbeite ich",
    title: "Vier Schritte von der Idee zum funktionierenden Prototyp.",
    steps: [
      { title: "Anforderungen", body: "Ziele, Rahmenbedingungen und eine Definition of Done – schriftlich festgehalten, bevor Code entsteht." },
      { title: "Bauen", body: "Kleine, prüfbare Schritte mit KI-Unterstützung. Jede Änderung wird gelesen und verstanden." },
      { title: "Prüfen", body: "Tests, Typprüfungen, Linting und QA auf echten Bildschirmgrößen, bevor etwas live geht." },
      { title: "Iterieren", body: "Echte Nutzung und Feedback zeigen, was als Nächstes besser wird. Die Schleifen bleiben kurz." },
    ],
  },
  work: {
    eyebrow: "Arbeitsnachweise",
    title: "Echte Projekte, klar gekennzeichnet.",
    body: "Live-Projekte, Prototypen und Experimente – jedes ehrlich etikettiert, damit sichtbar ist, was ausgeliefert wurde und was zum Lernen entstand.",
  },
  featured: {
    eyebrow: "Ausgewählte Arbeiten",
    title: "Die stärksten Projekte zuerst.",
  },
  closing: {
    title: "Sprechen wir über Ihr Team.",
    body: "Ich suche eine Junior-IT-Stelle oder eine Quereinsteiger-Position in Webentwicklung, Automatisierung oder KI-gestützter digitaler Arbeit. Beschreiben Sie die Stelle, und ich antworte, wie meine Erfahrung dazu passt.",
  },
};

const th: HomeContent = {
  meta: {
    title: "Digital Builder ที่ใช้ AI · IT Quereinsteiger",
    description:
      "พอร์ตโฟลิโอของชัยพล — IT Quereinsteiger ในเยอรมนี สร้างต้นแบบเว็บ แอป และระบบอัตโนมัติโดยมี AI ช่วย โปรเจกต์จริงติดป้ายตรงไปตรงมา ทักษะที่ใช้ได้จริง และจุดยืนที่ชัดเจน",
  },
  hero: {
    role: "นักสร้างดิจิทัลที่ใช้ AI ช่วย · IT Quereinsteiger",
    titleA: "ป้อนไอเดีย",
    titleB: "ได้ต้นแบบ",
    titleAccent: "สร้างด้วย AI",
    lede:
      "เปลี่ยนไอเดียให้เป็นต้นแบบเว็บ แอป และระบบอัตโนมัติที่ใช้งานได้จริง ด้วยความช่วยเหลือของเครื่องมือ AI สมัยใหม่ จุดแข็งคือการกำหนดความต้องการ แก้ปัญหาทีละขั้น ใช้ Git อย่างใช้งานได้จริง และเรียนรู้เทคโนโลยีใหม่ได้เร็ว",
    secondary: "ดูวิธีใช้ AI",
    outcomesLabel: "สิ่งที่นำมาให้",
    outcomes: [
      "กำหนดความต้องการ",
      "สร้างต้นแบบเว็บและแอป",
      "พัฒนาโดยมี AI ช่วย",
      "เชื่อมต่อ API",
      "ระบบอัตโนมัติ",
      "เทสต์และแก้บั๊ก",
      "Git Workflow ที่ใช้ได้จริง",
      "Deployment",
    ],
  },
  services: {
    eyebrow: "สิ่งที่ร่วมทีมได้",
    title: "จุดแข็งที่มีค่าต่อทีม",
    lede: "ไม่ได้อ้างว่าเป็น Senior Engineer สิ่งที่นำมาให้คือสิ่งที่พิสูจน์แล้ว: ไอเดียกลายเป็นต้นแบบที่ใช้งานได้ มีขอบเขตชัดเจน สร้างโดยมี AI ช่วย ผ่านการทดสอบและทำซ้ำจนใช้งานได้จริง",
    youGet: "ในทางปฏิบัติหมายความว่า",
    lead: [
      {
        id: "prototypes",
        title: "สร้างต้นแบบเว็บและแอป",
        outcome: "จากสเก็ตช์แรกจนถึงต้นแบบที่ใช้งานและ Deploy ได้จริง มีโครงสร้างที่สะอาด ผ่านการตรวจสอบจริง และขอบเขตที่ตรงไปตรงมา",
        points: ["Next.js, React และ TypeScript", "อินเทอร์เฟซที่รองรับทุกหน้าจอและเข้าถึงได้", "API และตรรกะฝั่งเซิร์ฟเวอร์", "Deploy แล้วพร้อมเอกสาร"],
        cta: "ดูโปรเจกต์",
        href: "projects",
      },
      {
        id: "ai-assisted",
        title: "พัฒนาโดยมี AI ช่วย",
        outcome: "ใช้ Claude, ChatGPT และ Claude Code ทุกวัน ทั้งร่างโค้ด รีวิว แก้บั๊ก และเทสต์ ส่วนการกำหนดความต้องการและการตัดสินใจเป็นหน้าที่ของคนเสมอ",
        points: ["แยกความต้องการและเขียน Prompt", "อ่านและเข้าใจโค้ดที่ AI สร้าง", "แก้บั๊กวนซ้ำไปพร้อมกับ AI", "คนตรวจก่อนขึ้นระบบจริงเสมอ"],
        cta: "วิธีใช้ AI",
        href: "ai-native",
      },
      {
        id: "automation",
        title: "ระบบอัตโนมัติและการเชื่อมต่อ",
        outcome: "ระบบอัตโนมัติขนาดเล็กที่เชื่อถือได้ เชื่อม API ฟอร์ม และข้อมูลเข้าด้วยกัน โดยมีจุดตรวจที่ชัดเจนให้คนเป็นผู้ควบคุม",
        points: ["สคริปต์และ Pipeline ด้วย Python", "เชื่อม API และ Webhook", "แนวคิด Workflow บน n8n", "Validation และการจัดการ Error"],
        cta: "ดูโปรเจกต์ทดลอง",
        href: "projects",
      },
      {
        id: "quality",
        title: "เทสต์และทำซ้ำ",
        outcome: "ต้นแบบทุกชิ้นผ่านการทดสอบ เช็กบนอุปกรณ์จริง และปรับปรุงเป็นรอบสั้น ๆ เพราะคำว่าใช้งานได้แปลว่าผ่านการยืนยัน ไม่ใช่แค่ Deploy แล้วจบ",
        points: ["Unit และ Integration Test", "Type Check และ Linting", "QA เรื่อง Responsive บนหลายอุปกรณ์", "รอบการปรับปรุงที่เร็วและมีบันทึก"],
        cta: "ดูกรณีศึกษา",
        href: "case-studies",
      },
    ],
    more: {
      title: "เครื่องมือ",
      engineering: {
        title: "ใช้งานจริง",
        items: [
          { title: "พัฒนา Frontend", note: "React, Next.js, TypeScript และ UI ที่รองรับทุกหน้าจอและเข้าถึงได้" },
          { title: "พัฒนา Backend", note: "Route Handler, Server Action, Validation และข้อมูล" },
          { title: "เชื่อมต่อ API", note: "REST API, Webhook และบริการภายนอก" },
          { title: "Deployment", note: "GitHub, Vercel และกระบวนการ Release ที่ทำซ้ำได้" },
          { title: "การทดสอบ", note: "Vitest, Playwright และการเช็ก QA บนอุปกรณ์จริง" },
        ],
      },
      ai: {
        title: "กำลังเรียนรู้",
        items: [
          { title: "Workflow ที่มี AI ช่วย", note: "Claude Code, ChatGPT และการเขียน Prompt อย่างเป็นระบบ" },
          { title: "Agentic Workflow", note: "แนวคิด Multi-agent ที่มีขั้นตอนอนุมัติโดยคน" },
          { title: "ทดลอง RAG", note: "ค้นหาเอกสารก่อนแล้วค่อยสร้างคำตอบ พร้อมแหล่งอ้างอิง" },
          { title: "แพลตฟอร์มอัตโนมัติ", note: "แนวคิด n8n สำหรับ Workflow ที่มองเห็นและกำหนดได้ชัดเจน" },
          { title: "แนวคิด Local AI", note: "การตั้งค่าโมเดลแบบส่วนตัวบนเครื่องของตัวเอง" },
        ],
        cta: "ติดต่อ",
      },
    },
  },
  ai: {
    eyebrow: "วิธีใช้ AI",
    title: "AI ทำให้เร็วขึ้น แต่เราคือคนตัดสินใจ",
    body:
      "ChatGPT, Claude และ Claude Code อยู่ในงานประจำวัน ทั้งร่าง อธิบาย และทดสอบ ส่วนคนเป็นผู้กำหนดความต้องการ อ่านโค้ด รันการตรวจสอบ และตัดสินใจว่าจะเอาอะไรขึ้นระบบ ทุกขั้นตอนผ่านการยืนยันโดยคน ไม่ใช่โดยโมเดล",
    generated: "แผงวงจรนี้สร้างจากสคริปต์ Python ใน Repository: {nodes} ชิ้นส่วน {edges} เส้นทาง",
    imageAlt:
      "แผนผังวงจร: ความต้องการของคนเข้าสู่ Orchestrator ส่งต่อไปยัง ChatGPT, Claude และ Local AI ผ่าน Tool router ไปยัง Python, Web API, ข้อมูล และ GitHub จากนั้นผ่าน Validation และการอนุมัติของคน ไปสู่ Deployment และ Production",
  },
  process: {
    eyebrow: "วิธีทำงาน",
    title: "สี่ขั้นตอน จากไอเดียสู่ต้นแบบที่ใช้งานได้",
    steps: [
      { title: "ความต้องการ", body: "เป้าหมาย ข้อจำกัด และนิยามของคำว่าเสร็จ เขียนเป็นลายลักษณ์อักษรก่อนมีโค้ดแม้แต่บรรทัดเดียว" },
      { title: "สร้าง", body: "ทำงานทีละขั้นเล็ก ๆ ที่ตรวจได้ โดยมี AI ช่วย ทุกการเปลี่ยนแปลงถูกอ่านและทำความเข้าใจ" },
      { title: "ตรวจสอบ", body: "เทสต์ Type Check Linting และ QA บนหน้าจอจริงหลายขนาดก่อนขึ้นระบบ" },
      { title: "ทำซ้ำ", body: "การใช้งานจริงและฟีดแบ็กบอกว่าต้องปรับอะไรต่อ รอบการปรับปรุงต้องสั้น" },
    ],
  },
  work: {
    eyebrow: "หลักฐานฝีมือ",
    title: "โปรเจกต์จริง ติดป้ายชัดเจน",
    body: "โปรเจกต์ที่ใช้งานจริง ต้นแบบ และโปรเจกต์ทดลอง ทุกชิ้นติดป้ายตรงไปตรงมา ให้เห็นชัดว่าอะไรส่งมอบแล้ว อะไรสร้างไว้เพื่อเรียนรู้",
  },
  featured: {
    eyebrow: "ผลงานที่คัดมา",
    title: "เริ่มจากโปรเจกต์ที่แข็งแกร่งที่สุด",
  },
  closing: {
    title: "มาคุยเรื่องทีมของคุณกัน",
    body: "กำลังมองหาตำแหน่งงาน IT ระดับ Junior หรืองาน Quereinsteiger สายพัฒนาเว็บ ระบบอัตโนมัติ หรืองานดิจิทัลที่ใช้ AI เล่าเรื่องตำแหน่งงานมาได้เลย แล้วจะตอบกลับว่าประสบการณ์เข้ากันได้อย่างไร",
  },
};

export const homeContent: Localized<HomeContent> = { en, de, th };
