import type { Localized } from "@/i18n/config";
import type { JsonErrorCode } from "@/lib/lab/json";
import type { WcagLevel } from "@/lib/lab/color";
import type { DevicePresetId } from "@/lib/lab/responsive";
import type { RequestWarning } from "@/lib/lab/request";

const en = {
  meta: {
    title: "Lab",
    description: "Four working developer tools built from scratch: an API request inspector with cURL, fetch and Python output, a JSON inspector, a container-query preview and a color-token generator with WCAG checks.",
  },
  hero: {
    eyebrow: "Lab",
    title: "Developer tools that actually run.",
    lede: "Build and send an API request, inspect JSON, stress-test a layout, generate accessible color tokens. Small, fast and dependency-free.",
  },
  shell: {
    path: "lab",
    status: "Runs locally in your browser",
    keys: "← → switch tools",
    tool: "Tool",
    of: "of",
  },
  workbench: {
    label: "Lab tools",
    privacy: "Runs entirely in your browser. Nothing is uploaded or stored.",
    tabs: {
      request: { label: "API request", blurb: "Build, check and send requests; export cURL, fetch or Python." },
      json: { label: "JSON inspector", blurb: "Validate, format, minify and explore." },
      responsive: { label: "Responsive preview", blurb: "Watch a layout react to its container." },
      tokens: { label: "Color tokens", blurb: "Scales, contrast and exportable variables." },
    },
  },
  json: {
    input: "JSON input",
    output: "Result",
    load: "Load sample",
    clear: "Clear",
    prettify: "Format",
    minify: "Minify",
    sort: "Sort keys",
    indent: "Indent",
    indentOptions: { "2": "2 spaces", "4": "4 spaces", tab: "Tab" },
    copy: "Copy",
    copied: "Copied",
    valid: "Valid JSON",
    invalid: "Invalid JSON",
    empty: "Paste JSON on the left to validate and explore it.",
    errorAt: "Line {line}, column {column}",
    errors: {
      empty: "There is nothing to parse yet.",
      "unexpected-end": "The document ends too early.",
      "unexpected-token": "Unexpected character {char}.",
      "expected-key": "Expected a property name in double quotes.",
      "expected-colon": "Expected a colon after the property name.",
      "expected-comma-or-close": "Expected a comma or a closing bracket.",
      "invalid-escape": "Invalid escape sequence in a string.",
      "invalid-number": "This number is not valid JSON.",
      "invalid-literal": "Expected true, false or null.",
      "control-char": "Line breaks and control characters must be escaped inside strings.",
      "trailing-content": "Extra content after the end of the document.",
      "too-deep": "The document is nested too deeply to inspect.",
    } satisfies Record<JsonErrorCode, string>,
    stats: { bytes: "Bytes", nodes: "Values", keys: "Keys", depth: "Depth" },
    structure: "Structure",
    structureHint: "Select a value to copy its path.",
    copyPath: "Copy path",
    pathCopied: "Path copied",
    items: "{n} items",
    properties: "{n} properties",
    showMore: "Show {n} more",
    expandAll: "Expand all",
    collapseAll: "Collapse all",
    sample: `{
  "project": "Portfolio",
  "locales": ["en", "de", "th"],
  "stack": { "framework": "Next.js", "language": "TypeScript", "styling": "Tailwind CSS" },
  "pages": 10,
  "tested": true,
  "notes": null
}`,
  },
  responsive: {
    viewport: "Viewport width",
    widthInput: "Width in pixels",
    presets: { phone: "Phone", phoneLarge: "Large phone", tablet: "Tablet", laptop: "Laptop", desktop: "Desktop" } satisfies Record<DevicePresetId, string>,
    container: "Active container breakpoint",
    layout: "Layout",
    columns: "{n} column(s)",
    scale: "Preview scale",
    drag: "Drag the right edge of the frame, use the slider or pick a device.",
    frameLabel: "Live preview of the sample layout",
    sample: {
      brand: "Studio",
      menu: "Menu",
      nav: ["Work", "About", "Contact"],
      title: "Layouts that adapt to the space they are given.",
      body: "This preview uses container queries, so it reacts to the frame width instead of the window.",
      cta: "Start a project",
      cards: [
        { title: "Design", body: "Type, spacing and hierarchy first." },
        { title: "Build", body: "Typed components and real data." },
        { title: "Ship", body: "Tested, deployed and documented." },
      ],
    },
  },
  tokens: {
    base: "Base color",
    baseInput: "Hex value",
    name: "Token name",
    format: "Export format",
    formats: { css: "CSS variables", tailwind: "Tailwind theme", json: "JSON" },
    invalid: "Enter a valid hex color such as #f2411a.",
    scale: "Generated scale",
    baseTag: "Base",
    contrastOnWhite: "on white",
    contrastOnInk: "on ink",
    levels: { AAA: "AAA", AA: "AA", "AA-large": "AA large text", fail: "Fails" } satisfies Record<WcagLevel, string>,
    legend: "Contrast ratio of each step used as text color. AA needs 4.5:1, AAA needs 7:1.",
    export: "Export",
    copy: "Copy",
    copied: "Copied",
    step: "Step",
  },
  request: {
    method: "Method",
    url: "URL",
    urlPlaceholder: "https://api.example.com/v1/items",
    sectionsLabel: "Request parts",
    sections: { params: "Query", headers: "Headers", body: "Body" },
    key: "Key",
    value: "Value",
    enabled: "Include row",
    add: "Add row",
    remove: "Remove row",
    bodyHint: "JSON or plain text. Ignored for GET and DELETE.",
    presets: { label: "Examples", health: "This site's /api/health", post: "JSON POST" },
    resolved: "Resolved request",
    parts: { protocol: "Protocol", host: "Host", path: "Path", query: "Query" },
    urlErrors: { empty: "Enter a URL or a path such as /api/health.", invalid: "This is not a valid URL.", "unsupported-protocol": "Only http and https URLs can be requested." },
    warningsTitle: "Checks",
    noWarnings: "No issues found.",
    warnings: {
      "insecure-url": "Plain http outside localhost: data travels unencrypted.",
      "body-ignored": "GET and DELETE requests don't send a body here; it will be ignored.",
      "invalid-json-body": "The body looks like JSON but doesn't parse.",
      "missing-content-type": "JSON body without a Content-Type header.",
      "invalid-header-name": "A header name contains characters HTTP doesn't allow.",
      "duplicate-header": "The same header is set more than once.",
      "credentials-in-url": "Credentials in the URL end up in logs and history.",
    } satisfies Record<RequestWarning, string>,
    snippets: "Code",
    formats: { curl: "cURL", fetch: "fetch", python: "Python" },
    copy: "Copy",
    copied: "Copied",
    send: "Send request",
    sending: "Sending…",
    sendNote: "Requests go straight from your browser. Other sites must allow CORS.",
    response: "Response",
    status: "Status",
    time: "Time",
    size: "Size",
    type: "Type",
    emptyResponse: "Send the request to see the live response here.",
    networkError: "The request failed. The server may be unreachable or may not allow cross-origin requests.",
    timeout: "No response after 10 seconds.",
    truncated: "Showing the first {n} characters.",
  },
  principles: {
    eyebrow: "How these are built",
    title: "Logic first, interface second.",
    items: [
      { title: "Pure functions", body: "Parsing, contrast math and layout rules live in small typed functions with no UI attached." },
      { title: "Covered by tests", body: "Error positions, WCAG ratios and scale generation are checked by automated tests." },
      { title: "No dependencies", body: "No HTTP, JSON or color libraries. Less code shipped, and every rule is readable." },
    ],
  },
  cta: { label: "Build a tool like this" },
};

export type LabContent = typeof en;

const de: LabContent = {
  meta: {
    title: "Labor",
    description: "Vier funktionierende Entwickler-Tools, von Grund auf gebaut: API-Request-Inspektor mit cURL-, fetch- und Python-Ausgabe, JSON-Inspektor, Container-Query-Vorschau und Farbtoken-Generator mit WCAG-Prüfung.",
  },
  hero: {
    eyebrow: "Labor",
    title: "Entwickler-Tools, die wirklich laufen.",
    lede: "API-Requests bauen und senden, JSON prüfen, Layouts testen, barrierefreie Farbtokens erzeugen. Klein, schnell und ohne Abhängigkeiten.",
  },
  shell: {
    path: "labor",
    status: "Läuft lokal in deinem Browser",
    keys: "← → Tool wechseln",
    tool: "Tool",
    of: "von",
  },
  workbench: {
    label: "Labor-Werkzeuge",
    privacy: "Läuft vollständig im Browser. Nichts wird hochgeladen oder gespeichert.",
    tabs: {
      request: { label: "API-Request", blurb: "Requests bauen, prüfen und senden; als cURL, fetch oder Python exportieren." },
      json: { label: "JSON-Inspektor", blurb: "Prüfen, formatieren, minimieren und erkunden." },
      responsive: { label: "Responsive-Vorschau", blurb: "Ein Layout reagiert auf seinen Container." },
      tokens: { label: "Farbtokens", blurb: "Skalen, Kontrast und exportierbare Variablen." },
    },
  },
  json: {
    input: "JSON-Eingabe",
    output: "Ergebnis",
    load: "Beispiel laden",
    clear: "Leeren",
    prettify: "Formatieren",
    minify: "Minimieren",
    sort: "Schlüssel sortieren",
    indent: "Einrückung",
    indentOptions: { "2": "2 Leerzeichen", "4": "4 Leerzeichen", tab: "Tabulator" },
    copy: "Kopieren",
    copied: "Kopiert",
    valid: "Gültiges JSON",
    invalid: "Ungültiges JSON",
    empty: "JSON links einfügen, um es zu prüfen und zu erkunden.",
    errorAt: "Zeile {line}, Spalte {column}",
    errors: {
      empty: "Es gibt noch nichts zu verarbeiten.",
      "unexpected-end": "Das Dokument endet zu früh.",
      "unexpected-token": "Unerwartetes Zeichen {char}.",
      "expected-key": "Erwartet wird ein Eigenschaftsname in doppelten Anführungszeichen.",
      "expected-colon": "Nach dem Eigenschaftsnamen fehlt ein Doppelpunkt.",
      "expected-comma-or-close": "Erwartet wird ein Komma oder eine schließende Klammer.",
      "invalid-escape": "Ungültige Escape-Sequenz in einer Zeichenkette.",
      "invalid-number": "Diese Zahl ist kein gültiges JSON.",
      "invalid-literal": "Erwartet wird true, false oder null.",
      "control-char": "Zeilenumbrüche und Steuerzeichen müssen in Zeichenketten maskiert werden.",
      "trailing-content": "Zusätzlicher Inhalt nach dem Ende des Dokuments.",
      "too-deep": "Das Dokument ist zu tief verschachtelt.",
    },
    stats: { bytes: "Bytes", nodes: "Werte", keys: "Schlüssel", depth: "Tiefe" },
    structure: "Struktur",
    structureHint: "Wert auswählen, um seinen Pfad zu kopieren.",
    copyPath: "Pfad kopieren",
    pathCopied: "Pfad kopiert",
    items: "{n} Einträge",
    properties: "{n} Eigenschaften",
    showMore: "{n} weitere anzeigen",
    expandAll: "Alle öffnen",
    collapseAll: "Alle schließen",
    sample: `{
  "project": "Portfolio",
  "locales": ["en", "de", "th"],
  "stack": { "framework": "Next.js", "language": "TypeScript", "styling": "Tailwind CSS" },
  "pages": 10,
  "tested": true,
  "notes": null
}`,
  },
  responsive: {
    viewport: "Viewport-Breite",
    widthInput: "Breite in Pixeln",
    presets: { phone: "Smartphone", phoneLarge: "Großes Smartphone", tablet: "Tablet", laptop: "Laptop", desktop: "Desktop" },
    container: "Aktiver Container-Breakpoint",
    layout: "Layout",
    columns: "{n} Spalte(n)",
    scale: "Vorschau-Skalierung",
    drag: "Rechten Rand des Rahmens ziehen, den Regler nutzen oder ein Gerät wählen.",
    frameLabel: "Live-Vorschau des Beispiel-Layouts",
    sample: {
      brand: "Studio",
      menu: "Menü",
      nav: ["Arbeiten", "Über mich", "Kontakt"],
      title: "Layouts, die sich dem verfügbaren Platz anpassen.",
      body: "Diese Vorschau nutzt Container Queries und reagiert daher auf die Rahmenbreite statt auf das Fenster.",
      cta: "Projekt starten",
      cards: [
        { title: "Gestalten", body: "Zuerst Typografie, Abstände und Hierarchie." },
        { title: "Bauen", body: "Typisierte Komponenten und echte Daten." },
        { title: "Ausliefern", body: "Getestet, deployt und dokumentiert." },
      ],
    },
  },
  tokens: {
    base: "Basisfarbe",
    baseInput: "Hex-Wert",
    name: "Token-Name",
    format: "Exportformat",
    formats: { css: "CSS-Variablen", tailwind: "Tailwind-Theme", json: "JSON" },
    invalid: "Bitte einen gültigen Hex-Wert wie #f2411a eingeben.",
    scale: "Erzeugte Skala",
    baseTag: "Basis",
    contrastOnWhite: "auf Weiß",
    contrastOnInk: "auf Dunkel",
    levels: { AAA: "AAA", AA: "AA", "AA-large": "AA für große Schrift", fail: "Nicht bestanden" },
    legend: "Kontrastverhältnis jeder Stufe als Textfarbe. AA verlangt 4,5:1, AAA verlangt 7:1.",
    export: "Export",
    copy: "Kopieren",
    copied: "Kopiert",
    step: "Stufe",
  },
  request: {
    method: "Methode",
    url: "URL",
    urlPlaceholder: "https://api.example.com/v1/items",
    sectionsLabel: "Teile des Requests",
    sections: { params: "Query", headers: "Header", body: "Body" },
    key: "Schlüssel",
    value: "Wert",
    enabled: "Zeile einbeziehen",
    add: "Zeile hinzufügen",
    remove: "Zeile entfernen",
    bodyHint: "JSON oder Text. Bei GET und DELETE wird er ignoriert.",
    presets: { label: "Beispiele", health: "/api/health dieser Website", post: "JSON-POST" },
    resolved: "Aufgelöster Request",
    parts: { protocol: "Protokoll", host: "Host", path: "Pfad", query: "Query" },
    urlErrors: { empty: "Gib eine URL oder einen Pfad wie /api/health ein.", invalid: "Das ist keine gültige URL.", "unsupported-protocol": "Nur http- und https-URLs sind möglich." },
    warningsTitle: "Prüfungen",
    noWarnings: "Keine Auffälligkeiten.",
    warnings: {
      "insecure-url": "Einfaches http außerhalb von localhost: Daten werden unverschlüsselt übertragen.",
      "body-ignored": "GET- und DELETE-Requests senden hier keinen Body; er wird ignoriert.",
      "invalid-json-body": "Der Body sieht nach JSON aus, ist aber ungültig.",
      "missing-content-type": "JSON-Body ohne Content-Type-Header.",
      "invalid-header-name": "Ein Header-Name enthält Zeichen, die HTTP nicht erlaubt.",
      "duplicate-header": "Derselbe Header ist mehrfach gesetzt.",
      "credentials-in-url": "Zugangsdaten in der URL landen in Logs und Verlauf.",
    },
    snippets: "Code",
    formats: { curl: "cURL", fetch: "fetch", python: "Python" },
    copy: "Kopieren",
    copied: "Kopiert",
    send: "Request senden",
    sending: "Wird gesendet …",
    sendNote: "Requests gehen direkt aus deinem Browser. Andere Websites müssen CORS erlauben.",
    response: "Antwort",
    status: "Status",
    time: "Zeit",
    size: "Größe",
    type: "Typ",
    emptyResponse: "Sende den Request, um hier die echte Antwort zu sehen.",
    networkError: "Der Request ist fehlgeschlagen. Der Server ist vielleicht nicht erreichbar oder erlaubt keine Cross-Origin-Requests.",
    timeout: "Keine Antwort nach 10 Sekunden.",
    truncated: "Die ersten {n} Zeichen werden angezeigt.",
  },
  principles: {
    eyebrow: "So sind sie gebaut",
    title: "Erst die Logik, dann die Oberfläche.",
    items: [
      { title: "Reine Funktionen", body: "Parsing, Kontrastberechnung und Layoutregeln stecken in kleinen, typisierten Funktionen ohne UI." },
      { title: "Durch Tests abgesichert", body: "Fehlerpositionen, WCAG-Werte und die Skalenerzeugung werden automatisch getestet." },
      { title: "Keine Abhängigkeiten", body: "Keine HTTP-, JSON- oder Farbbibliotheken. Weniger ausgelieferter Code, jede Regel bleibt lesbar." },
    ],
  },
  cta: { label: "So ein Tool bauen lassen" },
};

const th: LabContent = {
  meta: {
    title: "Lab",
    description: "เครื่องมือสำหรับนักพัฒนา 4 ตัวที่สร้างเองทั้งหมด: API Request Inspector ที่ส่งออกเป็น cURL, fetch และ Python, JSON Inspector, พรีวิว Container Query และตัวสร้าง Color Token พร้อมตรวจ WCAG",
  },
  hero: {
    eyebrow: "Lab",
    title: "เครื่องมือนักพัฒนาที่ใช้งานได้จริง",
    lede: "สร้างและส่ง API Request ตรวจ JSON ทดสอบเลย์เอาต์ และสร้าง Color Token ที่อ่านง่ายสำหรับทุกคน เล็ก เร็ว และไม่พึ่งไลบรารีเสริม",
  },
  shell: {
    path: "lab",
    status: "ทำงานในเบราว์เซอร์เท่านั้น",
    keys: "← → สลับเครื่องมือ",
    tool: "เครื่องมือ",
    of: "จาก",
  },
  workbench: {
    label: "เครื่องมือใน Lab",
    privacy: "ทำงานในเบราว์เซอร์ทั้งหมด ไม่มีการอัปโหลดหรือจัดเก็บข้อมูล",
    tabs: {
      request: { label: "API Request", blurb: "สร้าง ตรวจ และส่ง Request ส่งออกเป็น cURL, fetch หรือ Python" },
      json: { label: "JSON Inspector", blurb: "ตรวจสอบ จัดรูปแบบ ย่อ และสำรวจโครงสร้าง" },
      responsive: { label: "พรีวิว Responsive", blurb: "ดูเลย์เอาต์ตอบสนองต่อขนาดคอนเทนเนอร์" },
      tokens: { label: "โทเคนสี", blurb: "สเกลสี Contrast และตัวแปรที่ส่งออกได้" },
    },
  },
  json: {
    input: "JSON ที่ป้อน",
    output: "ผลลัพธ์",
    load: "โหลดตัวอย่าง",
    clear: "ล้าง",
    prettify: "จัดรูปแบบ",
    minify: "ย่อ",
    sort: "เรียงคีย์",
    indent: "การเยื้อง",
    indentOptions: { "2": "2 ช่องว่าง", "4": "4 ช่องว่าง", tab: "แท็บ" },
    copy: "คัดลอก",
    copied: "คัดลอกแล้ว",
    valid: "JSON ถูกต้อง",
    invalid: "JSON ไม่ถูกต้อง",
    empty: "วาง JSON ทางซ้ายเพื่อตรวจสอบและสำรวจโครงสร้าง",
    errorAt: "บรรทัด {line} คอลัมน์ {column}",
    errors: {
      empty: "ยังไม่มีข้อมูลให้ประมวลผล",
      "unexpected-end": "เอกสารจบก่อนครบโครงสร้าง",
      "unexpected-token": "พบอักขระที่ไม่คาดคิด {char}",
      "expected-key": "ต้องเป็นชื่อพร็อพเพอร์ตีในเครื่องหมายคำพูดคู่",
      "expected-colon": "ต้องมีเครื่องหมายโคลอนหลังชื่อพร็อพเพอร์ตี",
      "expected-comma-or-close": "ต้องเป็นเครื่องหมายจุลภาคหรือวงเล็บปิด",
      "invalid-escape": "Escape sequence ในสตริงไม่ถูกต้อง",
      "invalid-number": "ตัวเลขนี้ไม่ใช่ JSON ที่ถูกต้อง",
      "invalid-literal": "ต้องเป็น true, false หรือ null",
      "control-char": "การขึ้นบรรทัดใหม่และอักขระควบคุมต้องถูก escape ภายในสตริง",
      "trailing-content": "มีเนื้อหาเกินหลังจบเอกสาร",
      "too-deep": "เอกสารซ้อนลึกเกินกว่าจะตรวจสอบได้",
    },
    stats: { bytes: "ไบต์", nodes: "ค่า", keys: "คีย์", depth: "ความลึก" },
    structure: "โครงสร้าง",
    structureHint: "เลือกค่าเพื่อคัดลอกพาธ",
    copyPath: "คัดลอกพาธ",
    pathCopied: "คัดลอกพาธแล้ว",
    items: "{n} รายการ",
    properties: "{n} พร็อพเพอร์ตี",
    showMore: "แสดงอีก {n}",
    expandAll: "ขยายทั้งหมด",
    collapseAll: "ย่อทั้งหมด",
    sample: `{
  "project": "Portfolio",
  "locales": ["en", "de", "th"],
  "stack": { "framework": "Next.js", "language": "TypeScript", "styling": "Tailwind CSS" },
  "pages": 10,
  "tested": true,
  "notes": null
}`,
  },
  responsive: {
    viewport: "ความกว้าง Viewport",
    widthInput: "ความกว้างเป็นพิกเซล",
    presets: { phone: "โทรศัพท์", phoneLarge: "โทรศัพท์จอใหญ่", tablet: "แท็บเล็ต", laptop: "แล็ปท็อป", desktop: "เดสก์ท็อป" },
    container: "Breakpoint ของคอนเทนเนอร์ที่ใช้อยู่",
    layout: "เลย์เอาต์",
    columns: "{n} คอลัมน์",
    scale: "สเกลพรีวิว",
    drag: "ลากขอบขวาของเฟรม ใช้แถบเลื่อน หรือเลือกอุปกรณ์",
    frameLabel: "พรีวิวสดของเลย์เอาต์ตัวอย่าง",
    sample: {
      brand: "Studio",
      menu: "เมนู",
      nav: ["ผลงาน", "เกี่ยวกับ", "ติดต่อ"],
      title: "เลย์เอาต์ที่ปรับตามพื้นที่ที่ได้รับ",
      body: "พรีวิวนี้ใช้ Container Query จึงตอบสนองต่อความกว้างของเฟรม ไม่ใช่ความกว้างของหน้าต่าง",
      cta: "เริ่มโปรเจกต์",
      cards: [
        { title: "ออกแบบ", body: "เริ่มจากตัวอักษร ระยะห่าง และลำดับชั้น" },
        { title: "สร้าง", body: "Component แบบ Typed กับข้อมูลจริง" },
        { title: "ส่งมอบ", body: "ผ่านการทดสอบ Deploy แล้ว และมีเอกสาร" },
      ],
    },
  },
  tokens: {
    base: "สีตั้งต้น",
    baseInput: "ค่า Hex",
    name: "ชื่อโทเคน",
    format: "รูปแบบการส่งออก",
    formats: { css: "CSS variables", tailwind: "Tailwind theme", json: "JSON" },
    invalid: "กรอกสี Hex ที่ถูกต้อง เช่น #f2411a",
    scale: "สเกลที่สร้างขึ้น",
    baseTag: "ตั้งต้น",
    contrastOnWhite: "บนสีขาว",
    contrastOnInk: "บนพื้นเข้ม",
    levels: { AAA: "AAA", AA: "AA", "AA-large": "AA สำหรับตัวอักษรใหญ่", fail: "ไม่ผ่าน" },
    legend: "อัตราส่วน Contrast ของแต่ละขั้นเมื่อใช้เป็นสีตัวอักษร AA ต้องได้ 4.5:1 และ AAA ต้องได้ 7:1",
    export: "ส่งออก",
    copy: "คัดลอก",
    copied: "คัดลอกแล้ว",
    step: "ขั้น",
  },
  request: {
    method: "Method",
    url: "URL",
    urlPlaceholder: "https://api.example.com/v1/items",
    sectionsLabel: "ส่วนประกอบของ Request",
    sections: { params: "Query", headers: "Headers", body: "Body" },
    key: "Key",
    value: "Value",
    enabled: "ใช้แถวนี้",
    add: "เพิ่มแถว",
    remove: "ลบแถว",
    bodyHint: "JSON หรือข้อความธรรมดา GET และ DELETE จะไม่ใช้ส่วนนี้",
    presets: { label: "ตัวอย่าง", health: "/api/health ของเว็บนี้", post: "JSON POST" },
    resolved: "Request ที่ประกอบแล้ว",
    parts: { protocol: "Protocol", host: "Host", path: "Path", query: "Query" },
    urlErrors: { empty: "ใส่ URL หรือ Path เช่น /api/health", invalid: "URL นี้ไม่ถูกต้อง", "unsupported-protocol": "ส่งได้เฉพาะ URL แบบ http และ https" },
    warningsTitle: "การตรวจสอบ",
    noWarnings: "ไม่พบปัญหา",
    warnings: {
      "insecure-url": "ใช้ http นอก localhost ข้อมูลจะส่งแบบไม่เข้ารหัส",
      "body-ignored": "GET และ DELETE จะไม่ส่ง Body ในเครื่องมือนี้",
      "invalid-json-body": "Body ดูเหมือน JSON แต่รูปแบบไม่ถูกต้อง",
      "missing-content-type": "มี JSON Body แต่ไม่มี Header Content-Type",
      "invalid-header-name": "ชื่อ Header มีอักขระที่ HTTP ไม่อนุญาต",
      "duplicate-header": "ตั้ง Header เดียวกันซ้ำมากกว่าหนึ่งครั้ง",
      "credentials-in-url": "ข้อมูลล็อกอินใน URL จะไปอยู่ใน Log และประวัติการใช้งาน",
    },
    snippets: "โค้ด",
    formats: { curl: "cURL", fetch: "fetch", python: "Python" },
    copy: "คัดลอก",
    copied: "คัดลอกแล้ว",
    send: "ส่ง Request",
    sending: "กำลังส่ง…",
    sendNote: "Request ส่งตรงจากเบราว์เซอร์ เว็บปลายทางต้องเปิด CORS ไว้",
    response: "Response",
    status: "Status",
    time: "เวลา",
    size: "ขนาด",
    type: "ชนิด",
    emptyResponse: "กดส่ง Request เพื่อดู Response จริงที่นี่",
    networkError: "ส่ง Request ไม่สำเร็จ เซิร์ฟเวอร์อาจเข้าถึงไม่ได้หรือไม่อนุญาต Cross-origin",
    timeout: "ไม่มีการตอบกลับภายใน 10 วินาที",
    truncated: "แสดง {n} ตัวอักษรแรก",
  },
  principles: {
    eyebrow: "สร้างขึ้นอย่างไร",
    title: "ตรรกะมาก่อน หน้าตามาทีหลัง",
    items: [
      { title: "Pure Function", body: "การ Parse การคำนวณ Contrast และกฎของเลย์เอาต์อยู่ในฟังก์ชันเล็ก ๆ แบบ Typed ที่ไม่ผูกกับ UI" },
      { title: "มีการทดสอบรองรับ", body: "ตำแหน่งข้อผิดพลาด ค่า WCAG และการสร้างสเกลสีถูกตรวจด้วยการทดสอบอัตโนมัติ" },
      { title: "ไม่พึ่งไลบรารีเสริม", body: "ไม่ใช้ไลบรารี HTTP, JSON หรือสี โค้ดที่ส่งถึงผู้ใช้จึงน้อยลง และทุกกฎอ่านเข้าใจได้" },
    ],
  },
  cta: { label: "สร้างเครื่องมือแบบนี้" },
};

export const labContent: Localized<LabContent> = { en, de, th };
