import type { Localized } from "@/i18n/config";
import type { JsonErrorCode } from "@/lib/lab/json";
import type { WcagLevel } from "@/lib/lab/color";
import type { DevicePresetId } from "@/lib/lab/responsive";

const en = {
  meta: {
    title: "Interactive Lab",
    description: "Three working tools built from scratch: a JSON inspector, a container-query preview and a colour-token generator with WCAG contrast checks.",
  },
  hero: {
    eyebrow: "Interactive Lab",
    title: "Small tools, built properly.",
    lede: "Everything here actually works. Paste real JSON, drag a layout through its breakpoints, generate a colour scale and check its contrast. Nothing leaves your browser.",
    complexity: "Complexity",
  },
  workbench: {
    label: "Lab tools",
    privacy: "Runs entirely in your browser. Nothing is uploaded or stored.",
    tabs: {
      json: { label: "JSON inspector", blurb: "Validate, format, minify and explore." },
      responsive: { label: "Responsive preview", blurb: "Watch a layout react to its container." },
      tokens: { label: "Colour tokens", blurb: "Scales, contrast and exportable variables." },
    },
  },
  json: {
    input: "JSON input",
    output: "Result",
    load: "Load sample",
    clear: "Clear",
    prettify: "Format",
    minify: "Minify",
    sort: "Sort keys",
    indent: "Indent",
    indentOptions: { "2": "2 spaces", "4": "4 spaces", tab: "Tab" },
    copy: "Copy",
    copied: "Copied",
    valid: "Valid JSON",
    invalid: "Invalid JSON",
    empty: "Paste JSON on the left to validate and explore it.",
    errorAt: "Line {line}, column {column}",
    errors: {
      empty: "There is nothing to parse yet.",
      "unexpected-end": "The document ends too early.",
      "unexpected-token": "Unexpected character {char}.",
      "expected-key": "Expected a property name in double quotes.",
      "expected-colon": "Expected a colon after the property name.",
      "expected-comma-or-close": "Expected a comma or a closing bracket.",
      "invalid-escape": "Invalid escape sequence in a string.",
      "invalid-number": "This number is not valid JSON.",
      "invalid-literal": "Expected true, false or null.",
      "control-char": "Line breaks and control characters must be escaped inside strings.",
      "trailing-content": "Extra content after the end of the document.",
      "too-deep": "The document is nested too deeply to inspect.",
    } satisfies Record<JsonErrorCode, string>,
    stats: { bytes: "Bytes", nodes: "Values", keys: "Keys", depth: "Depth" },
    structure: "Structure",
    structureHint: "Select a value to copy its path.",
    copyPath: "Copy path",
    pathCopied: "Path copied",
    items: "{n} items",
    properties: "{n} properties",
    showMore: "Show {n} more",
    expandAll: "Expand all",
    collapseAll: "Collapse all",
    sample: `{
  "project": "Portfolio",
  "locales": ["en", "de", "th"],
  "stack": { "framework": "Next.js", "language": "TypeScript", "styling": "Tailwind CSS" },
  "pages": 9,
  "tested": true,
  "notes": null
}`,
  },
  responsive: {
    viewport: "Viewport width",
    widthInput: "Width in pixels",
    presets: { phone: "Phone", phoneLarge: "Large phone", tablet: "Tablet", laptop: "Laptop", desktop: "Desktop" } satisfies Record<DevicePresetId, string>,
    container: "Active container breakpoint",
    layout: "Layout",
    columns: "{n} column(s)",
    scale: "Preview scale",
    drag: "Drag the right edge of the frame, use the slider or pick a device.",
    frameLabel: "Live preview of the sample layout",
    sample: {
      brand: "Studio",
      menu: "Menu",
      nav: ["Work", "About", "Contact"],
      title: "Layouts that adapt to the space they are given.",
      body: "This preview uses container queries, so it reacts to the frame width instead of the window.",
      cta: "Start a project",
      cards: [
        { title: "Design", body: "Type, spacing and hierarchy first." },
        { title: "Build", body: "Typed components and real data." },
        { title: "Ship", body: "Tested, deployed and documented." },
      ],
    },
  },
  tokens: {
    base: "Base colour",
    baseInput: "Hex value",
    name: "Token name",
    format: "Export format",
    formats: { css: "CSS variables", tailwind: "Tailwind theme", json: "JSON" },
    invalid: "Enter a valid hex colour such as #f2411a.",
    scale: "Generated scale",
    baseTag: "Base",
    contrastOnWhite: "on white",
    contrastOnInk: "on ink",
    levels: { AAA: "AAA", AA: "AA", "AA-large": "AA large text", fail: "Fails" } satisfies Record<WcagLevel, string>,
    legend: "Contrast ratio of each step used as text colour. AA needs 4.5:1, AAA needs 7:1.",
    export: "Export",
    copy: "Copy",
    copied: "Copied",
    step: "Step",
  },
  principles: {
    eyebrow: "How these are built",
    title: "Logic first, interface second.",
    items: [
      { title: "Pure functions", body: "Parsing, contrast maths and layout rules live in small typed functions with no UI attached." },
      { title: "Covered by tests", body: "Error positions, WCAG ratios and scale generation are checked by automated tests." },
      { title: "No dependencies", body: "No JSON or colour libraries. Less code shipped, and every rule is readable." },
    ],
  },
  cta: { label: "Discuss a project" },
};

export type LabContent = typeof en;

const de: LabContent = {
  meta: {
    title: "Interaktives Labor",
    description: "Drei funktionierende Werkzeuge, von Grund auf gebaut: JSON-Inspektor, Container-Query-Vorschau und Farbtoken-Generator mit WCAG-Kontrastprüfung.",
  },
  hero: {
    eyebrow: "Interaktives Labor",
    title: "Kleine Werkzeuge, sauber gebaut.",
    lede: "Alles hier funktioniert wirklich. Echtes JSON einfügen, ein Layout durch seine Breakpoints ziehen, eine Farbskala erzeugen und den Kontrast prüfen. Nichts verlässt den Browser.",
    complexity: "Komplexität",
  },
  workbench: {
    label: "Labor-Werkzeuge",
    privacy: "Läuft vollständig im Browser. Nichts wird hochgeladen oder gespeichert.",
    tabs: {
      json: { label: "JSON-Inspektor", blurb: "Prüfen, formatieren, minimieren und erkunden." },
      responsive: { label: "Responsive-Vorschau", blurb: "Ein Layout reagiert auf seinen Container." },
      tokens: { label: "Farbtokens", blurb: "Skalen, Kontrast und exportierbare Variablen." },
    },
  },
  json: {
    input: "JSON-Eingabe",
    output: "Ergebnis",
    load: "Beispiel laden",
    clear: "Leeren",
    prettify: "Formatieren",
    minify: "Minimieren",
    sort: "Schlüssel sortieren",
    indent: "Einrückung",
    indentOptions: { "2": "2 Leerzeichen", "4": "4 Leerzeichen", tab: "Tabulator" },
    copy: "Kopieren",
    copied: "Kopiert",
    valid: "Gültiges JSON",
    invalid: "Ungültiges JSON",
    empty: "JSON links einfügen, um es zu prüfen und zu erkunden.",
    errorAt: "Zeile {line}, Spalte {column}",
    errors: {
      empty: "Es gibt noch nichts zu verarbeiten.",
      "unexpected-end": "Das Dokument endet zu früh.",
      "unexpected-token": "Unerwartetes Zeichen {char}.",
      "expected-key": "Erwartet wird ein Eigenschaftsname in doppelten Anführungszeichen.",
      "expected-colon": "Nach dem Eigenschaftsnamen fehlt ein Doppelpunkt.",
      "expected-comma-or-close": "Erwartet wird ein Komma oder eine schließende Klammer.",
      "invalid-escape": "Ungültige Escape-Sequenz in einer Zeichenkette.",
      "invalid-number": "Diese Zahl ist kein gültiges JSON.",
      "invalid-literal": "Erwartet wird true, false oder null.",
      "control-char": "Zeilenumbrüche und Steuerzeichen müssen in Zeichenketten maskiert werden.",
      "trailing-content": "Zusätzlicher Inhalt nach dem Ende des Dokuments.",
      "too-deep": "Das Dokument ist zu tief verschachtelt.",
    },
    stats: { bytes: "Bytes", nodes: "Werte", keys: "Schlüssel", depth: "Tiefe" },
    structure: "Struktur",
    structureHint: "Wert auswählen, um seinen Pfad zu kopieren.",
    copyPath: "Pfad kopieren",
    pathCopied: "Pfad kopiert",
    items: "{n} Einträge",
    properties: "{n} Eigenschaften",
    showMore: "{n} weitere anzeigen",
    expandAll: "Alle öffnen",
    collapseAll: "Alle schließen",
    sample: `{
  "project": "Portfolio",
  "locales": ["en", "de", "th"],
  "stack": { "framework": "Next.js", "language": "TypeScript", "styling": "Tailwind CSS" },
  "pages": 9,
  "tested": true,
  "notes": null
}`,
  },
  responsive: {
    viewport: "Viewport-Breite",
    widthInput: "Breite in Pixeln",
    presets: { phone: "Smartphone", phoneLarge: "Großes Smartphone", tablet: "Tablet", laptop: "Laptop", desktop: "Desktop" },
    container: "Aktiver Container-Breakpoint",
    layout: "Layout",
    columns: "{n} Spalte(n)",
    scale: "Vorschau-Skalierung",
    drag: "Rechten Rand des Rahmens ziehen, den Regler nutzen oder ein Gerät wählen.",
    frameLabel: "Live-Vorschau des Beispiel-Layouts",
    sample: {
      brand: "Studio",
      menu: "Menü",
      nav: ["Arbeiten", "Über mich", "Kontakt"],
      title: "Layouts, die sich dem verfügbaren Platz anpassen.",
      body: "Diese Vorschau nutzt Container Queries und reagiert daher auf die Rahmenbreite statt auf das Fenster.",
      cta: "Projekt starten",
      cards: [
        { title: "Gestalten", body: "Zuerst Typografie, Abstände und Hierarchie." },
        { title: "Bauen", body: "Typisierte Komponenten und echte Daten." },
        { title: "Ausliefern", body: "Getestet, deployt und dokumentiert." },
      ],
    },
  },
  tokens: {
    base: "Basisfarbe",
    baseInput: "Hex-Wert",
    name: "Token-Name",
    format: "Exportformat",
    formats: { css: "CSS-Variablen", tailwind: "Tailwind-Theme", json: "JSON" },
    invalid: "Bitte einen gültigen Hex-Wert wie #f2411a eingeben.",
    scale: "Erzeugte Skala",
    baseTag: "Basis",
    contrastOnWhite: "auf Weiß",
    contrastOnInk: "auf Tintenschwarz",
    levels: { AAA: "AAA", AA: "AA", "AA-large": "AA für große Schrift", fail: "Nicht bestanden" },
    legend: "Kontrastverhältnis jeder Stufe als Textfarbe. AA verlangt 4,5:1, AAA verlangt 7:1.",
    export: "Export",
    copy: "Kopieren",
    copied: "Kopiert",
    step: "Stufe",
  },
  principles: {
    eyebrow: "So sind sie gebaut",
    title: "Erst die Logik, dann die Oberfläche.",
    items: [
      { title: "Reine Funktionen", body: "Parsing, Kontrastberechnung und Layoutregeln stecken in kleinen, typisierten Funktionen ohne UI." },
      { title: "Durch Tests abgesichert", body: "Fehlerpositionen, WCAG-Werte und die Skalenerzeugung werden automatisch getestet." },
      { title: "Keine Abhängigkeiten", body: "Keine JSON- oder Farbbibliotheken. Weniger ausgelieferter Code, jede Regel bleibt lesbar." },
    ],
  },
  cta: { label: "Projekt besprechen" },
};

const th: LabContent = {
  meta: {
    title: "ห้องทดลองเชิงโต้ตอบ",
    description: "เครื่องมือที่ใช้งานได้จริงสามชิ้นที่เขียนขึ้นเอง ได้แก่ JSON Inspector, พรีวิว Container Query และตัวสร้างโทเคนสีพร้อมตรวจ Contrast ตาม WCAG",
  },
  hero: {
    eyebrow: "ห้องทดลองเชิงโต้ตอบ",
    title: "เครื่องมือเล็ก ๆ ที่ทำอย่างพิถีพิถัน",
    lede: "ทุกอย่างในหน้านี้ใช้งานได้จริง วาง JSON จริง ลากเลย์เอาต์ผ่านแต่ละ Breakpoint สร้างสเกลสีและตรวจ Contrast ได้เลย ข้อมูลไม่ออกจากเบราว์เซอร์",
    complexity: "ความซับซ้อน",
  },
  workbench: {
    label: "เครื่องมือในห้องทดลอง",
    privacy: "ทำงานในเบราว์เซอร์ทั้งหมด ไม่มีการอัปโหลดหรือจัดเก็บข้อมูล",
    tabs: {
      json: { label: "JSON Inspector", blurb: "ตรวจสอบ จัดรูปแบบ ย่อ และสำรวจโครงสร้าง" },
      responsive: { label: "พรีวิว Responsive", blurb: "ดูเลย์เอาต์ตอบสนองต่อขนาดคอนเทนเนอร์" },
      tokens: { label: "โทเคนสี", blurb: "สเกลสี Contrast และตัวแปรที่ส่งออกได้" },
    },
  },
  json: {
    input: "JSON ที่ป้อน",
    output: "ผลลัพธ์",
    load: "โหลดตัวอย่าง",
    clear: "ล้าง",
    prettify: "จัดรูปแบบ",
    minify: "ย่อ",
    sort: "เรียงคีย์",
    indent: "การเยื้อง",
    indentOptions: { "2": "2 ช่องว่าง", "4": "4 ช่องว่าง", tab: "แท็บ" },
    copy: "คัดลอก",
    copied: "คัดลอกแล้ว",
    valid: "JSON ถูกต้อง",
    invalid: "JSON ไม่ถูกต้อง",
    empty: "วาง JSON ทางซ้ายเพื่อตรวจสอบและสำรวจโครงสร้าง",
    errorAt: "บรรทัด {line} คอลัมน์ {column}",
    errors: {
      empty: "ยังไม่มีข้อมูลให้ประมวลผล",
      "unexpected-end": "เอกสารจบก่อนครบโครงสร้าง",
      "unexpected-token": "พบอักขระที่ไม่คาดคิด {char}",
      "expected-key": "ต้องเป็นชื่อพร็อพเพอร์ตีในเครื่องหมายคำพูดคู่",
      "expected-colon": "ต้องมีเครื่องหมายโคลอนหลังชื่อพร็อพเพอร์ตี",
      "expected-comma-or-close": "ต้องเป็นเครื่องหมายจุลภาคหรือวงเล็บปิด",
      "invalid-escape": "Escape sequence ในสตริงไม่ถูกต้อง",
      "invalid-number": "ตัวเลขนี้ไม่ใช่ JSON ที่ถูกต้อง",
      "invalid-literal": "ต้องเป็น true, false หรือ null",
      "control-char": "การขึ้นบรรทัดใหม่และอักขระควบคุมต้องถูก escape ภายในสตริง",
      "trailing-content": "มีเนื้อหาเกินหลังจบเอกสาร",
      "too-deep": "เอกสารซ้อนลึกเกินกว่าจะตรวจสอบได้",
    },
    stats: { bytes: "ไบต์", nodes: "ค่า", keys: "คีย์", depth: "ความลึก" },
    structure: "โครงสร้าง",
    structureHint: "เลือกค่าเพื่อคัดลอกพาธ",
    copyPath: "คัดลอกพาธ",
    pathCopied: "คัดลอกพาธแล้ว",
    items: "{n} รายการ",
    properties: "{n} พร็อพเพอร์ตี",
    showMore: "แสดงอีก {n}",
    expandAll: "ขยายทั้งหมด",
    collapseAll: "ย่อทั้งหมด",
    sample: `{
  "project": "Portfolio",
  "locales": ["en", "de", "th"],
  "stack": { "framework": "Next.js", "language": "TypeScript", "styling": "Tailwind CSS" },
  "pages": 9,
  "tested": true,
  "notes": null
}`,
  },
  responsive: {
    viewport: "ความกว้าง Viewport",
    widthInput: "ความกว้างเป็นพิกเซล",
    presets: { phone: "โทรศัพท์", phoneLarge: "โทรศัพท์จอใหญ่", tablet: "แท็บเล็ต", laptop: "แล็ปท็อป", desktop: "เดสก์ท็อป" },
    container: "Breakpoint ของคอนเทนเนอร์ที่ใช้อยู่",
    layout: "เลย์เอาต์",
    columns: "{n} คอลัมน์",
    scale: "สเกลพรีวิว",
    drag: "ลากขอบขวาของเฟรม ใช้แถบเลื่อน หรือเลือกอุปกรณ์",
    frameLabel: "พรีวิวสดของเลย์เอาต์ตัวอย่าง",
    sample: {
      brand: "Studio",
      menu: "เมนู",
      nav: ["ผลงาน", "เกี่ยวกับ", "ติดต่อ"],
      title: "เลย์เอาต์ที่ปรับตามพื้นที่ที่ได้รับ",
      body: "พรีวิวนี้ใช้ Container Query จึงตอบสนองต่อความกว้างของเฟรม ไม่ใช่ความกว้างของหน้าต่าง",
      cta: "เริ่มโปรเจกต์",
      cards: [
        { title: "ออกแบบ", body: "เริ่มจากตัวอักษร ระยะห่าง และลำดับชั้น" },
        { title: "สร้าง", body: "คอมโพเนนต์แบบมีชนิดข้อมูลและข้อมูลจริง" },
        { title: "ส่งมอบ", body: "ผ่านการทดสอบ ดีพลอย และมีเอกสาร" },
      ],
    },
  },
  tokens: {
    base: "สีตั้งต้น",
    baseInput: "ค่า Hex",
    name: "ชื่อโทเคน",
    format: "รูปแบบการส่งออก",
    formats: { css: "CSS variables", tailwind: "Tailwind theme", json: "JSON" },
    invalid: "กรอกสี Hex ที่ถูกต้อง เช่น #f2411a",
    scale: "สเกลที่สร้างขึ้น",
    baseTag: "ตั้งต้น",
    contrastOnWhite: "บนสีขาว",
    contrastOnInk: "บนสีหมึก",
    levels: { AAA: "AAA", AA: "AA", "AA-large": "AA สำหรับตัวอักษรใหญ่", fail: "ไม่ผ่าน" },
    legend: "อัตราส่วน Contrast ของแต่ละขั้นเมื่อใช้เป็นสีตัวอักษร AA ต้องได้ 4.5:1 และ AAA ต้องได้ 7:1",
    export: "ส่งออก",
    copy: "คัดลอก",
    copied: "คัดลอกแล้ว",
    step: "ขั้น",
  },
  principles: {
    eyebrow: "สร้างขึ้นอย่างไร",
    title: "ตรรกะมาก่อน หน้าตามาทีหลัง",
    items: [
      { title: "ฟังก์ชันล้วน", body: "การแยกวิเคราะห์ การคำนวณ Contrast และกฎของเลย์เอาต์อยู่ในฟังก์ชันเล็ก ๆ ที่มีชนิดข้อมูลและไม่ผูกกับ UI" },
      { title: "มีการทดสอบรองรับ", body: "ตำแหน่งข้อผิดพลาด ค่า WCAG และการสร้างสเกลสีถูกตรวจด้วยการทดสอบอัตโนมัติ" },
      { title: "ไม่พึ่งไลบรารีเสริม", body: "ไม่ใช้ไลบรารี JSON หรือสี โค้ดที่ส่งถึงผู้ใช้จึงน้อยลง และทุกกฎอ่านเข้าใจได้" },
    ],
  },
  cta: { label: "ปรึกษาโปรเจกต์" },
};

export const labContent: Localized<LabContent> = { en, de, th };
