import type { Localized } from "@/i18n/config";
import type { CategoryId, ProjectId, ProjectKind } from "@/components/pages/projects/data";

interface ProjectCopy {
  tagline: string;
  problem: string;
  solution: string;
  decisions: readonly string[];
}

const en = {
  meta: {
    title: "Work",
    description:
      "Selected work: new websites, redesigns, feature additions, web apps, AI integration, automation, local AI and multi-agent systems — each labelled honestly as a concept, demonstration or architecture demo.",
  },
  hero: {
    eyebrow: "Selected work",
    title: "Websites, products",
    titleAccent: "and AI systems.",
    lede: "Every service on offer, shown as a worked example: the problem, the decisions and the stack. One is this live site; the rest are clearly labelled concepts.",
  },
  ui: {
    indexTitle: "Index",
    searchLabel: "Search work",
    searchPlaceholder: "Search: redesign, Python, RAG…",
    filterLabel: "Filter by service",
    all: "All",
    results: "{n} of {total}",
    empty: "Nothing matches. Try another word or clear the filters.",
    reset: "Clear filters",
    columns: { project: "Project", service: "Service", type: "Type" },
    jump: "Go to project",
  },
  kind: { concept: "Concept Project", demo: "Technical Demonstration", architecture: "Architecture Demo" } satisfies Record<ProjectKind, string>,
  detail: {
    problem: "Problem",
    solution: "Approach",
    decisions: "Engineering decisions",
    stack: "Stack",
    previewNote: "Illustrative mock-up, not a screenshot.",
    circuitNote: "The real Python-generated circuit used on this site.",
    source: "View source on GitHub",
    before: "Before",
    after: "After",
  },
  categories: {
    "new-website": "New website",
    redesign: "Redesign",
    features: "Feature addition",
    webapp: "Web application",
    "ai-integration": "AI integration",
    automation: "Automation",
    "local-ai": "Local AI",
    "multi-agent": "Multi-agent system",
  } satisfies Record<CategoryId, string>,
  disclaimer: {
    title: "How to read these labels",
    body: "Concept Projects are self-initiated and use synthetic data. Architecture Demos describe a system design rather than a deployed product. Neither was delivered to a client. The Technical Demonstration — this portfolio — is live and its source is public.",
  },
  cta: { title: "Something similar on your list?", body: "A new site, a redesign, a feature for an existing product or an AI workflow: describe it and you get a clear reply about scope and approach." },
  projects: {
    "this-portfolio": {
      tagline: "The site you are reading: three languages, a real backend, email delivery and a Python-generated circuit.",
      problem: "A portfolio should prove engineering ability, not only describe it.",
      solution: "An original design system, typed content in EN, DE and TH, a validated contact pipeline with Resend email, tests and continuous deployment to Vercel.",
      decisions: [
        "Server Components by default; client code only where something is interactive, so the pages ship little JavaScript.",
        "The AI circuit is generated by a Python script at build time and committed — production never needs a Python runtime.",
        "Contact delivery is one service with several channels; the form only reports success when a channel really accepted the message.",
      ],
    },
    "fern-clay": {
      tagline: "Redesigning a dated studio website into a fast, bilingual, accessible one.",
      problem: "The old site is slow on phones, hard to update and hides the enquiry form three clicks deep.",
      solution: "A content audit, a new editorial layout, localized routes and an enquiry form on every key page — without changing the hosting budget.",
      decisions: [
        "Start with an audit of what visitors actually use, so the redesign removes pages instead of adding them.",
        "Images resized and lazy-loaded through one helper, which removes most of the page weight on mobile.",
        "Content moved into typed files per language, so a missing translation fails the build instead of shipping.",
      ],
    },
    "relay-desk": {
      tagline: "Adding AI-assisted ticket triage to an existing helpdesk without rewriting it.",
      problem: "A working support tool is drowning in unsorted tickets, and a rewrite is not an option.",
      solution: "A new feature inside the existing app: incoming tickets get a suggested category and priority from Claude, which an agent confirms with one click.",
      decisions: [
        "Built behind a feature flag on the existing data model, so it can ship to one team first.",
        "The model returns structured output validated with Zod; anything invalid falls back to manual triage.",
        "Suggestions are never applied silently — a person accepts or corrects each one, and corrections are logged.",
      ],
    },
    tideline: {
      tagline: "A new website and storefront for a small-batch apparel brand.",
      problem: "A new brand needs a site that looks considered and sells on a phone, from day one.",
      solution: "A fast storefront with editorial product pages, a persistent cart and a short checkout flow designed mobile first.",
      decisions: [
        "Prices are always recalculated on the server; the browser only displays them.",
        "Cart state lives on the server under an opaque id, so it survives reloads and devices.",
        "Checkout is three short steps with inline validation, tuned for thumbs first.",
      ],
    },
    "ask-the-docs": {
      tagline: "An AI assistant integrated into an existing documentation site.",
      problem: "Users cannot find answers in long documentation and open support tickets instead.",
      solution: "A chat panel that retrieves the relevant documentation passages first, then asks a model to answer with links to its sources.",
      decisions: [
        "Retrieval before generation: every answer cites the passages it used, so it can be checked.",
        "The API key stays on the server; the browser only talks to a validated route with rate limiting.",
        "When retrieval finds nothing relevant, the assistant says so instead of guessing.",
      ],
    },
    rota: {
      tagline: "A shift-planning web application for teams that still schedule in spreadsheets.",
      problem: "Swaps, leave and coverage rules live in someone's head, and conflicts surface on the day.",
      solution: "A weekly planner that applies coverage rules while you edit and explains every conflict it finds.",
      decisions: [
        "Scheduling rules are pure functions with unit tests, separate from the interface.",
        "Every conflict names the rule and the people affected instead of saying “invalid”.",
        "Keyboard-first editing, because planners spend hours in the grid.",
      ],
    },
    "ledger-run": {
      tagline: "A Python automation that turns invoice PDFs into validated accounting entries.",
      problem: "Someone retypes invoice details into accounting software every week.",
      solution: "A scheduled Python pipeline: read PDFs, extract fields, validate them, and post entries through the accounting API after a human approves the batch.",
      decisions: [
        "Rule-based parsing first; the ChatGPT API only handles layouts the rules cannot read.",
        "Every extracted field is validated with typed models before anything is posted.",
        "A daily summary with an approve step keeps a person in control of what reaches the books.",
      ],
    },
    "quiet-archive": {
      tagline: "A private document search running on a local model — nothing leaves the machine.",
      problem: "Internal documents are too sensitive to send to a cloud AI service, but still need to be searchable.",
      solution: "A Python service that indexes documents into embeddings, retrieves relevant passages and queries a local model endpoint, with a simple web interface on top.",
      decisions: [
        "A local, OpenAI-compatible endpoint (Ollama- or llama.cpp-style), so models can be swapped without code changes.",
        "Answers always show their source passages, which makes wrong answers visible.",
        "Optional cloud routing only for documents explicitly marked as non-sensitive.",
      ],
    },
    "brief-loop": {
      tagline: "A multi-agent development system that turns a written brief into a reviewed pull request.",
      problem: "AI-generated code is fast but inconsistent when requests are vague and nobody checks the result.",
      solution: "An orchestrator splits the brief across design, frontend, backend and test agents, merges their work, runs CI and stops at a human review gate.",
      decisions: [
        "Each agent has an explicit input and output, so a failing step can be rerun alone.",
        "Tests and type checks run before a person reviews, so review time goes to design questions.",
        "Agents never merge their own work: the human gate is mandatory.",
      ],
    },
  } satisfies Record<ProjectId, ProjectCopy>,
};

export type ProjectsContent = typeof en;

const de: ProjectsContent = {
  meta: {
    title: "Arbeiten",
    description:
      "Ausgewählte Arbeiten: neue Websites, Redesigns, neue Features, Web-Apps, KI-Integration, Automatisierung, lokale KI und Multi-Agent-Systeme – jeweils ehrlich als Konzept, Demonstration oder Architektur-Demo gekennzeichnet.",
  },
  hero: {
    eyebrow: "Ausgewählte Arbeiten",
    title: "Websites, Produkte",
    titleAccent: "und KI-Systeme.",
    lede: "Jede Leistung als ausgearbeitetes Beispiel: das Problem, die Entscheidungen und der Stack. Eines ist diese Live-Website, die übrigen sind klar gekennzeichnete Konzepte.",
  },
  ui: {
    indexTitle: "Übersicht",
    searchLabel: "Arbeiten durchsuchen",
    searchPlaceholder: "Suche: Redesign, Python, RAG…",
    filterLabel: "Nach Leistung filtern",
    all: "Alle",
    results: "{n} von {total}",
    empty: "Keine Treffer. Versuch ein anderes Wort oder setz die Filter zurück.",
    reset: "Filter zurücksetzen",
    columns: { project: "Projekt", service: "Leistung", type: "Art" },
    jump: "Zum Projekt",
  },
  kind: { concept: "Konzeptprojekt", demo: "Technische Demonstration", architecture: "Architektur-Demo" },
  detail: {
    problem: "Problem",
    solution: "Ansatz",
    decisions: "Technische Entscheidungen",
    stack: "Stack",
    previewNote: "Illustratives Mock-up, kein Screenshot.",
    circuitNote: "Der echte, mit Python generierte Schaltplan dieser Website.",
    source: "Quellcode auf GitHub",
    before: "Vorher",
    after: "Nachher",
  },
  categories: {
    "new-website": "Neue Website",
    redesign: "Redesign",
    features: "Neues Feature",
    webapp: "Webanwendung",
    "ai-integration": "KI-Integration",
    automation: "Automatisierung",
    "local-ai": "Lokale KI",
    "multi-agent": "Multi-Agent-System",
  },
  disclaimer: {
    title: "So sind die Labels zu lesen",
    body: "Konzeptprojekte sind selbst initiiert und nutzen synthetische Daten. Architektur-Demos beschreiben ein Systemdesign, kein ausgeliefertes Produkt. Keines davon wurde für Auftraggebende umgesetzt. Die Technische Demonstration – dieses Portfolio – ist live und ihr Quellcode öffentlich.",
  },
  cta: { title: "Etwas Ähnliches auf deiner Liste?", body: "Neue Website, Redesign, ein Feature für ein bestehendes Produkt oder ein KI-Workflow: beschreib es kurz und du bekommst eine klare Antwort zu Umfang und Vorgehen." },
  projects: {
    "this-portfolio": {
      tagline: "Die Website, die du gerade liest: drei Sprachen, ein echtes Backend, E-Mail-Versand und ein mit Python generierter Schaltplan.",
      problem: "Ein Portfolio sollte technisches Können beweisen, nicht nur beschreiben.",
      solution: "Ein eigenes Designsystem, typisierte Inhalte auf EN, DE und TH, eine validierte Kontakt-Pipeline mit Resend-E-Mail, Tests und Continuous Deployment auf Vercel.",
      decisions: [
        "Standardmäßig Server Components, Client-Code nur dort, wo etwas interaktiv ist – so liefern die Seiten wenig JavaScript aus.",
        "Der KI-Schaltplan wird beim Build von einem Python-Skript erzeugt und committet – die Produktion braucht keine Python-Laufzeit.",
        "Der Kontaktversand ist ein Dienst mit mehreren Kanälen; das Formular meldet nur dann Erfolg, wenn ein Kanal die Nachricht wirklich angenommen hat.",
      ],
    },
    "fern-clay": {
      tagline: "Redesign einer veralteten Studio-Website zu einer schnellen, zweisprachigen und barrierearmen Seite.",
      problem: "Die alte Seite ist auf dem Handy langsam, schwer zu pflegen und versteckt das Anfrageformular drei Klicks tief.",
      solution: "Ein Inhalts-Audit, ein neues redaktionelles Layout, lokalisierte Routen und ein Anfrageformular auf jeder wichtigen Seite – ohne höheres Hosting-Budget.",
      decisions: [
        "Zuerst prüfen, was Besuchende wirklich nutzen, damit das Redesign Seiten entfernt statt neue hinzuzufügen.",
        "Bilder werden über einen zentralen Helfer skaliert und verzögert geladen – das spart auf dem Handy den Großteil des Seitengewichts.",
        "Inhalte liegen in typisierten Dateien pro Sprache, sodass eine fehlende Übersetzung den Build stoppt, statt live zu gehen.",
      ],
    },
    "relay-desk": {
      tagline: "KI-gestützte Ticket-Vorsortierung für einen bestehenden Helpdesk – ohne Neuentwicklung.",
      problem: "Ein funktionierendes Support-Tool ertrinkt in unsortierten Tickets, und ein Neubau kommt nicht infrage.",
      solution: "Ein neues Feature in der bestehenden App: Eingehende Tickets bekommen von Claude eine vorgeschlagene Kategorie und Priorität, die das Team mit einem Klick bestätigt.",
      decisions: [
        "Hinter einem Feature-Flag auf dem bestehenden Datenmodell gebaut, damit es zuerst für ein Team live gehen kann.",
        "Das Modell liefert strukturierte Ausgaben, die mit Zod validiert werden; Ungültiges fällt auf manuelle Sortierung zurück.",
        "Vorschläge werden nie stillschweigend übernommen – ein Mensch bestätigt oder korrigiert jeden, Korrekturen werden protokolliert.",
      ],
    },
    tideline: {
      tagline: "Eine neue Website mit Shop für eine kleine Modemarke.",
      problem: "Eine neue Marke braucht vom ersten Tag an eine Website, die durchdacht wirkt und auf dem Handy verkauft.",
      solution: "Ein schneller Shop mit redaktionellen Produktseiten, einem dauerhaften Warenkorb und einem kurzen Checkout, mobil zuerst gestaltet.",
      decisions: [
        "Preise werden immer auf dem Server berechnet, der Browser zeigt sie nur an.",
        "Der Warenkorb liegt serverseitig unter einer anonymen ID und übersteht Neuladen und Gerätewechsel.",
        "Der Checkout hat drei kurze Schritte mit Inline-Validierung, optimiert für die Bedienung mit dem Daumen.",
      ],
    },
    "ask-the-docs": {
      tagline: "Ein KI-Assistent, integriert in eine bestehende Dokumentationsseite.",
      problem: "Nutzende finden Antworten in langer Dokumentation nicht und eröffnen stattdessen Support-Tickets.",
      solution: "Ein Chat-Panel, das zuerst die passenden Dokumentationsabschnitte sucht und dann ein Modell mit Quellenangaben antworten lässt.",
      decisions: [
        "Erst suchen, dann generieren: Jede Antwort nennt die verwendeten Abschnitte und lässt sich so prüfen.",
        "Der API-Schlüssel bleibt auf dem Server; der Browser spricht nur mit einer validierten Route mit Rate-Limit.",
        "Findet die Suche nichts Relevantes, sagt der Assistent das, statt zu raten.",
      ],
    },
    rota: {
      tagline: "Eine Webanwendung zur Schichtplanung für Teams, die noch in Tabellen planen.",
      problem: "Schichttausch, Urlaub und Besetzungsregeln existieren nur im Kopf einer Person, Konflikte zeigen sich erst am Tag selbst.",
      solution: "Ein Wochenplaner, der Besetzungsregeln schon beim Bearbeiten anwendet und jeden Konflikt erklärt.",
      decisions: [
        "Planungsregeln sind reine Funktionen mit Unit-Tests, getrennt von der Oberfläche.",
        "Jeder Konflikt nennt die Regel und die betroffenen Personen, statt nur „ungültig“ zu melden.",
        "Tastatur zuerst, weil Planende Stunden im Raster verbringen.",
      ],
    },
    "ledger-run": {
      tagline: "Eine Python-Automatisierung, die Rechnungs-PDFs in validierte Buchungen verwandelt.",
      problem: "Jede Woche tippt jemand Rechnungsdaten von Hand in die Buchhaltungssoftware ab.",
      solution: "Eine geplante Python-Pipeline: PDFs lesen, Felder extrahieren, validieren und nach Freigabe des Stapels über die Buchhaltungs-API buchen.",
      decisions: [
        "Zuerst regelbasiertes Parsen; die ChatGPT-API übernimmt nur Layouts, die die Regeln nicht lesen können.",
        "Jedes extrahierte Feld wird mit typisierten Modellen validiert, bevor etwas gebucht wird.",
        "Eine tägliche Zusammenfassung mit Freigabeschritt lässt eine Person entscheiden, was in die Bücher kommt.",
      ],
    },
    "quiet-archive": {
      tagline: "Eine private Dokumentensuche mit lokalem Modell – nichts verlässt den Rechner.",
      problem: "Interne Dokumente sind zu sensibel für einen Cloud-KI-Dienst, sollen aber trotzdem durchsuchbar sein.",
      solution: "Ein Python-Dienst indexiert Dokumente als Embeddings, sucht passende Abschnitte und fragt einen lokalen Modell-Endpunkt; darüber liegt eine schlichte Weboberfläche.",
      decisions: [
        "Ein lokaler, OpenAI-kompatibler Endpunkt (im Stil von Ollama oder llama.cpp), damit Modelle ohne Codeänderung austauschbar sind.",
        "Antworten zeigen immer ihre Quellabschnitte – so werden falsche Antworten sichtbar.",
        "Optionales Cloud-Routing nur für Dokumente, die ausdrücklich als unkritisch markiert sind.",
      ],
    },
    "brief-loop": {
      tagline: "Ein Multi-Agent-Entwicklungssystem, das aus einem schriftlichen Briefing einen geprüften Pull Request macht.",
      problem: "KI-generierter Code ist schnell, aber uneinheitlich, wenn Anforderungen vage sind und niemand das Ergebnis prüft.",
      solution: "Ein Orchestrator verteilt das Briefing auf Design-, Frontend-, Backend- und Test-Agents, führt ihre Arbeit zusammen, startet CI und stoppt vor einer verpflichtenden menschlichen Freigabe.",
      decisions: [
        "Jeder Agent hat einen klaren Input und Output, sodass ein fehlgeschlagener Schritt einzeln wiederholt werden kann.",
        "Tests und Typprüfungen laufen vor dem Review, damit die Review-Zeit in Designfragen fließt.",
        "Agents mergen nie ihre eigene Arbeit: Die menschliche Freigabe ist Pflicht.",
      ],
    },
  },
};

const th: ProjectsContent = {
  meta: {
    title: "ผลงาน",
    description:
      "ผลงานที่คัดมา: เว็บไซต์ใหม่ Redesign เพิ่มฟีเจอร์ เว็บแอป AI Integration ระบบอัตโนมัติ Local AI และระบบ Multi-agent พร้อมระบุชัดเจนว่าเป็นโปรเจกต์แนวคิด งานสาธิต หรือเดโมสถาปัตยกรรม",
  },
  hero: {
    eyebrow: "ผลงานที่คัดมา",
    title: "เว็บไซต์ ผลิตภัณฑ์",
    titleAccent: "และระบบ AI",
    lede: "ทุกบริการมีตัวอย่างงานให้ดู: ปัญหา การตัดสินใจ และสแตกที่ใช้ ชิ้นหนึ่งคือเว็บไซต์นี้ซึ่งใช้งานอยู่จริง ส่วนที่เหลือเป็นโปรเจกต์แนวคิดที่ระบุไว้ชัดเจน",
  },
  ui: {
    indexTitle: "สารบัญ",
    searchLabel: "ค้นหาผลงาน",
    searchPlaceholder: "ค้นหา: Redesign, Python, RAG…",
    filterLabel: "กรองตามบริการ",
    all: "ทั้งหมด",
    results: "{n} จาก {total}",
    empty: "ไม่พบผลงานที่ตรงกัน ลองใช้คำอื่นหรือล้างตัวกรอง",
    reset: "ล้างตัวกรอง",
    columns: { project: "โปรเจกต์", service: "บริการ", type: "ประเภท" },
    jump: "ไปที่โปรเจกต์",
  },
  kind: { concept: "โปรเจกต์แนวคิด", demo: "งานสาธิตทางเทคนิค", architecture: "เดโมสถาปัตยกรรม" },
  detail: {
    problem: "ปัญหา",
    solution: "แนวทาง",
    decisions: "การตัดสินใจทางเทคนิค",
    stack: "สแตก",
    previewNote: "ภาพจำลองเพื่ออธิบาย ไม่ใช่ภาพหน้าจอจริง",
    circuitNote: "วงจรจริงของเว็บไซต์นี้ที่สร้างด้วย Python",
    source: "ดูซอร์สโค้ดบน GitHub",
    before: "ก่อน",
    after: "หลัง",
  },
  categories: {
    "new-website": "เว็บไซต์ใหม่",
    redesign: "Redesign",
    features: "เพิ่มฟีเจอร์",
    webapp: "เว็บแอปพลิเคชัน",
    "ai-integration": "AI Integration",
    automation: "ระบบอัตโนมัติ",
    "local-ai": "Local AI",
    "multi-agent": "ระบบ Multi-agent",
  },
  disclaimer: {
    title: "วิธีอ่านป้ายกำกับ",
    body: "โปรเจกต์แนวคิดเป็นงานที่ริเริ่มเองและใช้ข้อมูลสังเคราะห์ ส่วนเดโมสถาปัตยกรรมอธิบายการออกแบบระบบ ไม่ใช่ผลิตภัณฑ์ที่ส่งมอบแล้ว ทั้งสองแบบไม่ได้ทำหรือส่งมอบให้ลูกค้า ส่วนงานสาธิตทางเทคนิค ซึ่งก็คือพอร์ตโฟลิโอนี้ ใช้งานได้จริงและเปิดซอร์สโค้ดให้ดู",
  },
  cta: { title: "มีงานคล้ายกันอยู่ในแผนไหม", body: "เว็บไซต์ใหม่ Redesign ฟีเจอร์สำหรับระบบเดิม หรือ AI Workflow เล่ามาสั้น ๆ แล้วจะได้คำตอบที่ชัดเจนเรื่องขอบเขตและแนวทาง" },
  projects: {
    "this-portfolio": {
      tagline: "เว็บไซต์ที่กำลังอ่านอยู่นี้: สามภาษา Backend จริง ส่งอีเมลได้จริง และวงจรที่สร้างด้วย Python",
      problem: "พอร์ตโฟลิโอควรพิสูจน์ฝีมือทางวิศวกรรม ไม่ใช่แค่บรรยาย",
      solution: "ระบบดีไซน์ที่ออกแบบเอง เนื้อหาแบบ Typed ทั้ง EN, DE และ TH ระบบฟอร์มติดต่อที่ผ่าน Validation และส่งอีเมลผ่าน Resend มีเทสต์ และ Deploy ขึ้น Vercel อัตโนมัติ",
      decisions: [
        "ใช้ Server Components เป็นค่าเริ่มต้น และใช้โค้ดฝั่ง client เฉพาะส่วนที่ต้องโต้ตอบ หน้าเว็บจึงส่ง JavaScript น้อย",
        "วงจร AI สร้างโดยสคริปต์ Python ตอน build แล้ว commit เก็บไว้ ฝั่ง Production จึงไม่ต้องมี Python runtime",
        "การส่งข้อความติดต่อเป็นบริการเดียวที่มีหลายช่องทาง ฟอร์มจะแจ้งว่าสำเร็จก็ต่อเมื่อมีช่องทางรับข้อความไปจริงเท่านั้น",
      ],
    },
    "fern-clay": {
      tagline: "Redesign เว็บไซต์สตูดิโอที่ล้าสมัยให้เร็ว รองรับสองภาษา และเข้าถึงได้",
      problem: "เว็บเดิมช้าบนมือถือ อัปเดตยาก และซ่อนฟอร์มสอบถามไว้ลึกถึงสามคลิก",
      solution: "ตรวจสอบเนื้อหา วางเลย์เอาต์ใหม่แบบ editorial แยก route ตามภาษา และวางฟอร์มสอบถามไว้ทุกหน้าสำคัญ โดยไม่เพิ่มงบค่าโฮสติ้ง",
      decisions: [
        "เริ่มจากดูว่าผู้เข้าชมใช้อะไรจริง Redesign จึงลดจำนวนหน้าลงแทนที่จะเพิ่ม",
        "ปรับขนาดและ lazy-load รูปผ่าน helper เดียว ลดน้ำหนักหน้าเว็บบนมือถือได้มาก",
        "ย้ายเนื้อหาไปไว้ในไฟล์แบบ Typed แยกตามภาษา หากคำแปลขาด build จะไม่ผ่าน",
      ],
    },
    "relay-desk": {
      tagline: "เพิ่มระบบคัดแยก Ticket ด้วย AI ให้ Helpdesk เดิม โดยไม่ต้องเขียนใหม่",
      problem: "เครื่องมือ Support ที่ใช้งานได้ดีกำลังจมอยู่กับ Ticket ที่ไม่ได้คัดแยก และการเขียนระบบใหม่ทั้งหมดไม่ใช่ทางเลือก",
      solution: "ฟีเจอร์ใหม่ในแอปเดิม: Ticket ที่เข้ามาจะได้หมวดหมู่และลำดับความสำคัญที่ Claude แนะนำ แล้วทีมยืนยันได้ในคลิกเดียว",
      decisions: [
        "สร้างไว้หลัง feature flag บนโมเดลข้อมูลเดิม จึงเปิดให้ทีมเดียวใช้ก่อนได้",
        "โมเดลคืนค่าแบบมีโครงสร้างที่ตรวจด้วย Zod หากไม่ถูกต้องจะกลับไปคัดแยกด้วยมือ",
        "ระบบไม่นำคำแนะนำไปใช้เองเงียบ ๆ ต้องมีคนยืนยันหรือแก้ไขทุกครั้ง และบันทึกการแก้ไขไว้",
      ],
    },
    tideline: {
      tagline: "เว็บไซต์และร้านค้าออนไลน์ใหม่สำหรับแบรนด์เสื้อผ้าขนาดเล็ก",
      problem: "แบรนด์ใหม่ต้องมีเว็บที่ดูประณีตและขายได้บนมือถือตั้งแต่วันแรก",
      solution: "ร้านค้าที่โหลดเร็ว หน้าสินค้าแบบ editorial ตะกร้าที่จำค่าไว้ และขั้นตอนชำระเงินสั้น ๆ ที่ออกแบบสำหรับมือถือก่อน",
      decisions: [
        "คำนวณราคาใหม่ที่เซิร์ฟเวอร์ทุกครั้ง เบราว์เซอร์มีหน้าที่แสดงผลเท่านั้น",
        "เก็บสถานะตะกร้าไว้ที่เซิร์ฟเวอร์ด้วย id ที่ไม่ระบุตัวตน ตะกร้าจึงไม่หายแม้รีโหลดหรือเปลี่ยนอุปกรณ์",
        "ชำระเงินสามขั้นตอนสั้น ๆ มี validation ทันที ออกแบบให้ใช้นิ้วโป้งได้สะดวก",
      ],
    },
    "ask-the-docs": {
      tagline: "ผู้ช่วย AI ที่เชื่อมเข้ากับเว็บเอกสารที่มีอยู่แล้ว",
      problem: "ผู้ใช้หาคำตอบในเอกสารยาว ๆ ไม่เจอ จึงเปิด Support ticket แทน",
      solution: "แผงแชตที่ค้นหาส่วนของเอกสารที่เกี่ยวข้องก่อน แล้วให้โมเดลตอบพร้อมลิงก์อ้างอิง",
      decisions: [
        "ค้นหาก่อนค่อยสร้างคำตอบ ทุกคำตอบอ้างอิงส่วนที่ใช้ จึงตรวจสอบได้",
        "API key อยู่ที่เซิร์ฟเวอร์เท่านั้น เบราว์เซอร์คุยกับ route ที่มี validation และ rate limit",
        "หากค้นหาไม่เจอข้อมูลที่เกี่ยวข้อง ผู้ช่วยจะบอกตรง ๆ แทนการเดา",
      ],
    },
    rota: {
      tagline: "เว็บแอปจัดตารางกะสำหรับทีมที่ยังจัดตารางใน spreadsheet",
      problem: "การแลกกะ การลา และกฎการจัดคนอยู่ในหัวของคนคนเดียว ปัญหาจึงโผล่มาในวันทำงานจริง",
      solution: "ตารางวางแผนรายสัปดาห์ที่ตรวจกฎการจัดคนระหว่างแก้ไข และอธิบายทุกข้อขัดแย้งที่พบ",
      decisions: [
        "กฎการจัดตารางเป็น pure function ที่มี unit test แยกจากส่วนอินเทอร์เฟซ",
        "ทุกข้อขัดแย้งระบุกฎและคนที่ได้รับผลกระทบ แทนคำว่า “ไม่ถูกต้อง”",
        "ใช้คีย์บอร์ดเป็นหลัก เพราะผู้วางแผนใช้เวลาหลายชั่วโมงกับตาราง",
      ],
    },
    "ledger-run": {
      tagline: "ระบบอัตโนมัติด้วย Python ที่เปลี่ยน PDF ใบแจ้งหนี้เป็นรายการบัญชีที่ผ่านการตรวจสอบ",
      problem: "ทุกสัปดาห์ต้องมีคนพิมพ์ข้อมูลใบแจ้งหนี้ลงโปรแกรมบัญชีด้วยมือ",
      solution: "Pipeline Python ที่ตั้งเวลาไว้: อ่าน PDF ดึงข้อมูล ตรวจสอบ แล้วส่งรายการผ่าน API ของระบบบัญชีหลังจากมีคนอนุมัติชุดข้อมูล",
      decisions: [
        "ใช้การ parse ตามกฎก่อน ส่วน ChatGPT API ใช้เฉพาะเลย์เอาต์ที่กฎอ่านไม่ได้",
        "ทุกฟิลด์ที่ดึงมาต้องผ่าน validation ด้วยโมเดลแบบมี type ก่อนส่งเข้าระบบ",
        "สรุปรายวันพร้อมขั้นตอนอนุมัติ ทำให้คนเป็นผู้ตัดสินว่าอะไรจะเข้าสู่บัญชี",
      ],
    },
    "quiet-archive": {
      tagline: "ระบบค้นหาเอกสารส่วนตัวที่รันบน Local model ข้อมูลไม่ออกจากเครื่อง",
      problem: "เอกสารภายในอ่อนไหวเกินกว่าจะส่งให้บริการ Cloud AI แต่ยังต้องค้นหาได้",
      solution: "บริการ Python ที่ทำ index เอกสารเป็น Embeddings ค้นหาส่วนที่เกี่ยวข้อง แล้วถาม Local model endpoint โดยมีเว็บอินเทอร์เฟซเรียบง่ายอยู่ด้านบน",
      decisions: [
        "ใช้ endpoint ภายในที่เข้ากันได้กับ OpenAI (แบบ Ollama หรือ llama.cpp) จึงเปลี่ยนโมเดลได้โดยไม่ต้องแก้โค้ด",
        "ทุกคำตอบแสดงส่วนของเอกสารที่อ้างอิง คำตอบที่ผิดจึงเห็นได้ชัด",
        "Routing ไป Cloud เป็นตัวเลือก และใช้เฉพาะเอกสารที่ระบุชัดว่าไม่อ่อนไหว",
      ],
    },
    "brief-loop": {
      tagline: "ระบบพัฒนาแบบ Multi-agent ที่เปลี่ยน brief เป็น Pull request ที่ผ่านการรีวิว",
      problem: "โค้ดที่ AI สร้างนั้นเร็ว แต่ไม่สม่ำเสมอเมื่อความต้องการคลุมเครือและไม่มีใครตรวจผลลัพธ์",
      solution: "Orchestrator แบ่ง brief ให้ Agent ด้าน Design, Frontend, Backend และ Test รวมงานเข้าด้วยกัน รัน CI แล้วหยุดรอให้คนรีวิว",
      decisions: [
        "ทุก Agent มี input และ output ที่ชัดเจน ขั้นตอนที่ล้มเหลวจึงรันใหม่แยกได้",
        "เทสต์และ type check รันก่อนถึงมือคนรีวิว เวลารีวิวจึงใช้กับเรื่องการออกแบบ",
        "Agent ไม่ merge งานของตัวเองเด็ดขาด การอนุมัติโดยคนเป็นขั้นตอนบังคับ",
      ],
    },
  },
};

export const projectsContent: Localized<ProjectsContent> = { en, de, th };
