import type { Localized } from "@/i18n/config";
import type { CategoryId, ProjectId, ProjectKind } from "@/components/pages/projects/data";

interface ProjectCopy {
  tagline: string;
  problem: string;
  solution: string;
  decisions: readonly string[];
}

const en = {
  meta: {
    title: "Projects",
    description:
      "Selected projects of Chaiyaphol — live websites, an Android app prototype, automation work and AI experiments. Each project is honestly labelled as live, prototype or experiment.",
  },
  hero: {
    eyebrow: "Selected work",
    title: "Real projects,",
    titleAccent: "honestly labelled.",
    lede: "Every project says what it is: live and used, a working prototype, or an experiment built to learn. Links go to what really exists — nothing is invented.",
  },
  ui: {
    indexTitle: "Index",
    searchLabel: "Search projects",
    searchPlaceholder: "Search: website, Android, RAG, Python…",
    filterLabel: "Filter by category",
    all: "All",
    results: "{n} of {total}",
    empty: "Nothing matches. Try another word or clear the filters.",
    reset: "Clear filters",
    columns: { project: "Project", service: "Category", type: "Status" },
    jump: "Go to project",
  },
  kind: {
    live: "Live Project",
    prototype: "Prototype",
    experiment: "Experimental Project",
    learning: "Learning Project",
    concept: "Concept Project",
    architecture: "Concept / Experimental Architecture",
  } satisfies Record<ProjectKind, string>,
  detail: {
    problem: "Problem",
    solution: "Approach",
    decisions: "Key decisions",
    stack: "Stack",
    previewNote: "Illustrative mock-up, not a screenshot.",
    circuitNote: "The real Python-generated circuit used on this site.",
    source: "View source on GitHub",
    live: "Visit live site",
    before: "Before",
    after: "After",
  },
  categories: {
    web: "Web",
    app: "App",
    automation: "Automation",
    ai: "AI",
    cloud: "Cloud",
  } satisfies Record<CategoryId, string>,
  disclaimer: {
    title: "How to read these labels",
    body: "Live Projects are deployed and really used. Prototypes work but are not production software. Experimental Projects were built to explore a technology and to learn — they prove how I work, not that the idea is a product. Only links that really exist are shown.",
  },
  cta: { title: "Looking for a team member?", body: "I'm open to junior IT roles and Quereinsteiger positions in web development, automation and AI-assisted digital work. Write to me and I'll reply with how my experience fits your team." },
  projects: {
    "wat-charoen-dham": {
      tagline: "Real-world website for a Buddhist organization in Germany — built and maintained with AI-assisted development.",
      problem: "The organization needed a modern, multilingual website where visitors can find events, meditation times and contact information.",
      solution: "A trilingual website (German, English, Thai) with event announcements, news, visiting information and a clean, accessible layout — deployed and improved iteratively with AI assistance.",
      decisions: [
        "Content is structured around what visitors actually need: events, meditation, visiting and contact.",
        "Trilingual routing (DE / EN / TH) with a clear language switcher on every page.",
        "Built through an AI-assisted workflow: requirements first, generated code reviewed and tested, then deployed and iterated.",
      ],
    },
    "android-app": {
      tagline: "Android App Prototype — developed with AI assistance and prepared for Google Play release and testing.",
      problem: "Learning what it takes to get a real app from code to a store listing and real test users.",
      solution: "An Android app taken through the Google Play Console workflow to the closed-testing stage — including signing, the store listing and test releases.",
      decisions: [
        "Developed with AI assistance; requirements and app structure were defined before writing code.",
        "Reached the closed-testing stage in Google Play Console.",
        "Not publicly released — the page says honestly what was achieved.",
      ],
    },
    "this-portfolio": {
      tagline: "The site you are reading: three languages, a real backend, email delivery and a Python-generated circuit.",
      problem: "A portfolio should prove practical ability, not only describe it.",
      solution: "An original design system, typed content in EN, DE and TH, a validated contact pipeline with Resend email, tests and continuous deployment to Vercel.",
      decisions: [
        "Server Components by default; client code only where something is interactive, so the pages ship little JavaScript.",
        "The AI circuit is generated by a Python script at build time and committed — production never needs a Python runtime.",
        "Contact delivery is one service with several channels; the form only reports success when a channel really accepted the message.",
      ],
    },
    "hetzner-neon": {
      tagline: "Cloud Experiment – Hetzner & Neon. Practical experimentation with cloud deployment, hosted services and database-backed applications.",
      problem: "Understanding how a hosted application and a serverless database work together — and what that really costs.",
      solution: "Experimented with deploying applications on Hetzner cloud infrastructure with a Neon serverless Postgres backend, then evaluated the operating costs.",
      decisions: [
        "Set up hosted compute and a serverless database, wired together through environment variables.",
        "Evaluated the real operating costs against what the project actually needed.",
        "Project discontinued after the cost evaluation — documented as a learning experiment, not as production infrastructure.",
      ],
    },
    "rag-workflow": {
      tagline: "Experimental RAG workflow: an assistant that answers from documentation by retrieving the right passages first.",
      problem: "Users cannot find answers in long documentation, and a chat model alone would guess instead of citing sources.",
      solution: "A retrieval-augmented workflow: relevant passages are retrieved first, then a model answers with links to the sources it used.",
      decisions: [
        "Retrieval before generation: every answer cites its passages, so it can be checked.",
        "The API key stays on the server; the browser only talks to a validated route with rate limiting.",
        "When retrieval finds nothing relevant, the assistant says so instead of guessing.",
      ],
    },
    "agent-workflow": {
      tagline: "Agent Workflow Experiment — exploring multi-agent orchestration with a mandatory human review gate.",
      problem: "AI-generated code is fast but inconsistent when requirements are vague and nobody checks the result.",
      solution: "An orchestrator splits a brief across design, frontend, backend and test agents, merges their work, runs CI and stops at a human review gate.",
      decisions: [
        "Each agent has an explicit input and output, so a failing step can be rerun alone.",
        "Tests and type checks run before a person reviews, so review time goes to design questions.",
        "Agents never merge their own work: the human gate is mandatory.",
      ],
    },
    "automation-prototype": {
      tagline: "Automation Prototype — a Python pipeline that turns invoice PDFs into validated entries.",
      problem: "Invoice details get retyped into accounting software by hand, every week.",
      solution: "A scheduled Python pipeline: read PDFs, extract fields, validate them and post entries through an API only after a human approves the batch.",
      decisions: [
        "Rule-based parsing first; the ChatGPT API only handles layouts the rules cannot read.",
        "Every extracted field is validated with typed models before anything is posted.",
        "A daily summary with an approve step keeps a person in control of what reaches the books.",
      ],
    },
    "local-ai-concept": {
      tagline: "Local AI Concept — a private document search running on a local model, nothing leaves the machine.",
      problem: "Internal documents are too sensitive for a cloud AI service, but still need to be searchable.",
      solution: "A Python service indexes documents into embeddings, retrieves relevant passages and queries a local model endpoint, with a simple web interface on top.",
      decisions: [
        "A local, OpenAI-compatible endpoint (Ollama- or llama.cpp-style), so models can be swapped without code changes.",
        "Answers always show their source passages, which makes wrong answers visible.",
        "Optional cloud routing only for documents explicitly marked as non-sensitive.",
      ],
    },
  } satisfies Record<ProjectId, ProjectCopy>,
};

export type ProjectsContent = typeof en;

const de: ProjectsContent = {
  meta: {
    title: "Projekte",
    description:
      "Ausgewählte Projekte von Chaiyaphol – Live-Websites, ein Android-App-Prototyp, Automatisierungsarbeiten und KI-Experimente. Jedes Projekt ist ehrlich als Live-Projekt, Prototyp oder Experiment gekennzeichnet.",
  },
  hero: {
    eyebrow: "Ausgewählte Arbeiten",
    title: "Echte Projekte,",
    titleAccent: "ehrlich gekennzeichnet.",
    lede: "Jedes Projekt sagt, was es ist: live und in Nutzung, ein funktionierender Prototyp oder ein Experiment, das zum Lernen entstand. Links führen zu dem, was wirklich existiert – nichts ist erfunden.",
  },
  ui: {
    indexTitle: "Übersicht",
    searchLabel: "Projekte durchsuchen",
    searchPlaceholder: "Suche: Website, Android, RAG, Python …",
    filterLabel: "Nach Kategorie filtern",
    all: "Alle",
    results: "{n} von {total}",
    empty: "Keine Treffer. Versuchen Sie ein anderes Wort oder setzen Sie die Filter zurück.",
    reset: "Filter zurücksetzen",
    columns: { project: "Projekt", service: "Kategorie", type: "Status" },
    jump: "Zum Projekt",
  },
  kind: {
    live: "Live-Projekt",
    prototype: "Prototyp",
    experiment: "Experimentelles Projekt",
    learning: "Lernprojekt",
    concept: "Konzeptprojekt",
    architecture: "Konzept / Experimentelle Architektur",
  },
  detail: {
    problem: "Problem",
    solution: "Ansatz",
    decisions: "Wichtige Entscheidungen",
    stack: "Stack",
    previewNote: "Illustratives Mock-up, kein Screenshot.",
    circuitNote: "Der echte, mit Python generierte Schaltplan dieser Website.",
    source: "Quellcode auf GitHub ansehen",
    live: "Live-Website ansehen",
    before: "Vorher",
    after: "Nachher",
  },
  categories: {
    web: "Web",
    app: "App",
    automation: "Automatisierung",
    ai: "KI",
    cloud: "Cloud",
  },
  disclaimer: {
    title: "So sind die Labels zu lesen",
    body: "Live-Projekte sind deployt und wirklich in Nutzung. Prototypen funktionieren, sind aber keine Produktionssoftware. Experimentelle Projekte entstanden, um eine Technologie zu erkunden und zu lernen – sie zeigen, wie ich arbeite, nicht, dass die Idee ein Produkt ist. Es werden nur Links gezeigt, die wirklich existieren.",
  },
  cta: { title: "Auf der Suche nach einem Teammitglied?", body: "Ich bin offen für Junior-IT-Stellen und Quereinsteiger-Positionen in Webentwicklung, Automatisierung und KI-gestützter digitaler Arbeit. Schreiben Sie mir, und ich antworte, wie meine Erfahrung zu Ihrem Team passt." },
  projects: {
    "wat-charoen-dham": {
      tagline: "Echte Website für eine buddhistische Organisation in Deutschland – gebaut und gepflegt mit KI-gestützter Entwicklung.",
      problem: "Die Organisation brauchte eine moderne, mehrsprachige Website, auf der Besuchende Veranstaltungen, Meditationszeiten und Kontaktinformationen finden.",
      solution: "Eine dreisprachige Website (Deutsch, Englisch, Thai) mit Veranstaltungshinweisen, Neuigkeiten, Besuchsinformationen und einem klaren, barrierefreien Layout – iterativ mit KI-Unterstützung deployt und verbessert.",
      decisions: [
        "Die Inhalte sind um das strukturiert, was Besuchende wirklich brauchen: Veranstaltungen, Meditation, Besuch und Kontakt.",
        "Dreisprachiges Routing (DE / EN / TH) mit einer klaren Sprachumschaltung auf jeder Seite.",
        "Gebaut über einen KI-gestützten Workflow: zuerst Anforderungen, dann generierter Code – gelesen und getestet –, danach deployt und iteriert.",
      ],
    },
    "android-app": {
      tagline: "Android-App-Prototyp – mit KI-Unterstützung entwickelt und für Veröffentlichung und Tests über Google Play vorbereitet.",
      problem: "Lernen, was es braucht, um eine echte App vom Code bis zu einem Store-Eintrag und echten Testnutzenden zu bringen.",
      solution: "Eine Android-App, die über den Google-Play-Console-Workflow bis zur Stufe des Closed Testing geführt wurde – inklusive Signierung, Store-Eintrag und Test-Release.",
      decisions: [
        "Mit KI-Unterstützung entwickelt; Anforderungen und App-Struktur standen fest, bevor Code entstand.",
        "Die Stufe des Closed Testing in der Google Play Console erreicht.",
        "Nicht öffentlich veröffentlicht – die Seite sagt ehrlich, was erreicht wurde.",
      ],
    },
    "this-portfolio": {
      tagline: "Die Website, die Sie gerade lesen: drei Sprachen, ein echtes Backend, E-Mail-Zustellung und ein mit Python generierter Schaltplan.",
      problem: "Ein Portfolio sollte praktisches Können beweisen, nicht nur beschreiben.",
      solution: "Ein eigenes Designsystem, typisierte Inhalte in EN, DE und TH, eine validierte Kontakt-Pipeline mit Resend-E-Mail, Tests und Continuous Deployment auf Vercel.",
      decisions: [
        "Standardmäßig Server Components; Client-Code nur dort, wo etwas interaktiv ist – so liefern die Seiten wenig JavaScript aus.",
        "Der KI-Schaltplan wird beim Build von einem Python-Skript erzeugt und eingecheckt – die Produktion braucht nie eine Python-Laufzeit.",
        "Die Kontaktzustellung ist ein Dienst mit mehreren Kanälen; das Formular meldet nur Erfolg, wenn ein Kanal die Nachricht wirklich angenommen hat.",
      ],
    },
    "hetzner-neon": {
      tagline: "Cloud-Experiment – Hetzner & Neon. Praktisches Experimentieren mit Cloud-Deployment, gehosteten Diensten und datenbankgestützten Anwendungen.",
      problem: "Verstehen, wie eine gehostete Anwendung und eine serverlose Datenbank zusammenarbeiten – und was das wirklich kostet.",
      solution: "Experimentiert mit dem Deployment von Anwendungen auf Hetzner-Cloud-Infrastruktur mit einem serverlosen Postgres-Backend von Neon; anschließend wurden die Betriebskosten bewertet.",
      decisions: [
        "Gehostete Rechenleistung und eine serverlose Datenbank eingerichtet und über Umgebungsvariablen verbunden.",
        "Die tatsächlichen Betriebskosten gegen den tatsächlichen Bedarf des Projekts abgewogen.",
        "Projekt nach der Kostenbewertung eingestellt – dokumentiert als Lernexperiment, nicht als Produktionsinfrastruktur.",
      ],
    },
    "rag-workflow": {
      tagline: "Experimenteller RAG-Workflow: ein Assistent, der aus Dokumentation antwortet, indem er zuerst die passenden Abschnitte abruft.",
      problem: "Nutzende finden in langer Dokumentation keine Antworten – und ein Chat-Modell allein würde raten, statt Quellen zu nennen.",
      solution: "Ein Retrieval-Augmented-Workflow: Zuerst werden relevante Abschnitte abgerufen, dann antwortet ein Modell mit Links zu den verwendeten Quellen.",
      decisions: [
        "Erst abrufen, dann generieren: Jede Antwort nennt ihre Abschnitte und ist damit prüfbar.",
        "Der API-Schlüssel bleibt auf dem Server; der Browser spricht nur mit einer validierten Route mit Rate-Limit.",
        "Findet das Retrieval nichts Relevantes, sagt der Assistent das, statt zu raten.",
      ],
    },
    "agent-workflow": {
      tagline: "Agent-Workflow-Experiment – Multi-Agent-Orchestrierung mit einer verpflichtenden menschlichen Review-Stufe.",
      problem: "KI-generierter Code ist schnell, aber uneinheitlich, wenn Anforderungen vage sind und niemand das Ergebnis prüft.",
      solution: "Ein Orchestrator verteilt ein Briefing auf Design-, Frontend-, Backend- und Test-Agents, führt ihre Arbeit zusammen, startet CI und stoppt an einer menschlichen Review-Stufe.",
      decisions: [
        "Jeder Agent hat einen klaren Input und Output – ein fehlgeschlagener Schritt lässt sich allein wiederholen.",
        "Tests und Typprüfungen laufen vor dem menschlichen Review, damit die Review-Zeit in Designfragen fließt.",
        "Agents mergen nie ihre eigene Arbeit: Die menschliche Freigabe ist Pflicht.",
      ],
    },
    "automation-prototype": {
      tagline: "Automatisierungs-Prototyp – eine Python-Pipeline, die Rechnungs-PDFs in validierte Buchungen verwandelt.",
      problem: "Rechnungsdaten werden Woche für Woche von Hand in die Buchhaltungssoftware übertragen.",
      solution: "Eine geplante Python-Pipeline: PDFs lesen, Felder extrahieren, validieren und erst nach menschlicher Freigabe des Stapels über eine API buchen.",
      decisions: [
        "Zuerst regelbasiertes Parsen; die ChatGPT-API übernimmt nur Layouts, die die Regeln nicht lesen können.",
        "Jedes extrahierte Feld wird mit typisierten Modellen validiert, bevor etwas gebucht wird.",
        "Eine tägliche Zusammenfassung mit Freigabeschritt lässt einen Menschen kontrollieren, was in die Bücher gelangt.",
      ],
    },
    "local-ai-concept": {
      tagline: "Lokales KI-Konzept – eine private Dokumentensuche auf einem lokalen Modell, nichts verlässt den Rechner.",
      problem: "Interne Dokumente sind zu sensibel für einen Cloud-KI-Dienst, müssen aber durchsuchbar bleiben.",
      solution: "Ein Python-Dienst indexiert Dokumente als Embeddings, ruft relevante Abschnitte ab und fragt einen lokalen Modell-Endpunkt – darüber liegt eine schlichte Weboberfläche.",
      decisions: [
        "Ein lokaler, OpenAI-kompatibler Endpunkt (im Stil von Ollama oder llama.cpp), damit Modelle ohne Codeänderungen austauschbar sind.",
        "Antworten zeigen immer ihre Quellabschnitte – falsche Antworten werden dadurch sichtbar.",
        "Optionales Cloud-Routing nur für Dokumente, die ausdrücklich als unkritisch markiert sind.",
      ],
    },
  },
};

const th: ProjectsContent = {
  meta: {
    title: "โปรเจกต์",
    description:
      "ผลงานที่คัดมาของชัยพล — เว็บไซต์ที่ใช้งานจริง ต้นแบบแอป Android งานระบบอัตโนมัติ และการทดลองกับ AI ทุกโปรเจกต์ติดป้ายตรงไปตรงมาว่าเป็นของจริง ต้นแบบ หรือการทดลอง",
  },
  hero: {
    eyebrow: "ผลงานที่คัดมา",
    title: "โปรเจกต์จริง",
    titleAccent: "ติดป้ายตรงไปตรงมา",
    lede: "ทุกโปรเจกต์บอกว่าตัวเองคืออะไร: ใช้งานจริง เป็นต้นแบบที่ทำงานได้ หรือเป็นการทดลองเพื่อเรียนรู้ ลิงก์ทั้งหมดชี้ไปยังสิ่งที่มีอยู่จริง ไม่มีอะไรที่แต่งขึ้น",
  },
  ui: {
    indexTitle: "สารบัญ",
    searchLabel: "ค้นหาโปรเจกต์",
    searchPlaceholder: "ค้นหา: เว็บไซต์, Android, RAG, Python…",
    filterLabel: "กรองตามหมวดหมู่",
    all: "ทั้งหมด",
    results: "{n} จาก {total}",
    empty: "ไม่พบรายการที่ตรงกัน ลองใช้คำอื่นหรือล้างตัวกรอง",
    reset: "ล้างตัวกรอง",
    columns: { project: "โปรเจกต์", service: "หมวดหมู่", type: "สถานะ" },
    jump: "ไปที่โปรเจกต์",
  },
  kind: {
    live: "โปรเจกต์ที่ใช้งานจริง",
    prototype: "ต้นแบบ",
    experiment: "โปรเจกต์ทดลอง",
    learning: "โปรเจกต์เรียนรู้",
    concept: "โปรเจกต์แนวคิด",
    architecture: "แนวคิด / สถาปัตยกรรมเชิงทดลอง",
  },
  detail: {
    problem: "ปัญหา",
    solution: "แนวทาง",
    decisions: "การตัดสินใจสำคัญ",
    stack: "สแตก",
    previewNote: "ภาพจำลองเพื่ออธิบาย ไม่ใช่ภาพหน้าจอจริง",
    circuitNote: "วงจรจริงของเว็บไซต์นี้ที่สร้างด้วย Python",
    source: "ดูซอร์สโค้ดบน GitHub",
    live: "เปิดเว็บไซต์จริง",
    before: "ก่อน",
    after: "หลัง",
  },
  categories: {
    web: "เว็บ",
    app: "แอป",
    automation: "ระบบอัตโนมัติ",
    ai: "AI",
    cloud: "คลาวด์",
  },
  disclaimer: {
    title: "วิธีอ่านป้ายกำกับ",
    body: "โปรเจกต์ที่ใช้งานจริงคือสิ่งที่ Deploy แล้วและมีคนใช้จริง ต้นแบบทำงานได้แต่ไม่ใช่ซอฟต์แวร์ระดับ Production โปรเจกต์ทดลองสร้างขึ้นเพื่อสำรวจเทคโนโลยีและเรียนรู้ มันแสดงให้เห็นวิธีทำงาน ไม่ได้บอกว่าไอเดียนั้นคือผลิตภัณฑ์ จะแสดงเฉพาะลิงก์ที่มีอยู่จริงเท่านั้น",
  },
  cta: { title: "กำลังหาคนเข้าทีมอยู่ไหม", body: "เปิดรับตำแหน่ง IT ระดับ Junior และงาน Quereinsteiger สายพัฒนาเว็บ ระบบอัตโนมัติ หรืองานดิจิทัลที่ใช้ AI เขียนมาได้เลย แล้วจะตอบกลับว่าประสบการณ์เข้ากับทีมของคุณอย่างไร" },
  projects: {
    "wat-charoen-dham": {
      tagline: "เว็บไซต์ใช้งานจริงขององค์กรพุทธในเยอรมนี สร้างและดูแลด้วยการพัฒนาโดยมี AI ช่วย",
      problem: "องค์กรต้องการเว็บไซต์ที่ทันสมัยและหลายภาษา ให้ผู้เข้าชมหากิจกรรม เวลานั่งสมาธิ และข้อมูลติดต่อได้",
      solution: "เว็บไซต์สามภาษา (เยอรมัน อังกฤษ ไทย) พร้อมประกาศกิจกรรม ข่าวสาร ข้อมูลการเยี่ยมชม และเลย์เอาต์ที่สะอาดและเข้าถึงได้ ปรับปรุงและ Deploy วนซ้ำโดยมี AI ช่วย",
      decisions: [
        "จัดเนื้อหารอบสิ่งที่ผู้เข้าชมต้องการจริง: กิจกรรม การปฏิบัติธรรม การเยี่ยมชม และการติดต่อ",
        "Routing สามภาษา (DE / EN / TH) พร้อมตัวสลับภาษาที่ชัดเจนทุกหน้า",
        "สร้างผ่าน Workflow ที่มี AI ช่วย: กำหนดความต้องการก่อน โค้ดที่สร้างขึ้นต้องอ่านและทดสอบ แล้วจึง Deploy และปรับปรุงวนซ้ำ",
      ],
    },
    "android-app": {
      tagline: "ต้นแบบแอป Android พัฒนาโดยมี AI ช่วย และเตรียมพร้อมสำหรับการเผยแพร่และทดสอบบน Google Play",
      problem: "เรียนรู้ว่าการพาแอปจริงจากโค้ดไปสู่หน้าร้านค้าและผู้ทดสอบจริงต้องทำอะไรบ้าง",
      solution: "พาแอป Android ผ่าน Workflow ของ Google Play Console จนถึงขั้น Closed Testing ทั้งการ Sign รายการในหน้าร้าน และ Release สำหรับทดสอบ",
      decisions: [
        "พัฒนาโดยมี AI ช่วย กำหนดความต้องการและโครงสร้างแอปก่อนเขียนโค้ด",
        "ไปถึงขั้น Closed Testing ใน Google Play Console",
        "ยังไม่เผยแพร่สาธารณะ หน้านี้บอกตรง ๆ ว่าทำอะไรสำเร็จบ้าง",
      ],
    },
    "this-portfolio": {
      tagline: "เว็บไซต์ที่กำลังอ่านอยู่นี้: สามภาษา Backend จริง ส่งอีเมลได้จริง และวงจรที่สร้างด้วย Python",
      problem: "พอร์ตโฟลิโอควรพิสูจน์ความสามารถในทางปฏิบัติ ไม่ใช่แค่บรรยาย",
      solution: "ระบบดีไซน์ที่ออกแบบเอง เนื้อหาแบบ Typed ทั้ง EN, DE และ TH ระบบติดต่อที่ผ่าน Validation และส่งอีเมลผ่าน Resend มีเทสต์ และ Deploy ขึ้น Vercel อย่างต่อเนื่อง",
      decisions: [
        "ใช้ Server Components เป็นค่าเริ่มต้น และใช้โค้ดฝั่ง Client เฉพาะส่วนที่ต้องโต้ตอบ หน้าเว็บจึงส่ง JavaScript น้อย",
        "วงจร AI สร้างโดยสคริปต์ Python ตอน Build แล้ว Commit เก็บไว้ ฝั่ง Production จึงไม่ต้องมี Python Runtime",
        "การส่งข้อความติดต่อเป็นบริการเดียวที่มีหลายช่องทาง ฟอร์มจะแจ้งว่าสำเร็จก็ต่อเมื่อมีช่องทางรับข้อความไปจริงเท่านั้น",
      ],
    },
    "hetzner-neon": {
      tagline: "ทดลองคลาวด์ – Hetzner & Neon ลงมือทดสอบการ Deploy บนคลาวด์ บริการแบบ Hosted และแอปที่ใช้ฐานข้อมูล",
      problem: "ทำความเข้าใจว่าแอปพลิเคชันแบบ Hosted กับฐานข้อมูลแบบ Serverless ทำงานร่วมกันอย่างไร และค่าใช้จ่ายจริงอยู่ที่เท่าไร",
      solution: "ทดลอง Deploy แอปพลิเคชันบนโครงสร้างพื้นฐานคลาวด์ของ Hetzner โดยมี Neon Serverless Postgres เป็น Backend แล้วประเมินค่าใช้จ่ายในการใช้งาน",
      decisions: [
        "ตั้งค่าเครื่องแบบ Hosted และฐานข้อมูลแบบ Serverless เชื่อมกันผ่าน Environment Variable",
        "ชั่งน้ำหนักค่าใช้จ่ายจริงเทียบกับสิ่งที่โปรเจกต์ต้องการจริง ๆ",
        "ยุติโปรเจกต์หลังประเมินค่าใช้จ่ายแล้ว บันทึกไว้เป็นการทดลองเพื่อเรียนรู้ ไม่ใช่โครงสร้างพื้นฐานสำหรับ Production",
      ],
    },
    "rag-workflow": {
      tagline: "Workflow RAG แบบทดลอง: ผู้ช่วยที่ตอบจากเอกสารโดยค้นหาข้อความที่เกี่ยวข้องก่อน",
      problem: "ผู้ใช้หาคำตอบในเอกสารยาว ๆ ไม่เจอ และโมเดลแชตเพียงอย่างเดียวจะเดาแทนการอ้างอิงแหล่งที่มา",
      solution: "Workflow แบบ Retrieval-Augmented: ค้นหาข้อความที่เกี่ยวข้องก่อน แล้วให้โมเดลตอบพร้อมลิงก์ไปยังแหล่งที่ใช้",
      decisions: [
        "ค้นหาก่อนแล้วค่อยสร้างคำตอบ ทุกคำตอบอ้างอิงข้อความที่ใช้ จึงตรวจสอบได้",
        "API Key อยู่ที่เซิร์ฟเวอร์เท่านั้น เบราว์เซอร์คุยกับ Route ที่ผ่าน Validation และมี Rate Limit",
        "ถ้าค้นหาไม่เจอข้อมูลที่เกี่ยวข้อง ผู้ช่วยจะบอกตรง ๆ แทนการเดา",
      ],
    },
    "agent-workflow": {
      tagline: "ทดลอง Agent Workflow สำรวจการประสานงานแบบ Multi-agent โดยมีขั้นตอนรีวิวโดยคนเป็นข้อบังคับ",
      problem: "โค้ดที่ AI สร้างนั้นเร็ว แต่ไม่สม่ำเสมอเมื่อความต้องการคลุมเครือและไม่มีใครตรวจผลลัพธ์",
      solution: "Orchestrator แบ่ง Brief ให้ Agent ด้าน Design, Frontend, Backend และ Test รวมงานเข้าด้วยกัน รัน CI แล้วหยุดรอที่ขั้นตอนรีวิวโดยคน",
      decisions: [
        "ทุก Agent มี Input และ Output ที่ชัดเจน ขั้นตอนที่ล้มเหลวจึงรันใหม่แยกได้",
        "เทสต์และ Type Check รันก่อนถึงมือคนรีวิว เวลารีวิวจึงใช้กับคำถามด้านการออกแบบ",
        "Agent ไม่ Merge งานของตัวเองเด็ดขาด การรีวิวโดยคนเป็นขั้นตอนบังคับ",
      ],
    },
    "automation-prototype": {
      tagline: "ต้นแบบระบบอัตโนมัติ Pipeline Python ที่เปลี่ยน PDF ใบแจ้งหนี้เป็นรายการที่ผ่านการตรวจสอบ",
      problem: "ทุกสัปดาห์ต้องมีคนพิมพ์ข้อมูลใบแจ้งหนี้ลงโปรแกรมบัญชีด้วยมือ",
      solution: "Pipeline Python ที่ตั้งเวลาไว้: อ่าน PDF ดึงข้อมูล ตรวจสอบ แล้วส่งรายการผ่าน API หลังจากมีคนอนุมัติชุดข้อมูลแล้วเท่านั้น",
      decisions: [
        "ใช้การ Parse ตามกฎก่อน ส่วน ChatGPT API ใช้เฉพาะเลย์เอาต์ที่กฎอ่านไม่ได้",
        "ทุกฟิลด์ที่ดึงมาต้องผ่าน Validation ด้วยโมเดลแบบมี Type ก่อนส่งเข้าระบบ",
        "สรุปรายวันพร้อมขั้นตอนอนุมัติ ทำให้คนเป็นผู้ตัดสินว่าอะไรจะเข้าสู่บัญชี",
      ],
    },
    "local-ai-concept": {
      tagline: "แนวคิด Local AI ระบบค้นหาเอกสารส่วนตัวที่รันบนโมเดลในเครื่อง ข้อมูลไม่ออกจากเครื่อง",
      problem: "เอกสารภายในอ่อนไหวเกินกว่าจะส่งให้บริการ Cloud AI แต่ยังต้องค้นหาได้",
      solution: "บริการ Python ที่ทำ Index เอกสารเป็น Embeddings ค้นหาข้อความที่เกี่ยวข้อง แล้วถาม Local Model Endpoint โดยมีเว็บอินเทอร์เฟซเรียบง่ายอยู่ด้านบน",
      decisions: [
        "ใช้ Endpoint ภายในที่เข้ากันได้กับ OpenAI (แบบ Ollama หรือ llama.cpp) จึงเปลี่ยนโมเดลได้โดยไม่ต้องแก้โค้ด",
        "ทุกคำตอบแสดงข้อความต้นทางที่อ้างอิง คำตอบที่ผิดจึงเห็นได้ชัด",
        "Routing ไป Cloud เป็นตัวเลือก และใช้เฉพาะเอกสารที่ระบุชัดว่าไม่อ่อนไหว",
      ],
    },
  },
};

export const projectsContent: Localized<ProjectsContent> = { en, de, th };
