import type { Localized } from "@/i18n/config";
import type { GroupId, SkillId } from "@/components/pages/skills/data";

type Item = { name: string; note: string };

const en = {
  meta: {
    title: "Toolbox",
    description: "Frontend, backend, AI-native and engineering capabilities, shown as a connected system instead of skill bars.",
  },
  hero: {
    eyebrow: "Skills",
    titlePlain: "A toolbox,",
    titleAccent: "not a scoreboard.",
    lede: "Percentages say little about how someone works. Here each capability is shown by what it connects to: choose one and follow the lines.",
    complexity: "Complexity",
  },
  map: {
    eyebrow: "Capability map",
    title: "Follow the connections",
    body: "Select a capability to see how it works with the rest of the system. The same map reads as a plain list without JavaScript.",
    inspectorHint: "Selected capability",
    groupLabel: "Group",
    worksWith: "Works with",
    connections: "{n} connections",
    listLabel: "Capabilities in {group}",
  },
  groups: {
    frontend: { name: "Frontend", blurb: "Interfaces that load fast, work for everyone and feel considered." },
    backend: { name: "Backend", blurb: "Server logic, data and APIs that stay predictable under real use." },
    ai: { name: "AI-native", blurb: "AI as an accelerator inside a disciplined engineering process." },
    engineering: { name: "Engineering", blurb: "The habits that turn working code into a product you can keep." },
  } satisfies Record<GroupId, { name: string; blurb: string }>,
  items: {
    html: { name: "HTML", note: "Semantic structure first: headings, landmarks and forms that work before any script runs." },
    css: { name: "CSS", note: "Layout, typography and spacing systems built with modern CSS instead of workarounds." },
    javascript: { name: "JavaScript", note: "The language under every interaction, written without framework crutches where it matters." },
    typescript: { name: "TypeScript", note: "Strict types that catch mistakes at build time and document intent." },
    react: { name: "React", note: "Component-driven interfaces, server components by default, client code only where needed." },
    nextjs: { name: "Next.js", note: "App Router, server rendering and route handlers in one coherent full-stack framework." },
    tailwind: { name: "Tailwind CSS", note: "Design tokens and utilities that keep a large interface consistent." },
    "responsive-ui": { name: "Responsive UI", note: "Layouts designed for small screens on purpose, not shrunk down from desktop." },
    accessibility: { name: "Accessibility", note: "Keyboard paths, focus states, contrast and semantics treated as requirements." },
    nodejs: { name: "Node.js", note: "Server-side JavaScript for APIs, tooling and scripts." },
    apis: { name: "APIs", note: "Clear request and response contracts with predictable errors." },
    serverless: { name: "Serverless", note: "Functions that scale with demand and keep operations simple." },
    databases: { name: "Databases", note: "Relational modelling in PostgreSQL, with schemas that can evolve." },
    auth: { name: "Authentication concepts", note: "Sessions, tokens and permissions understood well enough to choose safely." },
    validation: { name: "Validation", note: "Every input checked on the server against shared schemas, never trusted." },
    "backend-arch": { name: "Backend architecture", note: "Boundaries between routes, services and data that stay readable as the app grows." },
    "claude-code": { name: "Claude Code", note: "An agentic coding environment used daily for building, refactoring and reviewing." },
    "ai-engineering": { name: "AI-assisted engineering", note: "AI speeds up the work; human judgment decides what ships." },
    prompting: { name: "Structured prompting", note: "Specifications, constraints and examples instead of vague requests." },
    agents: { name: "Agent workflows", note: "Specialised agents for research, implementation and review, coordinated by a plan." },
    debugging: { name: "Debugging", note: "Reproduce, isolate, fix, then add a test, with AI as a second pair of eyes." },
    research: { name: "Automated research", note: "Comparing libraries, reading docs and summarising options before decisions." },
    "code-analysis": { name: "Code analysis", note: "Mapping unfamiliar codebases quickly and spotting risky patterns." },
    prototyping: { name: "Rapid prototyping", note: "Working drafts in hours to test an idea before investing in it." },
    automation: { name: "Workflow automation", note: "Repetitive steps scripted so attention goes to the hard parts." },
    git: { name: "Git", note: "Small, well-described commits and branches that tell the story of a change." },
    github: { name: "GitHub", note: "Pull requests, issues and CI as the shared record of the work." },
    testing: { name: "Testing", note: "Unit and integration tests around the logic that matters." },
    deployment: { name: "Deployment", note: "Automated builds, preview environments and verified production releases." },
    performance: { name: "Performance", note: "Budgets for JavaScript, images and fonts, measured rather than guessed." },
    maintainability: { name: "Maintainability", note: "Code the next person can read, change and trust." },
    architecture: { name: "Architecture", note: "Choosing structures that fit the problem and can be explained simply." },
  } satisfies Record<SkillId, Item>,
  principles: {
    eyebrow: "How it fits together",
    title: "Breadth with a spine",
    items: [
      { title: "Every layer has a reason", text: "Interface choices, data models and deployment steps are made together, so nothing is bolted on at the end." },
      { title: "AI accelerates, people decide", text: "Agents draft and explore. Tests, review and judgment decide what is accepted." },
      { title: "Built to be handed over", text: "Clear structure, types and documentation, so a project stays easy to extend after launch." },
    ],
  },
};

export type SkillsContent = typeof en;

const de: SkillsContent = {
  meta: {
    title: "Werkzeugkasten",
    description: "Frontend, Backend, KI-natives Arbeiten und Engineering-Praxis als vernetztes System statt als Skill-Balken.",
  },
  hero: {
    eyebrow: "Fähigkeiten",
    titlePlain: "Ein Werkzeugkasten,",
    titleAccent: "keine Punktetafel.",
    lede: "Prozentwerte sagen wenig darüber, wie jemand arbeitet. Hier zeigt sich jede Fähigkeit durch ihre Verbindungen: Wähle eine aus und folge den Linien.",
    complexity: "Komplexität",
  },
  map: {
    eyebrow: "Fähigkeitenkarte",
    title: "Den Verbindungen folgen",
    body: "Wähle eine Fähigkeit, um zu sehen, wie sie mit dem Rest des Systems zusammenspielt. Ohne JavaScript liest sich dieselbe Karte als einfache Liste.",
    inspectorHint: "Ausgewählte Fähigkeit",
    groupLabel: "Gruppe",
    worksWith: "Zusammenspiel mit",
    connections: "{n} Verbindungen",
    listLabel: "Fähigkeiten in {group}",
  },
  groups: {
    frontend: { name: "Frontend", blurb: "Oberflächen, die schnell laden, für alle funktionieren und durchdacht wirken." },
    backend: { name: "Backend", blurb: "Serverlogik, Daten und APIs, die im echten Betrieb berechenbar bleiben." },
    ai: { name: "KI-nativ", blurb: "KI als Beschleuniger innerhalb eines disziplinierten Engineering-Prozesses." },
    engineering: { name: "Engineering", blurb: "Die Gewohnheiten, die aus funktionierendem Code ein Produkt mit Zukunft machen." },
  },
  items: {
    html: { name: "HTML", note: "Semantische Struktur zuerst: Überschriften, Landmarks und Formulare, die schon vor jedem Skript funktionieren." },
    css: { name: "CSS", note: "Layout-, Typografie- und Abstandssysteme mit modernem CSS statt mit Behelfslösungen." },
    javascript: { name: "JavaScript", note: "Die Sprache unter jeder Interaktion, dort ohne Framework-Krücken, wo es darauf ankommt." },
    typescript: { name: "TypeScript", note: "Strikte Typen finden Fehler schon beim Build und dokumentieren die Absicht." },
    react: { name: "React", note: "Komponentenbasierte Oberflächen, standardmäßig Server Components, Client-Code nur bei Bedarf." },
    nextjs: { name: "Next.js", note: "App Router, Server-Rendering und Route Handler in einem stimmigen Full-Stack-Framework." },
    tailwind: { name: "Tailwind CSS", note: "Design-Tokens und Utilities, die auch große Oberflächen konsistent halten." },
    "responsive-ui": { name: "Responsives UI", note: "Layouts, die bewusst für kleine Bildschirme entworfen sind, nicht vom Desktop heruntergerechnet." },
    accessibility: { name: "Barrierefreiheit", note: "Tastaturwege, Fokuszustände, Kontrast und Semantik gelten als Anforderung, nicht als Extra." },
    nodejs: { name: "Node.js", note: "Serverseitiges JavaScript für APIs, Tooling und Skripte." },
    apis: { name: "APIs", note: "Klare Verträge für Anfrage und Antwort, mit vorhersehbaren Fehlern." },
    serverless: { name: "Serverless", note: "Funktionen, die mit der Nachfrage skalieren und den Betrieb einfach halten." },
    databases: { name: "Datenbanken", note: "Relationale Modellierung in PostgreSQL, mit Schemata, die sich weiterentwickeln lassen." },
    auth: { name: "Authentifizierungskonzepte", note: "Sessions, Tokens und Berechtigungen so gut verstanden, dass sich sicher entscheiden lässt." },
    validation: { name: "Validierung", note: "Jede Eingabe wird serverseitig gegen gemeinsame Schemata geprüft und nie blind vertraut." },
    "backend-arch": { name: "Backend-Architektur", note: "Klare Grenzen zwischen Routen, Services und Daten, die auch beim Wachsen lesbar bleiben." },
    "claude-code": { name: "Claude Code", note: "Eine agentische Entwicklungsumgebung, täglich im Einsatz für Aufbau, Refactoring und Review." },
    "ai-engineering": { name: "KI-gestützte Entwicklung", note: "KI beschleunigt die Arbeit; menschliches Urteil entscheidet, was live geht." },
    prompting: { name: "Strukturiertes Prompting", note: "Spezifikationen, Randbedingungen und Beispiele statt vager Anfragen." },
    agents: { name: "Agenten-Workflows", note: "Spezialisierte Agenten für Recherche, Umsetzung und Review, koordiniert durch einen Plan." },
    debugging: { name: "Debugging", note: "Reproduzieren, eingrenzen, beheben, dann einen Test ergänzen; KI dient als zweites Augenpaar." },
    research: { name: "Automatisierte Recherche", note: "Bibliotheken vergleichen, Dokumentation lesen und Optionen zusammenfassen, bevor entschieden wird." },
    "code-analysis": { name: "Code-Analyse", note: "Unbekannte Codebasen schnell erfassen und riskante Muster erkennen." },
    prototyping: { name: "Schnelles Prototyping", note: "Lauffähige Entwürfe in Stunden, um eine Idee zu prüfen, bevor viel investiert wird." },
    automation: { name: "Workflow-Automatisierung", note: "Wiederkehrende Schritte werden skriptgesteuert, damit die Aufmerksamkeit den schwierigen Teilen gehört." },
    git: { name: "Git", note: "Kleine, gut beschriebene Commits und Branches, die die Geschichte einer Änderung erzählen." },
    github: { name: "GitHub", note: "Pull Requests, Issues und CI als gemeinsame Dokumentation der Arbeit." },
    testing: { name: "Tests", note: "Unit- und Integrationstests rund um die Logik, auf die es ankommt." },
    deployment: { name: "Deployment", note: "Automatisierte Builds, Vorschauumgebungen und geprüfte Produktiv-Releases." },
    performance: { name: "Performance", note: "Budgets für JavaScript, Bilder und Schriften, gemessen statt geschätzt." },
    maintainability: { name: "Wartbarkeit", note: "Code, den die nächste Person lesen, ändern und dem sie vertrauen kann." },
    architecture: { name: "Architektur", note: "Strukturen wählen, die zum Problem passen und sich einfach erklären lassen." },
  },
  principles: {
    eyebrow: "Wie alles zusammenpasst",
    title: "Breite mit Rückgrat",
    items: [
      { title: "Jede Ebene hat einen Grund", text: "Oberfläche, Datenmodell und Deployment werden gemeinsam entschieden, nichts wird am Ende angeflanscht." },
      { title: "KI beschleunigt, Menschen entscheiden", text: "Agenten entwerfen und erkunden. Tests, Review und Urteilsvermögen entscheiden, was übernommen wird." },
      { title: "Gebaut für die Übergabe", text: "Klare Struktur, Typen und Dokumentation, damit ein Projekt auch nach dem Launch leicht erweiterbar bleibt." },
    ],
  },
};

const th: SkillsContent = {
  meta: {
    title: "เครื่องมือ",
    description: "ความสามารถด้านฟรอนต์เอนด์ แบ็กเอนด์ การทำงานแบบ AI-native และวิศวกรรม นำเสนอเป็นระบบที่เชื่อมโยงกัน ไม่ใช่แถบคะแนนทักษะ",
  },
  hero: {
    eyebrow: "ทักษะ",
    titlePlain: "กล่องเครื่องมือ",
    titleAccent: "ไม่ใช่ตารางคะแนน",
    lede: "เปอร์เซ็นต์บอกได้น้อยว่าใครทำงานอย่างไร ที่นี่แต่ละความสามารถแสดงผ่านสิ่งที่เชื่อมโยงกัน เลือกหนึ่งอย่างแล้วตามเส้นไปดูได้เลย",
    complexity: "ความซับซ้อน",
  },
  map: {
    eyebrow: "แผนที่ความสามารถ",
    title: "ตามเส้นเชื่อมโยงไป",
    body: "เลือกความสามารถหนึ่งอย่างเพื่อดูว่าทำงานร่วมกับส่วนอื่นของระบบอย่างไร หากไม่เปิด JavaScript แผนที่เดียวกันนี้ก็อ่านเป็นรายการปกติได้",
    inspectorHint: "ความสามารถที่เลือก",
    groupLabel: "กลุ่ม",
    worksWith: "ทำงานร่วมกับ",
    connections: "{n} การเชื่อมโยง",
    listLabel: "ความสามารถในกลุ่ม {group}",
  },
  groups: {
    frontend: { name: "ฟรอนต์เอนด์", blurb: "อินเทอร์เฟซที่โหลดเร็ว ใช้ได้กับทุกคน และผ่านการคิดมาอย่างดี" },
    backend: { name: "แบ็กเอนด์", blurb: "ตรรกะฝั่งเซิร์ฟเวอร์ ข้อมูล และ API ที่คาดเดาได้แม้ใช้งานจริง" },
    ai: { name: "AI-native", blurb: "ใช้ AI เป็นตัวเร่งภายในกระบวนการวิศวกรรมที่มีวินัย" },
    engineering: { name: "วิศวกรรม", blurb: "นิสัยการทำงานที่เปลี่ยนโค้ดที่ใช้ได้ให้เป็นผลิตภัณฑ์ที่อยู่ได้นาน" },
  },
  items: {
    html: { name: "HTML", note: "โครงสร้างเชิงความหมายมาก่อน หัวข้อ landmark และฟอร์มที่ใช้งานได้ตั้งแต่ก่อนสคริปต์ทำงาน" },
    css: { name: "CSS", note: "ระบบเลย์เอาต์ ตัวอักษร และระยะห่างด้วย CSS สมัยใหม่ ไม่พึ่งวิธีแก้ขัด" },
    javascript: { name: "JavaScript", note: "ภาษาเบื้องหลังทุกการโต้ตอบ เขียนเองโดยไม่พึ่งเฟรมเวิร์กในจุดที่สำคัญ" },
    typescript: { name: "TypeScript", note: "ชนิดข้อมูลแบบเข้มงวด จับข้อผิดพลาดตั้งแต่ตอนบิลด์และบอกเจตนาของโค้ด" },
    react: { name: "React", note: "อินเทอร์เฟซแบบคอมโพเนนต์ ใช้ Server Components เป็นค่าเริ่มต้น และใช้โค้ดฝั่งไคลเอนต์เท่าที่จำเป็น" },
    nextjs: { name: "Next.js", note: "App Router การเรนเดอร์ฝั่งเซิร์ฟเวอร์ และ Route Handlers ในเฟรมเวิร์ก full-stack เดียวกัน" },
    tailwind: { name: "Tailwind CSS", note: "Design tokens และ utilities ที่ช่วยให้หน้าจอขนาดใหญ่ยังคงสม่ำเสมอ" },
    "responsive-ui": { name: "Responsive UI", note: "เลย์เอาต์ที่ออกแบบสำหรับจอเล็กโดยตั้งใจ ไม่ใช่แค่ย่อลงมาจากเดสก์ท็อป" },
    accessibility: { name: "การเข้าถึงได้ (Accessibility)", note: "การใช้งานด้วยคีย์บอร์ด โฟกัส คอนทราสต์ และความหมายของโครงสร้าง ถือเป็นข้อกำหนด ไม่ใช่ส่วนเสริม" },
    nodejs: { name: "Node.js", note: "JavaScript ฝั่งเซิร์ฟเวอร์สำหรับ API เครื่องมือ และสคริปต์" },
    apis: { name: "APIs", note: "สัญญาของคำขอและคำตอบที่ชัดเจน พร้อมข้อผิดพลาดที่คาดเดาได้" },
    serverless: { name: "Serverless", note: "ฟังก์ชันที่ขยายตามความต้องการ และทำให้การดูแลระบบเรียบง่าย" },
    databases: { name: "ฐานข้อมูล", note: "การออกแบบข้อมูลเชิงสัมพันธ์ด้วย PostgreSQL พร้อมสคีมาที่พัฒนาต่อได้" },
    auth: { name: "แนวคิดการยืนยันตัวตน", note: "เข้าใจเซสชัน โทเค็น และสิทธิ์พอที่จะเลือกแนวทางได้อย่างปลอดภัย" },
    validation: { name: "การตรวจสอบข้อมูล", note: "ตรวจทุกอินพุตฝั่งเซิร์ฟเวอร์ด้วยสคีมาร่วม ไม่เชื่อข้อมูลจากภายนอกโดยอัตโนมัติ" },
    "backend-arch": { name: "สถาปัตยกรรมแบ็กเอนด์", note: "แบ่งขอบเขตระหว่างเส้นทาง บริการ และข้อมูล ให้อ่านง่ายต่อไปแม้ระบบโตขึ้น" },
    "claude-code": { name: "Claude Code", note: "สภาพแวดล้อมเขียนโค้ดแบบเอเจนต์ที่ใช้ทุกวันสำหรับสร้าง รีแฟกเตอร์ และรีวิว" },
    "ai-engineering": { name: "วิศวกรรมที่มี AI ช่วย", note: "AI ช่วยเร่งงาน ส่วนวิจารณญาณของคนเป็นผู้ตัดสินว่าอะไรขึ้นระบบจริง" },
    prompting: { name: "การเขียนพรอมต์อย่างเป็นระบบ", note: "ใช้สเปก ข้อจำกัด และตัวอย่าง แทนคำขอที่คลุมเครือ" },
    agents: { name: "เวิร์กโฟลว์เอเจนต์", note: "เอเจนต์เฉพาะทางสำหรับค้นคว้า พัฒนา และรีวิว ประสานกันด้วยแผนงาน" },
    debugging: { name: "การดีบัก", note: "ทำซ้ำ แยกสาเหตุ แก้ไข แล้วเพิ่มเทสต์ โดยมี AI เป็นอีกสายตาช่วยดู" },
    research: { name: "การค้นคว้าอัตโนมัติ", note: "เปรียบเทียบไลบรารี อ่านเอกสาร และสรุปตัวเลือกก่อนตัดสินใจ" },
    "code-analysis": { name: "การวิเคราะห์โค้ด", note: "ทำความเข้าใจโค้ดเบสที่ไม่คุ้นเคยได้เร็ว และมองเห็นรูปแบบที่เสี่ยง" },
    prototyping: { name: "การทำต้นแบบเร็ว", note: "ร่างที่ใช้งานได้ภายในไม่กี่ชั่วโมง เพื่อทดสอบไอเดียก่อนลงทุนจริง" },
    automation: { name: "การทำเวิร์กโฟลว์อัตโนมัติ", note: "เขียนสคริปต์ให้ขั้นตอนที่ทำซ้ำ เพื่อให้เวลาไปอยู่กับส่วนที่ยากจริง" },
    git: { name: "Git", note: "คอมมิตเล็ก ๆ ที่อธิบายชัดเจน และบรานช์ที่เล่าเรื่องราวของการเปลี่ยนแปลง" },
    github: { name: "GitHub", note: "Pull Request, Issue และ CI เป็นบันทึกร่วมของงาน" },
    testing: { name: "การทดสอบ", note: "เทสต์หน่วยและเทสต์การทำงานร่วมกันรอบตรรกะที่สำคัญ" },
    deployment: { name: "การดีพลอย", note: "บิลด์อัตโนมัติ สภาพแวดล้อมพรีวิว และการปล่อยขึ้นระบบจริงที่ผ่านการตรวจสอบ" },
    performance: { name: "ประสิทธิภาพ", note: "กำหนดงบสำหรับ JavaScript รูปภาพ และฟอนต์ โดยวัดผลจริง ไม่ใช้การเดา" },
    maintainability: { name: "การดูแลรักษาได้ง่าย", note: "โค้ดที่คนถัดไปอ่าน แก้ไข และไว้ใจได้" },
    architecture: { name: "สถาปัตยกรรม", note: "เลือกโครงสร้างที่เหมาะกับปัญหาและอธิบายได้ง่าย" },
  },
  principles: {
    eyebrow: "ทุกอย่างเข้ากันอย่างไร",
    title: "กว้าง แต่มีแกนกลาง",
    items: [
      { title: "ทุกชั้นมีเหตุผล", text: "ตัดสินใจเรื่องอินเทอร์เฟซ โมเดลข้อมูล และการดีพลอยไปพร้อมกัน ไม่มีอะไรถูกแปะเพิ่มตอนท้าย" },
      { title: "AI เร่งงาน คนเป็นผู้ตัดสิน", text: "เอเจนต์ร่างและสำรวจทางเลือก ส่วนเทสต์ การรีวิว และวิจารณญาณเป็นตัวตัดสินว่าอะไรถูกรับไว้" },
      { title: "สร้างมาเพื่อส่งมอบต่อ", text: "โครงสร้าง ชนิดข้อมูล และเอกสารที่ชัดเจน ทำให้โปรเจกต์ขยายต่อได้ง่ายแม้หลังเปิดใช้งาน" },
    ],
  },
};

export const skillsContent: Localized<SkillsContent> = { en, de, th };
