import type { Localized } from "@/i18n/config";
import type { ContactErrorCode } from "@/lib/contact/schema";

const en = {
  meta: {
    title: "Backend & Systems",
    description: "A real contact backend with Zod validation, spam protection and storage, a live health endpoint and public GitHub data, explained end to end.",
  },
  hero: {
    eyebrow: "Backend & Systems",
    title: "The part you don't see, working in the open.",
    lede: "This site has a real server side. The form below posts to a validated Server Action, and the panels beneath show the same system running live.",
    complexity: "Complexity",
  },
  contact: {
    eyebrow: "Contact",
    title: "Tell me about your project.",
    body: "Share what you want to build, the rough scope and any timing. You get a clear reply about approach and next steps.",
    facts: ["Every field is validated on the server", "Hidden spam trap and rate limiting", "Your message is sent only to me"],
    labels: {
      name: "Name",
      email: "Email",
      company: "Company",
      projectType: "Project type",
      budget: "Budget",
      message: "Message",
      language: "Preferred language",
      consent: "I agree that my details are used to reply to this enquiry.",
      optional: "optional",
    },
    placeholders: { name: "Your name", email: "you@company.com", company: "Company or team", message: "What are you building, and what would a good outcome look like?" },
    select: "Select…",
    projectTypes: { website: "Business website", webapp: "Web application", saas: "SaaS product", ecommerce: "E-commerce", ai: "AI workflow or tool", other: "Something else" },
    budgets: { "under-1k": "Under 1,000 USD", "1k-5k": "1,000 – 5,000 USD", "5k-15k": "5,000 – 15,000 USD", "15k-plus": "15,000 USD and up", unsure: "Not sure yet" },
    languages: { en: "English", de: "Deutsch", th: "ไทย" },
    submit: "Send message",
    sending: "Sending…",
    success: { title: "Message sent", body: "Thank you. I'll reply as soon as I can, in your preferred language.", again: "Send another message" },
    states: {
      invalid: "Please check the highlighted fields.",
      rateLimited: "Too many messages in a short time. Please try again in {minutes} minute(s).",
      unavailable: "Messages can't be received right now.",
      unavailableMail: "Please write to me directly:",
      error: "Something went wrong on the server. Please try again in a moment.",
    },
    errors: {
      "name.short": "Please enter your name (at least 2 characters).",
      "name.long": "The name is too long (maximum 100 characters).",
      "email.invalid": "Please enter a valid email address.",
      "email.long": "The email address is too long.",
      "company.long": "The company name is too long (maximum 120 characters).",
      "projectType.invalid": "Please choose a project type.",
      "budget.invalid": "Please choose one of the budget ranges.",
      "message.short": "Please describe your project in at least 20 characters.",
      "message.long": "The message is too long (maximum 4,000 characters).",
      "language.invalid": "Please choose a language.",
      "consent.required": "Please confirm to continue.",
    } satisfies Record<ContactErrorCode, string>,
  },
  architecture: {
    eyebrow: "Architecture",
    title: "What happens when you press send.",
    lede: "One request, six steps. Each one has a single responsibility and a clear failure mode.",
    summary: "Diagram: the browser submits the form to Next.js, which calls a Server Action. The action validates the input with Zod, stores it in PostgreSQL and notifies a webhook, then returns a response to the browser.",
    steps: [
      { tag: "Client", title: "Browser", body: "Checks the fields instantly with the same schema, then submits." },
      { tag: "Framework", title: "Next.js", body: "App Router receives the request and runs server code." },
      { tag: "Entry point", title: "Server Action", body: "Reads the form data, applies the spam trap and rate limit." },
      { tag: "Validation", title: "Zod", body: "Rejects anything malformed. Errors are codes, translated in the UI." },
      { tag: "Storage", title: "PostgreSQL + webhook", body: "Saved to a contact_submissions table and forwarded if a webhook is set." },
      { tag: "Result", title: "Response", body: "Typed state back to the form: success, field errors or a safe error." },
    ],
    guards: { title: "Built-in protections", items: ["Honeypot field", "Rate limit per visitor", "Input validated twice", "No secrets in the client", "Safe error messages"] },
    sideRoute: "Also on the server: GET /api/health, a Route Handler that reports status.",
  },
  health: {
    eyebrow: "Live endpoint",
    title: "/api/health, called from your browser right now.",
    body: "A Route Handler returns safe, non-secret runtime information. The request below is real.",
    loading: "Calling the endpoint…",
    error: "The endpoint could not be reached.",
    refresh: "Call again",
    fields: {
      status: "Status",
      service: "Service",
      time: "Server time",
      node: "Node.js",
      region: "Region",
      environment: "Environment",
      commit: "Commit",
      database: "Database",
      webhook: "Contact webhook",
    },
    values: {
      ok: "Healthy",
      degraded: "Degraded",
      connected: "Connected",
      unreachable: "Unreachable",
      "not-configured": "Not configured",
      configured: "Configured",
      local: "Local",
      none: "n/a",
    } as Record<string, string>,
    httpStatus: "HTTP {status}",
  },
  github: {
    eyebrow: "Public GitHub",
    title: "Selected public repositories.",
    lede: "Fetched on the server from the public GitHub API and cached for an hour.",
    empty: "No public repositories to show yet.",
    failed: "GitHub data is temporarily unavailable.",
    profile: "View GitHub profile",
    updated: "Updated",
    stars: "stars",
    noDescription: "No description yet.",
  },
};

export type SystemsContent = typeof en;

const de: SystemsContent = {
  meta: {
    title: "Backend & Systeme",
    description: "Ein echtes Kontakt-Backend mit Zod-Validierung, Spamschutz und Speicherung, ein Live-Health-Endpunkt und öffentliche GitHub-Daten, durchgängig erklärt.",
  },
  hero: {
    eyebrow: "Backend & Systeme",
    title: "Der unsichtbare Teil, offen bei der Arbeit.",
    lede: "Diese Website hat eine echte Serverseite. Das Formular unten sendet an eine validierte Server Action, und die Bereiche darunter zeigen dasselbe System live.",
    complexity: "Komplexität",
  },
  contact: {
    eyebrow: "Kontakt",
    title: "Erzähl mir von deinem Projekt.",
    body: "Schildere, was du bauen möchtest, den groben Umfang und den zeitlichen Rahmen. Du erhältst eine klare Antwort zu Vorgehen und nächsten Schritten.",
    facts: ["Jedes Feld wird serverseitig geprüft", "Versteckte Spam-Falle und Ratenbegrenzung", "Deine Nachricht geht nur an mich"],
    labels: {
      name: "Name",
      email: "E-Mail",
      company: "Unternehmen",
      projectType: "Projektart",
      budget: "Budget",
      message: "Nachricht",
      language: "Bevorzugte Sprache",
      consent: "Ich bin damit einverstanden, dass meine Angaben zur Beantwortung dieser Anfrage verwendet werden.",
      optional: "optional",
    },
    placeholders: { name: "Dein Name", email: "du@firma.de", company: "Unternehmen oder Team", message: "Was baust du, und wie sähe ein gutes Ergebnis aus?" },
    select: "Auswählen…",
    projectTypes: { website: "Unternehmenswebsite", webapp: "Webanwendung", saas: "SaaS-Produkt", ecommerce: "E-Commerce", ai: "KI-Workflow oder -Tool", other: "Etwas anderes" },
    budgets: { "under-1k": "Unter 1.000 USD", "1k-5k": "1.000 – 5.000 USD", "5k-15k": "5.000 – 15.000 USD", "15k-plus": "Ab 15.000 USD", unsure: "Noch unklar" },
    languages: { en: "English", de: "Deutsch", th: "ไทย" },
    submit: "Nachricht senden",
    sending: "Wird gesendet…",
    success: { title: "Nachricht gesendet", body: "Danke! Die Antwort kommt so bald wie möglich, in deiner bevorzugten Sprache.", again: "Weitere Nachricht senden" },
    states: {
      invalid: "Bitte die markierten Felder prüfen.",
      rateLimited: "Zu viele Nachrichten in kurzer Zeit. Bitte in {minutes} Minute(n) erneut versuchen.",
      unavailable: "Nachrichten können derzeit nicht empfangen werden.",
      unavailableMail: "Bitte schreibe direkt an:",
      error: "Auf dem Server ist etwas schiefgelaufen. Bitte gleich noch einmal versuchen.",
    },
    errors: {
      "name.short": "Bitte gib deinen Namen an (mindestens 2 Zeichen).",
      "name.long": "Der Name ist zu lang (höchstens 100 Zeichen).",
      "email.invalid": "Bitte gib eine gültige E-Mail-Adresse an.",
      "email.long": "Die E-Mail-Adresse ist zu lang.",
      "company.long": "Der Firmenname ist zu lang (höchstens 120 Zeichen).",
      "projectType.invalid": "Bitte wähle eine Projektart.",
      "budget.invalid": "Bitte wähle einen der Budgetbereiche.",
      "message.short": "Bitte beschreibe dein Projekt mit mindestens 20 Zeichen.",
      "message.long": "Die Nachricht ist zu lang (höchstens 4.000 Zeichen).",
      "language.invalid": "Bitte wähle eine Sprache.",
      "consent.required": "Bitte bestätige, um fortzufahren.",
    },
  },
  architecture: {
    eyebrow: "Architektur",
    title: "Was passiert, wenn du auf Senden drückst.",
    lede: "Eine Anfrage, sechs Schritte. Jeder hat genau eine Aufgabe und einen klaren Fehlerfall.",
    summary: "Diagramm: Der Browser sendet das Formular an Next.js, das eine Server Action aufruft. Die Action validiert die Eingabe mit Zod, speichert sie in PostgreSQL, benachrichtigt einen Webhook und gibt dem Browser eine Antwort zurück.",
    steps: [
      { tag: "Client", title: "Browser", body: "Prüft die Felder sofort mit demselben Schema und sendet dann ab." },
      { tag: "Framework", title: "Next.js", body: "Der App Router nimmt die Anfrage entgegen und führt Servercode aus." },
      { tag: "Einstiegspunkt", title: "Server Action", body: "Liest die Formulardaten, wendet Spam-Falle und Ratenbegrenzung an." },
      { tag: "Validierung", title: "Zod", body: "Weist alles Fehlerhafte ab. Fehler sind Codes, die die Oberfläche übersetzt." },
      { tag: "Speicherung", title: "PostgreSQL + Webhook", body: "Gespeichert in der Tabelle contact_submissions und bei gesetztem Webhook weitergeleitet." },
      { tag: "Ergebnis", title: "Antwort", body: "Typisierter Zustand zurück ans Formular: Erfolg, Feldfehler oder ein sicherer Fehler." },
    ],
    guards: { title: "Eingebaute Schutzmaßnahmen", items: ["Honeypot-Feld", "Ratenbegrenzung pro Besuch", "Eingaben doppelt geprüft", "Keine Geheimnisse im Client", "Sichere Fehlermeldungen"] },
    sideRoute: "Ebenfalls serverseitig: GET /api/health, ein Route Handler, der den Status meldet.",
  },
  health: {
    eyebrow: "Live-Endpunkt",
    title: "/api/health, gerade aus deinem Browser aufgerufen.",
    body: "Ein Route Handler liefert sichere Laufzeitinformationen ohne Geheimnisse. Die Anfrage unten ist echt.",
    loading: "Endpunkt wird aufgerufen…",
    error: "Der Endpunkt war nicht erreichbar.",
    refresh: "Erneut aufrufen",
    fields: {
      status: "Status",
      service: "Dienst",
      time: "Serverzeit",
      node: "Node.js",
      region: "Region",
      environment: "Umgebung",
      commit: "Commit",
      database: "Datenbank",
      webhook: "Kontakt-Webhook",
    },
    values: {
      ok: "In Ordnung",
      degraded: "Eingeschränkt",
      connected: "Verbunden",
      unreachable: "Nicht erreichbar",
      "not-configured": "Nicht konfiguriert",
      configured: "Konfiguriert",
      local: "Lokal",
      none: "k. A.",
    },
    httpStatus: "HTTP {status}",
  },
  github: {
    eyebrow: "Öffentliches GitHub",
    title: "Ausgewählte öffentliche Repositories.",
    lede: "Serverseitig aus der öffentlichen GitHub-API geladen und eine Stunde zwischengespeichert.",
    empty: "Noch keine öffentlichen Repositories vorhanden.",
    failed: "Die GitHub-Daten sind vorübergehend nicht verfügbar.",
    profile: "GitHub-Profil ansehen",
    updated: "Aktualisiert",
    stars: "Sterne",
    noDescription: "Noch keine Beschreibung.",
  },
};

const th: SystemsContent = {
  meta: {
    title: "แบ็กเอนด์และระบบ",
    description: "ระบบติดต่อที่ทำงานจริง ตรวจสอบด้วย Zod มีการป้องกันสแปมและจัดเก็บข้อมูล พร้อม Health Endpoint แบบสด และข้อมูล GitHub สาธารณะ อธิบายครบทุกขั้นตอน",
  },
  hero: {
    eyebrow: "แบ็กเอนด์และระบบ",
    title: "ส่วนที่มองไม่เห็น เปิดให้ดูการทำงานจริง",
    lede: "เว็บไซต์นี้มีฝั่งเซิร์ฟเวอร์จริง แบบฟอร์มด้านล่างส่งข้อมูลไปยัง Server Action ที่ตรวจสอบครบถ้วน และส่วนถัดไปแสดงระบบเดียวกันที่กำลังทำงานอยู่",
    complexity: "ความซับซ้อน",
  },
  contact: {
    eyebrow: "ติดต่อ",
    title: "เล่าโปรเจกต์ของคุณให้ฟัง",
    body: "บอกสิ่งที่อยากสร้าง ขอบเขตคร่าว ๆ และกรอบเวลา จะได้คำตอบที่ชัดเจนเรื่องแนวทางและขั้นตอนถัดไป",
    facts: ["ทุกช่องถูกตรวจสอบที่ฝั่งเซิร์ฟเวอร์", "มีกับดักสแปมที่ซ่อนอยู่และจำกัดอัตราการส่ง", "ข้อความของคุณถึงเจ้าของเว็บไซต์เท่านั้น"],
    labels: {
      name: "ชื่อ",
      email: "อีเมล",
      company: "บริษัท",
      projectType: "ประเภทโปรเจกต์",
      budget: "งบประมาณ",
      message: "ข้อความ",
      language: "ภาษาที่สะดวก",
      consent: "ยินยอมให้ใช้ข้อมูลที่กรอกเพื่อตอบกลับคำขอนี้",
      optional: "ไม่บังคับ",
    },
    placeholders: { name: "ชื่อของคุณ", email: "you@company.com", company: "บริษัทหรือทีม", message: "กำลังสร้างอะไรอยู่ และผลลัพธ์ที่ดีควรเป็นอย่างไร" },
    select: "เลือก…",
    projectTypes: { website: "เว็บไซต์ธุรกิจ", webapp: "เว็บแอปพลิเคชัน", saas: "ผลิตภัณฑ์ SaaS", ecommerce: "อีคอมเมิร์ซ", ai: "เวิร์กโฟลว์หรือเครื่องมือ AI", other: "อื่น ๆ" },
    budgets: { "under-1k": "ต่ำกว่า 1,000 USD", "1k-5k": "1,000 – 5,000 USD", "5k-15k": "5,000 – 15,000 USD", "15k-plus": "15,000 USD ขึ้นไป", unsure: "ยังไม่แน่ใจ" },
    languages: { en: "English", de: "Deutsch", th: "ไทย" },
    submit: "ส่งข้อความ",
    sending: "กำลังส่ง…",
    success: { title: "ส่งข้อความแล้ว", body: "ขอบคุณ จะตอบกลับโดยเร็วที่สุดเป็นภาษาที่เลือกไว้", again: "ส่งข้อความอีกครั้ง" },
    states: {
      invalid: "โปรดตรวจสอบช่องที่ไฮไลต์ไว้",
      rateLimited: "ส่งข้อความถี่เกินไป โปรดลองใหม่ในอีก {minutes} นาที",
      unavailable: "ขณะนี้ยังรับข้อความไม่ได้",
      unavailableMail: "โปรดส่งอีเมลมาที่:",
      error: "เซิร์ฟเวอร์เกิดข้อผิดพลาด โปรดลองใหม่อีกครั้งในอีกสักครู่",
    },
    errors: {
      "name.short": "โปรดกรอกชื่อ (อย่างน้อย 2 ตัวอักษร)",
      "name.long": "ชื่อยาวเกินไป (สูงสุด 100 ตัวอักษร)",
      "email.invalid": "โปรดกรอกอีเมลให้ถูกต้อง",
      "email.long": "อีเมลยาวเกินไป",
      "company.long": "ชื่อบริษัทยาวเกินไป (สูงสุด 120 ตัวอักษร)",
      "projectType.invalid": "โปรดเลือกประเภทโปรเจกต์",
      "budget.invalid": "โปรดเลือกช่วงงบประมาณ",
      "message.short": "โปรดอธิบายโปรเจกต์อย่างน้อย 20 ตัวอักษร",
      "message.long": "ข้อความยาวเกินไป (สูงสุด 4,000 ตัวอักษร)",
      "language.invalid": "โปรดเลือกภาษา",
      "consent.required": "โปรดยืนยันเพื่อดำเนินการต่อ",
    },
  },
  architecture: {
    eyebrow: "สถาปัตยกรรม",
    title: "เกิดอะไรขึ้นเมื่อกดส่ง",
    lede: "หนึ่งคำขอ หกขั้นตอน แต่ละขั้นมีหน้าที่เดียวและรู้ชัดว่าล้มเหลวได้อย่างไร",
    summary: "แผนภาพ: เบราว์เซอร์ส่งฟอร์มไปยัง Next.js ซึ่งเรียก Server Action จากนั้น Action ตรวจสอบข้อมูลด้วย Zod บันทึกลง PostgreSQL แจ้ง Webhook แล้วส่งผลลัพธ์กลับไปยังเบราว์เซอร์",
    steps: [
      { tag: "ไคลเอนต์", title: "เบราว์เซอร์", body: "ตรวจช่องกรอกทันทีด้วยสคีมาเดียวกัน แล้วจึงส่ง" },
      { tag: "เฟรมเวิร์ก", title: "Next.js", body: "App Router รับคำขอและรันโค้ดฝั่งเซิร์ฟเวอร์" },
      { tag: "จุดเข้า", title: "Server Action", body: "อ่านข้อมูลฟอร์ม ใช้กับดักสแปมและจำกัดอัตราการส่ง" },
      { tag: "การตรวจสอบ", title: "Zod", body: "ปฏิเสธข้อมูลที่ผิดรูปแบบ ข้อผิดพลาดเป็นรหัสที่ UI แปลเป็นภาษาผู้ใช้" },
      { tag: "การจัดเก็บ", title: "PostgreSQL + Webhook", body: "บันทึกลงตาราง contact_submissions และส่งต่อไปยัง Webhook หากตั้งค่าไว้" },
      { tag: "ผลลัพธ์", title: "การตอบกลับ", body: "สถานะที่มีชนิดข้อมูลกลับไปที่ฟอร์ม ได้แก่ สำเร็จ ข้อผิดพลาดรายช่อง หรือข้อผิดพลาดที่ปลอดภัย" },
    ],
    guards: { title: "การป้องกันในตัว", items: ["ช่อง Honeypot", "จำกัดอัตราการส่งต่อผู้เข้าชม", "ตรวจสอบข้อมูลสองครั้ง", "ไม่มีความลับฝั่งไคลเอนต์", "ข้อความผิดพลาดที่ปลอดภัย"] },
    sideRoute: "ฝั่งเซิร์ฟเวอร์ยังมี GET /api/health ซึ่งเป็น Route Handler สำหรับรายงานสถานะ",
  },
  health: {
    eyebrow: "Endpoint แบบสด",
    title: "/api/health ที่เพิ่งถูกเรียกจากเบราว์เซอร์ของคุณ",
    body: "Route Handler ส่งข้อมูลรันไทม์ที่ปลอดภัยและไม่มีความลับ คำขอด้านล่างเป็นของจริง",
    loading: "กำลังเรียก Endpoint…",
    error: "เรียก Endpoint ไม่สำเร็จ",
    refresh: "เรียกอีกครั้ง",
    fields: {
      status: "สถานะ",
      service: "บริการ",
      time: "เวลาเซิร์ฟเวอร์",
      node: "Node.js",
      region: "ภูมิภาค",
      environment: "สภาพแวดล้อม",
      commit: "คอมมิต",
      database: "ฐานข้อมูล",
      webhook: "Webhook การติดต่อ",
    },
    values: {
      ok: "ปกติ",
      degraded: "ทำงานบางส่วน",
      connected: "เชื่อมต่อแล้ว",
      unreachable: "เข้าถึงไม่ได้",
      "not-configured": "ยังไม่ได้ตั้งค่า",
      configured: "ตั้งค่าแล้ว",
      local: "ในเครื่อง",
      none: "ไม่มี",
    },
    httpStatus: "HTTP {status}",
  },
  github: {
    eyebrow: "GitHub สาธารณะ",
    title: "รีโพซิทอรีสาธารณะที่คัดมา",
    lede: "ดึงจาก GitHub API สาธารณะที่ฝั่งเซิร์ฟเวอร์ และแคชไว้หนึ่งชั่วโมง",
    empty: "ยังไม่มีรีโพซิทอรีสาธารณะให้แสดง",
    failed: "ขณะนี้ข้อมูลจาก GitHub ยังใช้งานไม่ได้",
    profile: "ดูโปรไฟล์ GitHub",
    updated: "อัปเดต",
    stars: "ดาว",
    noDescription: "ยังไม่มีคำอธิบาย",
  },
};

export const systemsContent: Localized<SystemsContent> = { en, de, th };
