import type { Localized } from "@/i18n/config";

type Stage = { mark: string; tag: string; title: string; body: string; file: string };
type Channel = { title: string; role: string; body: string; file: string };

const en = {
  meta: {
    title: "Systems",
    description: "The real architecture of this portfolio: Next.js, a validated Server Action, Resend email delivery, optional PostgreSQL, GitHub and Vercel — with a live health endpoint.",
  },
  hero: {
    eyebrow: "Systems · architecture sheet",
    title: "The real architecture behind this site.",
    lede: "Not a mock-up. Every block on this sheet maps to a file in the repository, and the live panels call the production server.",
  },
  titleBlock: {
    project: "Project",
    projectValue: "Portfolio — web × AI",
    drawing: "Drawing",
    drawingValue: "System architecture",
    revision: "Revision",
    scale: "Scale",
    scaleValue: "NTS · not to scale",
    routes: "Routes",
    routesValue: "{routes} localized pages + 1 API",
    built: "Drawn",
    builtValue: "at build time",
  },
  request: {
    eyebrow: "Request path",
    title: "One enquiry, end to end.",
    lede: "What happens when someone sends the contact form. Each stage has one responsibility and one failure mode.",
    client: "Client",
    server: "Server · Vercel Functions",
    summary:
      "Diagram: the browser checks the form and submits it to Next.js. A Server Action validates it with Zod, applies a honeypot and rate limit, then hands it to a delivery service that sends a Resend email and optionally writes to PostgreSQL or a webhook. A typed result returns to the browser.",
    stages: [
      { mark: "A", tag: "Browser", title: "Contact form", body: "Checks every field instantly with the same Zod schema the server uses.", file: "components/pages/contact/ContactForm.tsx" },
      { mark: "B", tag: "Framework", title: "Next.js App Router", body: "Static, localized pages. src/proxy.ts sends unprefixed URLs to /en, /de or /th.", file: "app/[locale] · proxy.ts" },
      { mark: "C", tag: "Entry", title: "Server Action", body: "submitContact receives the form data. GET /api/health is a Route Handler next to it.", file: "app/actions/contact.ts" },
      { mark: "D", tag: "Guard", title: "Zod · honeypot · rate limit", body: "Malformed input is rejected with error codes the UI translates. Bots fill the hidden field and learn nothing.", file: "lib/contact/schema.ts" },
      { mark: "E", tag: "Delivery", title: "Delivery service", body: "Sends to every configured channel. Reports success only when at least one accepts the message.", file: "lib/contact/deliver.ts" },
      { mark: "F", tag: "Result", title: "Typed response", body: "success · invalid · rate-limited · unavailable · error. Never a provider error message.", file: "app/actions/contact.ts" },
    ] satisfies Stage[],
    channelsLabel: "Delivery channels",
    channels: [
      { title: "Resend email", role: "Primary", body: "Notification to the owner's inbox with Reply-To set to the sender. HTML-escaped template, API key on the server only.", file: "lib/contact/email.ts" },
      { title: "PostgreSQL", role: "Optional", body: "Neon via Vercel. Writes to contact_submissions, created on first use.", file: "lib/contact/store.ts" },
      { title: "Webhook", role: "Optional", body: "JSON to any Slack- or Discord-compatible URL.", file: "lib/contact/deliver.ts" },
    ] satisfies Channel[],
  },
  pipeline: {
    eyebrow: "Delivery pipeline",
    title: "From commit to production.",
    lede: "How code reaches the live site, including the one part written in Python.",
    nodes: [
      { mark: "P", tag: "Build-time artifact", title: "Python generator", body: "scripts/generate_ai_circuit.py lays out and routes the AI circuit, then writes JSON and SVG. The output is committed, so production never runs Python.", file: "scripts/generate_ai_circuit.py" },
      { mark: "G", tag: "Source", title: "GitHub", body: "Public repository, main branch. Every push to main triggers a production deployment.", file: "chaiyaphol752/Portfolio-" },
      { mark: "V", tag: "Build", title: "Vercel build", body: "next build type-checks the code and prerenders every localized page as static HTML.", file: "next build" },
      { mark: "R", tag: "Runtime", title: "Vercel runtime", body: "Static pages from the CDN. The Server Action and /api/health run as functions.", file: "Vercel Functions" },
    ] satisfies Stage[],
  },
  security: {
    eyebrow: "Notes",
    title: "Security, as built.",
    items: [
      "Security headers — HSTS, X-Frame-Options DENY, nosniff, Referrer-Policy and Permissions-Policy — are set in next.config.ts.",
      "RESEND_API_KEY and database credentials exist only as server environment variables. The email module is marked server-only.",
      "Input is validated with Zod on the server and HTML-escaped in the notification email. Subjects are stripped of line breaks.",
      "Spam mitigation: a hidden honeypot field and a per-visitor rate limit (best effort per serverless instance).",
      "Visitors only ever see safe status messages, never provider or database errors.",
      "External links open with rel=\"noopener noreferrer\".",
    ],
  },
  health: {
    eyebrow: "Live endpoint",
    title: "/api/health, called from your browser.",
    body: "A Route Handler returns safe, non-secret runtime information — including which contact channels are configured. The request is real.",
    loading: "Calling the endpoint…",
    error: "The endpoint could not be reached.",
    refresh: "Call again",
    fields: {
      status: "Status",
      service: "Service",
      time: "Server time",
      node: "Node.js",
      region: "Region",
      environment: "Environment",
      commit: "Commit",
      database: "Database",
      email: "Email (Resend)",
      webhook: "Webhook",
      channels: "Contact channels",
    },
    values: {
      ok: "Healthy",
      degraded: "Degraded",
      connected: "Connected",
      unreachable: "Unreachable",
      "not-configured": "Not configured",
      configured: "Configured",
      "configured-test-sender": "Configured · test sender",
      local: "Local",
      none: "n/a",
    } as Record<string, string>,
    httpStatus: "HTTP {status}",
  },
  github: {
    eyebrow: "Public GitHub",
    title: "Public repositories.",
    lede: "Fetched on the server from the public GitHub API and cached for an hour.",
    empty: "No public repositories to show yet.",
    failed: "GitHub data is temporarily unavailable.",
    profile: "View GitHub profile",
    updated: "Updated",
    stars: "stars",
    noDescription: "No description yet.",
  },
  cta: {
    title: "Need a backend like this behind your site?",
    body: "Forms that really deliver, APIs, databases, email and deployment — built, tested and documented.",
    label: "Start a project",
  },
};

export type SystemsContent = typeof en;

const de: SystemsContent = {
  meta: {
    title: "Systeme",
    description: "Die echte Architektur dieses Portfolios: Next.js, eine validierte Server Action, E-Mail-Zustellung über Resend, optional PostgreSQL, GitHub und Vercel – mit Live-Health-Endpunkt.",
  },
  hero: {
    eyebrow: "Systeme · Architekturblatt",
    title: "Die echte Architektur hinter dieser Website.",
    lede: "Kein Mock-up. Jeder Block auf diesem Blatt entspricht einer Datei im Repository, und die Live-Bereiche fragen den Produktionsserver ab.",
  },
  titleBlock: {
    project: "Projekt",
    projectValue: "Portfolio — Web × KI",
    drawing: "Zeichnung",
    drawingValue: "Systemarchitektur",
    revision: "Revision",
    scale: "Maßstab",
    scaleValue: "o. M. · ohne Maßstab",
    routes: "Routen",
    routesValue: "{routes} lokalisierte Seiten + 1 API",
    built: "Erstellt",
    builtValue: "beim Build",
  },
  request: {
    eyebrow: "Request-Pfad",
    title: "Eine Anfrage, von Anfang bis Ende.",
    lede: "Was passiert, wenn jemand das Kontaktformular abschickt. Jede Stufe hat genau eine Aufgabe und einen klaren Fehlerfall.",
    client: "Client",
    server: "Server · Vercel Functions",
    summary:
      "Diagramm: Der Browser prüft das Formular und sendet es an Next.js. Eine Server Action validiert es mit Zod, wendet Honeypot und Rate-Limit an und übergibt es einem Zustelldienst, der eine E-Mail über Resend sendet und optional in PostgreSQL oder an einen Webhook schreibt. Ein typisiertes Ergebnis geht zurück an den Browser.",
    stages: [
      { mark: "A", tag: "Browser", title: "Kontaktformular", body: "Prüft jedes Feld sofort mit demselben Zod-Schema wie der Server.", file: "components/pages/contact/ContactForm.tsx" },
      { mark: "B", tag: "Framework", title: "Next.js App Router", body: "Statische, lokalisierte Seiten. src/proxy.ts leitet URLs ohne Sprachpräfix auf /en, /de oder /th um.", file: "app/[locale] · proxy.ts" },
      { mark: "C", tag: "Einstieg", title: "Server Action", body: "submitContact nimmt die Formulardaten entgegen. GET /api/health ist ein Route Handler daneben.", file: "app/actions/contact.ts" },
      { mark: "D", tag: "Schutz", title: "Zod · Honeypot · Rate-Limit", body: "Fehlerhafte Eingaben werden mit Fehlercodes abgelehnt, die die Oberfläche übersetzt. Bots füllen das versteckte Feld und erfahren nichts.", file: "lib/contact/schema.ts" },
      { mark: "E", tag: "Zustellung", title: "Zustelldienst", body: "Sendet an jeden konfigurierten Kanal. Meldet nur Erfolg, wenn mindestens einer die Nachricht annimmt.", file: "lib/contact/deliver.ts" },
      { mark: "F", tag: "Ergebnis", title: "Typisierte Antwort", body: "success · invalid · rate-limited · unavailable · error. Nie eine Fehlermeldung des Anbieters.", file: "app/actions/contact.ts" },
    ],
    channelsLabel: "Zustellkanäle",
    channels: [
      { title: "E-Mail über Resend", role: "Primär", body: "Benachrichtigung an den eigenen Posteingang, Reply-To auf den Absender gesetzt. HTML-escapte Vorlage, API-Key nur auf dem Server.", file: "lib/contact/email.ts" },
      { title: "PostgreSQL", role: "Optional", body: "Neon über Vercel. Schreibt in contact_submissions, beim ersten Aufruf angelegt.", file: "lib/contact/store.ts" },
      { title: "Webhook", role: "Optional", body: "JSON an eine beliebige Slack- oder Discord-kompatible URL.", file: "lib/contact/deliver.ts" },
    ],
  },
  pipeline: {
    eyebrow: "Auslieferung",
    title: "Vom Commit bis zur Produktion.",
    lede: "Wie Code auf die Live-Website kommt – einschließlich des Teils, der in Python geschrieben ist.",
    nodes: [
      { mark: "P", tag: "Build-Artefakt", title: "Python-Generator", body: "scripts/generate_ai_circuit.py berechnet Layout und Leiterbahnen des KI-Schaltplans und schreibt JSON und SVG. Die Ausgabe ist eingecheckt, Produktion führt nie Python aus.", file: "scripts/generate_ai_circuit.py" },
      { mark: "G", tag: "Quelle", title: "GitHub", body: "Öffentliches Repository, Branch main. Jeder Push auf main löst ein Produktions-Deployment aus.", file: "chaiyaphol752/Portfolio-" },
      { mark: "V", tag: "Build", title: "Vercel-Build", body: "next build prüft die Typen und rendert jede lokalisierte Seite vorab als statisches HTML.", file: "next build" },
      { mark: "R", tag: "Laufzeit", title: "Vercel-Laufzeit", body: "Statische Seiten aus dem CDN. Die Server Action und /api/health laufen als Functions.", file: "Vercel Functions" },
    ],
  },
  security: {
    eyebrow: "Hinweise",
    title: "Sicherheit, wie gebaut.",
    items: [
      "Security-Header – HSTS, X-Frame-Options DENY, nosniff, Referrer-Policy und Permissions-Policy – sind in next.config.ts gesetzt.",
      "RESEND_API_KEY und Datenbank-Zugangsdaten existieren nur als Server-Umgebungsvariablen. Das E-Mail-Modul ist als server-only markiert.",
      "Eingaben werden auf dem Server mit Zod validiert und in der Benachrichtigungs-E-Mail HTML-escaped. Betreffzeilen werden von Zeilenumbrüchen befreit.",
      "Spamschutz: ein verstecktes Honeypot-Feld und ein Rate-Limit pro Besucher (best effort pro Serverless-Instanz).",
      "Besucher sehen nur sichere Statusmeldungen, nie Fehler von Anbieter oder Datenbank.",
      "Externe Links öffnen mit rel=\"noopener noreferrer\".",
    ],
  },
  health: {
    eyebrow: "Live-Endpunkt",
    title: "/api/health, direkt aus deinem Browser.",
    body: "Ein Route Handler liefert sichere, nicht geheime Laufzeitinformationen – auch, welche Kontaktkanäle konfiguriert sind. Die Anfrage ist echt.",
    loading: "Endpunkt wird abgefragt…",
    error: "Der Endpunkt ist nicht erreichbar.",
    refresh: "Erneut abfragen",
    fields: {
      status: "Status",
      service: "Dienst",
      time: "Serverzeit",
      node: "Node.js",
      region: "Region",
      environment: "Umgebung",
      commit: "Commit",
      database: "Datenbank",
      email: "E-Mail (Resend)",
      webhook: "Webhook",
      channels: "Kontaktkanäle",
    },
    values: {
      ok: "Gesund",
      degraded: "Eingeschränkt",
      connected: "Verbunden",
      unreachable: "Nicht erreichbar",
      "not-configured": "Nicht konfiguriert",
      configured: "Konfiguriert",
      "configured-test-sender": "Konfiguriert · Test-Absender",
      local: "Lokal",
      none: "–",
    } as Record<string, string>,
    httpStatus: "HTTP {status}",
  },
  github: {
    eyebrow: "Öffentliches GitHub",
    title: "Öffentliche Repositories.",
    lede: "Serverseitig über die öffentliche GitHub-API abgerufen und eine Stunde zwischengespeichert.",
    empty: "Noch keine öffentlichen Repositories vorhanden.",
    failed: "GitHub-Daten sind vorübergehend nicht verfügbar.",
    profile: "GitHub-Profil ansehen",
    updated: "Aktualisiert",
    stars: "Sterne",
    noDescription: "Noch keine Beschreibung.",
  },
  cta: {
    title: "So ein Backend für deine Website?",
    body: "Formulare, die wirklich zustellen, APIs, Datenbanken, E-Mail und Deployment – gebaut, getestet und dokumentiert.",
    label: "Projekt starten",
  },
};

const th: SystemsContent = {
  meta: {
    title: "ระบบ",
    description: "สถาปัตยกรรมจริงของพอร์ตโฟลิโอนี้ ทั้ง Next.js, Server Action ที่ตรวจสอบข้อมูล, การส่งอีเมลผ่าน Resend, PostgreSQL แบบเลือกได้, GitHub และ Vercel พร้อม Health Endpoint แบบสด",
  },
  hero: {
    eyebrow: "ระบบ · แบบสถาปัตยกรรม",
    title: "สถาปัตยกรรมจริงเบื้องหลังเว็บไซต์นี้",
    lede: "ไม่ใช่ภาพจำลอง ทุกบล็อกในแผ่นนี้ตรงกับไฟล์จริงใน Repository และส่วนที่แสดงผลสดเรียกเซิร์ฟเวอร์ Production จริง",
  },
  titleBlock: {
    project: "โปรเจกต์",
    projectValue: "Portfolio — Web × AI",
    drawing: "แบบ",
    drawingValue: "สถาปัตยกรรมระบบ",
    revision: "Revision",
    scale: "มาตราส่วน",
    scaleValue: "NTS · ไม่ตามมาตราส่วน",
    routes: "Routes",
    routesValue: "{routes} หน้าหลายภาษา + 1 API",
    built: "สร้างเมื่อ",
    builtValue: "ตอน Build",
  },
  request: {
    eyebrow: "เส้นทางของ Request",
    title: "หนึ่งข้อความ ตั้งแต่ต้นจนจบ",
    lede: "สิ่งที่เกิดขึ้นเมื่อมีคนส่งแบบฟอร์มติดต่อ แต่ละขั้นมีหน้าที่เดียวและกรณีผิดพลาดที่ชัดเจน",
    client: "Client",
    server: "Server · Vercel Functions",
    summary:
      "แผนภาพ: เบราว์เซอร์ตรวจแบบฟอร์มแล้วส่งไปที่ Next.js จากนั้น Server Action ตรวจสอบด้วย Zod ใช้ Honeypot และ Rate Limit แล้วส่งต่อให้ Delivery Service ซึ่งส่งอีเมลผ่าน Resend และบันทึกลง PostgreSQL หรือ Webhook ได้ตามที่ตั้งค่าไว้ ผลลัพธ์แบบมี Type ส่งกลับไปที่เบราว์เซอร์",
    stages: [
      { mark: "A", tag: "Browser", title: "แบบฟอร์มติดต่อ", body: "ตรวจทุกช่องทันทีด้วย Zod Schema ชุดเดียวกับที่เซิร์ฟเวอร์ใช้", file: "components/pages/contact/ContactForm.tsx" },
      { mark: "B", tag: "Framework", title: "Next.js App Router", body: "หน้าเว็บแบบ Static หลายภาษา src/proxy.ts พา URL ที่ไม่มีภาษาไปยัง /en, /de หรือ /th", file: "app/[locale] · proxy.ts" },
      { mark: "C", tag: "Entry", title: "Server Action", body: "submitContact รับข้อมูลจากฟอร์ม ส่วน GET /api/health เป็น Route Handler ที่อยู่ข้างกัน", file: "app/actions/contact.ts" },
      { mark: "D", tag: "Guard", title: "Zod · Honeypot · Rate Limit", body: "ข้อมูลผิดรูปแบบถูกปฏิเสธด้วย Error Code ที่หน้าเว็บแปลเป็นภาษาของผู้ใช้ บอตที่กรอกช่องซ่อนจะไม่ได้ข้อมูลอะไรกลับไป", file: "lib/contact/schema.ts" },
      { mark: "E", tag: "Delivery", title: "Delivery Service", body: "ส่งไปทุกช่องทางที่ตั้งค่าไว้ และรายงานว่าสำเร็จก็ต่อเมื่อมีอย่างน้อยหนึ่งช่องทางรับข้อความ", file: "lib/contact/deliver.ts" },
      { mark: "F", tag: "Result", title: "Response แบบมี Type", body: "success · invalid · rate-limited · unavailable · error ไม่มีการแสดง Error ของผู้ให้บริการ", file: "app/actions/contact.ts" },
    ],
    channelsLabel: "ช่องทางส่งข้อความ",
    channels: [
      { title: "อีเมลผ่าน Resend", role: "หลัก", body: "แจ้งเตือนเข้าอีเมลเจ้าของเว็บ ตั้ง Reply-To เป็นผู้ส่ง เทมเพลต Escape HTML แล้ว และ API Key อยู่บนเซิร์ฟเวอร์เท่านั้น", file: "lib/contact/email.ts" },
      { title: "PostgreSQL", role: "เลือกได้", body: "Neon ผ่าน Vercel บันทึกลงตาราง contact_submissions ที่สร้างอัตโนมัติตอนใช้ครั้งแรก", file: "lib/contact/store.ts" },
      { title: "Webhook", role: "เลือกได้", body: "ส่ง JSON ไปยัง URL ที่รองรับรูปแบบ Slack หรือ Discord", file: "lib/contact/deliver.ts" },
    ],
  },
  pipeline: {
    eyebrow: "Delivery Pipeline",
    title: "จาก Commit สู่ Production",
    lede: "เส้นทางที่โค้ดเดินทางไปถึงเว็บไซต์จริง รวมถึงส่วนที่เขียนด้วย Python",
    nodes: [
      { mark: "P", tag: "Build-time Artifact", title: "Python Generator", body: "scripts/generate_ai_circuit.py จัดเลย์เอาต์และเดินเส้นวงจร AI แล้วเขียนไฟล์ JSON และ SVG ผลลัพธ์ถูก Commit ไว้ Production จึงไม่ต้องรัน Python", file: "scripts/generate_ai_circuit.py" },
      { mark: "G", tag: "Source", title: "GitHub", body: "Repository สาธารณะ Branch main ทุกครั้งที่ Push เข้า main จะ Deploy ขึ้น Production อัตโนมัติ", file: "chaiyaphol752/Portfolio-" },
      { mark: "V", tag: "Build", title: "Vercel Build", body: "next build ตรวจ Type และ Prerender ทุกหน้าในทุกภาษาเป็น HTML แบบ Static", file: "next build" },
      { mark: "R", tag: "Runtime", title: "Vercel Runtime", body: "หน้า Static เสิร์ฟจาก CDN ส่วน Server Action และ /api/health ทำงานเป็น Functions", file: "Vercel Functions" },
    ],
  },
  security: {
    eyebrow: "หมายเหตุ",
    title: "ความปลอดภัยตามที่สร้างจริง",
    items: [
      "Security Header ได้แก่ HSTS, X-Frame-Options DENY, nosniff, Referrer-Policy และ Permissions-Policy ตั้งค่าไว้ใน next.config.ts",
      "RESEND_API_KEY และข้อมูลเข้าฐานข้อมูลอยู่ใน Environment Variable ฝั่งเซิร์ฟเวอร์เท่านั้น และโมดูลอีเมลถูกกำหนดเป็น server-only",
      "ข้อมูลที่ส่งเข้ามาตรวจสอบด้วย Zod บนเซิร์ฟเวอร์ และ Escape HTML ก่อนใส่ในอีเมลแจ้งเตือน หัวเรื่องถูกตัดการขึ้นบรรทัดใหม่ออก",
      "ป้องกันสแปมด้วยช่อง Honeypot ที่ซ่อนไว้และ Rate Limit ต่อผู้เข้าชม (แบบ Best Effort ต่อ Serverless Instance)",
      "ผู้เข้าชมเห็นเฉพาะข้อความสถานะที่ปลอดภัย ไม่เห็น Error จากผู้ให้บริการหรือฐานข้อมูล",
      "ลิงก์ภายนอกเปิดด้วย rel=\"noopener noreferrer\"",
    ],
  },
  health: {
    eyebrow: "Endpoint แบบสด",
    title: "/api/health เรียกจากเบราว์เซอร์ของคุณ",
    body: "Route Handler ส่งข้อมูลรันไทม์ที่ปลอดภัยและไม่เป็นความลับ รวมถึงช่องทางติดต่อที่ตั้งค่าไว้ Request นี้เป็นของจริง",
    loading: "กำลังเรียก Endpoint…",
    error: "เชื่อมต่อ Endpoint ไม่ได้",
    refresh: "เรียกอีกครั้ง",
    fields: {
      status: "สถานะ",
      service: "Service",
      time: "เวลาเซิร์ฟเวอร์",
      node: "Node.js",
      region: "Region",
      environment: "Environment",
      commit: "Commit",
      database: "ฐานข้อมูล",
      email: "อีเมล (Resend)",
      webhook: "Webhook",
      channels: "ช่องทางติดต่อ",
    },
    values: {
      ok: "ปกติ",
      degraded: "ทำงานไม่เต็มที่",
      connected: "เชื่อมต่อแล้ว",
      unreachable: "เชื่อมต่อไม่ได้",
      "not-configured": "ยังไม่ได้ตั้งค่า",
      configured: "ตั้งค่าแล้ว",
      "configured-test-sender": "ตั้งค่าแล้ว · ผู้ส่งทดสอบ",
      local: "Local",
      none: "—",
    } as Record<string, string>,
    httpStatus: "HTTP {status}",
  },
  github: {
    eyebrow: "GitHub สาธารณะ",
    title: "Repository สาธารณะ",
    lede: "ดึงจาก GitHub API สาธารณะฝั่งเซิร์ฟเวอร์ และแคชไว้หนึ่งชั่วโมง",
    empty: "ยังไม่มี Repository สาธารณะ",
    failed: "ข้อมูล GitHub ไม่พร้อมใช้งานชั่วคราว",
    profile: "ดูโปรไฟล์ GitHub",
    updated: "อัปเดต",
    stars: "ดาว",
    noDescription: "ยังไม่มีคำอธิบาย",
  },
  cta: {
    title: "อยากได้ Backend แบบนี้ให้เว็บไซต์ของคุณไหม",
    body: "ฟอร์มที่ส่งข้อความได้จริง API ฐานข้อมูล อีเมล และการ Deploy สร้าง ทดสอบ และมีเอกสารครบ",
    label: "เริ่มโปรเจกต์",
  },
};

export const systemsContent: Localized<SystemsContent> = { en, de, th };
