// Functional smoke test against a running server: BASE_URL=http://localhost:3100 node scripts/e2e.mjs
import { chromium } from "@playwright/test";
const base = process.env.BASE_URL ?? "http://localhost:3100";
const submitReal = process.env.E2E_SUBMIT === "1";
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1366, height: 820 }, locale: "de-DE" });
const p = await ctx.newPage();
const errors = [];
p.on("pageerror", (e) => errors.push(String(e)));
const results = [];
const check = async (name, fn) => { try { await fn(); results.push(`PASS ${name}`); } catch (e) { results.push(`FAIL ${name}: ${String(e.message).split("\n")[0]}`); } };
const assert = (c, m) => { if (!c) throw new Error(m); };
const text = () => p.locator("main").innerText();

await check("unprefixed URL redirects by Accept-Language (de)", async () => { await p.goto(`${base}/about`); assert(p.url().endsWith("/de/about"), p.url()); });
await check("old /skills URL redirects to /capabilities", async () => { await p.goto(`${base}/en/skills`); assert(p.url().endsWith("/en/capabilities"), p.url()); });
await check("language switch keeps page", async () => { await p.goto(`${base}/en/capabilities`); await p.locator("header").getByRole("link", { name: "ไทย" }).click(); await p.waitForURL("**/th/capabilities"); assert((await p.locator("html").getAttribute("lang")) === "th", "lang"); });
await check("unknown route -> 404", async () => { const r = await p.goto(`${base}/en/nope`); assert(r.status() === 404, `status ${r.status()}`); });
await check("no page numbers or complexity labels anywhere", async () => { for (const s of ["", "/lab", "/command-center"]) { await p.goto(`${base}/en${s}`); const t = await p.locator("body").innerText(); assert(!/complexity|\b0[1-9]\s*\/\s*0?9\b/i.test(t), `found on ${s}`); } });
await check("footer has mailto and tel links", async () => { await p.goto(`${base}/en`); assert(await p.locator('footer a[href="mailto:chaiyaphol.752@gmail.com"]').count() > 0, "mailto"); assert(await p.locator('footer a[href="tel:+4915154914268"]').count() > 0, "tel"); });
await check("palette opens with Ctrl+K and navigates", async () => { await p.goto(`${base}/en`); await p.keyboard.press("Control+k"); await p.getByRole("combobox").fill("lab"); await p.keyboard.press("Enter"); await p.waitForURL("**/en/lab"); });
await check("mobile menu lists 10 pages and contact actions", async () => { await p.setViewportSize({ width: 360, height: 780 }); await p.goto(`${base}/en`); await p.getByRole("button", { name: /menu/i }).click(); const d = p.locator("dialog[open]"); assert((await d.locator("ul li a[href^='/en']").count()) >= 10, "pages"); assert(await d.locator('a[href^="tel:"]').count() === 1, "tel"); await p.keyboard.press("Escape"); await p.setViewportSize({ width: 1366, height: 820 }); });
await check("AI circuit: selecting Python highlights its connections", async () => { await p.goto(`${base}/en/ai-native`); const before = await p.locator("main").innerText(); await p.getByRole("button", { name: /^python$/i }).first().click(); await p.waitForTimeout(300); const after = await text(); assert(after !== before && /automation/i.test(after), "inspector did not change"); });
await check("generated circuit SVG is served", async () => { const r = await p.request.get(`${base}/generated/ai-circuit.svg`); assert(r.ok() && (await r.text()).includes("generate_ai_circuit.py"), "svg"); });
await check("capability network reacts to selection", async () => { await p.goto(`${base}/en/capabilities`); const btn = p.getByRole("button", { name: /chatgpt/i }).first(); await btn.click(); await p.waitForTimeout(200); const pressed = (await btn.getAttribute("aria-pressed")) ?? (await btn.getAttribute("aria-selected")) ?? (await btn.getAttribute("aria-current")); assert(pressed && pressed !== "false", `state ${pressed}`); });
await check("project search filters to an empty state", async () => { await p.goto(`${base}/en/projects`); await p.getByRole("searchbox").or(p.locator("input[type=search]")).first().fill("zzzzqq"); await p.waitForTimeout(400); assert(/no project|0 of|nothing/i.test(await text()), "no empty state"); });
await check("lab JSON inspector flags invalid JSON", async () => { await p.goto(`${base}/en/lab`); await p.getByRole("tab", { name: /json/i }).click(); const ta = p.locator("textarea:visible").first(); await ta.fill('{"a": }'); await p.waitForTimeout(400); assert(/invalid|line 1/i.test(await text()), "no error"); });
await check("lab API inspector calls /api/health", async () => { await p.goto(`${base}/en/lab`); await p.getByRole("tab", { name: /api|request/i }).first().click(); await p.getByRole("button", { name: /send/i }).first().click(); await p.waitForTimeout(1500); assert(/200/.test(await text()), "no 200"); });
await check("terminal runs `capabilities`", async () => { await p.goto(`${base}/en/command-center`); const i = p.locator('input[maxlength="120"]'); await i.fill("capabilities"); await i.press("Enter"); await p.waitForTimeout(300); assert(/python/i.test(await text()), "no output"); });
await check("terminal refuses shell commands", async () => { const i = p.locator('input[maxlength="120"]'); await i.fill("rm -rf /"); await i.press("Enter"); await p.waitForTimeout(300); assert(/unknown|not found|help/i.test(await text()), "no rejection"); });
await check("contact: ?type=redesign preselects project type", async () => { await p.goto(`${base}/en/contact?type=redesign`); await p.waitForTimeout(500); assert((await p.locator('select[name="projectType"]').inputValue()) === "redesign", "not preselected"); });
await check("contact: client validation errors", async () => { await p.goto(`${base}/en/contact`); await p.getByRole("button", { name: /send/i }).click(); await p.waitForTimeout(300); assert((await p.locator('[aria-invalid="true"]').count()) >= 3, "no invalid fields"); });
await check("contact: has direct email + phone", async () => { assert(await p.locator('main a[href="mailto:chaiyaphol.752@gmail.com"]').count() > 0, "mailto"); assert(await p.locator('main a[href="tel:+4915154914268"]').count() > 0, "tel"); });
// Real submissions send email once Resend is configured, so they are opt-in: E2E_SUBMIT=1.
if (submitReal) await check("contact: REAL submission is delivered", async () => {
  await p.goto(`${base}/en/contact`);
  await p.locator('input[name="name"]').fill("Portfolio QA");
  await p.locator('input[name="email"]').fill(process.env.E2E_EMAIL ?? "qa@example.com");
  await p.locator('select[name="projectType"]').selectOption("redesign");
  await p.locator('textarea[name="message"]').fill("Automated production check of the contact pipeline. Please ignore.");
  await p.locator('input[name="consent"]').check();
  await p.getByRole("button", { name: /send/i }).click();
  await p.waitForTimeout(6000);
  const t = await text();
  assert(/thank|received|sent|reached/i.test(t) && !/unavailable|can.t deliver|went wrong/i.test(t), t.slice(0, 300));
});
await check("/api/health ok", async () => { const r = await p.request.get(`${base}/api/health`); assert(r.ok(), "status"); });
await check("sitemap + robots", async () => { assert((await (await p.request.get(`${base}/sitemap.xml`)).text()).includes("/th/contact"), "sitemap"); assert((await (await p.request.get(`${base}/robots.txt`)).text()).includes("Sitemap"), "robots"); });
await check("no uncaught page errors", async () => { assert(errors.length === 0, errors.slice(0, 2).join(" | ")); });
console.log(results.join("\n")); await b.close(); process.exitCode = results.some((r) => r.startsWith("FAIL")) ? 1 : 0;
